### ISSUE TITLE
[3.2.15, 3.2.16] Mysterious file with no extension created along with jadeite.ERRORS

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#1000]
I noticed a file named jadeite3.2.16 (no extension) in my jadeite directory, and I just deleted one named jadeite3.2.15. 
This file contains:
***** Starting Dolphin stack dump at 10:35:02 2/17/2023 *****
***** Ending Dolphin stack dump started at 10:35:02 2/17/2023 *****
***** Starting Dolphin stack dump at 10:35:08 2/17/2023 *****
***** Ending Dolphin stack dump started at 10:35:08 2/17/2023 *****

I think this file should not be created... if it had useful content it should have an extension so I can open it...

**Comment by ericwinger** [comment]
The error log path is derived from 1) the image path and 2) the 'errors' extension in Dolphin code `File class>>default:extension:` However, if the executable file has a `.` in the image file name prefix then the path is returned without appending the .errors extension to the error log file name.  The image file Jadeite3.2.16.exe has a `.` in the image file name prefix between 2 & 16.  This might be a bug in Dolphin code. 

Jadeite uses the file returned to print header and footer timestamp information but when it dumps information about the error. (See `logError:`) However, it calls the vm to dump the full stack. The vm does the right thing and appends the `.errors` extension.  So you end up with two files - one that contains just the headers and footer timestamps and the second with the error dump.

**Comment by ericwinger** [comment]
Don't use Dolphin's errorLogName method as it is buggy for paths with '.'s in them.
