### ISSUE TITLE
[3.2.16] saving parameters saves host password in plain text

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#1001]
If you need to set the host user and host password, and you save these parameters, it writes the host password to a file in plain text. This is Not A Good Thing.  Since it's on the "advanced" tab you might not notice (I had this on sometime ago for testing).

I don't remember what GBS/VW does, but I sorta think it might have had a warning about this?  GBS/VA doesn't provide fileout for params.

**Comment by ericwinger** [comment]
Added password in plain text warnings. Not sure it's a great solution but a small improvement.
