### ISSUE TITLE
[3.2.16] Login Advanced Tab radio buttons are nonfunctional

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#1002]
The Login dialog advanced tab has some radio buttons
o NetLDI Guest Mode
o Native OS User

These appear to be completely ignored.  I can't imagine what the original intention was; perhaps, if you select guest, perhaps it was meaning hide the host user and password fields?  
I recommend removing these radio buttons, and adding some text above OS UserId "Following fields are only required if NetLDI is not in guest mode".  It's not entirely clear but better than nonfunctional radio buttons.

(or possibly they could be repurposed for regular login and single sign on)

**Comment by ericwinger** [comment]
Got rid of dysfunctional radio buttons and added text per request
