### ISSUE TITLE
Dictionaries browser class > browse references to class hangs jadeite

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#102]
Dictionaries Browser, navigate to Date class, and do Browse References.
This gets an error:
   RowanMethodDefinition does not understand #displayClassName

in a loop... close and get another one... so I have to kill jadeite entirely.

I tried this with finding references to a rowanized class and that appears to get this error twice, displays the reference line in the top, gets another error then hangs the image. No problem if there are no references; in this case I have a reference to this class in another method.

This is in 3.0.17 (latest rowan)

**Comment by ericwinger** [comment]
We were opening the new jadeite method list browser but using the old display model. I suspect there are more bugs lurking in the dictionary browser like this as I always open the new Jadeite method list browser now. Fixed in 3.0.18.
