### ISSUE TITLE
(non-string) inspectors have questionable menu items

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#105]
Inspect:
    Dictionary new at: #abc put: 'hello'; yourself

Most items on the Edit menu get errors such as 
    ListBox does not understand #copySelection

Many items in the Jade menu (display,execute, inspect) get errors such as
    Association does not understand #replaceCrLfWithLf

**Comment by ericwinger** [comment]
The menu options in question were trying to access the focused view and assumed it was the text pane. 
Disabled the menu options if the focus pane wasn't a text pane. Fixed in 3.0.21
