### ISSUE TITLE
Only one letter of stone name in transcript and other windows

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#11]
at least I think it's the first letter, since it's an s and the stone name is stone3215

e.g.
    Jadeite version [Oscar] 1 (SystemUser) - Transcript on s

**Comment by ericwinger** [comment]
This is what I see using the exe which is different than you describe. Could you upload a picture? 

Note - I'm happy to put whatever text you'd like in the transcript window header but Dale has some strong feelings about this. So, I'd ask first that you and he coordinate on exactly what's desired. 

![image](https://user-images.githubusercontent.com/36212516/43792484-9e52c3ee-9a2d-11e8-9925-0750a40e649c.png)

**Comment by LisaAlmarode** [comment]
You have an "on l" that looks suspicious... but I'll send a picture when I can run oscar again.

**Comment by LisaAlmarode** [comment]
![image](https://user-images.githubusercontent.com/13142166/43798608-f60a7764-9a3f-11e8-8774-839e760544e1.png)

**Comment by LisaAlmarode** [comment]
Much improved.  But I've looked at rowan issues 110 (me) and 130 (dale) and will file a new request for changes...
