### ISSUE TITLE
deleted project stuck in Project Browser list (3.0.18)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#113]
**NOTE: you need to use the latest candidateV1.1 branch to get the bugfix for `deleteProjectNamed:`**

1. clone and load RowanSample1 using Project Browser
2. Execute the following in workspace:
   ```smalltalk
   Rowan projectTools delete deleteProjectNamed: 'RowanSample1'
   ```
3. Refresh Project Browser, but the deleted project seems to be stuck...the walkback occurs when I select the deleted project:
![image](https://user-images.githubusercontent.com/623951/44614057-bb2c1800-a7d2-11e8-9d5d-95f73577a0cd.png)
4. Open a new Project Browser and the deleted project is gone ...

**Comment by ericwinger** [comment]
Removed projects better handled in 3.0.19.

**Comment by dalehenrich** [comment]
It seems that this bug is still present, but in a slightly different form ... 
1. clone and load RowanSample1 using Project Browser
2. do an abort
3. refresh the project browser:
![image](https://user-images.githubusercontent.com/623951/44748897-ce3a3300-aac5-11e8-8a63-e5352e7f7702.png)
select project nd get 'no project found' ... open a new project browser and the project is not present

**Comment by ericwinger** [comment]
Likely https://github.com/GemTalk/Rowan/issues/349
