### ISSUE TITLE
Remote performance - ability to disable client-forwarder transcript writes

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#117]
When I was on the extremely slow internet, Eric and I determined that the worst performance impact was client forwarders whose purpose is transcript writes.  Eric had me comment out one, but clearly there are others; when I set a default project, performance went south and I had trouble un-setting a default project. The transcript writes are never, even of interest to me. 

I think there should be a way to disable ALL the client-forwarder transcript writes everywhere, for when on a slower network connection.  This might help me working from Lebanon, where VPN constrains performance to much slower than in the office.

**Comment by ericwinger** [comment]
Isn't this issue #114?  Fixed in 3.0.19.

**Comment by ericwinger** [comment]
Oh wait. Sorry. There may not be an open issue, but I did add a switch to turn off all transcript writes.

**Comment by LisaAlmarode** [comment]
I didn't see bug reported so filed this one, since I'm still annoyed by performance.  I see the fix in 3.0.19 and will review the impact; thanks for fixing it.

**Comment by LisaAlmarode** [comment]
This makes a huge difference in performance! E.g update/load went from over 15 seconds to about 5 seconds; opening a project/project list browser went from 8-10 seconds to about 2 seconds.
