### ISSUE TITLE
Checkout list of branches should have current branch selected

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#119]
When you try to checkout, you are presented with an alphabetical list of branches.  It highlights the first one.  This confuses me about what I branch I have loaded. 

This list should highlight to match what is current (at least best guess in jadeite); that is, the selection should be the same as what is showing on the Project tab.  It will never be correct but there's no way to predict the actual correct one.

**Comment by ericwinger** [comment]
Fixed in 3.0.21. Initial selection is current branch.
