### ISSUE TITLE
Debugger, edits in text, copy to clipboard, get error

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#120]
If you want to do some ad-hoc execution in a debugger, you type in code in the method frame.  Then if you select a different frame, it asks if you want to save changes to the clipboard.  Saying yes results in an error:
   String does not understand #value

I'm not sure what the correct behavior is supposed to be, but (with new jadeite debugger enabled selected), it keeps showing the edited text from the previous frame, while the new frame is selected.

**Comment by ericwinger** [comment]
Think this is fixed in 3.0.21

**Comment by LisaAlmarode** [comment]
verified in 3.0.22, writes to clipboard, click back to frame gets original method; good.
