### ISSUE TITLE
Need to be able to refresh project browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#14]
After loading my example project, this project does not show up in an existing Projects Browser.  One hates to have to close and reopen a browser to refresh.

I don't mean the refresh of a particular project, which reports feature not implemented - this is the list of projects.  Since selecting a project refreshes everything I'm not sure what the refresh menu item could possibly do.

**Comment by ericwinger** [comment]
Checkin for Oscar 3.0.2. 

Some of the strings being put into the WriteStream from which the title bar is created had UTF16 characters. Not sure that's what we want so sending #printString to them before display fixed the problem. We may want to revisit this and allow the larger characters in the future if windows title bars support them.

**Comment by LisaAlmarode** [comment]
Refresh works, though it was hard to find on the jade menu when I kept seeing the refresh in the projects pane with a refresh that just would refresh a selected project.  Probably one or the other needs to be renamed or something.  However, this is good to go on.
