### ISSUE TITLE
Can't easily and reliable get to Projects Browser as application user/Console Jadeite menu flakey

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#189]
In 3.0.38, I'm having a very hard time pulling down the Jadeite menu on the console as user Lisa, a non-DataCurator, non-SystemUser user with appropriate permissions.  I have got it a couple of times, if I slide the cursor around just right or move it in a circle, it will sometimes appear.

This particular menu has been excessively slow in earlier releases, I was thinking about filing an issue earlier; but it's now non-functional, not just slow.  Or at least I waited about 20 seconds which seems like enough.

What happens: cursor over Jadeite, press and hold.  See dialog fade in and out saying something about RowanAnsweringService.  It goes away.  See no menu.  Now, if I continue to hold and slide over to Edit and File menus, they don't pop down either.  If I click off then come back, click and hold on Edit and slide over to Jadeite, I get the dialog and then nothing.  

Sadly, there's an icon bar item for the Dictionaries Browser!  But not for the Projects Browser.  

To create the user:

run
| securityPolicy newUser |
      securityPolicy := GsObjectSecurityPolicy new
        ownerAuthorization: #write;
worldAuthorization: #read;
        yourself.
      System commit.
      newUser := (AllUsers 
        addNewUserWithId: 'Lisa'
        password: 'asil'
        defaultObjectSecurityPolicy: securityPolicy)
        addPrivilege: #CodeModification;
        addPrivilege: #UserPassword;
        addPrivilege: #OtherPassword;
        yourself.
      securityPolicy owner: newUser 
%
commit

then login as Lisa and execute:

GsPackagePolicy current enable.
UserGlobals at: #rowanCompile put: true.
System commit

I've deleted the prefs file and this occurs with both transcript writes enabled and disabled.  I also sometimes at a "must be boolean" error when enabling or disabling transcript writes.

**Comment by LisaAlmarode** [comment]
After doing some testing in 3.0.36 and 3.0.38, I'm not sure that there's a significant difference in flakiness of the Console Jadeite menu; it's not behaving all that well there either.  
I would like to have a reliably reproducible way to get to this menu!

The other menu items on the console, you can get to them by: 
1. press and release on menu header, move cursor down and click on desired item
2. press and hold on menu item, move cursor down and release on desired item
3. start with either of these on a different menu header, slide sideways to the other menu and click or release on desired item.

I can't find a reliable pattern for the Jadeite menu - although I do think there's some kind of jiggle down and up that helps.

**Comment by ericwinger** [comment]
Although I can't reproduce it, I believe the problem was in the test for the transcript writes menu option. Changed this to test local state so it doesn't make a round trip.
