### ISSUE TITLE
Oscar-3.0.40: Wodkspace window still uses `Jade` labels

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#194]
![image](https://user-images.githubusercontent.com/623951/45930871-3a1f8800-bf1a-11e8-91ac-46d5a9f3fb18.png)

**Comment by dalehenrich** [comment]
... and the Jade menu items is missing ability to browse projects, etc.
![image](https://user-images.githubusercontent.com/623951/45930892-908cc680-bf1a-11e8-9ea8-40f932db046b.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.47. Also changed the ``Exit Jade`` from a regular workspace to ``Exit`` as it only closes the workspace.

**Comment by LisaAlmarode** [comment]
The inspector has the same problem - it has the Jade menu item and the File menu option says Exit Jade.

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.49.

**Comment by LisaAlmarode** [comment]
Please make the Inspector Jadeite menu NOT say "exit Jadeite", it should only say "Exit" or "Close"

**Comment by ericwinger** [comment]
All the inspectors have just `Exit` in the File menu as of 3.0.50

**Comment by LisaAlmarode** [comment]
The inspector Help menu item is titled About Jade.  While this could be "About Jadeite", I'd suggest removing the Help menu title from the inspector.  

I don't think it's really useful on the Workspace, either.

Speaking of Help menus, the Login windows menu has some grayed out items that might be removed: Contents, On This Tool, and What's This?.

**Comment by ericwinger** [comment]
I've removed Help from the inspectors and the workspace. 
The Login window help items are removed. Both fixes are in 3.0.52. 

Question @LisaAlmarode - Since we put a link up to the GemTalk Systems home page on the Login Help menu, would it be useful to also put links up to the rowan and jadeite github projects?

**Comment by ericwinger** [comment]
Closing issue. question to @LisaAlmarode can be opened in a new issue if enhancement is desirable.
