### ISSUE TITLE
Add browse method/class/package to Jadeite SUnit Browser

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#196]
- [ ] It would be handy to be able to easily browse the test code from the SUnit browser.

- [ ] Also, The Sunit Browser title is "Rowan SUnit Browser..." Probably should be "Jadeite SUnit Browser" for consistency.

**Comment by LisaAlmarode** [comment]
As of 3.0.75, the classes pane as a browse class, and the methods pane has a browse methods.  The title is now Jadeite SUnit Browser.  So this is fixed.
