### ISSUE TITLE
Deprecated error, can't log--in with Ernie loaded. Should not be using deprecated API

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#201]
No Jadeite stack traced produced:
![image](https://user-images.githubusercontent.com/1958382/46099613-0fcd0500-c17c-11e8-8aa2-5860c05c3c0a.png)

**Comment by dalehenrich** [comment]
One caveat here is that Rowan does use constraints because of customer requirements and constraints are deprecated ... Ideally Rowan should be able to isolate the constraint operations so that we can audit Rowan for using deprecated APIs in other areas ...

**Comment by LisaAlmarode** [comment]
As of 3.0.74, I can turn on Deprecation Error and login.  There might be issues but they should be reported elsewhere when found.
