### ISSUE TITLE
Make sure that Jadeite Transcript handling is clean

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#206]
The customer was wondering why JadeServer64bit32 was showing up in a stack for code that was executed by Topaz and it turns out that this was due to the way that Jade was handling Transcritpt client forwarders ... I know that @ericwinger and I have made one pass over this already, but we should revisit our solution one more time to make sure that we've got it right ... 

A detail that I didn't remember from our work was that apparently "Jade was setting Transcript to some instance of JadeServer for all users in their UserGlobals"  ... I didn't recall that UserGlobals was involved, so we need to look at this closely as well

**Comment by LisaAlmarode** [comment]
Since it's a customer issue, it gets a priority.  It may be already done.

**Comment by ericwinger** [comment]
After review, it appears that the fix put in back in September(ish) is solid. Transcript installation and interactions won't go through UserGlobals in Jadeite. See ``JadeServer64bit3x>>installTranscript`` for implementation.
