### ISSUE TITLE
Pane resizing in project and dictionary browsers

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#210]
Most of the pane dividers resizes are simple divider moves.  

However, the third divider from the right, between the classes list and the categories pane, causes all the panes to resize themselves.  This is never what I want.

This is on the
- [ ] projects browser
- [ ] dictionaries browser

Speaking of layout, I note the categories/variable tabs are along the top in the projects browser and vertically on the dictionaries browser.  Taking up width and being inconsistent are both undesirable. 

- [ ] make categories and variables along the top in dictionaries browser.

**Comment by ericwinger** [comment]
@LisaAlmarode since my hope is to get rid of the dictionary browser when the base is rowan-ized, it seems that the latter two check boxes in this issue are minor enough to eliminate. Thoughts?

**Comment by ericwinger** [comment]
Fix for 1 will be in 3.0.41. Awaiting input on 2 and 3.

**Comment by LisaAlmarode** [comment]
Resize is independent in the project browser in 3.0.41.  I'll close this issue on the assumption that the Dictionary Browser isn't very important and/or eliminated or replaced by something that doesn't pretend to be a complete browser.
