### ISSUE TITLE
`Copy` menu item grayed out in inspector when text selected ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#212]
In Issue #211, when I selected the result of the expression, the `Copy` menu item was grayed out and `CTL-C` silently failed as well ... I **was** able to use the `Cut` menu item to get the text into the paste buffer, so it seems that there is no reason to disable the `Copy` menu item ...

**Comment by dalehenrich** [comment]
Here's picture of the inspector, menu with greyed out entry and the debugger where the inspector oon the string came from:
![image](https://user-images.githubusercontent.com/623951/46563208-0b5bc700-c8b5-11e8-972a-bc133adbf946.png)

**Comment by dalehenrich** [comment]
hit again in 3.0.46 ... worth bumping up, since it's not obvious what to do when you need to copy text (using the cut menu item is not my fist thought:)

**Comment by dalehenrich** [comment]
Came up in HR9917 ... let's include a fix in next Jadeite release

**Comment by LisaAlmarode** [comment]
Easy reproduction: In a workspace inspect-it on 1-> 3,  and pop in the right pane.

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.51.
