### ISSUE TITLE
Eliminate Dictionary Browser

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#217]
In order to release to the general public as a "beta" we need to show & change non-rowanized code in the projects browser. 

- Create a (NONE) project
- Show dictionaries in package pane
- Eliminate `rowanCompile`
- Rowan allow non-packaged compiles automatically. 
- Move non-packaged methods/classes to packages with menu item.

**Comment by LisaAlmarode** [comment]
While I don't think the dictionary browser is very useful... there does need to be some way to see what all symbolDictionaries are present in the image, and what is in a given symbolDictionary.  Funny stuff can happen. 

I think the recommended rowan use case for customers is to load everything in a single symboldictionary but I don't think that's a requirement. We might want to see what Dale thinks, if the goal is to actively suppress SymbolDictionaries and replace the GemStone uses of them, by other rowan features.

**Comment by dalehenrich** [comment]
The recommended for our customer is to use a single symbol dictionary ... except that in general in GemStone that means you are using 2 symbol dictionaries: your symbol dictionary and Globals ... Rowan uses 3 symbol dictionaries (not counting Globals) ... So until symbol dictionaries are replaces by something that provides the equivalent functionality ... being able to view symbol dictionaries is necessary ... and I believe that @ericwinger has some ideas on how to fold the symbol dictionary view into the project browser ...

**Comment by ericwinger** [comment]
Marking as fixed before doing an internal release in 3.0.73. Please open new issues for problems.
