### ISSUE TITLE
error when saving source with compile error in debugger

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#219]
1. edit code in debugger in a block context 
2. get error about cannot edit in block
3. select correct frame and get notifier about copy string
4. say yes
5. select all
6. paste
7. accept 
8.get error about something does not understand view.
  ![image](https://user-images.githubusercontent.com/623951/46562986-db5ff400-c8b3-11e8-8fb4-4f689d3346a1.png)

9. close dialog 
10. get error ... seems to be rerunning the process?
  ![image](https://user-images.githubusercontent.com/623951/46562722-69d37600-c8b2-11e8-8ef3-ea1f484c5460.png)

11. close debugger 
12. browse method
13. paste source
14. accept ... and boom ... there was a compile error
  ![image](https://user-images.githubusercontent.com/623951/46562936-83c18880-c8b3-11e8-9b03-30162241fecf.png)

**Comment by ericwinger** [comment]
Should have a fix for this in 3.0.54. Debugger has a status bar now for reporting compile errors. Functions similarly to project browser.
