### ISSUE TITLE
Project name in project browser does not stay red when dirtied

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#221]
FileSystemGs was red and then I modified a method and it turned black again:
![image](https://user-images.githubusercontent.com/623951/46564654-73aea680-c8bd-11e8-81ee-5a7fbfafd91b.png)

also looks like the SHA was (magically) changed to match what was on disk... both of these projects should have the same SHA .. :
![image](https://user-images.githubusercontent.com/623951/46564688-d43de380-c8bd-11e8-84ef-cde69f16e8f4.png) ![image](https://user-images.githubusercontent.com/623951/46564699-ecadfe00-c8bd-11e8-84d0-cce1df536cd9.png)

neither of the projects were loaded/written ... the only thing was that methods were modified, but the commit has apparently been loaded into the loadedCommitId field:
![image](https://user-images.githubusercontent.com/623951/46564744-40204c00-c8be-11e8-843f-c0131a12fa1e.png)

**Comment by dalehenrich** [comment]
this is still an *issue* in 3.0.56

**Comment by LisaAlmarode** [comment]
I don't see the turning black after being red on a non-Rowan project.  Dale should verify if there is a problem with the shas in the handling of the Rowan set of projects.

**Comment by dalehenrich** [comment]
I think that this ended up being a Rowan problem (GemTalk/Rowan#469) which was fixed back in February for v1.2
