### ISSUE TITLE
Error attempting to set breakpoint in debugger

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#222]
Overview:
![image](https://user-images.githubusercontent.com/623951/46565344-364d1780-c8c3-11e8-802e-7d1a17069bf1.png)
Stack:
```
a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'asSymbol'
RowanMethodService >> classFromName @3 line 3
RowanMethodService >> classOrMeta @6 line 5
RowanMethodService >> gsNMethod @2 line 3
RowanMethodService >> setBreakAt: @2 line 3
RowanMethodService (RowanService) >> servicePerform:withArguments: @2 line 2
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1
```
Here's picture of debugger open on stack:
![image](https://user-images.githubusercontent.com/623951/46565378-8af09280-c8c3-11e8-95a7-99ca5b59f11c.png)
Looks like the className is nil in the methodService returned from the server:
![image](https://user-images.githubusercontent.com/623951/46565412-fc304580-c8c3-11e8-9c6c-990fc70be16c.png)

... My guess is that I'm trying to set a breakpoint in a block frame and the method associated with frame is not the real compiled method ... so the class is not set (seem to recall that is how you know you have a block method as opposed to a real method) ...

**Comment by dalehenrich** [comment]
... sure enough if I set the break point in the parent method, it is set just fine ...

**Comment by ericwinger** [comment]
@LisaAlmarode Worth rechecking in 3.1.0.

**Comment by LisaAlmarode** [comment]
does not reproduce in 3.2.12
