### ISSUE TITLE
Cannot see implementors/senders in debugger on method w/breakpoint

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#223]
cursor was on the nextPutAll: method with breakpoint:
![image](https://user-images.githubusercontent.com/623951/46565606-d1df8780-c8c5-11e8-998c-5db1fcf35ce9.png)
writeStreamDo: is recognized:
![image](https://user-images.githubusercontent.com/623951/46565625-19661380-c8c6-11e8-8743-573a7b41afa4.png)
seems like methods with breakpoints cannot do senders/implementors as #contents doesn't work:
![image](https://user-images.githubusercontent.com/623951/46565672-9b563c80-c8c6-11e8-9213-7a1903fa9f67.png)

**Comment by LisaAlmarode** [comment]
If you set a breakpoint on a selector in method, when you get into the debugger, in the text pane popup menu, it doesn't add the selector.  So you can't look for implementors of that selector. 

This is simpler than Dale's report:
![image](https://user-images.githubusercontent.com/13142166/47892804-01c37180-de17-11e8-8289-560d0207a7c5.png)

If you remove the breakpoint, you get the extra menu items I expect:
![image](https://user-images.githubusercontent.com/13142166/47892902-77c7d880-de17-11e8-9cc8-abbe367d3e09.png)

**Comment by ericwinger** [comment]
Hmmm, might need a little more help figuring out what's different about your use case. Although I think your cursor is in the right spot, make sure it's on foo & the breakpoint. 

![image](https://user-images.githubusercontent.com/36212516/47928733-446f6300-de84-11e8-849f-e50a4c4c75d1.png)

**Comment by LisaAlmarode** [comment]
Still the same for me in 3.0.48.  I don't know how to show more clearly that foo is highlighted - "clear break" should be good evidence.  I'm glad it's working for you but... 

![image](https://user-images.githubusercontent.com/13142166/48579670-0174ad00-e8d2-11e8-9e63-9b6e84eb98c8.png)

**Comment by LisaAlmarode** [comment]
I'm also seeing the senders and implementors menu items go away when I put a breakpoint on a selector in the Projects Browser.

![image](https://user-images.githubusercontent.com/13142166/49689357-df3b0d00-fad4-11e8-9fa2-a8b8e6ff5111.png)

**Comment by ericwinger** [comment]
@LisaAlmarode I still can't reproduce this with the cursor over ``bar``. (I can make the senders/implementors go away by clicking outside ``bar``).

In spite of that I did a code review and can't find anything that would point to the break point as the culprit behind the behavior you are seeing. However, I did make a couple changes in 3.0.54 which should eliminate showing the breakpoint menu item without the implementors/senders. 

One thing to remember is that those menu items are dependent upon where your pointer or girder cursor is when you release the mouse. If you right mouse down over ``bar`` but release off of ``bar`` the menu options won't be displayed. (Note that I don't think this is the problem based on the picture of where your menu is placed)

A few things I'd be curious about: 
- In the debugger, do you see a pop-up flash by as you move the mouse over bar? It should say "Break at step point #2"  
- If you do see the pop-up, can you right mouse down/up in that spot? Do you then see the implementors/senders even with a breakpoint? 
- Have you verified your mouse is calibrated as a sanity check?  (I suspect it's ok though based on menu placement in the picture)
- Do you see the problem with the pointer or the girder cursor? Or both? (I noticed that the girder cursor's point is in the middle is in the middle of the i-beam.)

**Comment by dalehenrich** [comment]
This is 3.0.52. In the first screen shot, you can see that the step point is being highlighted ... ![image](https://user-images.githubusercontent.com/623951/50244419-ba705080-0384-11e9-94f3-b08b45c46c3a.png)

In the second screen shot I positioned the cursor to get the popup then brought up the menu and the senders/implementers aren't present ...
![image](https://user-images.githubusercontent.com/623951/50244500-edb2df80-0384-11e9-9b2d-869b8ec808ae.png)

My observation is that you **might** need to be in a nested exec block frame to have this happen.  for this screenshot I followed the same procedure as before ... but note that I am in the home frame for the method ... not a nested exec block:
![image](https://user-images.githubusercontent.com/623951/50244845-cdcfeb80-0385-11e9-9b94-932aec3ddf60.png)

Note that in these last two screen shots you see that the cursor is located in the same spot in the source code ... and the breakpoint popup showed in both cases before selecting the menu item ...

**Comment by dalehenrich** [comment]
Also worth noting that in the nested exec block frames, the selectors are not underlined (you have to look closely):
 ![image](https://user-images.githubusercontent.com/623951/50245263-df65c300-0386-11e9-9039-ffb40f5bc86c.png)

and the selectors are all underlined in the home frame of the method"
![image](https://user-images.githubusercontent.com/623951/50245431-4aaf9500-0387-11e9-9a1e-beac99fd8910.png)

**Comment by dalehenrich** [comment]
... further observation is that once the underlines are gone the breakpoint popup does not show up ... all of the screen shots in the last few comments are of the same debugger ... so selecting around in the debugger has resulted in subtle changes to the frame state ... and close examplination of the first snapshot where the breakpoint pop was visible in a nested exec block frame shows that the methods **were** underlined and in the second to last snapshot the same frame as the first is selected, but this time the methods **are not** underlined ... this was the same debugger instance for all of the screen shots ...

**Comment by dalehenrich** [comment]
This screen shot is for 3.0.53 and shows that a home frame method is not showing the implementors/senders menu items ... selectors are underlined:
![image](https://user-images.githubusercontent.com/623951/50255608-6e82d300-03a7-11e9-8602-ff2cb9376a9b.png)

... and here's screenshot showing that popup is present (previous screen shot waited til popup appeared before getting menu):
![image](https://user-images.githubusercontent.com/623951/50255685-b6095f00-03a7-11e9-8fc4-fbb9df657591.png)

**Comment by ericwinger** [comment]
@LisaAlmarode @dalehenrich - Please take a read through this.  If you get into a weird situation where you can't find the implementors or senders menu options, please send me the results of the code snippet I describe at the bottom of this comment. 

While implementing the fix discussed in the meeting yesterday, I stumbled onto a case where a compiled method was returning totally bizarre step points when sent  ``_sourceOffsetsOfSends ``.

``(<MyClass> compiledMethodAt: #<myMethod>:) _sourceOffsetsOfSends ``
This was the method source. 
```
initialize: aGsProcess status: aString

	| theOrganizer |
	theOrganizer := ClassOrganizer new. 
	frames := Array new: aGsProcess stackDepth.
	1 to: aGsProcess stackDepth do: [:i | 
		frames at: i put: (RowanFrameService process: aGsProcess level: i organizer: theOrganizer).
	].
	oop := aGsProcess asOop.  
	status := aString.
```

The results of sending ``__sourceOffsetsOfSends`` were - 
``anArray( 91, #''new'', 159, #''stackDepth'', 190, #''at:put:'', 144, #''+'', 147, #''>='', 298, #''asOop'')``

When I recompiled the exact same source, I got these stepPoints 
``anArray( 91, #''new'', 130, #''stackDepth'', 114, #''new:'', 160, #''stackDepth'', 221, #''process:level:organizer:'', 191, #''at:put:'', 145, #''+'', 148, #''>='', 299, #''asOop'')``

I can't explain how I got into this situation, but the next time you see problems with the implementors/senders menu options not appearing, please: 

1. Print the results of this code in a workspace ``(<MyClass> compiledMethodAt: #<myMethod>:) _sourceOffsetsOfSends ``
2. Recompile the offending method. 
3. Print the above code snippet again. 
4. Send me the output. 

This will help me know if some of the problems are coming from the server. Thanks.

**Comment by LisaAlmarode** [comment]
Eric, you are on to something here. It looks like the act of adding the breakpoint (in the projects browser method pane) is causing it to be no longer included in the results of _sourceOffsetsOfSends.

This is my test method:
'''test
	"OrderPricer test "

	| temp total |
	temp := Dictionary new.
	temp at: #aa put: DateTime now.
	total := 0.
	temp values do: [:aVal |
		total := total + aVal asSecondsGmt].
	^total
'''

Commit the transaction, and log out and in again.

verify source offsets:

(OrderPricer class compiledMethodAt: #test) _sourceOffsetsOfSends printString, '
', (OrderPricer class compiledMethodAt: #test) _allBreakpoints printString

 'anArray( 64, #''new'', 97, #''now'', 75, #''at:put:'', 121, #''values'', 128, #''do:'', 165, #''asSecondsGmt'', 158, #''+'')
nil'

back in Project browser, set break at step point 11, asSecondsGmt.  Now:

 'anArray( 64, #''new'', 97, #''now'', 75, #''at:put:'', 121, #''values'', 128, #''do:'', 158, #''+'')
anArray( 1, aGsNMethod, 80)'

execute OrderPricer test which brings up debugger, hover shows missing menu items.

=====================

I had captured a previous incident but lost detail due to jadeite crash.  The good/bad reports show similarly, that the method on which the breakpoint was set was then no longer reported.

 anArray( 132, #'size', 175, #'at:', 190, #'isOrderTotalPrice:', 236, #'removeAtIndex:', 122, #'+', 125, #'>=')

anArray( 132, #'size', 175, #'at:', 236, #'removeAtIndex:', 122, #'+', 125, #'>=')

**Comment by LisaAlmarode** [comment]
After playing with the code to set breakpoints, this turns out to be a server issue that is not showing up in 3.3.x or 3.4.x.  Filed bug 47866.

It would be nice to find a workaround but I have doubts. Hopefully once issue #371 is implemented this situation may improve.
