### ISSUE TITLE
nice to have a breakpoint browser ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#225]
Being able to enable/disab/delete break points is superior to hunting down down and indvidually clearing breakpoints ... I log out/in rather than do that even with one breakpoint ...

**Comment by LisaAlmarode** [comment]
I think eric claiming fixed in 3.0.76, otherwise ought not to be for review and assigned to me.

**Comment by ericwinger** [comment]
Yes, this is fixed in 3.0.76.  Ability to browse breakpoints and clear them ready for review.
