### ISSUE TITLE
error when setting breakpoint in a nested block in debugger ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#227]
Trying to set breakpoint for binaryReadStreamOn: on line 4:
![image](https://user-images.githubusercontent.com/623951/46632111-646a6b80-cafe-11e8-9b8d-d3e0200f0f8e.png)
... if I selet the top frame for the method, I can set breakpoint:
![image](https://user-images.githubusercontent.com/623951/46632196-a8f60700-cafe-11e8-95af-03e18eeaa05e.png)

**Comment by LisaAlmarode** [comment]
This does not produce a walkback in 3.0.75.  However, highlighting and setting breakpoints in a nested context still does not work correctly (looks light the server returns offsets relative to the block, while jadeite highlight from the method start).  Will check for a report (seems like there must be one), or create a more specific bug.
