### ISSUE TITLE
lose selected class in project browser when new version created

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#228]
before save (adding iv `x`):
![image](https://user-images.githubusercontent.com/623951/46638131-4c054b80-cb14-11e8-8560-edf76192af94.png)
after save:
![image](https://user-images.githubusercontent.com/623951/46638155-62130c00-cb14-11e8-8130-150c1facb234.png)
have to go hunting for the new class ... class definition pane is pink ... which means what?
It's white when I find the class again:
![image](https://user-images.githubusercontent.com/623951/46638213-98508b80-cb14-11e8-9882-408b7873d302.png)

**Comment by LisaAlmarode** [comment]
When modifying an existing class, it is wrong to unset the selection.  This is in the list view; it does correctly retain the class selection in the hierarchy view.  

In #233 I'm looking at creating a new class... the added class automatically shows up in the list of classes in the list view, but not in the hierarchy view.  

When adding a new class, I'd be inclined to set selection to the new class, rather than leaving selection on the existing class.

**Comment by ericwinger** [comment]
After a class compile, now we return the newly compiled class to be selected by Jadeite. See ``RowanPackageService>>compileClass:``.  Server test added.

**Comment by LisaAlmarode** [comment]
In general, the new behavior is good (I don't like the class list going empty for so long but it's not terrible).

However, there's a problem related to this.  The new system doesn't seem to be prepared for some kinds of class compile errors. 

To reproduce:

create class One
create a subclass of One, call it Two
add instance variable aa to Two.
then try to add instance variable a to One

If you look sharp you can see the error flit across the error bar but I could only read as far as Improper before it cleared.  Selection is Two. The display is now

One
Two (2/2)  

if you select One, it updates to

One (1/2)
Two (2/2)

and the aa is not visible for One, which of course wouldn't work.  Not sure the correct behavior just that this isn't it.

**Comment by ericwinger** [comment]
I was able to reproduce the odd versioning in a workspace, independent of the Jadeite browsers. I filed rowan bug https://github.com/GemTalk/Rowan/issues/388. 

The "flittering" error message is fixed to be visible in 3.0.44.

**Comment by LisaAlmarode** [comment]
Jadeite behaves well.  The spurious class version is still created per GemTalk/Rowan#388.
