### ISSUE TITLE
project browser tabs appear to randomly display just `Rowan` or package name

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#229]
would e nice to always be able to see the full package name
![image](https://user-images.githubusercontent.com/623951/46686624-a8687980-cbad-11e8-85dc-727fd10c06f8.png)![image](https://user-images.githubusercontent.com/623951/46686668-c0d89400-cbad-11e8-8364-8897ab41dd97.png)

**Comment by LisaAlmarode** [comment]
When you select a package or class, the tab displays the package name.

However, if you select a method category, the tab only displays the project name.  It seems to get stuck back on the project name after that.

**Comment by dalehenrich** [comment]
My recollection of the steps  took don't quite match yours as it seems that some tabs retain the package name no matter what I do and other tabs don't ... I've assumed that it might be related to the length of the package name ... but it does seem to like certain packages ahd "hate" others:)

**Comment by dalehenrich** [comment]
oh and this bug report report pre-dates 3.0.41, so behavior might have changed

**Comment by dalehenrich** [comment]
@LisaAlmarode and @ericwinger , in 3.0.41, I have noticed that if I select a package and a class in the package then switch tabs BEFORE selecting a method, then package name sticks in the tab and I can select methods without losing the package name in tab ... so I guess we were both right:)

**Comment by ericwinger** [comment]
Should have another fix to test out in 3.0.43

**Comment by LisaAlmarode** [comment]
The tab labeling seems to work quite well now even when I try to trick it.

that is... unless you select two projects.  In this case, the tab is stuck on "Project" regardless of the selected package.

**Comment by ericwinger** [comment]
Pretty sure I've got this fixed in 3.0.45.
