### ISSUE TITLE
RowanService tests and JadeServer tests failing when run using topaz

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#230]
I assume that all of the **RowanServiceTest** and **JadeServerTest** cases are passing when you run them in Jadeite, but I am seeing failures when run in topaz. I've been consistently seeing failures of tests barked by `-->`, the the ones marked with `++>` are newly failing:
```
Rowan STON Cypress Tonel tests for GemStone '3.2.15'
548 run, 529 passed, 4 failed, 15 errors
  errors
++>	JadeServerTest>>#test_updateFromSton
++>	RowanClassServiceTest>>#testAddCategory
++>	RowanClassServiceTest>>#testClassComment
-->	RowanProjectServiceTest>>#test_addPackage
-->	RowanProjectServiceTest>>#test_updateAddsCommandResult
	RwBrowserToolApiTest>>#testMoveGlobalExtensionSessionMethods
	RwBrowserToolApiTest>>#testNewClassVersion_session_method_unchanged_extension_method_protocol
	RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
	RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
	RwRowanSample2Test>>#testNoMigration_gitolite
	STONLargeWriteReadTests>>#testUnicodeStrings
	STONReaderTests>>#testString
	STONWritePrettyPrinterReadTests>>#testUnicodeStrings
	STONWriteReadTests>>#testUnicodeStrings
	TonelCypressReaderTest>>#testLoadDefinitions
  failures
++>	JadeServerTest>>#test_jadeServerCanonicalLocation
++>	JadeServerTest>>#test_serviceUsesCanonicalJadeServer
	RwLoadingTest>>#testPoolDictionaryChanges
	RwSymbolDictionaryTest>>#testClassVersioningPatch
```
The Rowan test failures/errors are expected failures (and I am tracking those by recording this list with each of my commits) the `-->` guys have been failing for awhile, but when I looked it seemed that they were depending upon Jadeite specific things ...

Now that I am about to start working on GemTalk/Rowan#368, it probably makes sense to make an attempt get the RowanService and JadeServer tests running in topaz --- since that is the way I run all of my validation tests...

**Comment by ericwinger** [comment]
@dalehenrich 
I haven't run any server tests through Topaz before. What code do you use to invoke them?

**Comment by ericwinger** [comment]
And, fyi - the JadeiteServer* instance reuses the Topaz session state slot 3 so I wouldn't expect tests that rely directly on JadeServer to work in Topaz. Only in Jadeite. 

Please let me know if there is another session state slot that is safe from both GemStone and application code that Jadeite can use.

**Comment by dalehenrich** [comment]
Regarding using the session slot ... maybe you should confer with James or invent another mechanism ... not quite sure why you need to put a class reference into a session slot ... my guess is that it is there because in Jade there are no direct references to the class itself and there needed to be a session-based reference to the class ... in the modern GemStone implementations SessionTemps is the right way to keep a class alive ... in Jadeite the class is alive because it is hooked into a persistent structure so I assume you can get rid of the session slot altogether ...

**Comment by ericwinger** [comment]
It's not a class reference, it's the **instance** of JadeServer*. That's used by Jadeite as the server entry point for all gci calls. It's also the canonical place that the services code can find it. 

(Edited for typo)

**Comment by dalehenrich** [comment]
A topaz script that runs the tests is [here](https://github.com/GemTalk/Rowan/blob/master/platforms/gemstone/topaz/rowanTestSuite.gs) part of the checkin ... this test script really should be run from topaz before every checkin ... or at a minimum before you make your merge into the candidate* branch ... it should be the second half of confirming that you can run a Rowan install from topaz ... both or these are really required ... when Issue #302 (SmalltalkCI support for Rowan) is completee, the toopaz-based tests will be run every time a push is made to github ...

**Comment by dalehenrich** [comment]
So my guess was wrong, however, the suggestion to use  `SessionTemps current` still applies

**Comment by dalehenrich** [comment]
... using `SessionTemps current` **is** the safe place to stash session temps ...

**Comment by ericwinger** [comment]
I was unfamiliar with ``SessionTemps``. It appears to be a simple dictionary. Simply adding a key like this
``SessionTemps current at: #jadeServer put: <my initialized jade server>`` 
would probably do the trick. I'll give that a try. Thanks. 

In order for Topaz to use the instance of JadeServer, it would have to have some way to initialize the instance of JadeServer itself in SessionTemps. 

Do you start topaz against a Rowan-enabled server with a script to which we could add initialization? Or is there a hook in the topaz post-login code that could be use to do the initialization?

**Comment by dalehenrich** [comment]
>Do you start topaz against a Rowan-enabled server with a script to which we could add initialization? 

The test script is expected to be run against a stone that already has Rowan installed... I would probably be best if you include the initialization of the SessionTemps slot as part of the setup/teardown of the test itself --- that way you can guard against stomping on the value if the tests are run in Jadeite ... Is there a reason that you can't just lazily initialize the slot? In Jadeite runs, presumably the GCI client sets the value and in topaz you have access to the class, so you can just create it on demand ...

**Comment by ericwinger** [comment]
> I would probably be best if you include the initialization of the SessionTemps slot as part of the setup/teardown of the test itself
....
>Is there a reason that you can't just lazily initialize the slot?

Jadeite needs the reference to that object to be stored on the client so it can send gci calls to it. I don't think setup/teardown in the test would work because it would replace the instance the instance Jadeite relies on. However, lazy initialization that explicitly sets the SessionTemps might work as long as that is the only place that sets it. I'll give it a try. Will add comment to #231.

**Comment by ericwinger** [comment]
@dalehenrich  Regarding https://github.com/GemTalk/Jadeite/issues/230#issuecomment-428664614

About how long does it take to run the entire test suite with this [script?](https://github.com/GemTalk/Rowan/blob/master/platforms/gemstone/topaz/rowanTestSuite.gs)

**Comment by dalehenrich** [comment]
the test suite itself looks like it takes a minute or so to run ... never really timed it ...

**Comment by ericwinger** [comment]
Having trouble running the topaz tests. At first I was getting test failures but now I just get this failure - ``ERROR 2336 ,  (ClientForwarderSend)``. I pushed my changes to rowan oscar #f153627

Perhaps you can find something I did wrong. It's very hard to debug in topaz. 

```topaz 1> run
| suite strm res projectNames |
        projectNames := #( 'Rowan' 'STON' 'Cypress' 'Tonel' ).
        projectNames do: [:projectName |
                "load test groups ... include deprecated packages for now"
                Rowan projectTools load
                        loadProjectNamed: projectName
                        withGroupNames: #('tests' 'deprecated') ].

        suite := Rowan projectTools test testSuiteForProjectsNamed: projectNames.
        res := suite run.
        strm := WriteStream on: String new.
  strm nextPutAll: suite name, ' for GemStone ', (System gemVersionAt: #gsVersion) printString; lf.
        strm nextPutAll: res printString; lf.
        strm nextPutAll: '  errors'; lf.
        (res errors collect: [:each | each printString ]) asArray sort do: [:each |
                strm tab; nextPutAll: each; lf].
        res failures size = 0
                ifTrue: [ ^ strm contents ].
        strm nextPutAll: '  failures'; lf.
                (res failures collect: [:each | each printString]) asArray sort do: [:each |
                strm tab; nextPutAll: each; lf].
strm contents
%
ERROR 2336 ,  (ClientForwarderSend)
topaz 1> 
```

**Comment by dalehenrich** [comment]
can you get a stack? don't you hate bug reports that say --- "it doesn't work" with no real information? ... `topaz help` and `where` are your friends (the basic commands are pretty easy to learn ... and you should probably start learning now:) ...

 `where` will give you the stack and from the stack you will see the source of the ClientForwarderSend error, `frame` will give you the args and temps for a stack frame (`help frame`) `display oops` will make it possible to inspect the objects that show up in the `frame` report as the oop of the object will be displayed .. `obj2 @<oop>` will display two levels of the object with oop <oop> I  ... rinse and repeat ... i open `vi` and take notes of the interesting objects if things get complicated (and I wish I could do the same with Jadeite) ... Personally once I've characterized a bug in topaz i make my edits in Jadeite, save to disk and then rerun tests (my test runner script installs a fresh extent, installs Rowan and runs tests so there is very little manual monkey business required ... topaz should only be needed when the error doesn't show up in Jadeite ... presumably the case for all of the failing RowanService tests ... 

this client forwarder send is clearly in your code and somewhere you must be sending a message to the client via a client forwarder I have no idea where that might be ... this is something that you probably don't want to trigger in the topaz-based tests because there is no client around to field the message ... presumably you know the spots where you send messages from the server to the client ... so the stack might be all that you need ...

**Comment by ericwinger** [comment]
Yes, (re)learning topaz is the challenge as I rarely use it.

``where`` did reveal some information. See below. Looks like a transcript write on the clone. Do you have a strategy for turning off transcript writes when you run the tests? 

I can turn them off manually with ``JadeServer theJadeiteServer uninstallTranscript`` but I suspect you've already solved this. 

```
ERROR 2336 ,  (ClientForwarderSend)
topaz 1> where
==> 1 JadeServer64bit32 (JadeServer64bit3x) >> nextPutAll: @7 line 9
2 JadeServer64bit32 (JadeServer) >> nextPut:    @3 line 3
3 [] in  ExecBlock0 (TranscriptStreamPortable) >> nextPut: @3 line 3
4 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12
5 Semaphore >> critical:                        @3 line 6
6 TranscriptStreamPortable >> nextPut:          @3 line 3
7 TranscriptStreamPortable (Stream) >> cr       @3 line 5
8 RwGsImage class >> _cloneRowanLoaderSymbolDictionary @9 line 12
9 RwGsImage class >> applyModification_254:instanceMigrator: @4 line 5
10 RwPrjLoadTool >> _loadProjectSetDefinition_254:instanceMigrator: @17 line 18
11 [] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
12 ExecBlock0 (ExecBlock) >> on:do:              @3 line 42
13 RwPrjLoadTool >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
14 RwPrjLoadTool >> loadProjectNamed:withGroupNames:instanceMigrator: @7 line 10
15 RwPrjLoadTool >> loadProjectNamed:withGroupNames: @4 line 5
16 [] in  Executed Code                          @4 line 6
17 Array (Collection) >> do:                     @5 line 10
18 Executed Code                                 @3 line 3
19 GsNMethod class >> _gsReturnToC               @1 line 1
topaz 1> 

```

**Comment by ericwinger** [comment]
>  i open vi and take notes of the interesting objects if things get complicated (and I wish I could do the same with Jadeite) ... 

In Jadeite, I open a workspace and take notes.

**Comment by ericwinger** [comment]
All the Jadeite services tests are passing now (at least for me)
```
Rowan STON Cypress Tonel tests for GemStone '3.2.17'
548 run, 540 passed, 2 failed, 6 errors
  errors
        RwBrowserToolApiTest>>#testMoveGlobalExtensionSessionMethods
        RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
        RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
        RwRowanProjectIssuesTest>>#testIssue150_branches
        RwRowanSample2Test>>#testNoMigration_bitbucket
        RwRowanSample2Test>>#testNoMigration_gitlab
  failures
        RwLoadingTest>>#testPoolDictionaryChanges
        RwSymbolDictionaryTest>>#testClassVersioningPatch
```

**Comment by dalehenrich** [comment]
I see that you are running tests on 3.2.17 ... I don't think that there is a real issue with running on 3.2.17 --- there don't seem to be any Rowan-specific differences --- it's just that it seems to be more correct to use exactly the same version of GemStone as the customer ... it only matters when it matters and a version difference could mask an issue (in theory if not practice --- I'm not personally aware of the exact differences between 3.2.15 and 3.2.17) ...
