### ISSUE TITLE
Use SessionTemps to initialize JadeServer instance

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#231]
An instance of JadeServer is required to connect Jadeite to a server. This is currently done in the client and the instance is held in session state slot 3. 

Instead of using session state slot 3 to hold an instance of JadeServer, we should store it in the SessionTemps dictionary which would allow topaz to use the JadeServer as well. See #230.

**Comment by ericwinger** [comment]
In order for Topaz to find the JadeServer instance, we should move the SessionTemps initialization to be done lazily on the server.

**Comment by ericwinger** [comment]
Fixed in Oscar 3.0.42

**Comment by ericwinger** [comment]
Not much externally to review @LisaAlmarode but you may wish to look at SessionTemps at #jadeiteServer to ensure it's there.

**Comment by LisaAlmarode** [comment]
SessionTemps empty in topaz on login but has state after running tests, and session state is empty.
