### ISSUE TITLE
Define subclass get spurious error

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#233]
If you are in the hierarchy view in the project browser and use the "add subclass menu" item to show the text to add a class, you get an error: 
    Class has unsaved changes! Copy changes to clipboard?
This is alarming but the class is in fact created just fine.

ALSO if you use the add subclass menu item in the classes view, or edit the pane text to define a new class, it does not error but it leaves the pane pink meaning unsaved edits. So while it doesn't actually produce an error, this should be fixed.

**Comment by LisaAlmarode** [comment]
Hey, it's not the same pink as unsaved method changes.  That is a sort of peach color, while the class definition is a cool pink.  What does the cool pink mean?

**Comment by dalehenrich** [comment]
similar to #228

**Comment by LisaAlmarode** [comment]
This appears to be not a problem in 3.0.74
