### ISSUE TITLE
Need Find Class/Method from console

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#235]
For convenience, enhance Jadeite to have these menu options available from the console. Preferable with a hot-key. 

- Browse Class
- Browse Implementors
- Browse Senders
- Browse References (to a class) ?

**Comment by ericwinger** [comment]
Will have a fix in 3.0.42. Included Browse Class, Implementors, and Senders but skipped References as the menu is already pretty busy.

**Comment by LisaAlmarode** [comment]
One of the following needs to be renamed.  

Console Jadeite > Browse Class 
Projects Browser Jadeite> Find Class...

If you want to keep Browse Class (rename menu item in the Projects Browser), please at least make it Browse Class...

**Comment by LisaAlmarode** [comment]
Another problem (I think): the Browse Implementors Of... also wants to do the job of Browse Implementors.  

In console workspace,  I had a left over code selection such as 

| str refs |
str := String new.

This was from an earlier test of tests.  For a new issue, I was in the projects browser then went to the Console menu item to Browse Senders Of to enter a particular string. And it didn't give me a dialog to enter my search string; it opened a method list browser on '|' .  

You get even more baffling results if you just put the cursor at some other random location, with no selection; it returns the empty list of senders of ''

Perhaps the popup console menu could get a browse senders/implementors ?

**Comment by ericwinger** [comment]
Browse Class on the console is now Find Class ... with the same hot key. 

The workspace was intercepting the browse implementors and senders on the menu bar. When it did, it picked up the selection in the workspace.  I've added browse menu items in the pop-up which (I think) alleviate the confusion. Also renamed the menu bar methods so the user can reach the dialog. 

Fixed in 3.0.45
