### ISSUE TITLE
time stamp at end of Dolphin stack dump would be useful

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#237]
`***** End of dump *****` with timestamp would mean that I could use `find` to get to the top of the dump without having to pay careful attention while scrolling up to find the top of stack ...

**Comment by ericwinger** [comment]
The stack dump comes directly from the VM and isn't modifiable in smalltalk code. However, I did wrap the stack dump to provide a findable time/date which should make it easier to search for the beginning and end of the stack dump.

Example: 
```
***** Starting Dolphin stack dump at 11:39:07 AM 11/5/2018 *****

************************** Dolphin Virtual Machine Dump Report ***************************
...
***** End of dump *****

***** Ending Dolphin stack dump started at 11:39:07 AM 11/5/2018 *****
```
