### ISSUE TITLE
long update times possible when selecting a package with `hierarchy` tab selected

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#239]
@ericwinger I know you know, but while I was waiting for a selected package to be usable, I thought I'd submit a bug:)

**Comment by dalehenrich** [comment]
... turns out that the tab is still updating:)

**Comment by dalehenrich** [comment]
**Accidentally** selecting Rowan/Rowan-Tests in project browser with Hierarchy tab selected results in "infinite loop" and I have to leave Jadeite:
![image](https://user-images.githubusercontent.com/623951/47171618-038d2100-d2be-11e8-9bda-323febad2bf3.png)
... sooo I'm bumping priority

**Comment by ericwinger** [comment]
There was a bug in the class hierarchy service code ending up with repeated classes in the tree of hierarchy services on the client. The client then got confused and ran in circles. Fix is in the server in RowanPackageService>>classHierarchy in 3.0.42.
