### ISSUE TITLE
in package browser a drag of class method ends up on instance side of target (3.0.41)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#241]

**Comment by ericwinger** [comment]
@dalehenrich Hmm, I'm not seeing this behavior.  It's possible that I fixed it when I did some other work in the drag drop area. Can you confirm if it is still happening?  I tried: 

- class method drag to new class in hierarchy & class list
- class method drag to new category in hierarchy & class list
- instance method drag to new class in hierarchy & class list
- instance method drag to new category in hierarchy & class list. 

I'm using 3.0.46

**Comment by dalehenrich** [comment]
If you can't reproduce this .... I will trust that you've got it fixed and report a new bug or reopen if it occurs again ...
