### ISSUE TITLE
`implementors in hierarchy` doesn't include method in the currently selected class?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#242]
The browser I used is in background and the selected method is `RwModificationFiletreeWriterVisitor>>processProject:`. Note that not only is this method not in the list of implementors, but an implemention from RwGsModificationTopazWriter is included and RwGsModificationTopazWriter is not even in the hierarchy of RwModificationFiletreeWriterVisitor:
![image](https://user-images.githubusercontent.com/623951/47167676-dfc4dd80-d2b3-11e8-9e9d-3cc661f31ca4.png)

**Comment by ericwinger** [comment]
I didn't have any luck reproducing this. It appears this method is not in current Rowan so I couldn't test the exact use case. Assigning to @LisaAlmarode to see if she has better luck. 

![image](https://user-images.githubusercontent.com/36212516/48232925-2021f380-e368-11e8-99d6-5afd089ed518.png)

I did notice the window caption didn't show ``Hierarchy implementors ...`` and fixed that.

**Comment by dalehenrich** [comment]
Here's a screenshot with the missing information (so this still seems to be a bug):
![image](https://user-images.githubusercontent.com/623951/48293000-c0901a80-e431-11e8-88d2-eec24b5d1aeb.png)

**Comment by ericwinger** [comment]
We weren't getting all the subclasses before searching for hierarchy implementors. Fix in 3.0.46.

**Comment by LisaAlmarode** [comment]
I can't catch out a problem in 3.0.46.  (though that doesn't mean it's not there)
