### ISSUE TITLE
`Error while processing error:` from halt in block inside #tearDown method of test

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#245]
![image](https://user-images.githubusercontent.com/623951/47170776-bc059580-d2bb-11e8-9c13-dff0a1ce6139.png)

**Comment by LisaAlmarode** [comment]
This is an old bug related to dolphin and debugger, which have both many changes as of 3.2.12; closing.  New issues should be filed if similar problems occur.
