### ISSUE TITLE
Jadeite handling project that's not committed

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#246]
This is the front end half of https://github.com/GemTalk/Rowan/issues/378.

If a project isn't committed or otherwise all nice on disk, Jadeite breaks, and it would be nice if Jadeite was a bit more tolerant.

example case:
| proj pkg cls meth |
proj := RwProjectDefinition newForGitBasedProjectNamed: 'Tashkent'.
proj repositoryRootPath: '$ROWAN_PROJECTS_HOME/Tashkent'.
Rowan projectTools create createProjectFor: proj.
Rowan projectTools load loadProjectDefinition: proj.
Rowan projectTools write writeProjectDefinition: proj.
(RowanProjectService newNamed: 'Tashkent') refresh

stack:

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $ROWAN_PROJECTS_HOME/Tashkent; git --git-dir $ROWAN_PROJECTS_HOME/Tashkent/.git --work-tree $ROWAN_PROJECTS_HOME/Tashkent log -1 --pretty=format:%h ' stdout: 'fatal: your current branch ''master'' does not have any commits yet
' failed with status: 32768 errno: 0 errStr: nil

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $ROWAN_PROJECTS_
UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitlogIn:with: @2 line 3
RwGitTool >> gitcommitShaIn: @4 line 5
RwProject >> repositoryCommitId @10 line 8
RowanProjectService >> repositorySha @3 line 3
RowanProjectService >> isSkew @6 line 3
RowanProjectService >> basicRefresh @9 line 6
RowanProjectService >> refresh @2 line 2
RowanProjectService class >> newNamed: @5 line 6
Executed Code @2 line 1
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by LisaAlmarode** [comment]
This is part of what customer reported.  RowanClassService >> update is also implicated.

The following example will produce his other walkback.  

```
| proj pkg cls meth |
proj := RwProjectDefinition newForGitBasedProjectNamed: 'Azer'.
proj repositoryRootPath: '$ROWAN_PROJECTS_HOME/Azer'.
Rowan projectTools create createProjectFor: proj.

Rowan projectTools load loadProjectDefinition: proj.
Rowan projectTools commit commitProjectDefinition: proj message: 'test'.

pkg := RwPackageDefinition newNamed: 'Baijan'.
proj addPackage: pkg.
cls := RwClassDefinition
	newForClassNamed: #Baijan
	super: 'Object'
	instvars: #(name address orderHistory)
	classinstvars: #()
	classvars: #()
	category: nil
	comment: 'a CustomerRecord holds the sales record for a customer.'
	pools: #()
	type: 'normal'.
pkg addClassDefinition: cls.

(RowanClassService forClassNamed: 'Baijan') update
```

**Comment by ericwinger** [comment]
@LisaAlmarode I'm not sure the second example is reasonable. The failure isn't related to the disk state. Rowan services presume that a class exists in the image, not just a definition. It gives a walkback because there is no class ``Baijan`` in the image. 

Here's a slightly modified version of your example. If you run it and refresh open a browser, you'll see that ``Rowan globalNamed: 'Baijan'`` exists and update works fine. In your example it does not. 

```
	| proj pkg cls projectService |
	proj := RwProjectDefinition newForGitBasedProjectNamed: 'Azer'.
	proj repositoryRootPath: '$ROWAN_PROJECTS_HOME/Azer'.
	Rowan projectTools create createProjectFor: proj.
	pkg := RwPackageDefinition newNamed: 'Baijan'.
	proj addPackage: pkg.

	cls := RwClassDefinition
		newForClassNamed: #Baijan
		super: 'Object'
		instvars: #(name address orderHistory)
		classinstvars: #()
		classvars: #()
		category: nil
		comment: 'a CustomerRecord holds the sales record for a customer.'
		pools: #()
		type: 'normal'.
	pkg addClassDefinition: cls.
	Rowan projectTools load loadProjectDefinition: proj.
	Rowan projectTools write writeProjectDefinition: proj.
```

**Comment by ericwinger** [comment]
I've got a fix for the first example. It will be in 3.0.42. Reassigning back to @LisaAlmarode  for review of second example.

**Comment by LisaAlmarode** [comment]
I'm not sure what I did to move this to done last October, but assume I was OK with the fixes, and finally close this.
