### ISSUE TITLE
HR9905: Browse references to a class in Oscar 3.0.40

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#249]
GsMethod does not understand _literalsIncludesSymbol:value: exception.
It works in earlier versions of Jadeite:
![image](https://user-images.githubusercontent.com/623951/47378517-3748bc00-d6ad-11e8-8d8f-b56703fb8a1e.png)
using Project Browser: 'Browse References`

**Comment by ericwinger** [comment]
The failure is in ``ClassOrganizer>>referencesTo:in:``, a GemStone base class, which is called by Jadeite. It's tripping over a GsNMethod-only method. 

It appears they have GsMethods in their repository. However, I didn't think this is generally recommended. 

@dalehenrich  is contacting the customer.

**Comment by dalehenrich** [comment]
Whatever the result of customer contact ... it won't be fixed in Jadeite:)
