### ISSUE TITLE
Security Issue trying to modify service class as DataCurator

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#25]
I can login to Jadeite-Oscar as DataCurator. However, opening a projects browser gets an error trying to modify a class variable in RowanCommandResult. Stack below. 

a SecurityError occurred (error 2116), An attempt was made to modify the object #'Results'->anArray( ) in objectSecurityPolicyId 1 with insufficient authorization.
SecurityError (AbstractException) >> _signalFromPrimitive: @5 line 15
RowanCommandResult class >> initializeResults @1 line 1
JadeServer64bit32 (JadeServer) >> updateFromSton: @2 line 3
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
We will need to get the oop of the object that is creating the security error and I think that means that you need to debug this using Dolphin or something  ... once you get the oop and we find out which object is causing the problem, we should be able to address the problem ...

**Comment by ericwinger** [comment]
@dalehenrich 

Thanks for the response. The code fails when initializing a class variable:

``RowanCommandResult class>>initializeResults
         Results := Array new``

The oop of the class is: 
`` RowanCommandResult asOop 35598337``

Presumably, class variable values are put in the same security policy as their class. 
I think this class (and other service classes that set a class variable) need to be in a security policy that has different authorization. Perhaps all service classes should be in a different security policy? 
``RowanCommandResult objectSecurityPolicy  anObjectSecurityPolicy, Number 1 in Repository SystemRepository, Owner SystemUser write, World read``

fyi - This is code added since Jadeite Alpha 2.0.1. 
Also, debugging in Jadeite will be difficult because the debugger doesn't work without this code.

**Comment by dalehenrich** [comment]
Class variables are problematic in a multi- user system ... if the storage is meant to be session-specific then it shouldn’t be persisted at all. The values should be stored in session temps ... if the storage is user specific (I.e., a user preference), the bales should be stored in UserGlobals ... if the values apply system-wide then class variables are appropriate ... to avoid conflicts and/or permissions issues lazy initialization should be avoided .. instead arrange for  the owner of the value to initialize the storage

**Comment by ericwinger** [comment]
Thanks, @dalehenrich. 

I believe I have worked past this issue. I've encountered what I think is an unrelated problem and have opened #31. Any guidance is appreciated.
