### ISSUE TITLE
Need logging capability in Jadeite

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#250]
It would be nice to have a feature similar to call tracing in GBS that a Jadeite customer could turn on to log server calls. 

To start, any call that comes through ``JadeServer>>updateFromSton:`` could be logged to get a sense of which services are being executed prior to a failure.

**Comment by ericwinger** [comment]
Initial cut at ston-based logging in 3.0.70.  Two files are created - one in the Jadeite working directory and the other in the gem log directory. Turn on logging from the console's Jadeite menu. Browse the logs from the console's Browse menu. Logs are integrated into one display. If no files are specified, the above directories are searched for the latest logs. **Note, because a lot of information is written to the file on each log entry, log files can get big fast. Turn on/off Logging in the Jadeite menu to reset the log file.** 

Some nice to have's would be:
- A "rolling buffer" option so a file will wrap around after a specified number of bytes are written.
- A browser that will only show the last N records. Scrolling up would show more. 
- A nicer browser.

**Comment by LisaAlmarode** [comment]
While the feature has been added (I can confirm), it's not entirely user-friendly per side comments in #495.  There is, at least, a text file at least if you need to find out anything. 

Whatever further features are needed to make this feature entirely do whatever we think it ought to do should be filed in separate issues by whoever feels the absence of said features.
