### ISSUE TITLE
`Browse Methods Containing` available from Console menu

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#251]
Very nice that senders and implementors now available, but `Browse Methods Containing` and any other general method/class menu items should be accessible as well ... basically would be nice not to have to open a project browser in order to do a query ...

**Comment by ericwinger** [comment]
Moved the existing console browse items to their own Browse menu to reduce clutter. Added ``Browse Methods Containing`` & ``Browse Literal References`` Fixed in 3.0.46.
