### ISSUE TITLE
Find string literals in addition to 'methods containing string' would be useful 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#256]
In the face of a large code base with lots of potential string matches, matching string literals narrows the field. ClassOrganizer>>referencesToLiteral: can be used ...

**Comment by ericwinger** [comment]
Added a literal reference search in the projects browser in 3.0.43 .

**Comment by LisaAlmarode** [comment]
I think it's getting wrong answers; it's finding references to the literal symbol, but not the literal string.

Define methods (in my case on the class Two):

theAString
	^'apple'
invokeA
	^self apple

The new menu item Browse Literals References, given the string apple, produces a list with only invokeA.

However, the underlying code suggested by Dale, produces only theAString. 

| str refs |
str := String new.
refs := ClassOrganizer new referencesToLiteral: 'apple' in:{Two}.
refs first do: [:ref | str add: ref selector asString; lf].
str 
'theAString
'

**Comment by ericwinger** [comment]
We were casting the input string into a symbol. Now the Literal References finds the string 'apple' in the issue example. Fixed in 3.0.45
