### ISSUE TITLE
wildcard senders and implentors don't return proper selection list

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#258]
Pattern *symboldict* returns a reasonable result, while

*symboldict:* and *SymbolDict:*  do not find the methods.
![image](https://user-images.githubusercontent.com/36212516/47593139-155c6d00-d92b-11e8-9ad8-4813e661e06f.png)

![image](https://user-images.githubusercontent.com/36212516/47593145-1a212100-d92b-11e8-87b6-d79bccd8efef.png)

![image](https://user-images.githubusercontent.com/36212516/47593152-1f7e6b80-d92b-11e8-93e0-bf7b7fda6e29.png)

![image](https://user-images.githubusercontent.com/36212516/47593156-23aa8900-d92b-11e8-92e1-300cc4644e74.png)

**Comment by ericwinger** [comment]
The pattern entered by the user is converted to an array to be used by ``_matchPatternNoCase:`` on the server. However, during the conversion process, the wildcard symbol $* was not being inserted correctly in some cases. Fix in 3.0.43

**Comment by LisaAlmarode** [comment]
Don't see a case of missing results in various combinations of case and asterisks.
