### ISSUE TITLE
RowanDebuggerTestCase failures and hangs

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#26]
In running the RowanDebuggerTestCase for the first time, I'm seeing 

- intermittent hangs (Unit Tests tab stays on yellow, but test thread is not in Process Monitor list). 
- Test failures - but unfortunately I can't get a debugger on the failure as the tests run clean individually. 

It seems to make no difference if I've set the JadeDebugger or RowanDebugger in ``RowanDebugger debuggerClass:``

Hang: 
![image](https://user-images.githubusercontent.com/36212516/43996113-ae1ad866-9d70-11e8-9d27-e149a9756dc5.png)
 
Test failures (only when running all the tests):
![image](https://user-images.githubusercontent.com/36212516/43996124-e629d2c0-9d70-11e8-91c1-7e851d5251e0.png)

**Comment by ericwinger** [comment]
Interesting side note. It appears that the debugger tests made some source code modifications. Here is what git diff looks like. Note, I didn't make any of these changes and don't recall seeing them after the latest merge of James' code. 

```$ git diff sources/RowanDebuggerTestCase.cls
diff --git a/sources/RowanDebuggerTestCase.cls b/sources/RowanDebuggerTestCase.cls
index 2a02233..c25aa1d 100755
--- a/sources/RowanDebuggerTestCase.cls
+++ b/sources/RowanDebuggerTestCase.cls
@@ -17,15 +17,9 @@ closeDebuggers
        semaphore := Semaphore new.
        list do: [:each |
                [
-                       [
-                               each view close.
-                               semaphore signal.
-                               SessionManager inputState prod.
-                       ] on: ProcessTermination do: [:ex |
-                               semaphore signal.
-                               SessionManager inputState prod.
-                               ex pass.
-                       ].
+                       each view close.
+                       semaphore signal.
+                       SessionManager inputState prod.
                ] fork. "A debugger wants to terminate the current process!!"
                semaphore wait.
                GciSession allInstances first removeEventsTriggeredFor: each.
@@ -259,17 +253,6 @@ x yourself';

                debuggerDo: [debugger resumeProcess];
                yourself.
-!
-
-test8
-       "https://github.com/ericwinger/Jade/issues/20"
-
-       self
-               assert: RowanDebugger allInstances isEmpty;
-               debuggerDo: [process := [gciSession debugString: '#(abc def) do:[:symbol | symbol size]' fromContext: nil environment: 0] fork];                "Typically ~ 180ms"
-               yourself.
-       debugger := RowanDebugger allInstances detect: [:each | true].
-       self debuggerDo: [debugger resumeProcess].
 ! !
 !RowanDebuggerTestCase categoriesFor: #closeDebuggers!public!running! !
 !RowanDebuggerTestCase categoriesFor: #debuggerDo:!public!running! !
@@ -278,12 +261,11 @@ test8
 !RowanDebuggerTestCase categoriesFor: #setUp!public!running! !
 !RowanDebuggerTestCase categoriesFor: #systemBrowser!public!running! !
 !RowanDebuggerTestCase categoriesFor: #tearDown!public!running! !
-!RowanDebuggerTestCase categoriesFor: #test1!public!running!tests! !
-!RowanDebuggerTestCase categoriesFor: #test2!public!running!tests! !
-!RowanDebuggerTestCase categoriesFor: #test3!public!running!tests! !
-!RowanDebuggerTestCase categoriesFor: #test4!public!running!tests! !
:

**Comment by jgfoster** [comment]
PR #24 adds RowanDebuggerTestCase>>test8. Your Test Runner does not have a test8. Your git diff shows that test 8 was removed. PR #24 adds code to signal a semaphore in event of process termination (to avoid hangs) and this code has been removed in your checkout. Please take another clean checkout and try again.

**Comment by ericwinger** [comment]
I got a clean checkout and tried again. These are the results with test8 present. 

![image](https://user-images.githubusercontent.com/36212516/44038391-866e6998-9ecb-11e8-8d3b-ecd01aa77182.png)

**Comment by ericwinger** [comment]
@jgfoster I was able to run 3 full test runs of RowanDebuggerTestCase. Looks like your changes in pull request #38 did the trick. Thanks! 

Closing issue.
