### ISSUE TITLE
Need a space in CommitTransaction

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#260]
Projects Browser Jadeite > CommitTransaction  has no space separating the words.

This is quite annoying although not a functional problem.

Also, I was looking on the Projects menu to Abort and couldn't find it... the Commit... confused me. I recommend changing the Projects > Commit... to Commit to Git... to reduce ambiguity.

Checkout likewise is git specific and might be better Checkout Git Branch...  the others seem less backend-internals-specific.

**Comment by ericwinger** [comment]
All three will be fixed in 3.0.44.
