### ISSUE TITLE
Console debug-it does nothing if selected expression has temp variables

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#262]
The debug menu item in the console tends to ignore me and execute code without starting a debugger.  It turns out it hates temporary variables. 

Debug this just does an execute:
| ps |
ps := RowanProjectService newNamed: 'RowanSample1'.
ps refresh

While Debug on this opens the debugger:
(RowanProjectService newNamed: 'RowanSample1') refresh

**Comment by ericwinger** [comment]
Should have a fix in 3.0.53. Server only.
