### ISSUE TITLE
With class selected, but not method selected, in SUnit tab, project refresh gets error

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#263]
Load RowanSample1
Select RowanSample1-Test project and RowanSample1Test class (do not select method)

Go to SUnit tab.  Select something and use the little running guy to run tests.

Now to go to the Jadeite menu bar item and refresh (not the popup in the projects pane)
See error dialog: 
JadeSUnitInClassPresenter does not understand #refreshFromServer

**Comment by ericwinger** [comment]
Fixed in 3.0.46. Tested, too. Also found an unreported bug where the sunit tests were sticking around even though the test class was not selected.
