### ISSUE TITLE
Method List Browser Comparison tab contents are sticky (3.0.74)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#264]
In the Projects Browser, navigate to Rowan | Rowan-Definitions | RwAbstractClassDefinition | | compareAgainstBase:.

Click on the comparison tab.  See the class and superclass versions full of yellow-highlighted text.

Now use the implementors menu item to get implementors of compareAgainstBase:. The first method on the list is the one in the class and it's selected. 

Click on the comparison tab.  See emptiness.     
I think having a tab with the same name next to a tab labeled Method Source is misleading and confusing. Comparison should have a particular meaning, and I was expecting to see the comparison with superclass. This is not the bug yet, though.

Then, click on RwPackageDefinition.  Control-click on RwPackageSetDefinition, such that both are selected.  Now, the comparison tab is populated.  

Then, go back and select RwAbstractClassDefinition (not double click, you will end up with only this one selection).  Then click on Comparison.  Content!  But it's the wrong content - it's still got the comparison of RwPackageDefinition and RwPackageSetDefinition, neither of which are currently selected.

**Comment by LisaAlmarode** [comment]
The example is still demonstrating the error, but it's a bit complicated. 

Easy case: 

1. Open a list browser on implementors of asString.
2. Select Boolean and BinaryFloat, and then the Comparison Tab.  See the distinctive asString methods.

3. Now select another class, such as Abstract Exception.  Click on the Comparison Tab.

Error: It's still showing the comparison between Boolean and Binary Float.

![image](https://user-images.githubusercontent.com/13142166/63062014-240d1400-beac-11e9-8ad5-2822673de2a9.png)

**Comment by ericwinger** [comment]
The comparison tab was a little flaky probably because it hadn't been touched in a long time. 
Needed to do a better job of resetting it when selecting a new method. Also, brought the method list browser's code in this area more in line with the project browser. 

Believe I've fixed up the identified problems and a few more in 3.0.76.
