### ISSUE TITLE
logout closes project browsers but not method list browsers

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#267]
I'd like logout to close all open browsers, inspectors, method list browsers, debuggers and so on.  The method list browsers, at least, stick around, as of 3.0.45.

**Comment by ericwinger** [comment]
I believe that the method list browsers close properly in 3.0.45. However, it's possible that you found an "old-style" method list browser that isn't hooked up to logout on close. Or, you might be using a logout that I'm not familiar/aware of. (On the console, I go to File>Exit Jadeite)

If you can give me a few more specifics I might be able to find it.

**Comment by dalehenrich** [comment]
I occasionally see windows left around ... I always close the console to exit Jadeite ... I'll pay more attention the next time it happens ...

**Comment by dalehenrich** [comment]
I just had a case where I closed the console and both the console and SUnit test browser were left open ... this happened when I had shut the stone down **before** closing the console ... i get the "stone gone" dialog and the windows associated with session are not closed ... this is likely to be the case that I see "occasionally"...

**Comment by ericwinger** [comment]
If the server is lost without the gci session knowing about it, windows wouldn't be closed. Now, if the logout fails we still destroy all the registered Jadeite windows. Fixed in 3.0.46

**Comment by LisaAlmarode** [comment]
In 3.0.46, opened a debugger, then from this opened implementors, dictionaries browser and inspector.  If I close the console, the debugger shuts down but the other three windows are still there - and I still have a session, senders of produces results. This session appears really stuck; a new login has [2] in the title.

If I execute "System shutDown" prior to closing console, same; the debugger closed but the other three windows get errors "UndefinedObject does not understand #session:oopForString:"

**Comment by ericwinger** [comment]
Turns out the debugger window terminates the thread that closes it. Since Jade seems to think that's important (and debuggers are weird that way) I'm reluctant to take out the termination. Instead, I've reworked the window closing to do the debugger last. Not a perfect fix but should be better than leaving every other window open if a debugger is closed first. Fixed (again) in 3.0.47.

**Comment by LisaAlmarode** [comment]
Logout in 2.0.48 still left open the method list and  inspector opened from the debugger, although the debugger itself was closed.
Before:
![before](https://user-images.githubusercontent.com/13142166/48578613-05eb9680-e8cf-11e8-8261-f74fee0b973c.jpg)
after:
![after](https://user-images.githubusercontent.com/13142166/48578617-097f1d80-e8cf-11e8-8e3a-09d6585138e5.jpg)

**Comment by ericwinger** [comment]
Found a place in the code that was sending a super class implementation of ``onCloseRequested:`` which preempted the previous fix.  Fix (or at least an attempted fix) in 3.0.49.
