### ISSUE TITLE
3.0.45 - shortcut CTL-S brings up senders dialog instead of saving workspace in console workspace

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#268]
![image](https://user-images.githubusercontent.com/623951/48171223-cb22a680-e2af-11e8-9fc4-780a9108fc2f.png)

**Comment by ericwinger** [comment]
As noted, Ctrl-S should save a workspace to a file. However, Ctrl-S was overloaded by senders. 

Changed the hotkey for senders to Ctrl-Shift-S to avoid the overload. Also changed implementors to Ctrl-Shift-I.

**Comment by ericwinger** [comment]
Fixed in 3.0.46
