### ISSUE TITLE
SUnit Browser fragile in the face of change 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#273]
If I have the SUnit browser open, and do stuff in the projects browser, the SUnit browser tends to get walkbacks like the one below. 

The most reliable way to reproduce it is: with Sunit browser open on the text class, put a breakpoint on a test method.  click on a different test class in the sunit browser, then back on the original.  see walkback.

It also happens when I a new test method, and go back and click off and on the class again... but I think it might have taken an extra step. 

a Error occurred (error 2007), reason:rtErrShouldNotImplement, A method was invoked that has been sp
Error (AbstractException) >> _signalWith: @6 line 25
Error (AbstractException) >> signal @2 line 47
Interval class (Object) >> _error:args: @15 line 11
Interval class (Object) >> shouldNotImplement: @2 line 10
Interval class >> new: @2 line 5
Interval class (SequenceableCollection class) >> new:streamContents: @2 line 3
Interval class (SequenceableCollection class) >> streamContents: @2 line 2
Interval class (SequenceableCollection class) >> fromSton: @2 line 2
STONReader >> parseObject @6 line 5
STONReader >> parseValue @8 line 5
STONReader >> parseMapDo: @17 line 11
Association (Object) >> fromSton: @9 line 10
Association class (Object class) >> fromSton: @3 line 6
STONReader >> parseObject @6 line 5
STONReader >> parseValue @8 line 5
STONReader >> parseListDo: @9 line 8
[] in  ExecBlock1 (STONReader) >> parseList @2 line 5
Array class (SequenceableCollection class) >> new:streamContents: @5 line 4
Array class (SequenceableCollection class) >> streamContents: @2 line 2
STONReader >> parseList @5 line 4
STONReader >> parseValue @16 line 9
STONReader >> parseMapDo: @17 line 11
RowanMethodService (Object) >> fromSton: @9 line 10
RowanMethodService class (Object class) >> fromSton: @3 line 6
STONReader >> parseObject @6 line 5
STONReader >> parseValue @8 line 5
STONReader >> parseListDo: @9 line 8
[] in  ExecBlock1 (SequenceableCollection class) >> fromSton: @2 line 3
OrderedCollection class (SequenceableCollection class) >> new:streamContents: @5 line 4
OrderedCollection class (SequenceableCollection class) >> streamContents: @2 line 2
OrderedCollection class (SequenceableCollection class) >> fromSton: @2 line 2
STONReader >> parseObject @6 line 5
STONReader >> parseValue @8 line 5
STONReader >> parseMapDo: @17 line 11
RowanClassService (Object) >> fromSton: @9 line 10
RowanClassService class (Object class) >> fromSton: @3 line 6
STONReader >> parseObject @6 line 5
STONReader >> parseValue @8 line 5
STONReader >> parseListDo: @9 line 8
[] in  ExecBlock1 (STONReader) >> parseList @2 line 5
Array class (SequenceableCollection class) >> new:streamContents: @5 line 4
Array class (SequenceableCollection class) >> streamContents: @2 line 2
STONReader >> parseList @5 line 4
STONReader >> parseValue @16 line 9
STONReader >> parseMapDo: @17 line 11
RowanPackageService (Object) >> fromSton: @9 line 10
RowanPackageService class (Object class) >> fromSton: @3 line 6
STONReader >> parseObject @6 line 5
STONReader >> parseValue @8 line 5
STONReader >> parseListDo: @9 line 8
[] in  ExecBlock1 (STONReader) >> parseList @2 line 5
Array class (SequenceableCollection class) >> new:streamContents: @5 line 4
Array class (SequenceableCollection class) >> streamContents: @2 line 2
STONReader >> parseList @5 line 4
STONReader >> parseValue @16 line 9
STONReader >> next @3 line 4
STON class >> fromStream: @4 line 2
STON class >> fromString: @3 line 2
JadeServer64bit32 (JadeServer) >> updateFromSton: @3 line 4
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
@LisaAlmarode  Not much luck reproducing. I think you might be running into a class that STON is not happy with for some reason. Maybe Interval. Can you let me know what classes you're clicking on to get the walkback? 

```
...
Interval class (Object) >> _error:args: @15 line 11
Interval class (Object) >> shouldNotImplement: @2 line 10
Interval class >> new: @2 line 5
Interval class (SequenceableCollection class) >> new:streamContents: @2 line 3
Interval class (SequenceableCollection class) >> streamContents: @2 line 2
Interval class (SequenceableCollection class) >> fromSton: @2 line 2
...
```

**Comment by LisaAlmarode** [comment]
Clone and load rowansample4
Open SUnit browser and go look at rowansample4test, run test1, 
in PB, got to rowansample4 test > test2, set break on bar.
back in SUnit browser, click on STON-Tests  
Click back on rowansample4test,, run test1, and test2 
click on STON-Tests  
Click back again on rowansample4test,,  Now I see the stack, where it's trying to read the following 

'[RowanPackageService{#name:''RowanSample4-Tests'',#isDirty:false,#command:#testClasses,#commandArgs:[],#updateType:#''testClasses:'',#defaultTemplate:''Object rwSubclass: \''NameOfSubclass\''\n\tinstVarNames: #()\n\tclassVars: #()\n\tclassInstVars: #()\n\tpoolDictionaries: #()\n\tcategory: \''RowanSample4-Tests\''\n\toptions: #()\n'',#projectName:''RowanSample4'',#testClasses:[RowanClassService{#name:''RowanSample4Test'',#commandArgs:[],#comment:'''',#isExtension:false,#version:1,#versions:1,#template:''TestCase rwSubclass: \''RowanSample4Test\''\n\tinstVarNames: #()\n\tclassVars: #()\n\tclassInstVars: #()\n\tpoolDictionaries: #()\n\tcategory: \''RowanSample4-Tests\''\n\toptions: #()\n'',#oop:54597121,#filters:[],#methods:OrderedCollection[RowanMethodService{#commandArgs:[],#source:''test1\n\n\tself assert: RowanSample4 new foo = \''foo\'''',#selector:#test1,#category:''tests'',#packageName:''RowanSample4-Tests'',#projectName:''RowanSample4'',#className:#RowanSample4Test,#meta:false,#hasSupers:false,#hasSubs:false,#isExtension:false,#inSelectedPackage:false,#stepPoints:[Association{#key:1,#value:''''},Association{#key:35,#value:#new},Association{#key:39,#value:#foo},Association{#key:43,#value:#''=''},Association{#key:14,#value:#''assert:''},Association{#key:49,#value:''''}],#accessedInstVars:[],#breakPoints:[],#oop:54599169,#testResult:''failure'',#definedPackage:''RowanSample4-Tests''},RowanMethodService{#commandArgs:[],#source:''test2\n\n\tself assert: RowanSample4 bar = \''bar\'''',#selector:#test2,#category:''tests'',#packageName:''RowanSample4-Tests'',#projectName:''RowanSample4'',#className:#RowanSample4Test,#meta:false,#hasSupers:false,#hasSubs:false,#isExtension:false,#inSelectedPackage:false,#stepPoints:[Association{#key:Interval[1,2,3,4,5],#value:''''},Association{#key:Interval[35,36,37],#value:#bar},Association{#key:Interval[39,40],#value:#''=''},Association{#key:Interval[14,15,16,17,18,19,20],#value:#''assert:''},Association{#key:Interval[45,46],#value:''''}],#accessedInstVars:[],#breakPoints:[2],#oop:54600193,#definedPackage:''RowanSample4-Tests''},RowanMethodService{#commandArgs:[],#source:''testError\n\n\tself assert: RowanSample4 new bar = \''bar\''\n'',#selector:#testError,#category:''tests'',#packageName:''RowanSample4-Tests'',#projectName:''RowanSample4'',#className:#RowanSample4Test,#meta:false,#hasSupers:false,#hasSubs:false,#isExtension:false,#inSelectedPackage:false,#stepPoints:[Association{#key:1,#value:''''},Association{#key:39,#value:#new},Association{#key:43,#value:#bar},Association{#key:47,#value:#''=''},Association{#key:18,#value:#''assert:''},Association{#key:54,#value:''''}],#accessedInstVars:[],#breakPoints:@19,#oop:54599681,#definedPackage:''RowanSample4-Tests''},RowanMethodService{#commandArgs:[],#source:''testFailure\n\n\tself assert: RowanSample4 new foo = \''bar\''\n'',#selector:#testFailure,#category:''tests'',#packageName:''RowanSample4-Tests'',#projectName:''RowanSample4'',#className:#RowanSample4Test,#meta:false,#hasSupers:false,#hasSubs:false,#isExtension:false,#inSelectedPackage:false,#stepPoints:[Association{#key:1,#value:''''},Association{#key:41,#value:#new},Association{#key:45,#value:#foo},Association{#key:49,#value:#''=''},Association{#key:20,#value:#''assert:''},Association{#key:56,#value:''''}],#accessedInstVars:[],#breakPoints:@19,#oop:54600705,#definedPackage:''RowanSample4-Tests''}],#packageName:''RowanSample4-Tests'',#definedPackageName:''RowanSample4-Tests'',#selectedPackageServices:[],#selectedMethods:[],#projectName:''RowanSample4'',#categories:OrderedCollection[''testSelector''],#isTestCase:OrderedCollection[''tests''],#expand:true}]}]'

**Comment by ericwinger** [comment]
It appears that the ``testClasses`` inst var was not being cleared properly upon a replication to the server. Only use that inst var when returning. This is a possible fix in 3.0.47.

**Comment by dalehenrich** [comment]
@ericwinger ... remember that you can ship selected instance variables over the wire instead of having to remember to clear them before sending them over wire?

**Comment by ericwinger** [comment]
@dalehenrich I didn't have much luck with selective sending and receiving of select inst vars when I worked on it some time ago.  I can't remember the specific problems but they seemed insurmountable at the time. It was easier to just clear the inst vars.

**Comment by dalehenrich** [comment]
It was a pretty simple formula ... if you want to do selectively send ivs I can supply you with sample code ... up to you:)

**Comment by LisaAlmarode** [comment]
SUnit browser no longer fragile.

BUT it still doesn't show updated tests well. If I add test4 over in the Project Brower, I'd expect either that the SUnit browser would automatically update, or that there would be some manual way e.g. refresh, to update the SUnit browser other than clicking to another package and back.

**Comment by LisaAlmarode** [comment]
Refresh moved to new issue #279.  Close the breaking part of this issue.
