### ISSUE TITLE
Jadeite.errors and *.stb files left in Oscar-3.0.46 runtime.zip

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#276]
These should be cleaned up ... picture taken after downloading [Oscar-3.0.46/runtime.zip](https://github.com/GemTalk/Jadeite/releases/download/Oscar-3.0.46/runtime.zip) and renaming:
![image](https://user-images.githubusercontent.com/623951/48454493-4c74b000-e76c-11e8-9bca-476138729297.png)

Just a friendly reminder:)

**Comment by ericwinger** [comment]
Removed in 3.0.47.
