### ISSUE TITLE
nice to have the Jadeite version visible on the Jadeite launch

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#277]
Note that I've got 5 different versions of Jadeite on my desktop:
![image](https://user-images.githubusercontent.com/623951/48455383-cc504980-e76f-11e8-85a8-9d21845a0faa.png)
... which means that before I press the login button, I have to click three times to confirm that the launcher is the right version(menu, help, ok) ... and there are times when I have three different versions of Jadeite launchers open ... 

The login button would be a cool place to put the version ... but I can learn to look anywhere in the launcher if it is visible:)

**Comment by ericwinger** [comment]
It was easy enough to put in the window caption. This is what it looks like (except the version won't be Development).  Fixed in 3.0.48. 

![image](https://user-images.githubusercontent.com/36212516/48572991-db461180-e8bf-11e8-97e2-52d8396d4bfe.png)

**Comment by LisaAlmarode** [comment]
I might prefer it still included the word "login" but I'm good with this.
