### ISSUE TITLE
(3.0.46) cannot tell at glance which _hierarchy_ classes have extension methods for the selected package

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#278]
![image](https://user-images.githubusercontent.com/623951/48517443-2fe38100-e81b-11e8-82ed-0faeb463d82d.png)
I don't know if this has been discussed already, but I would *like* to be able to tell at a glance which classes have extension methods from the currently selected package ... Number and Integer are the only ones:
![image](https://user-images.githubusercontent.com/623951/48517655-daf43a80-e81b-11e8-9f45-f8c3e0a5942c.png)
I do indeed like seeing the full hierarchy for the classes, but I *would* like to be able to tell which classes have extension methods for the given package in the hierarchy ...

**Comment by dalehenrich** [comment]
Number and Integer should be purple to indicate that they have extension methods ... whether or not you are in hierarchy view ... this is still a problem in 3.0.56

**Comment by LisaAlmarode** [comment]
I believe this is the same as the problem reported as bug 497.  Closing this in favor of the more recent bug.
