### ISSUE TITLE
Sunit browser refresh, auto or manual

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#279]
If you have the SUnit browser open and add a test in the Project Browser, the new test isn't visible and there's no obvious way to refresh.  Other than clicking to another class and back.

**Comment by ericwinger** [comment]
Both the sunit browser and sunit tab should more or less update if methods are added or removed from the class. It was a decent size change so I expect a bug or three. Fixed in 3.0.49

**Comment by LisaAlmarode** [comment]
Sunit Browser broken - I can select a package but when I select a class I get an error:

JadeiteSUnitPresenter does not understand #classListPresenter

**Comment by LisaAlmarode** [comment]
I'm getting this same error all over the place... selecting a class in the projects browser and in the method list browser when I try the popup menu in the list pane, or the Methods menu bar item.

**Comment by ericwinger** [comment]
yes, looks like another runtime-only bug. I'll investigate.

**Comment by ericwinger** [comment]
Several methods got put in the test package. Moving them to the base package fixed the problem. Fix in 3.0.50.
