### ISSUE TITLE
Method List Browser debug option and Run Tests 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#280]
Control-B normally debugs selected code.  This is missing from the method list browser. The method text pane popup menu does not have a debug it option.

Also, I think the Run Tests menu item should be renamed Run Test in cases where it only runs the selected test.  It's most confusing in the Method List Browser, but it's not correct in the Project Browser method list pane.

**Comment by ericwinger** [comment]
Believe that this is fixed as of 3.0.49. Ctrl-B should debug selected tests in a list or open a debugger on selected text in a source pane.
