### ISSUE TITLE
Workspace-related items on other menus

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#281]
In the method list browser, the Jadeite menu has present but disabled, the menu items
   New workspace 
   Open system browser
   commit transaction

Makes no sense that these are disabled.

It has a method item save that is enabled.  This results in an error dialog:
  JadeiteMethodListPresenter does not understand #halt

In the inspector, there are also new workspace/open workspace options that are disabled.  I kinda think all those menu items on the inspector should probably go away.

**Comment by ericwinger** [comment]
Should have a fix for these menu items in 3.0.49.  Because menu items are so hard to get right in an ad-hoc  approach, I'd recommend we open a new issue to review the menu items on all the Jadeite windows with an eye for consistency.

**Comment by LisaAlmarode** [comment]
There needs to be a space in the method list browser item CommitTransaction .
No Nits Too Small (tm)

**Comment by ericwinger** [comment]
Fixed in 3.0.50
