### ISSUE TITLE
Workspace that persists through logout

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#282]
In GBS I'm used to workspaces that hold code that I won't lose if I log out and in again.  I miss this.   Perhaps it's not possible <sad face>

**Comment by ericwinger** [comment]
@LisaAlmarode  The only place Jadeite has that's session-neutral is the login window.  I could add a workspace there that doesn't go away on logout. If that is desirable, what should it be called?  Workspace?

**Comment by LisaAlmarode** [comment]
With the jadeite preferences allowing me to auto-open a workspace, this feature magically has been implemented!
