### ISSUE TITLE
(3.0.46) `git log` window left open after closing console window

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#283]
![image](https://user-images.githubusercontent.com/623951/48593289-fdac4f00-e900-11e8-8866-9eddc0f6c763.png)

**Comment by LisaAlmarode** [comment]
Easy to reproduce in 3.0.58, project menu item log opens a window and that stays open after logout.

**Comment by ericwinger** [comment]
Fixed in 3.0.59. Log browser needed to be a Jadeite shell. 
https://github.com/GemTalk/Jadeite/commit/ffce2a942ceccb194f080d5c3d278a87c438fc55
