### ISSUE TITLE
(3.0.49 and 3.0.50) project browser not updated properly on reload of project

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#284]
Here's the setup:
![image](https://user-images.githubusercontent.com/623951/48649994-64854300-e9a9-11e8-930f-9dc6b35190df.png)
1. Created _old method and it is selected in browser above)
2. select project list and then load the Rowan project (which will delete the new method)
3. old method is still selected (looks exactly the same, but I know that the method is gone
4. click off the method then on the method and get walkback:
![image](https://user-images.githubusercontent.com/623951/48650048-95fe0e80-e9a9-11e8-8474-0871dc943c22.png)

Here's the stack:
```
a LookupError occurred (error 2021), reason:rtErrKeyNotFound, A reference using the non-existent key #'addOrUpdateClassDefinition_old:type:superclass:instVarNames:classVars:classInstVars:poolDictionaries:category:packageName:options:' was made into the dictionary RwPrjBrowserTool
LookupError (AbstractException) >> _signalWith: @5 line 25
LookupError (AbstractException) >> signal @2 line 47
RwPrjBrowserTool class (Object) >> _error:args: @15 line 11
RwPrjBrowserTool class (Behavior) >> compiledMethodAt:environmentId: @5 line 9
RwPrjBrowserTool class (Behavior) >> compiledMethodAt: @2 line 2
RowanMethodService >> forClass:organizer: @6 line 7
RowanMethodService >> initialize:organizer: @29 line 20
RowanMethodService >> update @8 line 4
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @6 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by dalehenrich** [comment]
in 3.0.50, the method does not actually disappear until I click of and on the class ...

**Comment by ericwinger** [comment]
@dalehenrich This appears to be a bug that has existed for awhile. Do you consider this a show-stopper for the current release candidate 3.0.50?

**Comment by dalehenrich** [comment]
I am inclined to say yes ... abort clears up the method and I would expect that abort and reload to be equivalent operations, so I vote yes.

Is the project browser correctly updated for added/remove classes and methods when a load is done?

**Comment by ericwinger** [comment]
> Is the project browser correctly updated for added/remove classes and methods when a load is done?

I'll have to investigate.

**Comment by dalehenrich** [comment]
After [getting a method compiled in wrong category](https://github.com/GemTalk/Jadeite/issues/290#issuecomment-439633044), I thought this would be a perfect time to see what happens in the project browser if I do a lode/reload of a project and the following is the result:
![image](https://user-images.githubusercontent.com/623951/48663858-0c068200-ea4b-11e8-95eb-26fd83ce694c.png)
This is harsh.

When I abort in this situation, the project browser visibly updates but leaves you in the same state as you started with ... which would be preferred for the load case as well ... not really much difference between abort and load when it comes to the effect on the browser state

**Comment by ericwinger** [comment]
Refreshing properly in all situations is a large challenge, but I have a fix that addresses this issue in 3.0.51.

**Comment by LisaAlmarode** [comment]
in 3.0.51, if you have a class and method selected and reload the project using the console project list, added methods blip away and all is sunshine and roses.

If you reload the project using the project browser projects pane, all your selection goes away and you have to start again with selecting the package.   I think this is what Dale described as "harsh"; reopening this to determine if it's possible to be less harsh.

**Comment by ericwinger** [comment]
Less harsh refresh added in Oscar 3.0.52.
