### ISSUE TITLE
(3.0.50) method drag drop only drags a single method when multiple methods selected?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#286]
I had two method selected in ProjectBrowser but when I dragged them to the other class, only one method was transferred ... I could have sworn that in the past multiple method drag drop worked ... but that may have been months ago:)

**Comment by LisaAlmarode** [comment]
I'm running into this in 3.0.56.  I'm annoyed, so prioritizing this as an annoyance bug.

**Comment by ericwinger** [comment]
Fixed in 3.0.57. Should be able to drag multiple methods to new classes now.
