### ISSUE TITLE
(3.0.50) debugger "browse" menu disabled when on frame on nested block ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#287]
Interrupts the flow of debugging if you have to switch frames to do senders:
![image](https://user-images.githubusercontent.com/623951/48654969-690c2480-e9c6-11e8-98cb-8885b6a1c830.png)

**Comment by LisaAlmarode** [comment]
While I agree with this point, I've given up trying to make certain client application GUI developers handle block contexts as if they were the actual methods that you actually see.

**Comment by ericwinger** [comment]
In spite of the snarky comments, this was fixed in 3.1.0 by certain a client application GUI developer. :)

**Comment by LisaAlmarode** [comment]
Hey, the snarkiness worked!
