### ISSUE TITLE
(3.0.50) methods don't get displayed when switching from instance to class in project browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#288]
Note that `support` category is selected on the instance side:
![image](https://user-images.githubusercontent.com/623951/48663645-f17ed980-ea47-11e8-82a7-16dd6563f603.png)
Now click on `Class` button and note that there are no methods visible clicking below the categories in the category pan does not cause the list of methods to appear (I use this regularly to view all methods):
![image](https://user-images.githubusercontent.com/623951/48663669-46225480-ea48-11e8-9927-e18f16f16312.png)
Clicking on a category and then clicking below finally shows the methods I would have expected to see initially:
![image](https://user-images.githubusercontent.com/623951/48663698-b0d39000-ea48-11e8-85eb-81bdfea93f84.png)

**Comment by LisaAlmarode** [comment]
The given reproduction case, the methods are visible after clicking on class, in 3.0.74
