### ISSUE TITLE
Browse references to a class, or senders/receivers: get "Unrecognized response" error dialog

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#29]
This is in a Dictionaries Browser.  Select a dictionary, category, class.  Use menu item Browse References.  Happens for both rowanized and base classes.
Or select a method and try senders or receivers or browse history.

<snip snip>
{04F906F0: cf 04F906D1, sp 04F90704, bp 04F906EC, ip 4, RowanSystemBrowserPresenter(Object)>>error:}
	receiver: a RowanSystemBrowserPresenter
	arg[0]: 'Unrecognized response'

{04F906D0: cf 04F906B1, sp 04F906E4, bp 04F906CC, ip 24, RowanSystemBrowserPresenter(JadeSystemBrowserPresenter)>>browseClassReferences}
	receiver: a RowanSystemBrowserPresenter
	stack temp[0]: nil
<snip snip>

**Comment by ericwinger** [comment]
Had inadvertently taken out the response type return value in the dictionary browser code. May have larger impact on various menus. Will be checked in for 3.0.9.
