### ISSUE TITLE
(3.0.50) wrong methods displayed when switching from a superclass to subclass

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#290]
Note that the `running` category is selected, but the methods displayed are not in the `running` category:
![image](https://user-images.githubusercontent.com/623951/48663799-22600e00-ea4a-11e8-90a0-d7fec9157702.png)

**Comment by dalehenrich** [comment]
Note that if I don't notice that wrong category is selected and edit a method ... when I save the method is moved to the (imporperly) selected category:
![image](https://user-images.githubusercontent.com/623951/48663825-7d920080-ea4a-11e8-8ecc-59f5f4ff28f5.png)

**Comment by LisaAlmarode** [comment]
When you move between sub/super classes in the hierarchy view, it appears to be using the last category in the category list to decide what methods to display.  Sometimes there is no category selected, and sometimes it has the wrong category selected. 

(1) In the subclass, add a category that comes after all existing categories alphabetically, and is not present in the superclass. Define a method in that category.  Do not commit to GemStone.  select the superclass.   Select again on the subclass.  No category is selected, but the newly created method is shown in the list, implying that's the only method in the class.  

(2) Now, in the superclass, define a category that matches the first (alphabetically) category.  Select this in the superclass.  Now select the subclass (remember, this is in the hierarchy class view).  See that the first, matching category is selected, but the methods in the second category are displayed.

**Comment by ericwinger** [comment]
We were updating the service filters in the wrong class list. Should be fixed in 3.0.51.
