### ISSUE TITLE
(3.0.5.0) nice to have `browse class` option on test in SUnit browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#292]
I wanted to go to the class, but I had the method already selected to run the test and when i got the message browser, I had to search around for the `browse class` menu item`:
![image](https://user-images.githubusercontent.com/623951/48664539-ce0e5b80-ea54-11e8-9d08-9affae9dacf3.png)

**Comment by LisaAlmarode** [comment]
The class has a popup menu item browse class.  I suspect that this is a request to also have a browse class on the method menu.  I don't think it makes sense to have it both places, and it's logical to be on the class and not on the method pane menu.
