### ISSUE TITLE
(3.0.50) not sure I like the fact that all SUnit results in browser are cleared when a test method is changed

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#293]
On the one hand I understand why it might be done, but on the other hand when I'm working on a single test case in a test with lots of test cases, I like the fact that the SUnit browser was preserving the history of the various tests ... I would be able to quickly select the test for running .... because it had failed before ... I'd fix failing tests in order ... so once I fixed a failing test I would move onto the next failing test without having to rerun the whole shebang and lose my place ...

**Comment by LisaAlmarode** [comment]
This is seems related to #410 and should be considered.

**Comment by ericwinger** [comment]
Can I assume that this is referring to the SUnit tab in the Projects browser?  And not the stand-alone SUnit browser?

**Comment by dalehenrich** [comment]
This is an issue with the stand-alone SUnit browser ...

**Comment by LisaAlmarode** [comment]
Applies to Project Browser too, but harder to reproduce.

If you have two project browsers open, and modify a method, it flips the other one with the text results to show a method (not the same one), that was reported elsewhere.  So we don't know yet if this bug applies to the project browser.  

If you have tests results in an PB sunit tab and open a method browser on a method in that class, it clears test results too.

**Comment by LisaAlmarode** [comment]
This is not entirely correct in 3.0.60.

If you have two project browsers open on a test class.
In one, go to the sunit tabe and run tests.
In the other class, edit a method.  

Test results in the SUnit tab in the other project browser are cleared, though the SUnit browser isn't cleared.

**Comment by ericwinger** [comment]
@LisaAlmarode Between #410 and this issue, it's not clear what is supposed to be fixed nor do I see what error is being described by the comments. Can you please either create a new issue with a clear reproduction case? If it's multiple issues, adding a task list will help me.

**Comment by LisaAlmarode** [comment]
Closing in favor of #432
