### ISSUE TITLE
would be nice if text menu was available in the log view...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#299]
thought I might be able to find and copy the sha using the log view ... foiled again:)
![image](https://user-images.githubusercontent.com/623951/48676023-95828680-eb15-11e8-8bdf-a31813161da6.png)

**Comment by dalehenrich** [comment]
Looks CTL-C is availalbe, but I only found it because I'm desperate:) ... now if only I could remember the shortcut for find:)
![image](https://user-images.githubusercontent.com/623951/48676046-ea260180-eb15-11e8-8865-8a174440d0d4.png)

**Comment by dalehenrich** [comment]
alas CTL-F does not appear to be enabled:(

**Comment by LisaAlmarode** [comment]
The log is indeed a very lame window.  I think the menu name "log" is a bit off-putting.  It would be more likely to be used if it was "display git log" or something.  However, then the window would need to be un-lamed.   It is nice information if you are wondering what's going on with the git.

**Comment by ericwinger** [comment]
To promote user happiness the log tool is now more like a workspace with Ctrl-F available and several other workspace like features. Fixed in 3.0.75. 

![image](https://user-images.githubusercontent.com/36212516/63189664-4ff9d800-c019-11e9-8e1b-f00da4e18308.png)
