### ISSUE TITLE
would be nice to have `browse references to class` here as well

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#300]
![image](https://user-images.githubusercontent.com/623951/48676613-f6ae5800-eb1d-11e8-813f-5a7055cae49d.png)
tedious to be required to navigate from the method where I see *a reference* to the class to a browse window on the class just to bring up the list of references ...

**Comment by LisaAlmarode** [comment]
I don't really know the priority but it seems like a possible value.

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.76. ``Browse Class References`` on transcript Browse menu. Can use ``*`` wildcard to avoid typing long class names.

**Comment by LisaAlmarode** [comment]
If you are on the console pane of the workspace, clicking on the new menu item brings up an error dialog with 
   CodeSourcePresenter does not understand #selectedClassName

But it does work if you're on the projects pane.

**Comment by ericwinger** [comment]
Menu item code inherited from Jade is inconsistent but this menu item should work properly in all console tabs in 3.0.77.  Some refactoring done as well.
