### ISSUE TITLE
(3.0.50) inconsistent selector selection on double-click

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#301]
I used double-click on keyword in both method list browser and project browser ... the project browser does it **right**, includinge the $: in the selection ... the method list browser does it **wrong*:
![image](https://user-images.githubusercontent.com/623951/48873510-173b1400-eda3-11e8-853e-b9c96a0d760b.png)
I prefer the **right** way, but it is probably more important to be consistent:)

**Comment by dalehenrich** [comment]
double-click in debugger is also **wrong**:
![image](https://user-images.githubusercontent.com/623951/48874432-0d67df80-eda8-11e8-98bc-728ca6dd3359.png)
Note that when a frame is selected the **right** selection is made ... only double-click is letting us down:)

**Comment by LisaAlmarode** [comment]
This is annoying. I was a little confused by what Dale meant: this is a double click on any word within the text of a method. When you double click it selects "the whole word".  Should the selection include a trailing colon : or not?   Dale is a colon-includer and I would agree.

This means fixing the way double click selects in the method list and the debugger.

Alternately, a colon-excluder would fix the project browser.

**Comment by ericwinger** [comment]
No colon left behind! (colons now included in debugger double click) ...  Fixed in 3.0.75.
