### ISSUE TITLE
Unable to load Rowan into a clean 3.2.15 repository

### ISSUE THREAD

**Issue by jgfoster** [ericwinger/Jade#32]
I've updated to the latest Rowan:
```
vienna:Rowan jfoster$ git log
commit 0fcdfc55f4829172cc9bf162352e4894ab943b74 (HEAD -> james, upstream/oscar, origin/james, oscar)
Author: Eric Winger <eric.winger@gemtalksystems.com>
Date:   Mon Aug 13 14:38:16 2018 -0700

    project changes refactored
```

I have a script that is modeled on the Rowan README and includes the following:
```
input $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/3.2.15/install.tpz
```

This script stopped working as of 998c984. Are you able to load Rowan into a brand new 3.2.15 database?

**Comment by ericwinger** [comment]
@jgfoster I'm looking into this now.

**Comment by ericwinger** [comment]
@jgfoster  James, I've refactored the problematic methods and am able to run the rowan install script again. I'm also able to login to a server with the latest code. All changes pushed to the Oscar branch.
