### ISSUE TITLE
(3.0.50) I would have thought that the literal string 'filetree' would have been found...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#328]
Perhaps this is a GemStone issue?

![image](https://user-images.githubusercontent.com/623951/48923354-b70ba700-ee62-11e8-9143-b6c9bcf07d17.png)

The result of the above is an empty method list browser

**Comment by LisaAlmarode** [comment]
If you search for 'filetree' you don't get any results, but I'd bet if you searched for filetree you would find them.  The quotes are part of what is searched for.  An example that works in current code would be name vs. 'name'.

Since these are literal references there's no particular need to include single quotes.  However, consider a literal such as ' found.'  This is just awkward and weird to not leave the quotes in, but it doesn't find results with.

I think it would be preferable to strip off leading/traling single quotes.  However, we would want to see what this does to our ability to find '''name''' (a literal with embedded single quotes)

**Comment by dalehenrich** [comment]
....the use of `'filetree'` was intended to find the literal string: 'filetree' ... when searching for a literal, I would assume that I need to specify a literal ... `#filetree` would search for the literal symbol refs ... `#( 1 2 3)` would search for the literal array refs ... 1.0 would search for the literal `1.0` ... etc. ... at least this is my interpretation of searching for a literal ... 

I was almost glad that I **didn't** take your bet until I found that '.filetree' was matched:
![image](https://user-images.githubusercontent.com/623951/49112101-bc903500-f246-11e8-9404-0d9b1b7febcf.png)

In tODE i did implement the literal search feature that returned all of the above search results ... IIRC, I did have to fix some bugs related to literal searches in the ClassOrganizer ...

**Comment by LisaAlmarode** [comment]
Dale, I'm pretty sure the search did not find '.filetree', it's just the highlight of the search item in the results is not very clever.  There's an actual 'filetree' in the method a bit lower down which would have been what was found by the search part.

However, it does look like Eric and I conflated "literal" and "literal string" such that this feature in fact does not use the functionality of referencesToLiteral:.  I wrote methods with literals (see below) and run some code and searches. 

ClassOrganizer returns correct results; Jadeite Browse Literal References... not so much. (3.0.51).

This is the ClassOrganizer validation code:

| lits str |
lits := { 'gilgamesh' . '''gilgamesh'''  . #gilgamesh . #tutankamen . 6661666  . 6666.6666 . #[66 66 1 66 66] . #(6666 1 6666) }.
str := String new.
lits do: [:aLit |
	str add: aLit printString; space.
	((ClassOrganizer new referencesToLiteral: aLit)
		first collect: [:ea | ea selector]) do: [:aRef | str add: aRef printString; lf].
	].
str
 '''gilgamesh'' #''literalString1''
''''''gilgamesh'''''' #''literalString3''
#''gilgamesh'' #''literalSymbol1''
#''tutankamen'' #''literalSymbol2''
6661666 6.6666665999999996E03 #''literalFloat''
aByteArray( 66, 66, 1, 66, 66) #''literalByteArray''
anArray( 6666, 1, 6666) #''literalArray''
'

I'm thinking that Dale intends the search results to correspond.  

In the case if you enter gilgamesh with no single quotes, it will either - literal does not exist error?  Or assume the uses meant a string literal?

These are the methods.

{ #category : 'literals' }
Carrot >> allLiterals [
"literals include gilgamesh and other stuff"

^ { 'gilgamesh' . '''gilgamesh'''  . #gilgamesh . #tutankamen . 6661666  . 6666.6666 . #[66 66 1 66 66] . #(6666 1 6666) }
]

{ #category : 'test' }
Carrot >> another [
        ^5
]

{ #category : 'test' }
Carrot >> interesting [
        ^5
]

{ #category : 'literals' }
Carrot >> literalArray [
        ^#(6666 1 6666)
]

{ #category : 'literals' }
Carrot >> literalByteArray [
        ^#[66 66 1 66 66]
]

{ #category : 'literals' }
Carrot >> literalFloat [
        ^6666.6666
]

{ #category : 'literals' }
Carrot >> literalFraction [
        ^6666/16666
]

{ #category : 'literals' }
Carrot >> literalInteger [
        ^666616666
]

{ #category : 'literals' }
Carrot >> literalString1 [
        ^'gilgamesh'
]

{ #category : 'literals' }
Carrot >> literalString2 [
        ^'gilgamesh.ordinary'
]

{ #category : 'literals' }
Carrot >> literalString3 [
        ^'''gilgamesh'''
]

{ #category : 'literals' }
Carrot >> literalSymbol1 [
        ^#gilgamesh
]

{ #category : 'literals' }
Carrot >> literalSymbol2 [
        ^#tutankamen
]

**Comment by dalehenrich** [comment]
> Dale, I'm pretty sure the search did not find '.filetree', it's just the highlight of the search item in the results is not very clever. There's an actual 'filetree' in the method a bit lower down which would have been what was found by the search part.

If the search had been for the literal `'filetree'`, then I presume the `'.filetree'` would not have been matched by the search function ... 

> I'm thinking that Dale intends the search results to correspond.

You would be correct:)

> In the case if you enter gilgamesh with no single quotes, it will either - literal does not exist error? Or assume the uses meant a string literal?

If we are going to be literal about literals, then it should be an error ... In tODE I evaluated the string passed in to the search method and I expected the result to be a literal ... I assume something similar will have to be done ... 

In terms of showing the results of the search,  #referencesToLiteral: does include an array of indexes for the location in the method where the literal was found and I think that it is almost required to use that array of indexes, since a simple string match search will **not** work for the literal array, literal bytearray and symbol cases, because the #printString of these literals (and others?) may not match the  formatting in the method source.

**Comment by LisaAlmarode** [comment]
The index offsets from referencesToLiteral: are not working as far as I can tell in base GemStone... it's acting like it's doing a string search.  I get the first string matching as the index 9 (that's why it's highlighting .filetree). For literal float, array, bytearray , referencesToLiteral: seems to return 0.  
I filed a bug on gemstone,  47829.

**Comment by LisaAlmarode** [comment]
The first thing to do is at least make sure the dialog provides instructions to use single quotes or not...

**Comment by dalehenrich** [comment]
Since this issue was related to the original issue (#256) and it was a `Help Wanted` request I figure we should at least address the `dialog label` for the January release ... bumped to P1 as well

**Comment by ericwinger** [comment]
@LisaAlmarode I'm having trouble understanding the specific complaint. If I do a ``Browse Literal References...`` I would expect that if I type in ``filetree`` the resulting method list would show any method that has ``'filetree'`` in it's source - which it currently does.  Can you provide clarification on what needs to be fixed in Jadeite?

**Comment by dalehenrich** [comment]
`filetree` is not a literal string. `'filetree'` **is** a literal string ... if I use `1` in browse literal references, is that a SmallInteger or a string?

**Comment by ericwinger** [comment]
Maybe what is needed is an additional ``Browse Literal String ...`` search so the common use case could be done without having to remember whether to enter quotes or not.

**Comment by dalehenrich** [comment]
Before we go too far ... I believe there are several issues here ... 
1. **I** expected that a menu item labeled `Literal References` would take a string and interpret that as a Smalltalk literal (... yes compile the string) ... so naturally I typed in a literal string.
2. the method highlighting mechanism in the Method Browser **does not** do literal matching, so even if you do a literal search, the highlighting mechanism would not highlight only the literals without also finding partial string matches.

If you change the menu item label to be `Literal String references` and fix the method browser to only do exact string matches then I think that you would actually satisfy the original requirements ... as it stands the methods containing the literal string are returned and it isn't that egregious to wade through the false matches produced my the method browser (if any)...

I would like to have a `Literal References` menu item for those occasions when finding references to a Smalltalk literal like `1` or `true` or `#at:` is what you really need to do and when I saw the `Literal References` menu item, I (mistakenly) thought I'd gotten my wish:)

**Comment by ericwinger** [comment]
To summarize the issues to fix: 
- [x] Change Literal References menu option to compile the input string, then search. Change instructions in dialog accordingly. 
- [x] Review the highlighting mechanism for both searches.

**Comment by dalehenrich** [comment]
I don't understand what you mean by the second bullet point ... are you intending to have two literal search menu items?

**Comment by ericwinger** [comment]
Yes.  It fits with your comments and what I believe will be most useful - A Literal String search for the common case and a Literal Reference search for more complex cases.

**Comment by dalehenrich** [comment]
Since literal searches aren't that common in the first place, I would think that a single literal object search (that takes a Smalltalk expression that evaluates to a literal) would be more than sufficient ... but, it is your call and I rest my case:)

**Comment by ericwinger** [comment]
Yeah, ``Browse Methods Containing...`` handles the string case well enough even though you may get more back then you want. I'll see if I can make ``Literal References`` handle compiled code and review the highlighting code in the method list browser.

**Comment by dalehenrich** [comment]
yes ... I think that the string literal search use case is very similar the other literal use cases --- you use a literal search when you are searching for a literal that has too many false positives in the `method containing` case: `1`,  `true`, `'1'`, `'true'`, etc ...

**Comment by ericwinger** [comment]
Fixed in 3.0.72. Literal references now compiles the expression entered in the dialog. 

Unfortunately, the highlighting of the method list's first reference to the literal is done in the client which doesn't have access to the server results for browse literal references. Instead it just does a string search. Opening a new bug to move around functionality so that the highlighting matches the actual literal if the server can provide it.

**Comment by LisaAlmarode** [comment]
The string search is good.

I'm finding flaws with the literal search, but they all seem to be coming from the Class organizer.  E.g., it apparently only finds literal integers that are >= 4096, except it does find any small integer that is in a literal array. 

However, I do see that the find literals option is not on the method list (annoyingly for my testing).  But this resulted in further opinions on menus which I'll report separately.
