### ISSUE TITLE
(3.0.50) very long delay when clicking around after commit (before it finished?)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#331]
Jadeite appeared to be frozen in this state for  a few minutes:
![image](https://user-images.githubusercontent.com/623951/49049642-bd688e80-f194-11e8-966c-fb30207c4175.png)
It would beep when I clicked but otherwise was not responding and the `executing expression` dialog remained transparent for the duration ... not long after I made the screenshot (after I figured the display was frozen) and while I was copying the snapshot ... the `executing expression` dialog disappeared and I was back in business ...

I have a feeling that a second commit click while the first commit click was still running caused the `freeze` either that or the commit/update was taking an inordinate amount of time ...

**Comment by LisaAlmarode** [comment]
Closing this as stale; Dale, reopen if you see it again.
