### ISSUE TITLE
right mouse drag gives dolphin errors

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#338]
If you right-click and drag, both the Dolphin development environment (Dolphin 7.0.56) and the run-time image get a ``nmBeginRDrag:`` error. 

This appears to be a bug in the Dolphin initialization code; ``ListView class>>initializeNotificationMap`` is not getting run. By explicitly running this initialization at the end of the ``BootJade.st`` startup script we eliminate the problem in the dev environment. The runtime executable picks up the fix when the dev environment is correct. 

Made the above-noted change to the``BootJade.st`` script in Oscar 3.0.52.

**Comment by LisaAlmarode** [comment]
See comments on #334... this issue may underlie that bug.  I found no problems with right-drags execept for the hierarchy view in the class pane, so I'm calling this done although possibly some part of this was backed out with the backup of the fix in 334.
