### ISSUE TITLE
Errors browsing code

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#339]
Debugger when browing Notification because of deprecated error (same for all subclasses of Exception)
![image](https://user-images.githubusercontent.com/1958382/49399611-97903c00-f6f6-11e8-8c9e-9afeb0abb30c.png)

I'm guessing there are no testcases in NonCoreTestCase class
![image](https://user-images.githubusercontent.com/1958382/49399829-3f0d6e80-f6f7-11e8-95fe-29436bf26124.png)

**Comment by LisaAlmarode** [comment]
Same as issue #507.  We could ignore the Dictionary Browser, but the same thing now happens in in the Project Browser.
