### ISSUE TITLE
Unused method temps in method, compile gets Index 0 is out of bounds error

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#34]
Compiler in the project browser doesn't handle warnings.

Try compiling this method:
flutter	
	| asdf |
	^self isAlive

And you get an Index 0 is out of bounds error.
If you compile a second time, it does work...

Snippet from Jadeite.ERRORs:

{05050B20: cf 05050AF9, sp 05050B34, bp 05050B14, ip 31, [] in RowanMethodService(Object)>>fromSton:}
	receiver: a RowanMethodService
	arg[0]: compilationWarnings
	arg[1]: 'WARNING: unused method temp 'asdf'\0A\'

{05050AF8: cf 05050AD1, sp 05050B0C, bp 05050AEC, ip 45, STONReader>>parseMapDo:}
	receiver: a STONReader
	arg[0]: [] @ 25 in Object>>fromSton:
	stack temp[0]: compilationWarnings
	stack temp[1]: 'WARNING: unused method temp 'asdf'\0A\'

{05050AD0: cf 05050AA9, sp 05050AE4, bp 05050AC8, ip 33, RowanMethodService(Object)>>fromSton:}
	receiver: a RowanMethodService
	arg[0]: a STONReader
	stack temp[0]: a Array

{05050AA8: cf 05050A89, sp 05050AC0, bp 05050AA4, ip 6, RowanMethodService class(Object class)>>fromSton:}
	receiver: RowanMethodService
	arg[0]: a STONReader

{05050A88: cf 05050A61, sp 05050A9C, bp 05050A7C, ip 8, STONReader>>parseObject}
	receiver: a STONReader
	stack temp[0]: RowanMethodService
	stack temp[1]: a STONReference
	stack temp[2]: nil

{05050A60: cf 05050A3D, sp 05050A74, bp 05050A5C, ip 12, STONReader>>parseValue}
	receiver: a STONReader
	stack temp[0]: $R

{05050A3C: cf 05050A19, sp 05050A54, bp 05050A34, ip 20, STONReader>>parseListDo:}
	receiver: a STONReader
	arg[0]: [] @ 20 in STONReader>>parseList
	stack temp[0]: 1

{05050A18: cf 050509F9, sp 05050A2C, bp 05050A14, ip 25, [] in STONReader>>parseList}
	receiver: a STONReader
	arg[0]: a WriteStream

{050509F8: cf 050509D1, sp 05050A0C, bp 050509EC, ip 6, Array class(SequenceableCollection class)>>new:streamContents:}
	receiver: Array
	arg[0]: 100
	arg[1]: [] @ 12 in STONReader>>parseList
	stack temp[0]: a WriteStream

{050509D0: cf 050509B1, sp 050509E4, bp 050509CC, ip 6, Array class(SequenceableCollection class)>>streamContents:}
	receiver: Array
	arg[0]: [] @ 12 in STONReader>>parseList

{050509B0: cf 0505098D, sp 050509C4, bp 050509A8, ip 27, STONReader>>parseList}
	receiver: a STONReader
	stack temp[0]: a STONReference
	stack temp[1]: nil

{0505098C: cf 0505096D, sp 050509A0, bp 05050988, ip 28, STONReader>>parseValue}
	receiver: a STONReader
	stack temp[0]: $[

{0505096C: cf 0505094D, sp 05050980, bp 05050968, ip 4, STONReader>>next}
	receiver: a STONReader
	stack temp[0]: nil

{0505094C: cf 0505092D, sp 05050960, bp 05050948, ip 5, STON class>>fromStream:}
	receiver: STON
	arg[0]: a ReadStream

{0505092C: cf 0505090D, sp 05050940, bp 05050928, ip 13, STON class>>fromString:}
	receiver: STON
	arg[0]: '[RowanMethodService{#oop:54469377,#source:'flutter\t\n\t| asdf |\n\t^self isAliv...'

{0505090C: cf 050508E5, sp 05050920, bp 05050900, ip 6, BrowserUpdate>>update:afterStonReplication:}
	receiver: a BrowserUpdate
	arg[0]: a Array
	arg[1]: '[RowanMethodService{#oop:54469377,#source:'flutter\t\n\t| asdf |\n\t^self isAliv...'
	stack temp[0]: nil

{050508E4: cf 050508C1, sp 050508F8, bp 050508DC, ip 6, JadeiteProjectsBrowserPresenter(JadePresenterA)>>update:afterStonReplication:}
	receiver: a JadeiteProjectsBrowserPresenter
	arg[0]: a Array
	arg[1]: '[RowanMethodService{#oop:54469377,#source:'flutter\t\n\t| asdf |\n\t^self isAliv...'

{050508C0: cf 0505089D, sp 050508D4, bp 050508B8, ip 49, JadeiteProjectsBrowserPresenter(JadePresenterA)>>issueCommand:}
	receiver: a JadeiteProjectsBrowserPresenter
	arg[0]: a Array
	stack temp[0]: '[RowanClassService{#name:'Moth',#command:#'saveMethodSource:category:',#commandA...'
	env temp[0]: '[RowanMethodService{#oop:54469377,#source:'flutter\t\n\t| asdf |\n\t^self isAliv...'

**Comment by ericwinger** [comment]
Compilation warnings now give message instead of walkback. Fixed in 3.0.9
