### ISSUE TITLE
Add links to jadeite and rowan github projects to Jadeite

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#340]
Per Eric's question in issue #194; yes, I think we should have links to the jadeite and rowan github projects in Jadeite, along with the less-useful-to-users link to the gemtalk website.

I think these should be on both the console help menu and the login help menu.  I think they won't be found if only on the login dialog, but they should be on the login dialog in case you can't get to the console...

**Comment by ericwinger** [comment]
Github links added to login shell and console in 3.0.52.
