### ISSUE TITLE
Run sunit tests from class pass when they should not

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#341]
Consider RowanSample1Test, which has three passing tests, one testError and one testFailure.  
You get a nice mix of results from the Sunit Browser, and if you go to a method in this class and open the SUnit tab. 

If I select the class in the class pane and use the popup menu item "run tests" to run tests on the class, they ALL pass.

![image](https://user-images.githubusercontent.com/13142166/49460382-0aa4bb80-f7a6-11e8-851c-0f1e4a680b12.png)

**Comment by regkrock** [comment]
This is the same issue as #335.

**Comment by ericwinger** [comment]
Fixed in 3.0.53. Server was not properly finding test methods in that path. Actual fix in server code.

**Comment by LisaAlmarode** [comment]
When I run tests from the class menu item, it seems to do a debug-all rather than run-all.  Using RowanSample1Tests as an example, it opens a debugger on the first test error; I expected it to run to completion and show the SUnit tab.  It does that only if all tests pass.

**Comment by ericwinger** [comment]
@LisaAlmarode I'd like to keep this consistent with the Run Tests option on the method menu. The method menu option performs a debug. Also, if there are a lot of tests and you press Run Test on the class, the suite has to run to completion even if you made a dumb mistake and every test breaks. 

To run a suite of tests in a class without stopping for errors I use the SUnit browser.

**Comment by LisaAlmarode** [comment]
I think we have overloaded the term "run" to mean sometimes "run and show results with icons" and sometimes "run until assert or error and show debugger".  While debug also means the second of those. 

The Sunit browser operations menu items make sense to me; run all, run selected, debug (infer selected). Do we also have a debug all somewhere?  Is it useful?  If it's consistency, we might fix the method menu as well as the class menu, rather than spreading the confusion in the name of consistency.

I can't imagine wanting to to a debug-all from the class menu.  I actually don't think anyone uses this (since it was only me that found that it really meant "pass-all".  If it's too risky to run we can take it off? If it does a debug-all and there are no errors then it's no different than run-all and running to completion, from there or anywhere, correct?

**Comment by dalehenrich** [comment]
> The Sunit browser operations menu items make sense to me; run all, run selected, debug (infer selected). Do we also have a debug all somewhere? Is it useful?

tODE has a `debug all` in the test browser that I've used to debug test failures that only show up when running the full suite (unintended side effects between tests) ... I've also used it in cases where I've put a `halt` in a method when I'm interested in taking a peek at test coverage (in tODE halts are caught by the test driver and treated as errors) ... I've also used this when there are so man errors showing up that I can't decide which one to tackle first:) ... so it is useful when you need it (like the side effects case) but not used all of the time ...

**Comment by ericwinger** [comment]
@LisaAlmarode  - I have removed the ``run tests`` menu item from the class list pane per issue #336. Does this issue then become a mute point?  If not, please open a new bug with specific instructions on what needs changed.

**Comment by LisaAlmarode** [comment]
I think the removal of the class menu item avoids any actual confusion between run and debug.

I think "Run tests" in the projects browser methods pane, and method list browser, should be be "run selected" to match the Sunit browser, and also be clear and specific.

**Comment by LisaAlmarode** [comment]
the main point fixed; side issues have been separately discussed, closing this.
