### ISSUE TITLE
Can't use method menu in method list browser method list pane

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#344]
in 3.0.51, when I have a method selected in the method list browser, and the mouse is positioned over the selected method, and I attempt to right-click to open the menu... I get an error.  Also happens if I hover over the Methods menu bar.
UndefinedObject does not understand #isEmpty

I can bring up the menu in the empty space... but it un-selects the selected method.  It disables senders, but browese hierarchy senders/implementors are available (they should not be... it throws an error that exactly one object must be selected).

**Comment by ericwinger** [comment]
believe this is fixed in 3.0.52
