### ISSUE TITLE
Jadeite format option (server ready)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#345]
With GemTalk/Rowan#404, support was added at the server level (issue_404 branch off of candidateV1.2 branch).

This issue is a placeholder/reminder that formater can be added to Jadeite at any time ... that makes sense.

**Comment by ericwinger** [comment]
@dalehenrich If memory serves, there was some work to do to put the formatter code, ``RBParser`` into the current Oscar branch. Is this ready to merge?  (It's a good time for me to integrate it) 

![image](https://user-images.githubusercontent.com/36212516/55359193-18352e00-5486-11e9-9461-81b2f2b0a97f.png)

**Comment by dalehenrich** [comment]
Yes ... the code is ready to be merged ... I'll let you know when it is available on candidateV1.2

**Comment by dalehenrich** [comment]
[merged into candidateV1.2](https://github.com/GemTalk/Rowan/issues/404#issuecomment-479502251), so you're ready to go ... let me know if you need anything else.

**Comment by ericwinger** [comment]
Fixed in 3.0.74. Ctrl-Shift-F works in both projects & method list browsers

**Comment by LisaAlmarode** [comment]
Contrary to assertion in Eric's comment, in 3.0.74, the formater is control-shift-o

project browser with cursor in a method, control-shift-F opens a find class dialog.  
method list browser, with cursor in a method, control-shift-F causes a little red ACK to appear.

The project browser has undo option grayed out; the method list browser has the undo enabled, but it doesn't work.  That this is enabled and not working is technically a bug.  My main interaction with auto formatting is how to recover from accidentally autoformatting... undo would be nice, but this is a bit minor for reopening... 

Autoformat has such approval as I can give; I'll leave it to people who intentionally format code to find anything wonky.
