### ISSUE TITLE
Debugger - In Method Pane, Sender and Implementer Menu Items disaapear on method which has a breakpoint

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#347]
In the debugger, when right clicking on the method with the breakpoint, the 'browse implementers' and 'browse senders'  menu items are not visible. 

See image below for example.

![image](https://user-images.githubusercontent.com/7550442/49654278-6325c400-fa05-11e8-9cc1-a6251a7dc4ce.png)

**Comment by LisaAlmarode** [comment]
This is the same as issue #223.
