### ISSUE TITLE
`debug it` not working as expected

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#348]
When one uses "debug it" from the menu for the first (4 line) code snippet it behaves like "Execute it". No halt is added at the beginning. No debugger appears.

Debugging "1 printString" behaves as expected. An extra nil halt is prepended and a debugger pops up.

![image](https://user-images.githubusercontent.com/623951/49661464-f6f39200-f9fd-11e8-86aa-19e7df92a814.png)

**Comment by dalehenrich** [comment]
If this is still a bug then it should be included in the January release ...

**Comment by LisaAlmarode** [comment]
I think this is the same as issue #262... the temporary variables flummox the debug it.

**Comment by dalehenrich** [comment]
Thanks, @LisaAlmarode. Is #262 aimed targeted for inclusion in January release?

**Comment by LisaAlmarode** [comment]
I would say yes - this is upsetting; I hate it when code ignores me. I've been waiting til after we stablize/3.0.52 before doing a triage.

**Comment by dalehenrich** [comment]
sounds good ...

**Comment by LisaAlmarode** [comment]
I would say yes - this is upsetting; I hate it when code ignores me. I've been waiting til after we stablize/3.0.52 before doing a triage.
