### ISSUE TITLE
After method compile problem, UndefinedObject DNE select:

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#35]
Say you get a compile error, either issue 34 or just a syntax error, e.g.

flutter	
	^(true

Then click on a different method category and in the dialog, select No.
See error dialog.   Interesting bit of Jadeite.ERRORs is below.

If I select the class tab and instance tab, it clears up whatever the problem is.
Changing to the variables tab doesn't help.

{056907A8: cf 05690789, sp 056907BC, bp 056907A4, ip 4, Object>>doesNotUnderstand:}
	receiver: nil
	arg[0]: Message selector: select: arguments: #([] @ 47 in RowanClassService>>computeVisibleMethods )

{05690788: cf 05690769, sp 0569079C, bp 05690784, ip 54, RowanClassService>>computeVisibleMethods}
	receiver: a RowanClassService
	stack temp[0]: nil

{05690768: cf 05690741, sp 0569077C, bp 0569075C, ip 2, RowanClassService>>displayMethodsOn:}
	receiver: a RowanClassService
	arg[0]: a ListPresenter
	stack temp[0]: nil
	stack temp[1]: nil

{05690740: cf 0569071D, sp 05690754, bp 05690738, ip 43, JadeiteProjectsBrowserPresenter>>refreshMethodsOn:}
	receiver: a JadeiteProjectsBrowserPresenter
	arg[0]: a ListPresenter
	stack temp[0]: a RowanClassService

**Comment by ericwinger** [comment]
The list of methods can be legitimately nil in the class service if we got an error. When we're refreshing methods, do a double-check that we have methods. If not get them. Checking in to 3.0.9.
