### ISSUE TITLE
Browse references from dictionary browser doesn't show anything

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#350]
if called from hierarchy view.

**Comment by LisaAlmarode** [comment]
Note: it's not that it doesn't find existing references, it actually does nothing at all and just sits there.  
Since it's just the deprecated dictionary browser this might not be a big problem.

**Comment by ericwinger** [comment]
Even though the dictionary browser will eventually get rolled into the projects browser, this is annoying enough to warrant a fix. The fix will be in Oscar 3.0.53.

**Comment by ericwinger** [comment]
Should fix #360 too
