### ISSUE TITLE
Ability To Change Fonts in the non-source code portions of the windows

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#351]
The current windows take up to much window real estate. It would be very useful to be able to change the fonts just as one can change the fonts in the source code pane.

**Comment by LisaAlmarode** [comment]
I agree this is a handy feature.

**Comment by LisaAlmarode** [comment]
Recently discovered existing feature (console icon bar, leftmost icon that looks like a hand picking a menu), opens up a rather unattractive preferences dialog that allows you to control the system font.
