### ISSUE TITLE
Create method on class not in selected package, method disappears

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#352]
In the project browser, select a project, extensions package, extensions class, category, and method. See some class that is purple, then categories and methods.  

Fine a purple or black method.  Edit selector to create a new method.  Save.

Whoosh, the purple class is selected while the category and method panes are white space.

I suspect this is new in 5.0.52 although it might have been missed since it's specific to purple extension classes.

**Comment by LisaAlmarode** [comment]
Similar behavior on reload cf issue #284.  Note to self: when this is fixed retest that behavior too.

**Comment by ericwinger** [comment]
Fix in 3.0.54.

**Comment by LisaAlmarode** [comment]
This issue is probably the same as #375.  Verified that it is fixed in 3.0.56.  
However, retest of #284 shows that particular angle is not fixed for extension classes...  filed #408.
