### ISSUE TITLE
Debugger has inferior status bar, and opens dialog for unused temps (3.0.74)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#353]
Unused temp flagged in debugger:

![image](https://user-images.githubusercontent.com/623951/49766552-78f7eb00-fc8a-11e8-9f91-0f2daa1810ea.png)

but not in project browser or method browser ...

I almost like the warning, but one way or the other, we should be consistent

**Comment by LisaAlmarode** [comment]
I agree... I kind of like the warning too.

**Comment by LisaAlmarode** [comment]
As of 3.0.74, there's a warning in the status bar for unused temps.  It's still an error dialog in the debugger.  Now I would prefer a warning status bar in the debugger.  

Compile errors do appear in the status bar of the debugger so this is not impossible.  

The debugger status bar does not go dark pink, it stays the simple gray.

**Comment by ericwinger** [comment]
The status bar should now behave like the other browsers when compiler warnings & errors happen in the debugger. The pop-up is eliminated. 3.0.76.
