### ISSUE TITLE
Comments added to Class Documentation when in viewing the class in hierarchy mode are assigned to the last class

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#355]
I added a comment for ZnIncomplete but it was saved in ZnInvalidUTF8.

This is only a problem when in hierarchy mode. It works in the Classes mode.

![image](https://user-images.githubusercontent.com/7550442/49887150-8f788080-fe09-11e8-8e94-00a546f1a783.png)

**Comment by LisaAlmarode** [comment]
Definitely broken.

**Comment by ericwinger** [comment]
"Definitely" fixed in 3.0.53.  :)
