### ISSUE TITLE
Walkback, rather than error, when attempt to add duplicate category

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#357]
To Reproduce:

Add a category and commit.
Then attempt to add the same category and the following walkback occurs.

a ImproperOperation occurred (error 2032), reason:classErrMethCatExists, An attempt was made to create the method category 'instance creation' which already exists.  Class:  ZnNullEncoder class.
ImproperOperation (AbstractException) >> _signalWith: @5 line 25
ImproperOperation (AbstractException) >> signal @2 line 47
Metaclass3 (Object) >> _error:args: @15 line 11
Metaclass3 (Behavior) >> addCategory:environmentId: @9 line 11
Metaclass3 (Behavior) >> addCategory: @2 line 2
RowanClassService >> addCategory: @7 line 7
RowanClassService (RowanService) >> servicePerform:withArguments: @2 line 2
RowanClassService >> servicePerform:withArguments: @4 line 4
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by LisaAlmarode** [comment]
It doesn't error or walkback now: it quietly brings you to the existing category with that name. Open to debate as to if that's correct, but it's reasonable, so closing this.
