### ISSUE TITLE
(3.0.52) browse menu item in Method Browser opens browser, but doesn't select the method

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#358]
I expected that the selected method in Method Browser would be selected in the Project Browser as well:
![image](https://user-images.githubusercontent.com/623951/49907151-c65e8e80-fe29-11e8-875e-bc08a0a4b4f1.png)

**Comment by dalehenrich** [comment]
@LisaAlmarode suggests that `Browse Class` be changed to `Browse method` and always select the method ... it is a *method browser* after all and you get the class *for free*

**Comment by LisaAlmarode** [comment]
Magically, in v3.0.57, the method list browser browse class also selects the method in the browser. I think this is a better menu name since browse method implies method browser.
