### ISSUE TITLE
pull from git does a push ?

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#36]
I think I should be able to do a pull from git and load, on Rowan, to update to the latest using Jadeite.

When I use the Projects List Browser > pull from Git  I get this error:

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $ROWAN_PROJECTS_HOME/Rowan; git --git-dir $ROWAN_PROJECTS_HOME/Rowan/.git --work-tree $ROWAN_PROJECTS_HOME/Rowan push origin oscar' stdout: 'To git@github.com:dalehenrich/Rowan.git
 ! [rejected]        oscar -> oscar (fetch first)
error: failed to push some refs to ''git@github.com:dalehenrich/Rowan.git''
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., ''git pull ...'') before pushing again.
hint: See the ''Note about fast-forwards'' in ''git push --help'' for details.
' failed with status: 256 errno: 0 errStr: nil

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitpushIn:with: @2 line 3
RwGitTool >> gitpushIn:remote:branch: @4 line 3
RowanProjectService >> pushToGit @8 line 6
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Whoops. Had one place fixed, but not the other. Fixed in 3.0.9.
