### ISSUE TITLE
Browse Class References from Hierarchy returns nothing.

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#360]
Browsing class references when in 'Hierarchy' mode returns nothing. It does work in 'Classes' mode.

![image](https://user-images.githubusercontent.com/7550442/49958020-9b327880-fed7-11e8-819b-d9c7425efc55.png)

**Comment by LisaAlmarode** [comment]
I believe this is the same as #350

**Comment by regkrock** [comment]
It does look like it is the same issue from what I can see.

**Comment by ericwinger** [comment]
See #350
