### ISSUE TITLE
Projects Browser load doesn't work correctly for update

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#37]
I have a project loaded.  In projects browser, select a class, delete three method categories which each have one method, and add a method in a new category.  Then I use menu item project load to reload the disk version.

It deletes added methods (but leaves added method categories),
but it does not add back the deleted methods or method categories.  If I open a new projects browser or a dictionaries browser, I see the incorrect set of method categories/methods

The project refresh gets error "JadeiteProjectsBrowserPresented does not understand #refresh.  
The Jade list of project refresh makes no difference.

The project list load does load correctly, this is specific to the Projects browser load.  After loading from the project list, I can use the and the jade list-of-projects refresh and see correct contents.

**Comment by ericwinger** [comment]
> It deletes added methods (but leaves added method categories),

Dale told me once that method categories are not known by Rowan except as part of the method. So it doesn't surprise me that a project load "loses" categories. Does this affect the issue report? 

Made the projects menu refresh match the Jade menu refresh in 3.0.9.

**Comment by dalehenrich** [comment]
... yes, method categories are not first class objects in Rowan ... they are added when new, but not removed when empty (not sure that would be desirable behavior anyway) ...

**Comment by LisaAlmarode** [comment]
Behavior is the same in 3.0.9
When I delete a method category in jadeite, the methods also vanish. 
I do not abort or (gemstone) commit, but just reload the project from the project browser, and the methods remain vanished.  
I don't care that much about the categories but it's kind of inappropriate to lose the methods.

In 3.0.9, it's more broken since the project list browser load works the same way.

**Comment by ericwinger** [comment]
@LisaAlmarode  I discovered some bad behavior in rowan [when removing categories](https://github.com/dalehenrich/Rowan/issues/324). For the moment I'm coding around the method removal by moving the methods that would have been deleted into the 'other' method category -- but that's not the correct nor final answer. 

When the rowan issue is closed, we can revisit what the proper behavior should be.

**Comment by ericwinger** [comment]
Jadeite was[ using the wrong api](https://github.com/dalehenrich/Rowan/issues/324#issuecomment-413714617). 

Fixed api in 3.0.11.

**Comment by ericwinger** [comment]
Also added fancy removal message in 3.0.11

**Comment by LisaAlmarode** [comment]
This works nicely now.
