### ISSUE TITLE
(3.0.53) selecting package in one project browser causes sympathetic update in other

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#374]
![image](https://user-images.githubusercontent.com/623951/50405115-eca6f700-0764-11e9-9abd-ab88d0c19e03.png)

Package selection is not being respected in project browser

**Comment by dalehenrich** [comment]
... also seems to apply to tabs as well as separate browsers ... also seems that hierarchy view may be the only one affected/

**Comment by dalehenrich** [comment]
... also seems to apply to method browsers as well ...

**Comment by ericwinger** [comment]
I was able to reproduce in 3.0.53 but not in unreleased 3.0.54. Did some work here earlier which probably fixed the problem. Added lots of client tests in both the class & hierarchy tabs to make sure we don't regress again.

**Comment by LisaAlmarode** [comment]
I'm seeing a mild leftover bit of this problem in 3.0.56.  

In one browser, navigate to Rowan | Rowan-Definitions.  Select RwClassDefinition in the list view, then switch to hierarchy view.  You'll see four classes with the lowest one being RwClassDefinition.

In the other browser, go to Rowan | Rowan-Definitions.  Select in the list view, e.g. RwMethodDefinition.  Over in the other browser, that now pops up in the class list, below the RwClassDefinition.  In fact the more I select in browser two the more populated the hierachy in browser 1 becomes.

**Comment by ericwinger** [comment]
> In fact the more I select in browser two the more populated the hierachy in browser 1 becomes. 

This is a feature. :)  Actually, it only populates if the newly selected class is in the hierarchy but it probably shouldn't.

**Comment by ericwinger** [comment]
Fixed in 3.0.57. A class selected in another browser won't populate in the list with the exception of a newly added class. Selection of the new class is only done if one has created a new class in the browser you're working in.
