### ISSUE TITLE
(3.0.53) accept non-extension method in an extension package .... lose selected class

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#375]
before method accept:
![image](https://user-images.githubusercontent.com/623951/50409041-35ca6b80-07a4-11e9-8b55-5d403851babd.png)
after method accept:
![image](https://user-images.githubusercontent.com/623951/50409047-4d095900-07a4-11e9-87f5-f37555bba04d.png)
If you don't notice that the originally selected class has been deselected and try to edit method again, you get this error:
![image](https://user-images.githubusercontent.com/623951/50409073-7c1fca80-07a4-11e9-95d6-9902aa06901a.png)
... and realize that you have to remember which class you were working in and memorize the selector so you can find the method again

**Comment by ericwinger** [comment]
Fixed in 3.0.54. 

No explicit fix was done but I had done some recent work in this area which must have fixed it. Verified I could reproduce the bug in 3.0.53 but not in development line of 3.0.54. Added test coverage.
