### ISSUE TITLE
(3.0.53) project list does not update after load

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#376]
Prior to load in project list:
![image](https://user-images.githubusercontent.com/623951/50453940-2dd01000-08f9-11e9-854b-3bcbf59ffe8b.png)
after load -- Note that the RowanSample1 project is **italic** in project list and not in project browser:
![image](https://user-images.githubusercontent.com/623951/50453951-44766700-08f9-11e9-8174-985ef79d2504.png)
after activating project browser:, the project list updates as expected:
![image](https://user-images.githubusercontent.com/623951/50454000-8e5f4d00-08f9-11e9-9142-984cf3f919f3.png)

**Comment by LisaAlmarode** [comment]
Magically healed in 3.0.57.  The console list loses italic font immediately on load.
