### ISSUE TITLE
Add Accessors menu item is disabled

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#382]
When attempt to add accessors, the menu item is disabled.

![image](https://user-images.githubusercontent.com/7550442/50528482-87cd0300-0abc-11e9-9f9a-8705127381a2.png)

**Comment by LisaAlmarode** [comment]
This is closely related to issue #319.

**Comment by ericwinger** [comment]
awaiting feedback from question in - https://github.com/GemTalk/Jadeite/issues/319#issuecomment-451025960

**Comment by dalehenrich** [comment]
[feedback for comments](https://github.com/GemTalk/Jadeite/issues/319#issuecomment-451213540)

**Comment by ericwinger** [comment]
Fixed in 3.0.69. Warns before overriding existing methods. Tests added.
