### ISSUE TITLE
(3.0.53) the commit button on the SUnit browser is silent

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#383]
The commit button on the project browser makes a noise (for better or worse), so the absence of the sound on the SUnit button makes me suspicious that the commit is not being performed ... I've lost work over the last several days because I didn't commit often enough, so I've stopped using the SUnit browser commit button --- even though it would be more convenient --- simply because I am afraid that silence means that the commit is not performed ... and I don't want to lose my work ...

**Comment by regkrock** [comment]
Would it be possible to have the option to turn commit on/off. I like the way tODE works wrt commtits.

Also, I have had to start committing all the time just to be safe. Maybe this is the reason. The lack of auto-commit option really slows me down in my work.

**Comment by dalehenrich** [comment]
auto commit would be absolutely great ... and making it optional is a good idea ... I know that @regkrock has also mentioned that he likes autocommit ...

**Comment by dalehenrich** [comment]
... and I just lost a significant amount of work again ... with an out of memory ... we'll have to look into it ... but I'm guessing that it is a transcript problem ... it is hard to reproduce and when it does reproduce, you've lost work, so it isn't convenient to try to characterize more:)

**Comment by ericwinger** [comment]
The abort and commit code was a jumble. Synchronized all those paths into one path which does a commit or abort in the presenter. 

I left the beep in but we can remove it if you'd like.  (I don't have a sound card on my development workstation so I can't hear it) If so, let's file a new issue to remove it. 

Fix in 3.0.54.

**Comment by LisaAlmarode** [comment]
For the issues with beeping, I'll reassign to Dale for review...  I had no idea there was a beep and so it appears unchanged.
