### ISSUE TITLE
(3.0.53) sort by `type` in changes view does not do complete job

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#384]
Sorted by type (have to click twice) and as you can see, there is a `Modification` mixed in with `Addition` ... I'm sorting long lists with the expectation that I shouldn't have to scan the entire list looking for `Modications`:
![image](https://user-images.githubusercontent.com/623951/50530273-b513b400-0ab0-11e9-9d86-1e5d90e27c44.png)

**Comment by ericwinger** [comment]
The sort blocks were still set to Jade-time. Fix in Oscar 3.0.54.

**Comment by LisaAlmarode** [comment]
I've built up quite long lists of changes at various times over the last few days (in 54, 55 and 56) and have never seen any problems with order.
