### ISSUE TITLE
(3.0.53) no warning about unsaved changes in method browser when clicking on different method

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#386]
Should be consistent across all browsers ... project browser warns you, method browser does not ... don't know about debugger, but it shoiuld

**Comment by LisaAlmarode** [comment]
Debugger does ask if you want to save to clipboard. BUT there is no cancel - if you click on a different frame, you can either toss the edits or save them to clipboard, but you can't change your mind and stay and ponder the changes.

**Comment by ericwinger** [comment]
Debugger, method list, and projects browser should now handle unsaved changes the same way - like projects browser with unsaved changes dialog. Fix in 3.0.54.
