### ISSUE TITLE
(3.0.53) ... could use better method for identifying compile errors in a method ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#387]
My eyes aren't that good, but scanning for a thin red underline in a red background makes things that much harder:
![image](https://user-images.githubusercontent.com/623951/50569675-38870c80-0d20-11e9-9449-b3a3299aad04.png)
large methods make it even more difficult to find the `undefined symbol` ... highlighting instead of underlining (and making sure that the highlighted string is visible) would be preferable for my old eyes ...

**Comment by LisaAlmarode** [comment]
I agree... it's very hard to see the indicators.

**Comment by LisaAlmarode** [comment]
- [x] In 3.0.75, it's a thin blue underline, still quite hard to spot.  Maybe the text could (also) be made bold?

- [x] Uunderlining obscures underlines in the method, which makes it harder to parse what the error might be (my case was an undefined variable, but it looked like a message send).  The underlining is sticky while you are editing the method which limits options to see it clearly.

- [x] the method text should scroll to ensure that at least one compile error is visible.  I was quite baffled by this.  To reproduce: find a method that scrolls, add a single quote at the very end, then scroll up to the beginning of the method.  Compile.  You'll get a missing end of literal mark error in the status bar,, but  the last token in the method with the underline will not be visible.

**Comment by ericwinger** [comment]
In addition to the current compiler error identification, the compile error range is selected which should provide better visibility (as well as put the user's selection on the problem code) 

Example: 
![image](https://user-images.githubusercontent.com/36212516/64192243-143f7a80-ce2f-11e9-893c-febd7ae966a3.png)

User is shown and taken to the first compile error: 
![image](https://user-images.githubusercontent.com/36212516/64192139-e65a3600-ce2e-11e9-94d2-0f45b5011887.png)

**Comment by LisaAlmarode** [comment]
The blue underline still obscures underlines; it's not clear what was done to support checking that box...?  
However, the error is much more visible, and it scrolls, so we'll call this fixed.
