### ISSUE TITLE
Add Browser Panel (Tab) when in Sunit Subpanel fails

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#389]
When I attempt to open a new class browser tab it fails.

![image](https://user-images.githubusercontent.com/7550442/50653475-a0736800-0f57-11e9-94dd-4c3d8542a4c1.png)

![image](https://user-images.githubusercontent.com/7550442/50653484-a6694900-0f57-11e9-9bf4-f765c2a21c72.png)

**Comment by LisaAlmarode** [comment]
This reproduces in 3.0.56.  Need to actually have a test selected, not just be in the sunit tab.

**Comment by ericwinger** [comment]
Should be fixed in 3.0.57.  https://github.com/GemTalk/Jadeite/commit/be234a312bcba6d8bbe7ad2338464762653d84e4
