### ISSUE TITLE
Project menus in project browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#39]
1) Project browser project menu item commit: error   JadeiteProjectBrowserPresenter does not understand #gitCommit

2) Project browser project git checkout - the red for skew seems backwards.

I have branch lisa loaded with a lot of methods that are not in branch master.  When I check out master, I think the project should be red to show skew from disk.  It's not red. disk is definitely on master, image methods are from branch lisa.  Browse changes show the methods in branch lisa as additions.

Then when I checkout branch lisa (which is what matches the image) the project turns red.  Changes browser now empty.

**Comment by ericwinger** [comment]
> Project browser project menu item commit: error JadeiteProjectBrowserPresenter does not understand #gitCommit

@LisaAlmarode  - Does this still reproduce?  I tried in the latest without error. Both the project list and project browser open a commit dialog properly.

**Comment by LisaAlmarode** [comment]
This is latest, 3.0.9, though perhaps you have something even later. Hybrid with only the 3.0.9 .exe due to new release process, if that might affect anything. Rowan oscar 02ad7af.

{05C606D0: cf 05C606B1, sp 05C606E4, bp 05C606CC, ip 4, JadeiteProjectsBrowserPresenter(Object)>>doesNotUnderstand:}
	receiver: a JadeiteProjectsBrowserPresenter
	arg[0]: Message selector: gitCommit arguments: #()

{05C606B0: cf 05C60691, sp 05C606C4, bp 05C606AC, ip 4, Symbol>>forwardTo:}
	receiver: gitCommit
	arg[0]: a JadeiteProjectsBrowserPresenter

{05C60690: cf 05C60671, sp 05C606A4, bp 05C6068C, ip 4, CommandDescription>>performAgainst:}
	receiver: a CommandDescription
	arg[0]: a JadeiteProjectsBrowserPresenter

**Comment by ericwinger** [comment]
#gitCommit was getting stripped at runtime creation.

**Comment by LisaAlmarode** [comment]
On more rigorous test in 3.0.10 I'm not seeing the bad red-skew behavior.  I'll keep an eye on it and file a new issue if I see anything.
