### ISSUE TITLE
Rename instance variable with accessor method is... wonky

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#390]
This is 3.0.53.

I had a class with an instance variable with a settor method.
I renamed that instance variable.  Attempt to save the class definition.  

In the class I'm using, I get an error dialog "Index 279 is out of bounds".  That seems to be since there were several/longer methods with references to that instance variable.

In my test class to reproduce, I get different weirdness:
![image](https://user-images.githubusercontent.com/13142166/50658467-4fab4180-0f4e-11e9-819e-51625d212d17.png)

**Comment by ericwinger** [comment]
@LisaAlmarode  This appears to be coming from Rowan. I can reproduce it in a workspace outside the Jadeite tools. All one needs to do is remove a referenced inst var in the list of instance variables when compiling a class. See https://github.com/GemTalk/Rowan/issues/464.

**Comment by dalehenrich** [comment]
@ericwinger the **wonky** behavior that I thought that was being reported in this bug is the fact that the error is intercepted by Jadeite and the `undefined symbol` message is inserted in the class definition doit as if `rwSubclass:` is the undefined symbol ... what should happen is that error be presented to the user showing the **correct** compile error ...

**Comment by ericwinger** [comment]
@dalehenrich  is going to give some example code on how to compile the class in such a way that Jadeite can distinguish between a class compilation error and a subsequent method compilation error. (Methods are recompiled automatically in rowan after a class is compiled)

**Comment by dalehenrich** [comment]
The method `String>>evaluate` is where the compilation and execution is normally done:
```smalltalk
evaluate

"Compiles the receiver as an unbound method and executes it using the current
 default symbol list."

^ (self _compileInContext: nil 
       symbolList: GsSession currentSession symbolList)
  _executeInContext: nil
```
... and you can see the two components of `evaluate`:
- compile workspace code and create an *anonymous` method:
   ```smalltalk
   method := 'Object rwSubclass: ''Vegetable''
      instVarNames: #(one atwo three)
      classVars: #()
     classInstVars: #()
      poolDictionaries: #() 
      category: ''Vegetables'' options: #()' 
         _compileInContext: nil symbolList: GsSession currentSession symbolList.
   ```
- execution `anonymous` method
   ```smalltalk
   method _executeInContext: contextObject
   ```
The compile errors incurred while executing the `compileInContext:symbolList:` should have feedback show up in the workspace pane as is currently done.

The `_executeInContext:` code should present compile errors to the user in a debugger. In the case of the workspaces, the debugger is the only right answer ... for the project browser, we might want to provide a better interface for method compilation errors .. but a debugger is better than what is happening now.

Also, would will probably want to have a variant where the `compilation context` and `execution context` can be specified ... it is useful to used the `execution context` for a workspace in an inspector where `self` can be bound to the object being inspected ... the `compilation context` is useful in the debugger if one wants to be able to evaluate expressions involving instance variables in the recever's class ...

Finally, we have to be aware that we *do* have to use `private` methods and I know for a fact that these particular methods have changed one or more times between 3.2.15 and 3.4.x ... in 3.5 or so, we should have public methods available for doing this ...

**Comment by dalehenrich** [comment]
Retest by executing the class creation code in a workspace --- issue #257

**Comment by LisaAlmarode** [comment]
Still the same in 3.0.57.  

![image](https://user-images.githubusercontent.com/13142166/51495868-a5ffe900-1d72-11e9-94ab-5ad0e02a2ce5.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.69.  Similar to what was described here - https://github.com/GemTalk/Jadeite/issues/390#issuecomment-452478601

Two stage class compiles implemented - class compilation failures get highlighted text in class definition pane. Method recompilation failures get a debugger. 

Per the referenced comments, workspace context objects & class compilation in workspace should probably get a new issue.

**Comment by LisaAlmarode** [comment]
On rename, class compile doesn't fail, but it succeeds in creating weird state in your code since there's no alert that you have references to the instance variable.  The accessor methods remain there and work... but still this is weird.  Reported issue #496 on that situation.
Am seeing walkback on failed compile, but will wait for 3.0.74 coming soon.

**Comment by LisaAlmarode** [comment]
In 3.0.74, class compile errors seem to always throw a walkback.  Also if classcompile would succeed but if methods couldn't be recompiled it throws a walkback.  

It's not giving dialogs nor highlighting randomly, but still, please make it less grumpy.

**Comment by ericwinger** [comment]
@LisaAlmarode The problem that two-stage commit solves was that method compilation failures were showing up in class definition source pane. Now, a method compilation failure gets a debugger per the comment. https://github.com/GemTalk/Jadeite/issues/390#issuecomment-491458022

The reproduction case I tried works as I would expect. Can you give me a reproduction case that shows the deviant behavior?

**Comment by LisaAlmarode** [comment]
It's not right, nor at all useful, to throw a method compilation failure walkback that says "a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor" and gives a long stack with classes like aRwGsMethodAdditionSymbolDictPatch on the list. 
This is not a debugger situation, where I can edit something in the debugger and continue (at least not as far as I can see); it's an actual error in my compilation.

I most like to see something done the way GBS/VW handles it, which defers having to deal with it.  

But otherwise, if the method compile fails and thus the class compile fails, I think it should give you an error, perhaps on the error pane at the bottom, such as "could not compile class: method references to instance variables blah".

**Comment by dalehenrich** [comment]
in topaz you get a listing of the method with the little `^` pointing out the compile errors ... and this error string is actually on the stack in one of the CompleError frames ... so we could just display this (at a minimum) ... it used to be that pharo would pop up a dialog that allowed one to fix the compile error and continue on ... this would be nice to have in the long term ...

**Comment by ericwinger** [comment]
Instead of a walkback on a method compile failure, we now open a method list browser showing the method and as much information about the failure as possible. 

Filed [feature request in Rowan](https://github.com/GemTalk/Rowan/issues/503) to show all the method recompiles instead of just one which would (with a little Jadeite work) allow the user more flexibility to handle failed method compiles after a  class definition change.
