### ISSUE TITLE
(3.0.53) SUnit browser running test method in wrong class

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#391]
RwProjectTonelReaderWriterTest>>testWriterReader_A is the selected test, however, the stack from the debugger indicates that the RwProjectfileTreeTonelReaderWriterTest class is being used to execute the test:
 ![image](https://user-images.githubusercontent.com/623951/50663689-51c9cc00-0f5f-11e9-96dd-c96d40e7ba94.png)
Note the method #_writerVisitorClass in debugger and contrast the #_writerVisitorClass method in RwProjectTonelReaderWriterTest class in project browser ...
It does happen that the test method is defined in RwProjectfileTreeTonelReaderWriterTest, but it is inherited ...

**Comment by dalehenrich** [comment]
Same problem shows up when running test from Project Browser:
![image](https://user-images.githubusercontent.com/623951/50664461-0107a280-0f62-11e9-945f-c759d7e05426.png)

**Comment by ericwinger** [comment]
I believe that the ``debug`` option was wrong in the Sunit browser tab and all three were wrong in the stand along sunit browser. Should be fixed in 3.0.54.

**Comment by ericwinger** [comment]
"All three" being `debug`, `run selected`, and `run all`
