### ISSUE TITLE
(3.0.53) browse class menu item would be useful in debugger ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#392]
![image](https://user-images.githubusercontent.com/623951/50715799-afc7e380-1033-11e9-81e8-d458ee6cdff1.png)

**Comment by dalehenrich** [comment]
if there are two possible classes in the frame, it would be useful to be given a choice as well ..

**Comment by LisaAlmarode** [comment]
We have these features:
   - double click on class name in debugger to highlight, and Browse Class is on popup menu
   - select receiver in variables pane and you have Browse Object Class on popup menu.

I think this means you can browse the class for anything related to the current frame...
