### ISSUE TITLE
(3.0.53) restart icon not displayed until mouse over ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#393]
Before:
![image](https://user-images.githubusercontent.com/623951/50788701-02411400-126f-11e9-9fc6-fcdee2f46bb1.png)
After:
![image](https://user-images.githubusercontent.com/623951/50788719-0c631280-126f-11e9-970d-556c9116fa52.png)
@LisaAlmarode @ericwinger doesn't see this in his environment ...

**Comment by LisaAlmarode** [comment]
I see the missing-until-mousedover restart circle-arrow in the debugger when there's a test with an assert failure. 
The icon is present and normal if I use debug-it, or if there's an error or method breakpoint that is hit by evaluating some expression.

**Comment by LisaAlmarode** [comment]
To clarify: the bug reproduces for me only when the debugger is opened from an Sunit debug.

**Comment by dalehenrich** [comment]
I was running tests from SUnit browser when I saw the issue ...

**Comment by ericwinger** [comment]
This is worth reviewing in 3.1.0.  I suspect an toolbar button display problem in Dolphin that I don't see in the latest Dolphin code.

**Comment by LisaAlmarode** [comment]
I see this icon in 3.2.12, and with the dophin port we might be okay; close.
