### ISSUE TITLE
Debbuger does not show error message properly

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#394]
While in the debugger, the code looked like this:
![image](https://user-images.githubusercontent.com/7550442/50866388-c6de3c80-1377-11e9-974f-727f62a35d8e.png)

Added a carret and did a save. There is a compile error but the popup with the #view error occurred. Needs to show the actual error.

![image](https://user-images.githubusercontent.com/7550442/50866396-ccd41d80-1377-11e9-9cec-9e9e9870b25a.png)

**Comment by LisaAlmarode** [comment]
I don't see this; in 3.0.56 it reports a compiler error normally in the status bar.  I think something was fixed meanwhile, closing this.
![image](https://user-images.githubusercontent.com/13142166/51345857-f6b0d280-1a50-11e9-9180-fd7f492a49a4.png)
