### ISSUE TITLE
(3.0.54)  Sunit can display non-test methods

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#395]
A fresh login to 3.0.54 with fresh Rowan oscar.
I go to sunit browser, select my class.  Se see test methods in Plantis.  Run all and they all pass. 
Go to the Project Browser to run tests there.

Open a project browser, and navigate go to the same class.  When I click on the class...
the still-open Sunit browser now shows all methods in the test class, not just the ones starting with 'test'.

![image](https://user-images.githubusercontent.com/13142166/50875514-8da8cb00-137d-11e9-8d94-b2d63b19f4ad.png)

The poor, confused Sunit browser will even run tests although there's little chance the support methods will work.

**Comment by ericwinger** [comment]
Should be a fix in 3.0.55.

**Comment by LisaAlmarode** [comment]
Well the list is the same now but they all reverted status to untested.  I'll file a separate issue on that.
