### ISSUE TITLE
Ability to turn on autocommit would be nice

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#396]
In issue #383, there was a clamor for autocommit.  But I think that issue was only addressed by cleanup and bell-adjustment, not by adding this feature. 

I also would like autocommit and I don't find an existing request.  So: please add an autocommit option.

**Comment by regkrock** [comment]
Not just nice. Lack of auto-commit causes loss of work if something else goes wrong while working. For example, if the debugger hangs and I have to kill the session. This does not happen often but I have had it happen. 

In tODE I have always worked with the auto-commit turned on and I find it the better way to work when I am doing significant amounts of work.

**Comment by LisaAlmarode** [comment]
Eric would like some details on semantics. He notes that would be more manageable to code if the commit occurs on each service request, rather than adding code for every single specific operation (besides adds/removes/changes done in various browsers and debuggers and also category changes etc.)

I'd imagine the commit would occur after successful completion of a change, e.g. failed compile does not cause commit.  

Given my crashes in #406 I'm going to increase priority to critical, since critical means loss of work and the lack of this feature does risk loss of work.

**Comment by dalehenrich** [comment]
That's pretty much the model used by tODE (successful completion of a "service request") ...

**Comment by ericwinger** [comment]
I've added a first-cut at auto commit in 3.0.58. Default for a new login is false. Menu option is in the Console>Jadeite menu. No attempt to save the auto commit beyond the life of the session is currently made. Commits are done as the penultimate step after each service request to the server. An unexpected error in a service request 'should' not commit (but any subsequent service requests will).

**Comment by dalehenrich** [comment]
@ericwinger Sounds perfect ...

**Comment by LisaAlmarode** [comment]
I would like an indicator that auto commit is on that is always visible.  In GBS there's a specific icon in the icon bar for all browsers, which is highlighted when autocommit is on.  I like to check that it's on or off to avoid surprises.  

Perhaps you can change the color of the camera?

**Comment by ericwinger** [comment]
@LisaAlmarode  Can this be a new issue for our February release?

**Comment by LisaAlmarode** [comment]
opened issue #421 for the indicator

**Comment by LisaAlmarode** [comment]
@regkrock and @dalehenrich, you are testing the autocommit feature, right?  This should get some general broad-usage testing to detect holes in corner cases...

**Comment by dalehenrich** [comment]
I am not working on Rowan right now as I have been gearing up for 3.5 
work ... and @regkrock is on vacation at the moment and I don't think 
has updated to the latest version of Jadeite for a while ... if I don't 
finish up the 3.5 work by the end of this week, I'll switch over to 
Rowan and when I do I will turn on auto-commit for sure ... it is a 
highly anticipated feature:)

**Comment by LisaAlmarode** [comment]
I'm going to call this fixed, since it's there, although there are many details that are under discussion, those will be filed as separate bugs.
