### ISSUE TITLE
String Inspectors don't display lfs

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#398]
I often want to display a string containing line feeds.  The string inspector does not show the line feeds, although I can copy and paste into another text area and they are visible.  makes the string inspector pretty lame and useless.
![screenshot](https://user-images.githubusercontent.com/13142166/50923415-c25e6600-1401-11e9-9877-3dc9d8851610.jpg)

**Comment by regkrock** [comment]
A bigger issue is why not open a regular inspector. All of the other Smalltalks do that. This is very annoying as I wanted to look at some details and execute code against the string.

**Comment by ericwinger** [comment]
I have a fix for this bug in 3.0.59. Also, all inspectors open with a dual pane inspector with inst vars on the left & code pane on the right, as requested. It would be helpful to have extra testing on special objects to make sure that any cracks in the implementation are filled.
