### ISSUE TITLE
The "exactly one object" warning may also provide an unrelated debugger stack

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#399]
To reproduce
Go to RowanSample1Tests in the ProjectsBrowser and debug the test TestError.  Open the debugger on the error and leave it there.
Then go back to the ProjectsBrowser and select two methods and the menu item "browse hierarchy implementor".  

You'll see an error exactly one object must be selected.
Then you see another error with the stack of the debugger.
This is quite alarming if you forgot you had a debugger open and are thinking about something else.

![image](https://user-images.githubusercontent.com/13142166/50924413-5e896c80-1404-11e9-8b60-0dd005fe1010.png)

Subsequently I lost my session. So I'm increasing the priority although it's not proven to be related.

**Comment by LisaAlmarode** [comment]
Still happens in 3.0.58.  Session loss does not seem to be related.

**Comment by ericwinger** [comment]
To make it consistent with the method list browser, I disabled Browse Hierarchy Senders/Implementors in the project browser when multiple selections are made. That's what was getting the "exactly one object" error.
