### ISSUE TITLE
Exactly one object must be selected

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#40]
I see this error a number of places, but there's a couple that are especially annoying. 

If you have a package and class selected, and you click on a different package, you have then no class selected.  If you click on either the Variables and Category tabs, this error shows up.  
Clicking on Variables tab with no class selected tends to show the categories of the previously selected class which adds to the fun.

The other case is when you have two method categories selected (say you just moved a method from one category to the other.  Then you try to edit that method and save it - and you get exactly one object must be selected error.  Which isn't entirely accurate since it's okay to have zero objects selected.

**Comment by ericwinger** [comment]
Two method categories selected doesn't prevent method compile. 
If no class is selected, clear variable & category lists. 

Eventually, let me know about other places this appears.

**Comment by LisaAlmarode** [comment]
Note that part one of this is subsumed into issue #43.  Verified part 2 is fixed in 3.0.10
