### ISSUE TITLE
(3.0.55) Selecting class in one project browser loses method edits in another

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#400]
I have a method selected in project browser 1, and make some code edits; in my case, near the bottom of a long method.  The changes are not saved and the pane is green.

Then I go to a different project browser, and select the package and then the same class that is selected in PB1.  

After selecting the class, project browser 1 is still displaying the same method, but I've lost my edits; it's reverted to the original, turned back to yellow and scrolled back to the top.

**Comment by LisaAlmarode** [comment]
These issues are also in 3.0.53, so not a regression, but the losing work is rather upsetting.  I was defining a new method by editing an existing one... and it all disappeared.

There is another, related problem when the class is already selected before the scenario starts, and the same method is selected.  This isn't as bad since no work is lost, it's just weird.

If you have already selected the same class in both browsers, and have unsaved edits in one browser, and select the same method in the other browser, the one with unsaved edits inexplicably turns pink... a different color than the delicate peach of a compiler error.

This shows the second problem, with a compiler error for comparison:
![screenshot](https://user-images.githubusercontent.com/13142166/51090088-8b52c200-172b-11e9-9ff1-7f24d55d0ce9.jpg)

**Comment by ericwinger** [comment]
Should have a fix for both problems in Oscar 3.0.56
