### ISSUE TITLE
Step Into A Block Without going thru the detail code? Is this possible.

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#401]
In the image below, I want to go directly to the code in the block without stepping into the implementation of #should:raise:. Is this possible. It would be very handy.

![image](https://user-images.githubusercontent.com/7550442/51075808-a86d8f00-165e-11e9-8f65-0d420228d117.png)

**Comment by ericwinger** [comment]
Believe I have support added for debugger step through in 3.0.81

**Comment by LisaAlmarode** [comment]
Oops, hit wrong button

**Comment by LisaAlmarode** [comment]
I think I understand the feature, and I believe it's working.

But it does need a better icon.  While cute, I don't think the little apple is appropriate here.

![image](https://user-images.githubusercontent.com/13142166/67125853-89ca9480-f1aa-11e9-9978-822fac3899fc.png)

Speaking of icons, I also still have the blue circle question mark in the upper left of the SUnit browser.

**Comment by ericwinger** [comment]
Yes, I sent email on the icon. The apple is temporary.  I'll have it fixed up in the next few days.

If you have an issue with the SUnit browser, please open a new issue.

**Comment by LisaAlmarode** [comment]
The Sunit issue has been open a long time, it's issue #346.

**Comment by ericwinger** [comment]
New icon will appear in 3.0.82.

**Comment by LisaAlmarode** [comment]
Working!  and with Icons!
