### ISSUE TITLE
Saving method from debugger causes extra classes to appear in Project Browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#402]
With a browser in class hierarchy view on a test class, if you save a method in the test class, you get a duplicate purple version of the class in the project browser. 

![image](https://user-images.githubusercontent.com/13142166/51157006-e02d3000-1832-11e9-8f62-17bfdc5d4c90.png)

To reproduce, setup a breakpoint in a method in test code and debug the test.  When it comes up, make a trivial change and save the method.  The duplicate class, in purple, pops up in the project browser.  It doesn't seem to happen for non-test classes but reproduced both from the sunit browser and the sunit pane in the PB

**Comment by ericwinger** [comment]
@LisaAlmarode #402 and #409 appear to be very similar but they have much different labels and priorities in the Oscardale project. Could you help me prioritize & label them properly? Thanks.

**Comment by ericwinger** [comment]
This looks a lot like the bug in #374 which is fixed in 3.0.57 (https://github.com/GemTalk/Jadeite/commit/5133cd6b2b4653f28499daca081c9ba369efa4e6). Since I can't reproduce what appears to be an easily reproducible bug, it's possible that it's already fixed. Closing for retest.

**Comment by LisaAlmarode** [comment]
My test case, which was previously easy to reproduce, doesn't reproduce in 3.0.58.  So I'm not sorting out which bug was with which fix but call this one good.
