### ISSUE TITLE
Double click in method browser change class to show instance methods

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#403]
In the class methods of a class in the Project Browser.
Select a method, and browse implementors which brings up a method browser with some class methods.
Double click on the method (for the selected class in the PB) in the method browser.

And the class in the project browser is now displaying its instance methods, not its class methods.  It doesn't switch the class/instance tab to match, though.

It also pops up a new projects Browser which is also, incorrectly, showing instance methods and of course can't select the method since it was a class method.

**Comment by LisaAlmarode** [comment]
Also happens when I left-click to bring up the menu for the method in the method browser.

**Comment by ericwinger** [comment]
> In the class methods of a class in the Project Browser.
Select a method, and browse implementors which brings up a method browser with some class methods.
Double click on the method (for the selected class in the PB) in the method browser.

>And the class in the project browser is now displaying its instance methods, not its class methods. It doesn't switch the class/instance tab to match, though.

I believe the above part of the issue was fixed with #417. 

> It also pops up a new projects Browser which is also, incorrectly, showing instance methods and of course can't select the method since it was a class method.

The last paragraph (incorrect double-click selection) still needs to be fixed.

**Comment by ericwinger** [comment]
Double click action fixed in 3.0.58 https://github.com/GemTalk/Jadeite/commit/fa022e6e66e8658528d735bf130c79ba9214fef5
