### ISSUE TITLE
Removing a method using method browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#404]
The method browser has an item, remove method (s), which appears intended to remove a method from the image.  And it seems to do so.  However, it leaves the method in the method browser so it looks like it didn't work.  If you do the remove again in an attempt to get rid of the method, you get a walkback:
a UserDefinedError occurred (error 2318), reason:halt, These selectors were not removed ....

I think removing a method using remove method(s), which already asks you to confirm, should also remove it from the list.  However, if you don't want to, at least disable the remove method(s) item.

**Comment by ericwinger** [comment]
Fixed in 3.0.57 with supporting tests.
