### ISSUE TITLE
SUnit select class flips sunit pane in PB to the method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#405]
I was looking at my tests in the SUnit tab of the PB.  But I thought hey, I'll test in the SUnit browser.  So found that browser and clicked to that same class.
The PB flips the view off the Sunit pane, back to a method pane.

I don't like browsers changing other browsers.

**Comment by ericwinger** [comment]
It appears that you have to have a method selected in the projects browser for the issue to be exposed. Fix is in 3.0.58.

**Comment by LisaAlmarode** [comment]
If you have one or more test selected and/or run (with check icons) in the SUnit tab in the project browser, 
then selecting the same class in the SUnit browser loses the selection and the test result icons.
This is kind of minor... not sure it's worth reopening.

**Comment by LisaAlmarode** [comment]
last part appears okay in 3.0.59
