### ISSUE TITLE
(3.0.56) would like option to browse class OR method from changes window

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#407]
![image](https://user-images.githubusercontent.com/623951/51271250-e3800300-197b-11e9-8101-6eed243aa200.png)

Often I want to look at the source of a method in a method browser (so I can do senders/implementors or modify the method and getting a brand new giant project browser is overkill when all I want to see is the method ...

**Comment by ericwinger** [comment]
Fixed in 3.0.69.  I added Browse Senders / Browse Implementors to show the method list. Browse Implementors takes you directly to the changed method source.
