### ISSUE TITLE
(3.0.56) lose selected class/method on reload if it's an extension class

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#408]
This is more or less the same as issue #284 but it gets too muddy to reopen an old issue.

When I have an extension class and method selected, reload causes my selection to be lost.  This occurs both on reload from the console project list and reload from the PB project pane.

- Select RowanSample1-Extensions | RowanSample1 | accessing | foo 
- reload RowanSample1
- See selection revert to the package, RowanSample1-Extensions

**Comment by ericwinger** [comment]
I've done quite a bit of work in this area in the past few months. Trying the example, it seems to work. Can you review again @LisaAlmarode?

**Comment by ericwinger** [comment]
I think this just forgot to be closed based on September 9th, 2019 activity. Closing.
