### ISSUE TITLE
(3.0.56) duplicate class entry shows up hierarchy view

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#409]
RwRepositoryComponentProjectTonelReaderVisitor class shows up twice in class hierarchy list in project browser ... note that it shows up as if it is an extended class, but that class has no extension methods
![image](https://user-images.githubusercontent.com/623951/51284733-6cf5fc00-19a1-11e9-92f6-67b6a7aeb175.png)
**suddenly appears** while working away .. note the open debugger ... i did happen to be editing and saving methods that are in the *bad* class ... I have not been able to catch the exact moment that the class history flips over to the bad side ... 

pretty annoying since I don't trust the browser once this happens ... clears up when you select the superclass, click on class tab, then click on hierarchy tab ...

**Comment by dalehenrich** [comment]
I seems that the duplication does occur when I do an accept in the debugger ...

**Comment by LisaAlmarode** [comment]
This looks like it's the same as #402

**Comment by dalehenrich** [comment]
... i agree, except that this is more than an annoyance ... we need a category for embarrassing?

**Comment by dalehenrich** [comment]
The duplication keeps multiplying ...
![image](https://user-images.githubusercontent.com/623951/51286013-00c9c700-19a6-11e9-800c-5d5ffe1bd1a6.png)

**Comment by LisaAlmarode** [comment]
Well, I don't escalate to significant unless I am really stuck working... however, another tag might be a good idea since there are a number of issues lately that have minor impact to "work" (for me)... but are quite distressing emotionally, like any side effects to other browsers.

**Comment by ericwinger** [comment]
@LisaAlmarode #402 and #409 appear to be very similar but they have much different labels and priorities in the Oscardale project. Could you help me prioritize & label them properly? Thanks.

**Comment by LisaAlmarode** [comment]
Closing this one in favor of the earlier one which is IMO a bit less confusingly reported (which I would say since I reported it).  I increased priority on #402 to make up for it.
