### ISSUE TITLE
SUnit browser's colored status bar is sticky

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#411]
When you run tests, it puts a status bar over the panes with the results.  But those results stay there regardless of where you go and what you do...

The results from RowanSample1Test following me:

![image](https://user-images.githubusercontent.com/13142166/51299625-f75c5100-19dd-11e9-8656-ba8d049fe170.png)

**Comment by ericwinger** [comment]
The intent was to leave the results display until the next set of tests were run. However, we can change that. When should the results be cleared - method change? class change? package change? other?

**Comment by dalehenrich** [comment]
the useful information in the SUnit browser is the test status on a per test basis (green checkmarks in test pane) ... note that no test status is shown, so whenever you clear the per test icons is the time to clear the status at the top ... if you are showing actual test status and not the envelope the test summary should be retained --- they both should be showing the same results

**Comment by ericwinger** [comment]
Fix in 3.0.58. Status bar reset on class & package change (which is when method statuses are updated)

**Comment by LisaAlmarode** [comment]
cf issue #419

**Comment by LisaAlmarode** [comment]
The status bar is sticky in 3.0.60 under the conditions in issue #419.
