### ISSUE TITLE
(3.0.56) incorrect project browser update on method accept

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#412]
I had two tabs open and both tabs had the same test class selected ... I was in the first tab; edited code and on accept the browser switched to the second tab 

If the second tab does not have the same class selected I did not see it happen ...

**Comment by ericwinger** [comment]
Fixed in 3.0.57 https://github.com/GemTalk/Jadeite/commit/66854ac9fdff38e74505083c83c6bf8c343f754a
Both tabs had to have the same method selected.
