### ISSUE TITLE
Browse changes on a class definition change handled poorly

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#415]
When you look at the changes in a project, if you've been editing classes, you might find lines such as: 

```Modication  rwSubclass:   <empty field>  ClassDefinition```

- [x] rwSubclass: is insufficient; it really should provide the name of the class.  My Changes Browser shows three classes changed and there's no way to see other than clicking on each one.

- [x]  if you use the Browse pop-up menu item, it opens a Dictionary Browser, rather than the expected Project Browser.  

- [x]  Then it gives an error dialog: Not found: a BlockClosure
And nothing is selected in the Dictionary Browser.

**Comment by ericwinger** [comment]
We were parsing the changes string incorrectly. Fixed in 3.0.58.
