### ISSUE TITLE
NetLDI task in login is not displayed correctly

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#416]
In the Jadeite login dialog, Advanced tab, I set my NetLDI task name to gemnetdebug.  

After restarting Jadeite, the display says gemnetobject again.  

However, it's still executing gemnetdebug.  If I edit it, I can restore gemnetobject.  But it's not a trustworthy item; this is sometimes needed for debugging issues such as #413.

**Comment by ericwinger** [comment]
@LisaAlmarode From within a logged in session, what gemstone message can be sent to see what the netldi task name is?

**Comment by ericwinger** [comment]
The instance variable ``gemTask`` wasn't being saved to the external .gss file but the full netldi string (with the debug inserted) is saved. That explains the behavior and I'll have a fix in 3.0.58.
