### ISSUE TITLE
(3.0.56) extra method entries in project browser on accesp

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#417]
Could be related to #402, but reporting anyway, in case it matters, since it involves methods not classes:
![image](https://user-images.githubusercontent.com/623951/51571089-f00dcb00-1e55-11e9-9e31-448dd5a0b7c1.png)
I accepted a class method (_readObjectFrom:) in the method list on left and then extra methods showed up in **class-side** there should only be two methods in list:
![image](https://user-images.githubusercontent.com/623951/51571593-81317180-1e57-11e9-9edf-fb06ac5e1133.png)
Looks like the list is from the private protocol on the instance side ...

**Comment by ericwinger** [comment]
The bug I'm seeing doesn't even require a compile. Needed to make sure that method & category updates were restricted to the proper meta (class/instance side). Fixed in 3.0.58.
