### ISSUE TITLE
Navigating and category creation in class hiearchy view can't keep class side/instance side straight(3.0.58) 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#418]
Open a project browser, navigate to class, change to hierarchy view. click on class to see class side, add a class method category that is the same as one you know existing on the instance side. 

In a second project browser, navigate to class.  Click on hierachy view.  (The first browser reset, losing class selection, but this is a minor annoyance)

Reselect the class in the first/class methods browser.  (there are none, but there is that newly created directory).  So you are looking at the same class in both browser, just one is on class methods and one is on instance methods.

On the instance side, select the instance category that has the name of the newly created class directory.  See NO methods, where there should be existing instance method showing.  It's displaying the class side category, which is empty.  Frightening.  Click on another class and back and you can see the methods reappear.  Select one of the methods.

On the PB showing the class side, select that same category.  Now it shows the instance methods.

I'm having problems creating directories but I think the above cleanup may be the real problem.

**Comment by ericwinger** [comment]
> In a second project browser, navigate to class. Click on hierachy view. (The first browser reset, losing class selection, but this is a minor annoyance)

Even though this is referred to as an annoyance, I fixed it in 3.0.59. It was a bit disconcerting.

**Comment by ericwinger** [comment]
After some investigation, I believe that this was regression introduced in a recent release. A fix for review will be in the 3.0.59 release. https://github.com/GemTalk/Jadeite/commit/488756614dc7f59f12cc0e4db3b483d87ae7abcb
