### ISSUE TITLE
Customer requests "Find Method" feature

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#420]
Customer has requested a "Find Method" feature in the projects browser. A good start would be to add a menu item to the category browser that will present a list of methods with a "keystroke search" feature similar to the current Find Class dialog. 

VisualWorks has a similar feature which could be used as a model.

**Comment by regkrock** [comment]
The spotlight feature in Pharo is really nice. It returns classes, methods, senders, references, etc. Would that be possible?

Reg Krock

**Comment by ericwinger** [comment]
@regkrock The Spotlight feature would be worth investigating as a possible addition to Jadeite. Could you add a new issue and label it as an enhancement?

**Comment by dalehenrich** [comment]
@regkrock if you want spotlight-like features in Jadeite, could you be more specific about where and what bits you like and how they would be included in a separate issue ... I've never really understood spotlight as I haven't spent a lot of time in Pharo in the last few years so the more details about what you like and dislike the better ...

**Comment by ericwinger** [comment]
Find Method, similar to Find Class, will be in 3.0.59. Ctrl-Shift-M or a menu item will open the dialog. https://github.com/GemTalk/Jadeite/commit/013283f1436a4919a3821baff9a409e1b52c980e

**Comment by LisaAlmarode** [comment]
I happened to be on a test class Sunit tab, having run a test, when I tried the new findMethod feature and what happened was an error:

Jadeite error dialog:
JadeiteSUnitInClassPresenter does not understand #findMethod

**Comment by ericwinger** [comment]
Sunit tab walkback fixed in https://github.com/GemTalk/Jadeite/commit/4f1007341084a4455f6fe2017d0b692ca9a2e729

**Comment by LisaAlmarode** [comment]
With no class selected in the project browser, find method is enabled but does nothing.

**Comment by ericwinger** [comment]
Fixed in 3.0.64 https://github.com/GemTalk/Jadeite/commit/9de37ea7c538800f6075bee2da12bc9407539f31
