### ISSUE TITLE
Need a way to know if you are in autocommit

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#421]
It's very important to know if you are in autocommit.  I do all sorts of weird things when trying to reproduce bugs that I don't want committed.

In VW, there's an autocommit icon in the icon bar of all browsers, that shows selected if autocommit is on.  Some such highly-visible indicator is needed.

**Comment by ericwinger** [comment]
Have a fix for this in Oscar 3.0.60. https://github.com/GemTalk/Jadeite/commit/e31b2905800a20471c5cf4b4cc491aa2235a326d

**Comment by LisaAlmarode** [comment]
The autocommit icon is not in the debugger... which is okay, I guess.  Not in dictionary browser, which is fine. It's eye catching and in the main code browsers.  I'm going to call this done although I'm sure there's work to be done, but this is good for now.
