### ISSUE TITLE
(3.0.58)  Add subclass in hierachy view adds to wrong class (or does not work)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#422]
This is part of the issue #377 that didn't get fixed in 3.58.  Other class menu items now work in hierarchy view, but add subclass is still a no-op or even adds a subclass to the wrong class.

In class list view, select a class and go to hierarchy view.
Select a superclass or subclass of the selected class.
add subclass displays the definition to create a subclass on the class that was selected previously in the class list view, NOT the class that is currently displayed as selected.

If nothing was selected before looking at the class hierarchy, add subclass is a no-op.

**Comment by ericwinger** [comment]
Fixed in 3.0.60 https://github.com/GemTalk/Jadeite/commit/4191b4f9c870ae3d6dae037dfcf3686612512bfd
