### ISSUE TITLE
(3.0.59) would like to have auto-commit be persistent

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#423]
Since I tend to have development sessions that last for days ... I imagine that I will be so used to having "auto-commit" turned on that I will forget to enable it when I launch a new session ...

1. If it was on by default, then I wouldn't have to worry ... 
2. I it was persisted in the db, then I would only have to remember to set it when I build a new stone (part of the build script in the first place)
3. If it was persisted in the session file, then I would have to remember to set it when I created a new session file

As it stands now, I have to remember for each login which is the least convenient ...

I'm marking as `Februrary` because I want this issue considered and leave the final decision/disposition to @ericwinger and @LisaAlmarode

**Comment by LisaAlmarode** [comment]
Personally, I do NOT want autocommit to be persistent!  I'm a somewhat hesitant autocommit user so this is not an unbaised opinion. 

Autocommit is the kind of thing that ought to be in a preferences file somewhere.  We have an existing file-based mechanism that's used to disable tranlog writes that works like a charm for me, but I think you don't like that, and are working on a more fully developed preferences feature.  I'm not even opposed to some kind of hack of throwing some flag in UserGlobals.

**Comment by dalehenrich** [comment]
When storing prefs in a stone, it is (should be) a bit more complicated than just stash in UserGlobals.

See the test RwPlatformInstanceTest>>testPreferencePrecedence (issue_361 branch for sure) for examples of how to store preferences in a stone: global, user, session ....

So if we use that framework it would be possible to programatically set Global/User preferences when a stone is created  by adding logic to the stone creation script (fo those who prefer not to have to memorize and type the commands needed to create a stone) and allow a user to set a preference persistently or on a per session basis ...

I think I have mentioned in the past that the windows file for preferences should be used for preferences that need to be applied before one is able to connect to a stone --- from the GUI perspective an option for local file/global/user/session on setting each pref would cover the whole range of possibilities) ... (the Transcript control is one of those things that lives on the border, since I think currently the client forwarder is created during login ... so the preference cannot be stored in the stone without some (probably non-trivial) work ...

I don't quite remember when I implemented the preferences framework so I don't know if it is present in 1.2.x or only 2.0.0:) ... Could be easily move to 1.2.x if it isn't there ...

**Comment by ericwinger** [comment]
A few arguments against persistent auto commit:

1. I don't use the feature because making a change to server services code runs the risk of making my development environment unusable. If changes are automatically committed, recovery is difficult and potentially results in lost work. Without auto commit, I can just abort the transaction and continue. (Admittedly, I'm not doing "normal" Jadeite development work.) 

2. GBS's auto commit feature is off by default and must be enabled on every login. We haven't heard any requests from users to change that. 

As mentioned [earlier](https://github.com/GemTalk/Jadeite/issues/423#issuecomment-459823056), there are options for preference-based persistent settings that could be written. However, defaulting auto commit to false on login and requiring the user to enable it is the correct behavior to me.

**Comment by dalehenrich** [comment]
Just as another point of reference I use it all the time in tODE and in tODE it is on by default and I haven't heard many complaints either:) 

To be fair, your bullet points aren't about whether or not a developers choice for autocommit be persistent, but why you don't want the default to be auto commit  on ...  

I am asking that it be made persistent and I assume that I will be able to include it in my build script and turn it on withour too much trouble ... and keep in mind that this is a February issue not because it needs to be implemented in February, but because I wanted to make sure we discussed it in February ... and we have, so thank you!

**Comment by LisaAlmarode** [comment]
As of sometime before 3.0.82, autocommit is now in the prefs file.  
Default is off by default... for compatibility with previous.
