### ISSUE TITLE
Background colors of text pane

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#424]
In a project browser, the method pane background may have one of three colors,
  Color for Compile Errors (pink)
  Color for No Edits (yellow)
  Color for Unsaved Edits (green)

However, if you are on the class definition tab (or the class documentation tab), the background is white (usually).  If you edit it turns pink.  Then a compile error is inlined, not displayed in the status bar.  

It should DEFINITELY turn green when edited rather than pink - that's just wrong.
I think it should be yellow for no edits. 

I see this in reproducing a cross-browser problem... this bug is really a tail-end part of bug #418.  When you have two project browsers open, with the class definition showing in one, the background of the class definition is white.  If you select the same class in a second browser, the background of the text pane in the OTHER browser turns from white to yellow.   I think it's the initial white that's the problem.

**Comment by ericwinger** [comment]
Would like to fix this in the next customer release of Jadeite targeted for April. Changing label.

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.69. Will need review and, no, I couldn't get the sunit tab header to be anything other than white. The rest are yellow and a dirty class def pane is green - same as method pane dirty.

**Comment by LisaAlmarode** [comment]
I don't see anything white on the Sunit tab of the PB.  Just FYI - it looks good.

- [x] The class documentation tab does not turn green on edit.  

- [x] in a method browser, the comparison tab backgrounds are white; they are yellow in the project browser.

Class compile errors are currently not working quite correctly, I think, but that's not part of this issue.

**Comment by ericwinger** [comment]
Fixed in 3.0.75

**Comment by LisaAlmarode** [comment]
This is all consistent in 3.0.75.  
I will say that the comparison tab's bright yellow highlights on the softer yellow is... well... not a particularly agreeable color combination.  But it seems like it would be functional and I'll leave it for someone who uses this feature to initiate further aesthetic discussion.
