### ISSUE TITLE
Jadeite should be able to check out a git tag not just branch

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#425]
To use the correct rowan with jadeite I need to get the correct tag; the latest checkin in rowan may not work with the latest jadeite. 

But I can't do this from Jadeite.  I don't want to have to go to the command line and remember the correct git magic invocation -- I'm using jadeite so I can avoid having to do that.

In addition to Checkout Git Branch... there ought to be a Checkout Git Tag...

**Comment by LisaAlmarode** [comment]
Raised the priority since this really does seem like a missing piece.

**Comment by dalehenrich** [comment]
I agree that this is a missing piece, but for November 19, it is not a requirement - and you did not tag it as November 19:)

**Comment by ericwinger** [comment]
Should have a first-cut at this in 3.1.0pre-release2.

**Comment by LisaAlmarode** [comment]
<accidently put this on unrelated bug>

-- if you select multiple projects in the console, the checkout git branch is disabled, but the checkout git tag is enabled. The checkout git tag gives an error, so that menu item should be disabled too.

-- if you checkout git tag on one of the Rowan projects, like STON, then it really checks out tag on all but you can't tell... you have to explicitly refresh. I think after a git checkout operation, it would be worth the extra time required to automatically do a refresh.

-- this is just my not really understanding tags v. branches. When I have checked out a tag, am I still in some sense on a branch? I see my "branch" as "HEAD detached at ", with no mention of "oscar" anywhere. When I went to the checkout branch menu I felt a moment of unease since while I thought I was on oscar and in theory might be able to use the latest on that branch... I didn't see anyway to check that was in fact the branch I was generally following.

**Comment by dalehenrich** [comment]
> -- if you checkout git tag on one of the Rowan projects, like STON, then it really checks out tag on all but you can't tell... you have to explicitly refresh. I think after a git checkout operation, it would be worth the extra time required to automatically do a refresh.

This might be something that Rowan will have to get involved in ... STON is an `embedded project` which means it shares a git repository with more than one Rowan project ... so git operations on individual projects could/should return a list of the affected projects ... with V2, loading Rowan automagically loads STON, Tonel, FileSystem and Cypress ... so those projects need to be refreshed

**Comment by dalehenrich** [comment]
> -- this is just my not really understanding tags v. branches. When I have checked out a tag, am I still in some sense on a branch? I see my "branch" as "HEAD detached at ", with no mention of "oscar" anywhere. When I went to the checkout branch menu I felt a moment of unease since while I thought I was on oscar and in theory might be able to use the latest on that branch... I didn't see anyway to check that was in fact the branch I was generally following.

When you check out a tag, you are **not** on a branch ... you are on a commit and you will not be allowed to commit, pull, or any other operation that operates on branches. A single commit can be part of multiple branches so it is not really possible to automatically associate a tag with a branch. You can't be "on oscar" and "on a tag" at the same time, unless the tag is pointing at the commit that is at the HEAD of the branch ... 

Checking out a tag is a valid thing to do ... but if you really need to be on that specific commit **and** you want to be on a branch, then you must create a new branch using the tagged commit as the HEAD of the branch ... at this point you will be able to do commits, pulls, etc. 

Now if you are "following a branch", then you should checkout the branch and do periodic pulls ,, the problem with oscar is that Eric may have made changes on oscar that no longer work with your current Jadeite client ... so the only *safe* thing to do is to learn to be comfortable with checking out a tag and trusting that the commit you are on is the correct commit that is needed for your Jadeite client ... which is indeed the case.

**Comment by ericwinger** [comment]
> -- if you select multiple projects in the console, the checkout git branch is disabled, but the checkout git tag is enabled. The checkout git tag gives an error, so that menu item should be disabled too.

Believe that it was meant to say "git branch gives an error" . Enablement fixed. 

> ---- if you checkout git tag on one of the Rowan projects, like STON, then it really checks out tag on all but you can't tell... you have to explicitly refresh. I think after a git checkout operation, it would be worth the extra time required to automatically do a refresh.

Refresh after checkout tag/branch now done.

**Comment by LisaAlmarode** [comment]
Main issues were fixed in pr3, and per Dale I'll not worry about the branch - I don't normally, it was just testing checkout where I was at risk of getting lost.  

Especially nice that I didn't have to do a fetch on the branches, the tag was there and I could do it all in jadeite - that's even a happy dance!
