### ISSUE TITLE
Strange case of classes turning purple

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#426]
I have an SUnit browser open and a project browser open on the same package, which has several test cases.

When I select one of the classes in the SUnit browser, that class in the Project browser, the font turns purple.  Affects both class list and hierarchy view.

**Comment by ericwinger** [comment]
Have a fix in 3.0.60 https://github.com/GemTalk/Jadeite/commit/4d88ec2e0276c9b9cae36832f1f71bbe553eda22
