### ISSUE TITLE
Walkback on new inspector in presence of #size method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#433]
I have a class that's a subclass of IdentitySet that has an instance variable that holds an instance of a Dictionary.  When I attempt to inspect this, I get a walkback (now, previously it was all good in earlier Jadeite and in GBS). The walkback is very inexplicable.

This class implements the size method, which returns the size of the dictionary rather than the size of the collection itself.  This odd structure is an artifact of an optimization and I didn't want to change the superclass, but it's legal.

It's easy to reproduce 

IdentitySet rwSubclass: 'LisaSet'
	instVarNames: #( dictionary)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'RowanSample1-Tests'
	options: #()

instance methods:
dictionary: newValue
	dictionary := newValue

size
	^dictionary size

class method:
new
	| n d |
	n := super new.
	d := Dictionary new.
	d at: 1 put: 2.
	n dictionary: d.
	^n

And inspect:
LisaSet new

a OffsetError occurred (error 2003), reason:objErrBadOffsetIncomplete, max:1 actual:1
OffsetError (AbstractException) >> _signalWith: @5 line 25
OffsetError (AbstractException) >> signal @2 line 47
LisaSet (Object) >> _error:args: @15 line 11
LisaSet (IdentityBag) >> _at: @4 line 10
LisaSet (IdentityBag) >> do: @5 line 8
LisaSet (Collection) >> printNonRecursiveRepresentationOn:recursionSet: @7 line 10
LisaSet (Object) >> printOn:recursionSet: @7 line 8
LisaSet (Object) >> printNonRecursiveOn: @3 line 5
LisaSet (Collection) >> printOn: @2 line 5
LisaSet (Object) >> printString @6 line 14
JadeServer64bit32 (JadeServer64bit3x) >> inspect: @96 line 48
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
@LisaAlmarode  If I execute this code, I see the same error. ``LisaSet new printString``.  I would argue that this isn't an inspector bug.

**Comment by dalehenrich** [comment]
One _could_ also argue that the inspector should handle Errors during printing and allow the object to be inspected ...

**Comment by LisaAlmarode** [comment]
Is it a requirement that printString always be implemented?  This code doesn't given me any problems in GBS, and the tests are running clean.  It's not a display type object at all, but I needed size for the tests.  I'm not sure I agree that my code is "broken".

And, well, I am forever introducing problems in display for inspectors... as least for me it's part of code development.  I would expect a code development environment to at least attempt to cope with normal problems that occur when doing, well, code development...

**Comment by ericwinger** [comment]
The inspector should indeed play nice when an unexpected error occurs. However, is that an immediate need of this release?  I would argue that it could wait until a more robust error handling solution could be put into the inspectors.

**Comment by LisaAlmarode** [comment]
Surely developers who have no choice can live with this... it's just not great to give the impression that jadeite is quite that dainty.  I verifed that a recursive call does get an AlmostOutOfStack and not crash, though.

**Comment by ericwinger** [comment]
I have a fix in 3.0.63 that handles errors during inspection and displays a message with the oop and underlying error message instead. https://github.com/GemTalk/Jadeite/commit/e88121212dfa854c2a761732a33a524ccc4729dd

**Comment by LisaAlmarode** [comment]
weeealll it's fixed in the case where you inspect the bad object, which is nice.  But my actual use case is not fixed.

If you're inspecting the object that references the bad object, and select the instvar referencing the bad object, you get a walkback.  The error ought to be displayed on the right.

You can't see this in the example since Arrays show themselves as part of the main inspector so you get the error up front.  To reproduce, create a class 
Object rwSubclass: 'LisaClass'
	instVarNames: #( aaa)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'RowanSample1-Tests'
	options: #()
and method
aaa: something
	aaa := something

And reproduce my original walkback by inspecting this, which brings up an error-free inspector, and selecting aaa:
LisaClass new aaa: (LisaSet new); yourself

----------------

Also, it seems a little too forward about the error.  For example, the following:

Array with: Dictionary new with: Set new with: LisaSet new

Results in a single inspector on an error.  I was quite confused since I expected an Array of three with the last being an error.

**Comment by ericwinger** [comment]
Should have a fix in 3.0.64. Both examples reported today seem to work. https://github.com/GemTalk/Jadeite/commit/6a4555c046dfead9dadcdee6dd47b6c1273d16b3
