### ISSUE TITLE
New inspector pane sizes are very awkward

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#434]
I've been trying out the new inspector.  The half-and-half proportions aren't right, the left pane is too wide and the right pane is too narrow.  1/3 -2/3 would be much better, and even 1/4-3/4 might work.  

This is quite annoying in a new feature... and hopefully not a hard change so marking it for February.

![image](https://user-images.githubusercontent.com/13142166/52305684-9673c900-294a-11e9-83c2-1d9016bd1203.png)

![image](https://user-images.githubusercontent.com/13142166/52305662-85c35300-294a-11e9-9bcf-8f070e301bfa.png)

![image](https://user-images.githubusercontent.com/13142166/52305797-ddfa5500-294a-11e9-8a21-d09928b652a1.png)

**Comment by ericwinger** [comment]
The inspector isn't new but I'm using this inspector for all inspected objects now. Before, special objects, characters, etc used a simplified inspector but it was requested to be changed here https://github.com/GemTalk/Jadeite/issues/398#issuecomment-454833499

Regardless, I've changed the width to about a 1/3 - 2/3 proportion in 3.0.61. https://github.com/GemTalk/Jadeite/commit/0e22c1b91bf9b6b179846cb644ffe40851ee352f

Sample:
![image](https://user-images.githubusercontent.com/36212516/52360336-9928f980-29f0-11e9-9775-c597d06571b8.png)

**Comment by LisaAlmarode** [comment]
Much nicer.
