### ISSUE TITLE
Inspector should handle out of range characters a little better

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#435]
Inspecting an out of range character or strings gets weird errors.  The first two are for the same code, but I think a little white space around execution makes a difference.  This isn't really expected to work (customer not using out of range characters), but it should at least fail a little more gracefully.

![image](https://user-images.githubusercontent.com/13142166/52306126-d4bdb800-294b-11e9-80bc-c4bc16b17944.png)

![image](https://user-images.githubusercontent.com/13142166/52306193-08004700-294c-11e9-8414-80067b994e14.png)

![image](https://user-images.githubusercontent.com/13142166/52306272-4c8be280-294c-11e9-92dc-6d09251321a2.png)

A string is even more awkward; you get the first dialog, then a execution thing that lasts forever, when you close that you get the second dialog.

![image](https://user-images.githubusercontent.com/13142166/52307012-47c82e00-294e-11e9-8783-287e5b1bb0be.png)

**Comment by ericwinger** [comment]
I'll have a partial fix checked in for 3.0.67. Reassigning to Lisa for review at that time.

**Comment by LisaAlmarode** [comment]
It consistently errors the same way in 3.0.67, but previously it appears to have printed the correct results and now it always errors, which is reduced functionality.  It's okay for the single current customer but is not going to work for a more general audience.

**Comment by LisaAlmarode** [comment]
In 3.0.74, it does not print results and does not error.  Instead it prints a space and a single quote mark and highlights the last 11 characters in the line.  This cannot be described as unbroken.

![image](https://user-images.githubusercontent.com/13142166/62332407-69751e80-b474-11e9-9317-64c04530a359.png)

**Comment by ericwinger** [comment]
At least in the inspector, this should be better than before as of 3.0.92. Good enough to warrant a review and a more specific bug if necessary.

**Comment by LisaAlmarode** [comment]
The inspector part of this bug appears to be working in 92.3.  The print-it is broken as per an earlier pic; but I'll file a separate bug.  The handling of a pasted-in $š is different, but that appears to be due to the dolphin windows code page which is a separate (heinous) bug.
