### ISSUE TITLE
Need a way to handle preferences (that Dale likes)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#436]
Dale wants autocommit to be always on for him, per issue #423.  The rest of us want it to be always off unless turned on and then revert to off on logout.  We can't have both behaviors until we sort out how we are ultimately handling preferences for the user.

As of 3.0.60:

1. We have a file-based preferences mechanism that works very well for me to ensure Transcript Writes On is always off.  It's very limited and somewhat fragile.  Dale doesn't like this way of doing things, though, and is unlikely to accept it for autocommit status... so not worth generalizing.

2. There's another way settings get persisted, from the Jade base, the user name and other login parameters get put somewhere and magically reappear.  It's a mixed blessing, I like the GBS list better.  These count as persistent ways to configure your environment, though.  I don't think we should expand this beyond login settings.

3.  So... we need another way of handling preferences that will work for Dale for his autocommit, and also doesn't make it too difficult for my transcript writes setting.

Ultimately this is going to need a preferences browser but if the framework is reasonable we should be able to get the functionality there before all the bells & whistles.

Eric, I'm assigning this to you, Dale has some code he could back port but I'm guessing there will be some work on your part.  I think Dale would call this critical while I'd call it an annoyance so I've left it unprioritized...

**Comment by dalehenrich** [comment]
Lisa, you are putting an awful lot of words in my mouth ... why don't you take a chill pill and lets talk on Thursday when we are both in the office --- It is clear to me that besides misinterpreting my thoughts with relation to default behavior, now you are misinterpreting my thoughts on whether or not "the rest of you" can handle preferences (that "the rest of you like") ...

It is very obvious that we are not on the same page ... so before jumping the gun why don't we just make an attempt to get on the same page before firing off issues like this one? 

I'm closing this issue until we've had a chance to talk ...
