### ISSUE TITLE
`rename` class menu item would be useful

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#439]
The plan is to add rename class Rowan api in v1.2.x (GemTalk/Rowan#470) ... then a `rename class` menu item would be considered for addition to Project Browser for April release ... See [this comment](https://github.com/GemTalk/Rowan/issues/470#issuecomment-463365292) for details about the `renameClassNamed:to:` functionality --- available in candidateV1.2 now

**Comment by ericwinger** [comment]
When this is done, close #306.

**Comment by ericwinger** [comment]
Checked in a "final" fix in https://github.com/GemTalk/Jadeite/commit/8476f8fc39024c9f0e0fd3d74715a263ece05623
Should be in 3.0.67
