### ISSUE TITLE
Remove a constraint doesn't "take"

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#44]
My test case happens to have constraints in the class definition.  Removing one or both of the two constraints doesn't have any effect - the definition still shows the constraints.  It appears impossible remove constraints.

Creation and modification use the template:

Object rwSubclass: 'Moth'
	instVarNames: #( aaa bbb ccc)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'PackageTwoA'
	constraints: { { #aaa . String} . 
                { #bbb . Integer} }
	options: #()

**Comment by ericwinger** [comment]
This appears to a bug in Rowan. I created the Moth class in a workspace and it appeared in the browser showing constraints. Then I tried to remove the constraints by emptying the constraints part of the definition (in both the browser and workspace). In neither case were the constraints removed. 

Assigning to Dale and opening Rowan issue https://github.com/dalehenrich/Rowan/issues/326

**Comment by dalehenrich** [comment]
dalehenrich/Rowan#326 was fixed earlier today and is available on the candidate branch ... reassigning to @ericwinger so he can do the merge and then @LisaAlmarode cna validate

**Comment by LisaAlmarode** [comment]
Changes in constraints now do show up in the code browsers and are written to disk.  

Oddly, they do not show up in the project changes list. So not marking this closed, but the most important things are fixed.

**Comment by ericwinger** [comment]
Reassigning to @dalehenrich and reopening bug https://github.com/dalehenrich/Rowan/issues/326 referencing Lisa's comment about not showing up in change list.

**Comment by ericwinger** [comment]
Closed #326 in favor of https://github.com/dalehenrich/Rowan/issues/347

**Comment by ericwinger** [comment]
After talking with @dalehenrich, it appears Rowan is already prepared to give change information directly to Jadeite without going through the monticello patch layer. 

Need a new gui to display. See https://github.com/ericwinger/Jade/issues/123
