### ISSUE TITLE
(3.0.63) class def / instance var oddities

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#445]
1. add iv to class, switch to variables pane (pink background ... okay)
   - add instance variable `postLoadClassList`
   ![image](https://user-images.githubusercontent.com/623951/53132054-57856c00-3523-11e9-8fdd-1fbbf0788549.png)
   - accept (looks good)
   ![image](https://user-images.githubusercontent.com/623951/53132125-9ca99e00-3523-11e9-82ca-1dbf903501e3.png)
   - click on variables pane, with intent to add accessors (where'd the instance variable go?)
   ![image](https://user-images.githubusercontent.com/623951/53132170-d5497780-3523-11e9-9e09-a988a1a4df65.png)
   - click off the class and then back on (ins var reappears)
   ![image](https://user-images.githubusercontent.com/623951/53132296-32452d80-3524-11e9-99af-ffa8aeabb6d1.png)

I saw at least one other funky behavior in this area (adding an inst var to a class and clicking around), but I don't remember the exact sequence...

The fact that the inst var disappears make this a feb bug (in my opinion)

**Comment by ericwinger** [comment]
The service wasn't getting updated properly before selecting the variables tab. Fixed in 3.0.64. https://github.com/GemTalk/Jadeite/commit/7b316500b6b75697ea2951ab7d08965a1b45b0d9

**Comment by LisaAlmarode** [comment]
I don't see Dale's behavior.  It's not clear what he does in step 1 "switch to variables pane", since the catagories pane is showing and he switches to variables pane in step 3.  

I see a little peculiar behavior in that with variables tab selected, you can move around and between unsaved class and method defs, but when you select category you have to save or lose.  I don't see anything like a bug, just inconsistency.

**Comment by dalehenrich** [comment]
@LisaAlmarode in the first graphic (step 1) I had not actually added the instance variable yet ... just edited the (pink) pane and step 2 is the accept, so step 3 is the initial switch where the iv is not visible in the vars pane and that is/was the the bug ... I did see other odd behavior in this area and was just happy that I could take screen shots of the "bad behavior" ... many times even I cannot reproduce the bug:)
