### ISSUE TITLE
(3.0.63) Accessors menu disabled 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#446]
Continuing on from Issue #445, the Accessors menu item is disabled:
![image](https://user-images.githubusercontent.com/623951/53132559-e646b880-3524-11e9-8be2-d794d0a71741.png)

Don't know if it really ever worked, since I just noticed it the other day ... after I had added accessors manually:) ... was looking forward to using it too ...

If it's not expected to work I vote for including it in April release

**Comment by ericwinger** [comment]
Think this is the same as #382.  April release works for me.

**Comment by dalehenrich** [comment]
indeed
