### ISSUE TITLE
(3.0.63) more odd behavior with add instance variable

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#447]
I added an instance variable to a class and the the project browser updated and switched to method view ... but I wasn't done with adding instance variables ...

Not able to reproduce (tried several different possibilities, I hadn't been working too long in a fresh session before it appeared) ... might be related to Issue #445 ...

**Comment by ericwinger** [comment]
It appears that if the ``Variables`` tab is selected, the class switches to the ``Method Source`` tab after saving a class. That has been fixed in 3.0.67 https://github.com/GemTalk/Jadeite/commit/2be436e9d377b0e08a97a767b3a4d9c8024c4fbe
