### ISSUE TITLE
(3.0.63) missing class definition template in empty package

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#449]
I deleted the last class in a package and now there is no class definition template:
![image](https://user-images.githubusercontent.com/623951/53262840-8703b800-368c-11e9-82a4-c2881d8922dc.png)

Candidate for April consideration ...

**Comment by ericwinger** [comment]
Not sure how you deleted the class but I did find that if you delete the class from the hierarchy browser no class template is shown. Now we retain the removed class's template for convenience. 
Fixed in 3.0.66 https://github.com/GemTalk/Jadeite/commit/06eef323274ac0bd885333fc1d18b56507973ac5

**Comment by dalehenrich** [comment]
I'm not quite sure what you mean by: 
> Now we retain the removed class's template for convenience.

But when I delete the last class in a package, I expect to see the same class template that you see when you have just added a package (here I added the xxx package) and this is the class template I'd expect to see when I delete the last class in a package:
![image](https://user-images.githubusercontent.com/623951/56059393-d1162b00-5d18-11e9-9984-3df996c44ff5.png)

**Comment by ericwinger** [comment]
I don't retain the old class template forever, just until you click away.

**Comment by ericwinger** [comment]
Old class template was removed in favor of the package default template. https://github.com/GemTalk/Jadeite/commit/a4ac97526e4417d6fc3266bd6845937be6bb6a70

**Comment by dalehenrich** [comment]
so deleting a class does not count as "clicking away"? ... I'll repeat that I **expect** that when I delete a class the class template will be a fresh class template that looks the same as the template visible when I add a new package ... but it is only an expectation ...

**Comment by dalehenrich** [comment]
... deleted previous comment that was a reply to https://github.com/GemTalk/Jadeite/issues/449#issuecomment-482699627 ... without seeing the later comment (https://github.com/GemTalk/Jadeite/issues/449#issuecomment-482721355) where you appear to be saying that your expectations are the same as mine:)
