### ISSUE TITLE
(3.0.63) loading a project version when classes moved between packages (and possibly selected) hits error

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#451]
My use case involved the project [GsDevKit_upgradeDevKitImage](https://github.com/GsDevKit/GsDevKit_upgradeDevKitImage) where I was sitting at commit 3503a5e9fe4776d5e68e5600d2e4a77c508bbba9, with the class **GsuAbstractGsDevKit**  selected while viewing he **GsDevKit_upgradeDevKitImage-Core** package using hierarchy view; then loaded commit cf8ecda8a4a2641c3cbd35864917f80b31fd3ef7 .... and got the following stack:
```
a LookupError occurred (error 2021), reason:rtErrKeyNotFound, A reference using the non-existent key 208 was made into the dictionary anIdentityDictionary( 5->aRowanMethodService(GsuAbstractGsDevKit>>gemstone_user), 10->aRowanMethodService(GsuAbstractGsDevKit>>upgradeUserName:upgradeSymbolDictName:), 15->aRowanClassService:GsuAbstractGsDevKitUpgrade, 20->aRowanPackageService:GsDevKit_upgradeDevKitImage-Core, 25->anArray( ), 30->anOrderedCollection( ), 35->anArray( aSTONReference(20)), 40->anArray( ), 45->aRowanClassService:GsuGsDevKit_3_5_0_BootstrapUpgrade, 50->anOrderedCollection( 'bootstrapApplicationLoadSpecs', 'bootstrapExistingConfigurationList', 'bootstrapPostLoadClassList', 'bootstrapRepositoryDirectory', 'methodsWithPragmas', 'sourceGemStoneRelease', 'targetGemStoneRelease', 'upgradeSymbolDict', 'upgradeSymbolDictName', ...), ...)
LookupError (AbstractException) >> _signalWith: @5 line 25
LookupError (AbstractException) >> signal @2 line 47
IdentityDictionary (Object) >> _error:args: @15 line 11
IdentityDictionary (AbstractDictionary) >> _errorKeyNotFound: @2 line 5
IdentityDictionary >> at: @5 line 8
STONReader >> resolveReferenceIndex: @2 line 2
STONReader >> resolveReference: @3 line 2
[] in  ExecBlock1 (STONReader) >> processSubObjectsOf: @4 line 5
RowanClassService (Object) >> stonProcessSubObjects: @6 line 6
STONReader >> processSubObjectsOf: @6 line 4
STONReader >> next @7 line 6
STON class >> fromStream: @4 line 2
STON class >> fromString: @3 line 2
JadeServer64bit32 (JadeServer) >> updateFromSton: @3 line 4
GsNMethod class >> _gsReturnToC @1 line 1
```
If I don't have anything selected, the project browser doesn't (appear to) update and leaves the classes  that should have been moved to another package still visible ...

Added to Feb, because I want it reviewed .. this could very easily a scenario seen by a customer

**Comment by ericwinger** [comment]
STON replication can handle references but I've found that it works better to only replicate simple objects - strings, integers, booleans, etc.  This issue is representative of the kind of failure I've run into. Jadeite only replicates simple objects by and large and if we can figure out what inst var in RowanClassService was a reference instead of a simple object, we probably can fix this. 

@LisaAlmarode  - Is there any way you can help me find a simpler reproduction case?

**Comment by dalehenrich** [comment]
One thing that would help resolve issues like this is to have the option to include the values of args and temps when copying the stack (ala topaz stack dumps) to provide more information to the person who understands the code involved ... it doesn't replace the need to sometimes need to debug, but the extra information often provides enough clues to figure out what went wrong (I've been doing "remote topaz stack debugging" recently and the extra info has saved me from having to arrange to interactively debug a long and complicated set of topaz invocations (upgradeSeasideImage) ... 

In this case it looks like all of the juicy information would be in Object>>stonProcessSubObjects ... particularly the instance variable of RowanClassService that that references the non-simple Object...

**Comment by LisaAlmarode** [comment]
Closing as somewhat stale.  Dale, reopen if you still see things like this.  We do have the requested debugging details now.
