### ISSUE TITLE
busy cursor changes to insert over code pane (3.0.63)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#452]
Without the dialog, I'm looking at the cursor to know when things are done. 

I execute some code by do-it in a PB code pane.  This code does client file reads and takes a while to run.

When the cursor is over the code pane, it's the I insert, NOT the busy cursor.  When I move the mouse over the rest of the browser it's the busy hourglass cursor (rather than the arrow).  But the cursor over the code pane being non-busy is very confusing.

**Comment by ericwinger** [comment]
@LisaAlmarode I executed a simple expression ``(Delay forSeconds: 10) wait`` but didn't see the cursor change no matter which pane I passed it over. Perhaps it has something to do with the type of execution? 
If you execute this expression do you still see the insertion cursor? 

fyi - I'm running on Windows 10.

**Comment by LisaAlmarode** [comment]
In 3.0.73, I see the correct busy cursor over all panes when I do what I probably did to create the original problem, and also with Eric's code sample. Spot checked in workspace and PB code pane using doit and printit.  Call it fixed.
