### ISSUE TITLE
Variables tab, change variable selection, are not prompted to save method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#454]
If you are in a class with variables, and the variables tab, and select a variable, and edit the template to write a method, 
and then select a different variable,
you are not prompted to stay on unsaved method

**Comment by ericwinger** [comment]
Fixed in 3.0.57. https://github.com/GemTalk/Jadeite/commit/890e973e36be342104ed880b164bd2edd0c99a01
