### ISSUE TITLE
Jadeite - Inspector on characters in iso88599 fails

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#456]
Issue reported in Rowan https://github.com/GemTalk/Rowan/issues/473#issue-414657840

Looks like a Jadeite issue.

**Comment by LisaAlmarode** [comment]
The error in this issue can be reproduced in 3.0.75 by inspecting:
```
(Set with: (Character withValue: 353))
```
When you click once on the dict instvar, it shows: 
```
Error inspecting object Oop(148865793). Error text: an Error('Can''t hold $\x161')
```
When you double click in dict, you get an error dialog, Invalid format for Number.

**Comment by ericwinger** [comment]
As of 3.0.92, should no longer error.
