### ISSUE TITLE
`audit project` menu item in project list pane?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#457]
... having just made a bunch of edits on disk and then load/update ... would be useful thing to have ...

**Comment by ericwinger** [comment]
@dalehenrich What is the Rowan api & what output does the audit generate ?

**Comment by dalehenrich** [comment]
Api is in RwPrjAuditTool ... currently the most useful output is written to the gem log ... the audit returns a dictionary containing audit results ... the audit passes if the dictionary is empty ...  @alexkogan has plans to improve the form of the dictionary results and the prospect of supporting a Jadeite GUI would accelerate this work ... the simplest change would be to log output to a stream that could be presented to the user upon failure ...

**Comment by ericwinger** [comment]
@dalehenrich @alexkogan  I looked at ``RwPrjAuditTool `` and the api doesn't look too difficult to implement. However, it appears that the only easily accessible output is in the KeyValueDictionary.  I could spit out some output based on the dictionary that's produced but it would be nice if there was more user-friendly output I could present. 

Also, is there an easy way to make a project fail an audit so I can see some results?

**Comment by ericwinger** [comment]
Awaiting on @alexkogan for better output api's.

**Comment by dalehenrich** [comment]
The new audit work was done by @alexkogan on the candidateV2.0 branch, so at this point I'm inclined to defer the `audit project` work until you begin work on the V2.0 support work ... out v1.2 customer is satisfied with the current state of affairs

**Comment by ericwinger** [comment]
V2.0 audit code is `(Rowan projectNamed: <project-name>) audit` 

Moving this to the new V2.0 project so it will get addressed.

**Comment by ericwinger** [comment]
Fixed in Jadeite 3.2. Simply brings up the audit results in a workspace.
