### ISSUE TITLE
CompileWarnings should be more noticable ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#459]
I just found out that the ProjectBrowser has been giving me compile warnings all along, when Eric told me that the warnings show up in the tiny pane at the bottom of the project browser ... I knew that the debugger provided Warnings (via popup), but never realized that I was getting warnings from the Project Browser ...

With GemTalk/Rowan#477, the Rowan bootstrap code and Rowan test scripts will check for CompileWarnings during loads .... so I am hoping that that the compile warnings could be more noticeable than they are now ... when we get a compile error the background turns red ... which is better than nothing, although last week I probably worked for an hour or more without realizing that one of the methods I was working with never did compile ... the red background was not quite enough and of course I never did notice the "silent warnings" ...

Something a little bit gaudier would help old men like me (with failing eyes) to notice that errors and  warnings are afoot:)

**Comment by ericwinger** [comment]
@dalehenrich @LisaAlmarode 
Trying to work within the limits of what Dolphin will easily let me do ... What would you think about compile warnings and errors showing up something like this?

warnings - yellow status bar 
compile errors - more intense red

![image](https://user-images.githubusercontent.com/36212516/55348854-085d2000-546d-11e9-84eb-ed8a0f52d46c.png)

![image](https://user-images.githubusercontent.com/36212516/55351499-5ecd5d00-5473-11e9-906d-93211225ee3a.png)

**Comment by dalehenrich** [comment]
The yellow for warnings is okay -- I have enough information from the message to know what to do ... the only comment would be that the warning needs to be cleared when a recompile (that cleans up the warning is succeful) ... I have seen cases where the warning messages stick around after I removed the temp and recompiled.

**Comment by ericwinger** [comment]
@dalehenrich @LisaAlmarode Verbal feedback for the compiler error change was that the darker red background obscured the squiggly underlines. The picture below shows what would happen if we left the background color unchanged, but made the status bar red. 

Thoughts? 

![image](https://user-images.githubusercontent.com/36212516/55439211-ba254b00-5558-11e9-9788-cdd173918639.png)

**Comment by dalehenrich** [comment]
We're wandering into territory where it is hard for me to read the 
message with the darker red background ... I think a lighter red would 
still do the trick as long as white background always means no 
error/warning ...

Dale

**Comment by ericwinger** [comment]
@dalehenrich Better? 

![image](https://user-images.githubusercontent.com/36212516/55825008-eb9e9900-5ab9-11e9-9b0e-4db9379bbb02.png)

**Comment by dalehenrich** [comment]
... better yes ... i can read the message now ... I'm still thinking that just the background change is not enough to indicate (to me) that an error occurred ... so perhaps a bright yellow (like warning) in the message area at bottom would scream that there is "a message to look at down here" and draw my eye ...

**Comment by ericwinger** [comment]
Like this? 

![image](https://user-images.githubusercontent.com/36212516/55840693-2b2cab80-5ae1-11e9-9e21-01a94c0465d8.png)

**Comment by dalehenrich** [comment]
yes ... it makes my eyes hurt to see those two colors together, but that's what I'm looking for:) ... thanks

**Comment by ericwinger** [comment]
@LisaAlmarode  Could you weigh in on Dale's color scheme? Thanks.

**Comment by LisaAlmarode** [comment]
It's nice to have yellow=warning and red=error.  

Can we discuss the font? The footer font is regular-weight gray, and not easy to read in any case.  Making it bold and black would help visibility in all cases.

If we do that than the darker pink might work.  While the yellow is highly visible, there's no narrative continuity; we want a story about color meanings, not randomly making things clash.

**Comment by dalehenrich** [comment]
@LisaAlmarode sounds good to me ... while we're at it, could we re-evaluate the use of the squiggly red underline on red background at the same time ... that's a worse problem than the readability of the error text in my poor vision opinion ...

**Comment by LisaAlmarode** [comment]
Squiggle improvement would be great -  I don't have a problem noticing the pink error, myself, but often I have a very hard time actually FINDING the error in my code based on that teeny, low-contrast squiggle.

**Comment by dalehenrich** [comment]
I have trouble enough noticing the pink background as an error condition:) As I've mentioned before, I spent an hour with a pink background in browser before I realized that it meant a compile error ... In tode the window would flash when an error occurs, but in Jadeite the window flashes on updates as well and the color change from yellow to green to red or yellow just doesn't register :) ... 

I never even noticed that warning text was showing up in the bottom bar of the window until Eric pointed it out to me so I'm hoping that the bright yellow will actually register:)

**Comment by ericwinger** [comment]
@dalehenrich @LisaAlmarode Without modifying the colors, what about this for a squiggle improvement? 
![image](https://user-images.githubusercontent.com/36212516/56167692-b26c9a00-5f8d-11e9-93bb-9266a19b45e5.png)

**Comment by dalehenrich** [comment]
Looks good ... I can see it even at small size ... out of curiousity could you show what a missing `]` error would look like ....

**Comment by ericwinger** [comment]
This is one possibility. 
![image](https://user-images.githubusercontent.com/36212516/56168984-99fe7e80-5f91-11e9-85fe-cd5841414645.png)

**Comment by dalehenrich** [comment]
that works fine ...

**Comment by LisaAlmarode** [comment]
Definitely an improvement, though I can't say until I've got a mass of code with a buried error.

**Comment by ericwinger** [comment]
> Can we discuss the font? The footer font is regular-weight gray, and not easy to read in any case. Making it bold and black would help visibility in all cases.

>If we do that than the darker pink might work. While the yellow is highly visible, there's no narrative continuity; we want a story about color meanings, not randomly making things clash.

I made the text black and the colors more consistent (yellow-warning, red-error). What do you think? 

Warning: 
![image](https://user-images.githubusercontent.com/36212516/56241491-d7731280-604a-11e9-9309-e432d1c41bfb.png)

Error: 
![image](https://user-images.githubusercontent.com/36212516/56241569-05f0ed80-604b-11e9-9140-d23ab22d1f1b.png)

**Comment by dalehenrich** [comment]
I can read the message in both ... much better ...

**Comment by ericwinger** [comment]
@LisaAlmarode  - comments?

**Comment by LisaAlmarode** [comment]
I like the consistent colors, I can read both pretty well, so if Dale thinks it's the reds and pinks are 
noticeable enough it works for me.  

However, question: do warnings stop the compile from taking place?  The yellow background currently means "saved changes" so I hope so.  If not, we're back to misleading.... we might revisit the "saved changes" color (which is occasionally white).

**Comment by ericwinger** [comment]
@LisaAlmarode Warnings don't prevent compilation so yellow still means the changes have been saved. I'll go ahead and close this bug. The changes will be in 3.0.67 for review.

**Comment by dalehenrich** [comment]
Missing bold font in compiler error pane (3.0.67) ... 
![image](https://user-images.githubusercontent.com/623951/56839104-e53c4b00-6835-11e9-842a-7048d2871fce.png)
I downloaded the runtime.zip directory ... if that matters

**Comment by dalehenrich** [comment]
Warning is suffering from gray font has well:
![image](https://user-images.githubusercontent.com/623951/56839250-79a6ad80-6836-11e9-8cae-d624bd9641d9.png)

**Comment by ericwinger** [comment]
The method list browser still had gray text. Compiler & warning text is fixed.  Also noticed that the compiler error red status bar was hanging around when the method was changed. Fixed. https://github.com/GemTalk/Jadeite/commit/cf8b542dc5ae0d8a8bde0a75a7d16400d65afeef

**Comment by LisaAlmarode** [comment]
The colors and fonts are all very nice.

The warning bar is hanging around after the method has changed.  Not critical but nice to clean this up, assuming that's the intetnion.

If there are multiple unused temps, it's not handled very pleasingly. At least, please add a space between.

I'd added  
   | aa bb cc dd |
saved, got warning, then edited to remove the temps. 

![image](https://user-images.githubusercontent.com/13142166/62101645-f6d52a80-b24a-11e9-929b-462527b39520.png)


Really, all unused temps ought to grouped and not reported individually. And I think after some number of errors, say after twice as much as will fit on the bar? Three times? It should stop appending and assume that these are all consequences of some earlier problem.

**Comment by LisaAlmarode** [comment]
Closing this and opened issue #509 for the unused temp warnings
