### ISSUE TITLE
Class Documentation can't be saved or viewed

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#46]
In Projects Browser, go to Class Documentation tab.  Type in.  Save.  See UndefinedObject does not understand do: error dialog.  

In the Dictionaries Browser, do the same thing and it goes away without being saved.

You cannot view class documentation in the Dictionaries browser when it is present, which is actually serious.  Figuring out the codes for DateTime formatting is important.

**Comment by ericwinger** [comment]
Believe this is now fixed in 3.0.11

**Comment by LisaAlmarode** [comment]
I can now save a class comment in the projects browser.  However, it doesn't appear to "take" in rowan; it does not make anything dirty (not italic), does not show up in changes, and write to disk does not write it out.  

Also the Dictionaries browser, while saving class comments, does not display an existing class comment.  This is an important feature since the base is not rowanized.

**Comment by ericwinger** [comment]
> I can now save a class comment in the projects browser. However, it doesn't appear to "take" in rowan; it does not make anything dirty (not italic), does not show up in changes, and write to disk does not write it out.

This was reported as a Rowan bug https://github.com/dalehenrich/Rowan/issues/306

Still to do: 

- [ ] Also the Dictionaries browser, while saving class comments, does not display an existing class comment. This is an important feature since the base is not rowanized.

**Comment by ericwinger** [comment]
The dictionary browser's comment setter and getter code was fixed as of 3.0.12

**Comment by LisaAlmarode** [comment]
Don't see any changes in behavior in 3.0.12 with rowan oscar 93d3bc7.

**Comment by ericwinger** [comment]
This is a rowan-only fix that just affects the dictionary browser. Try shaw 292f145 for your review.

**Comment by LisaAlmarode** [comment]
Testing class comments verified under issue #58, using 3.0.14 and ef4afb6.
If I try to save a change to a base class class comment, I get a walkback, Attempt to add or modify an unpackage method in the class, which is perfectly reasonable.
