### ISSUE TITLE
Stuck with UndefinedObject doesn't understand #gciCallInProgress prompt

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#463]
After loosing connection to stone. I occasionally end up with this forever prompt. Have to use task manager to kill process. At this point we should probably just exit jadeite after user clicks prompt first time. Not much on can do. Or prevent it from popping up again so user could possibly copy content of current editor or something.
![image](https://user-images.githubusercontent.com/1958382/56753753-20f4e900-6740-11e9-85f9-1c56bed8f7b1.png)

**Comment by LisaAlmarode** [comment]
I'm going to close this since a lot of work was done on getting close down to work smoothly (not sure when).  I'm not seeing problems lately, but I don't know how common it was before.  Please reopen with a more information if this this happens again.
