### ISSUE TITLE
(3.0.68) nice to have selected test remain visible aftr pressing the `run selected` button

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#467]
BEFORE (note selected test):
![image](https://user-images.githubusercontent.com/623951/57155897-78730480-6d91-11e9-9bd0-04e4d63cc772.png)
AFTER:
![image](https://user-images.githubusercontent.com/623951/57155952-93457900-6d91-11e9-848b-c9470221a94b.png)
Would be nice if the selected test stayed visible after update ... for large number of tests, it can mean a bit of manual searching has to be repeated every time ...

**Comment by ericwinger** [comment]
As of 3.0.69, after test run, the first selected test is visible.
