### ISSUE TITLE
Find text dialog does not highlight correctly

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#468]
The Ctrl-F find dialog doesn't always highlight found text properly. Also, you have to click a radio button to search in the right direction. Replacing the current find dialog with an advanced find would add the wrap & regex search capabilities. 

Fixed in 3.0.69

**Comment by LisaAlmarode** [comment]
- [x] Layout needs to be tweaked for native windows 7 - the down and wrap labels  are wrapped and partly obscured. 

![image](https://user-images.githubusercontent.com/13142166/62105888-8503dd80-b258-11e9-8f2c-3258757a55d9.png)

 - [x] find direction up is broken.  Without wrap it only finds the first instance of the match; with wrap it goes back and forth between the first two occurrences.

 - [x]  This is not definitely a bug, but I couldn't really test the reg exp, there needs to be help. I couldn't get [0..9] to work (except one baffling one), but \d does work.

**Comment by ericwinger** [comment]
I created our own find dialog as the Dolphin version was limited and non-intuitive. @LisaAlmarode You'll need to look at the dialog on your native windows host as I can't see the formatting problem in check box 1. The up doesn't seem to be broken (as we discussed) but if you can provide a reproduction case, I'll take another look. The new dialog also has a working wildcard expression using a simple Smalltalk ``match:ignoreCase:`` call. It's more usable. 

Fixed in 3.0.75.

**Comment by LisaAlmarode** [comment]
Note to self: testing per issue #397, in 3.0.74 if you select a text that includes an lf or perhaps it was a tab or something... the find dialog fails to find. Check in 3.0.75 when that's available. Either stripping off things that are not searchable on, or finding them, seem alternatives

**Comment by LisaAlmarode** [comment]
In 3.0.75, I seem to be missing the wrap option - the find dialog appears to have reverted to the older version.  It doesn't have the little magnifying glass icon in the corner.  I like wrap, or at least search from beginning.

**Comment by ericwinger** [comment]
New Jadeite subclass of ``AdvancedFindDialog`` was getting stripped out image by Dolphin. Added ``JadeiteAdvancedFindDialog`` to list of classes in ``JadeImageStripper>>requiredClasses``

Fixed in 3.0.76.

**Comment by LisaAlmarode** [comment]
Alas, while it's back in 3.0.76, the layout tweaking was insufficient.

![image](https://user-images.githubusercontent.com/13142166/63881945-ce456b00-c985-11e9-9762-83153b3fdb08.png)

**Comment by LisaAlmarode** [comment]
![image](https://user-images.githubusercontent.com/13142166/64568718-4dd12380-d310-11e9-9b51-4a5b52d39807.png)

I suppose you could use "dwn" and "wrap"...

**Comment by ericwinger** [comment]
@LisaAlmarode Can you review in 3.0.78? I'm not sure which version [your comment](https://github.com/GemTalk/Jadeite/issues/468#issuecomment-529679660) is referencing.

**Comment by LisaAlmarode** [comment]
In 3.0.78, looks just like my most recent graphic.

**Comment by ericwinger** [comment]
Lisa-tested fix in 3.0.79

**Comment by LisaAlmarode** [comment]
Working nicely in 3.0.79.  I note that a * matches exactly one character, which is slightly different wild-card semantics from the usual... might be nice to add a note to the dialog, but I guess folks would figure it out.
