### ISSUE TITLE
(3.0.69) Jadeite process crashes shortly after closing debugger ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#472]
********************************************************************************
************************** Dolphin Crash Dump Report ***************************

11:05:46 AM, 5/18/2019: Jadeite.exe caused an unhandled Win32 Exception C0000005
at 004121E5 in module 00400000 (C:\Users\dhenrich\Oscar-3.0.69\Jadeite.exe)

*----> Exception Parameters <----*
00000001	
0241FFFC	

*----> CPU Context for thread 0x12f8 <----*
EAX = 02420000 EBX = 02630390 ECX = FFFFFFFF
ESI = 02846980 EDI = 02846980 EIP = 004121E5
ESP = 0019F6A8 EBP = 0019F6C4 EFL = 00010246
CS = 0023 SS = 002B DS = 002B
ES = 002B FS = 0053 GS = 002B

*----> VM Context <----*
Process: {80080210:size 536330277 words, suspended frame 7FE7028D, priority 3, callbacks 0
last failure 0:nil, FP control 80017, thread 00000000}
Active Method: Process>>primTerminate
IP: 023D50C0 (0)
SP: 7FE702B4
BP: 7FE7028C (-540656)
ActiveFrame: {7FE7028C: cf 02846700, sp 00000000, bp 7FE7028C, ip 0, Process>>primTerminate}
	receiver: a Process(RowanDebugger>>onIdleEntered base 7FE70000 in Process>>shutdown sp=7FE70288 ip=15 list=02620010)

New Method: Process>>primTerminate
Message Selector: primTerminate

*----> Stack Back Trace <----*
{7FE7028C: cf 02846700, sp 00000000, bp 7FE7028C, ip 0, Process>>primTerminate}
	receiver: a Process(RowanDebugger>>onIdleEntered base 7FE70000 in Process>>shutdown sp=7FE70288 ip=15 list=02620010)

***Unable to generate complete exception report (c0000005)

***** End of crash report *****

**Comment by dalehenrich** [comment]
Another mysterious crash ... not specifically related to debugger (logging showed that method browser closed last)  ... but it felt the same to me ... waving mouse around thinking about where to go next and Jadeite disappears:
```
********************************************************************************
************************** Dolphin Crash Dump Report ***************************

14:55:02 PM, 5/30/2019: Jadeite.exe caused an unhandled Win32 Exception C0000005
at 004121E5 in module 00400000 (C:\Users\dhenrich\Oscar-3.0.70\Jadeite.exe)

*----> Exception Parameters <----*
00000001	
021AFFFC	

*----> CPU Context for thread 0x187c <----*
EAX = 021B0000 EBX = 02500390 ECX = FFFFFFFF
ESI = 0265E880 EDI = 0265E880 EIP = 004121E5
ESP = 0019F368 EBP = 0019F384 EFL = 00010246
CS = 0023 SS = 002B DS = 002B
ES = 002B FS = 0053 GS = 002B

*----> VM Context <----*
Process: {80080210:size 244220028 words, suspended frame 3A4203E9, priority 3, callbacks 0
last failure 0:nil, FP control 80017, thread 00000000}
Active Method: Semaphore>>wait:ret:
IP: 007A7280 (0)
SP: 3A420410
BP: 3A4203E0 (-292650907)
ActiveFrame: {3A4203E8: cf 0265EA20, sp 00000000, bp 3A4203E0, ip 0, SmallInteger(Semaphore)>>wait:ret:}
	receiver: 488702450
	arg[0]: 488702436
	arg[1]: a Array


New Method: Semaphore>>wait:ret:
Message Selector: wait:ret:

*----> Stack Back Trace <----*
{3A4203E8: cf 0265EA20, sp 00000000, bp 3A4203E0, ip 0, SmallInteger(Semaphore)>>wait:ret:}
	receiver: 488702450
	arg[0]: 488702436
	arg[1]: a Array


***Unable to generate complete exception report (c0000005)

***** End of crash report *****
```

**Comment by ericwinger** [comment]
A hard crash like this while moving the mouse, unfortunately, implies Dolphin may be to blame. Getting a stack with Jadeite doing something bad would be helpful to show it's in our code.

**Comment by ericwinger** [comment]
@dalehenrich Just curious. Have there been anymore occurrences using 3.0.71?

**Comment by dalehenrich** [comment]
There haven't, but I have not been using Jadeite with autocommit turned on, because I got tired of having the browser lose it's mind ... have I tried autocommit at all with 3.0.71? Maybe once and things went haywire so I've quite using autocommit (not because I don't want to use it, but because it has become unstable) ... maybe you should turn autocommit on and see if you see the misbehavior I have seen ...

**Comment by ericwinger** [comment]
Ok, thanks for the feedback.

**Comment by LisaAlmarode** [comment]
This is an old bug related to dolphin and debugger, which have both many changes; closing.
