### ISSUE TITLE
(3.0.69) inconsistent debug menu on workspaces

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#474]
The Jadeite menu in console workspace:
![image](https://user-images.githubusercontent.com/623951/58196632-95f40980-7c7f-11e9-8487-ba33971a9b87.png)
 is not consistent with the Jadeite menu in a workspace opened from file:
![image](https://user-images.githubusercontent.com/623951/58196669-ae642400-7c7f-11e9-9167-acbd618d56ca.png)
The specific issue I am having is that the Debug shortcut key is `Ctrl+B` in the console workspace nad `Ctrl+G` in the file-based workspace and despite the fact that the popup menu in the file-based workspace claims that `Ctrl+B` is the shortcut for Debug:
![image](https://user-images.githubusercontent.com/623951/58196962-321e1080-7c80-11e9-92ff-daf5be69a596.png)
It seems that the Jadeite shortcut wins out ...

**Comment by ericwinger** [comment]
Accelerator fixe to Ctrl-B in workspace in 3.0.72.
