### ISSUE TITLE
(3.0.69) 'incorrect` class creation template

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#475]
Step 1. class creation template is `correct`:
![image](https://user-images.githubusercontent.com/623951/58373513-2894e280-7ee4-11e9-91c3-a7004ffab8f4.png)
Step 2. select class that is not defined in the Rowan-Tools-Deprecated package ... again class creation is `correct`:
![image](https://user-images.githubusercontent.com/623951/58373524-59751780-7ee4-11e9-96f7-2a0ca9a28f1b.png)
Step 3. deselect the class and the class creation template is `incorrect`:
![image](https://user-images.githubusercontent.com/623951/58373539-80334e00-7ee4-11e9-935d-d83cead3a4b9.png)
With no class selected, I expect to see the same class creation template displayed in step 1

**Comment by ericwinger** [comment]
Just needed to send ``JadeiteProjectsBrowserPresenter>>resetClassTemplate`` before bailing out of ``refreshClass`` after the deselection.  Fixed in 3.0.72.

**Comment by LisaAlmarode** [comment]
Eric, I cannot seem to deselect a class.  This is 3.0.74.  I can select a different package but that is hardly the same thing.  Am I suppose to be able to deselect?  Without deselect this bug is moot...

**Comment by ericwinger** [comment]
@LisaAlmarode Assuming the class list is visible, try selecting below the classes in the class list.

**Comment by LisaAlmarode** [comment]
I can deselect by clicking in the white space... thanks. 

But only in the class list view, not in the hierarchy view.  But I won't reopen for that... the hierarchy view has bigger problems.
