### ISSUE TITLE
SUnit Run all tests fails with index out of bounds

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#476]
oscar 3.0.69. Clicking run all tests with nothing selected results in error.
![image](https://user-images.githubusercontent.com/1958382/58534971-886be180-81a1-11e9-9d9b-9a588962a5e1.png)

**Comment by alexkogan** [comment]
![image](https://user-images.githubusercontent.com/1958382/58535106-e993b500-81a1-11e9-85a6-641796af65a0.png)

**Comment by LisaAlmarode** [comment]
This is fixed in 3.0.75
