### ISSUE TITLE
(3.0.70) need a new version of Jadeite with latest 3.5.0 gci libraries ... 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#478]
current 3.5.0 libs don't work with the latest builds ... I'm not shutdown, at the moment, since I'm mainly doing 3.2.15 based work, but would be nice to have sooner rather than later ...

**Comment by ericwinger** [comment]
Libs updated in 3.0.71

**Comment by LisaAlmarode** [comment]
I am not testing jadeite in 3.5

**Comment by dalehenrich** [comment]
I'm using 3.5.0 daily and can confirm that the 3.5.0 libraries have bee present since June ...
