### ISSUE TITLE
(3.0.71) would like method browser to be consistent with project browser when saving methods

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#481]
In the project browser, when you save a method, your position in the method is preserved, in fact the source pane is not modified at all ...
In the method browser, when you save a method, the source pane is reset to the beginning and you have to remember where you were and navigate (often painfully) back to the point where you were editing the method.

**Comment by dalehenrich** [comment]
I realize that when a method browser is brought up on a senders query, that it is definitely preferable to have the first message send in the method selected when it is selected from the list, but when a method is accepted, I would think that preserving the position at accept time should take precedence ... i should always be able to use the `Find Next` menu item if I want to search for more senders...

**Comment by LisaAlmarode** [comment]
I think this is fixed in 3.0.74.

**Comment by ericwinger** [comment]
Closing per Lisa's comment.
