### ISSUE TITLE
(Oscar-3.0.72) Empty Find Class dialog

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#484]
Here's the empty `Find Class` dialog (it starts out empty as well):
![image](https://user-images.githubusercontent.com/623951/59983027-7a0dbb80-95cf-11e9-8648-306708fd66f1.png)
auto commit is enabled and this is the first bad behavior that I've noticed for the system since turning on auto commit several hours ago.
I've attached the log file:
[log file.txt](https://github.com/GemTalk/Jadeite/files/3318659/log.file.txt)
I used this menu on the console to bring up the dialog:
![image](https://user-images.githubusercontent.com/623951/59983073-05874c80-95d0-11e9-8cd4-4751fc80199a.png)
I turned off auto commit and the Find Class dialog was functional again:
![image](https://user-images.githubusercontent.com/623951/59983094-34052780-95d0-11e9-9f38-7acdda545c56.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.73.  My hunch is that this will also fix other auto-commit "funnies" that were noticed in the past but were hard to reproduce.
