### ISSUE TITLE
(Oscar-3.0.72) Display in method source pane does not `visibly` dirty the pane

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#485]
The highlighted `nil` is evidence that I did a Display in the method window, but the background shows as unmodified...:
![image](https://user-images.githubusercontent.com/623951/60060144-2325e600-96a4-11e9-9b41-72e4c54b466c.png)
... until I click on something:
![image](https://user-images.githubusercontent.com/623951/60060193-5b2d2900-96a4-11e9-9c59-a2c941726f20.png)
A backspace will clear the `nil` as well and leave the pane appearing to be unmodified...

**Comment by ericwinger** [comment]
Fixed in 3.0.73. Browser needed to respond to the #textChanged event as well.
