### ISSUE TITLE
hierarchichal class list with versions(?) reorders on select

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#487]
Notice that the class order has changed and that difference classes are selected:
![image](https://user-images.githubusercontent.com/623951/60451889-062c6e00-9be2-11e9-870d-c2fdd3d521f1.png)

![image](https://user-images.githubusercontent.com/623951/60451907-13495d00-9be2-11e9-8d8d-67fb11b44362.png)

**Comment by ericwinger** [comment]
@dalehenrich This doesn't reproduce for me. If this happens again, it would be useful to have a Jadeite.errors file attached to see if there were any recent errors which might affect browser state. 
You can also turn on logging as you click on the hierarchy in the bad state then attach the log file.

**Comment by LisaAlmarode** [comment]
I'm not entirely sure what the reproduction case is... something wasn't selected and then became selected, or was selected and selected something different.  Tried various combinations but did not find a case that the classes were not ordered correctly. 
Closing and moving to retired; in case Dale sees it again and has more information.
