### ISSUE TITLE
(Oscar-3.0.72) seems that we've lost ability to login as non-SystemUser?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#488]
![image](https://user-images.githubusercontent.com/623951/61314239-0f583600-a7b1-11e9-9601-0cc7304c9063.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.73.
https://github.com/GemTalk/Rowan/commit/92936f0d4b3c4974fc9edad60565a0ba7f8ac84a

**Comment by LisaAlmarode** [comment]
I can login as non-System user in 3.0.77; but cf issue #529, which appears to have the same error, when browsing a symbol dictionary
