### ISSUE TITLE
(3.0.73) package multi-select is not functional

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#489]
I am interested in seeing the classes in the two selected packages, but it seems that Jadeite is not cooperating:
![image](https://user-images.githubusercontent.com/623951/61556429-9e19bc80-aa16-11e9-8591-907f39b15421.png)
It seems that multi-select of packages is not working ... I would like to be able to drag some methods from a class in one package to a class in another package and it seems that I can't arrange to see both classes at the same time (multi-select would make it possible) ...

I'm calling this a bug, because if multi-select is enabled, it should work ...

**Comment by ericwinger** [comment]
Until I can fix the hierarchy view, you can see the combined list in the ``Classes`` tab. 

![image](https://user-images.githubusercontent.com/36212516/61655002-8179c080-ac72-11e9-9254-e67d1ade046b.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.74. Single package/dictionary select (and class) hierarchy working. Needed to add multi-select support.

**Comment by LisaAlmarode** [comment]
It works nicely.  I don't think it's ideal that if you have a method selected, and you select a second package, you lose the method selection.  But that's a quibble.
