### ISSUE TITLE
(Oscar 3.0.73) need a way to find class in the dictionary view

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#491]
sometimes I want to find out which dictionary a class is located in and the natural way to do that would be to find class within context of dictionary view ...

**Comment by ericwinger** [comment]
Fixed in 3.0.74. Added a menu item that lets the user see the class's dictionary and go directly to it.

**Comment by dalehenrich** [comment]
... good idea ...

**Comment by LisaAlmarode** [comment]
Works nicely !
