### ISSUE TITLE
(oddity) change from category tab to variables tab should not give "method has unsaved changes" prompt

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#493]
Currently you do not lose the changed method (which is the desired behavior) ... but the prompt discourages the `timid`:)
![image](https://user-images.githubusercontent.com/623951/61818124-01d02b00-ae05-11e9-8e58-d4e574b5b71d.png)

**Comment by ericwinger** [comment]
Should have a fix for this in 3.0.74.

**Comment by LisaAlmarode** [comment]
I see no prompt and changes not lost.
