### ISSUE TITLE
(Oscar-3.0.74) highlighting of multi-keyword selectors in senders/implementors browser is broken

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#500]
1. Select a keyword message in projects browser
2. Senders
3. Method list browser is opened but no highlighting is done of the selector in the source

Example - do senders of 
![image](https://user-images.githubusercontent.com/623951/62482834-1698b100-b76b-11e9-8272-cfd7f4dc53a3.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.75.  Highlight should highlight the first characters before the colon when a keyword message sender list is shown. Also, took the opportunity to make sure senders & hierarchy senders were also using the first reference index sent back from the server.

**Comment by LisaAlmarode** [comment]
Highlights on search has got some problems in 3.0.75.

I randomly selected servicePerform:withArguments: senders (in class RowanPackageService).
The list has six methods.  Three display correctly; three have highlights in other places.  

Then I tried isDirty. the first 8 or so in the list were fine; then one had highlight in the wrong place, and the next one,  RwPackage >> isDirty

gives an error dialog, index 68 is out of bounds.

**Comment by ericwinger** [comment]
First reference calculation was wrong in a couple ways. Fix in Rowan in 3.0.76.
