### ISSUE TITLE
Make defined package text into a clickable button

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#501]
A nice to have feature suggested by Dale would be to make the two ``Defined Package: ..." text fields be buttons that go to the defined package.  Not a bad idea. 

In the attached picture, the text is ``Defined Package: RowanSample1-Tests``

![image](https://user-images.githubusercontent.com/36212516/62578135-4328f780-b855-11e9-86ec-f839687c2e6f.png)

**Comment by ericwinger** [comment]
This is fixed in 3.0.77. The buttons don't look like traditional buttons for aesthetic reasons, but they do have enough clues for a savvy user to deduce what they do.

**Comment by LisaAlmarode** [comment]
If I don't have a class selected, the button is present and clicking on it produces the error"
UndefinedObject does not understand #command:"

**Comment by ericwinger** [comment]
Have a fix in 3.0.78.
