### ISSUE TITLE
method menu consistency between project browser and method list

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#502]
I was missing the find literal references on the method list menu.  However, this may be just an artifact of testing and not actually a desirable addition.

However, there is some cleanup needed for consistency; the left is the method list, the right is the project browser.

![image](https://user-images.githubusercontent.com/13142166/62652012-2bae4500-b90f-11e9-9089-7e68c56ff288.png)

My opinions:

Method list browser,
 - [x]  move the two Hierarchy Implementors items up, so they are just under 
   the Browse Imp/Senders block. 

  - [x] Have a line between these and the Browse Methods Containing.  

  - [x] Perhaps add browse literal references.

Either/Or:

  - [x]  We should add the file out methods to the Method list browser; or remove it from the Project Browser since it is not functional.  It's either a placeholder or not...

  - [x]  Either there should be a line after Remove Method(s) on both or neither;  I am
    inclined to add one to the project browser menu, since remove method is not 
    naturally groupable with the run tests items.

**Comment by ericwinger** [comment]
Fixed in 3.0.75. Choices - removed file out methods menu item and removed the line after Remove Method(s)
