### ISSUE TITLE
(3.0.74) MNU on project browser update

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#503]
This is the second time I hit this this morning:
![image](https://user-images.githubusercontent.com/623951/62654729-4d122f80-b915-11e9-95e2-2404b211df1d.png)
The first time I had reloaded the st_launcher project form disk (load menu item) and the second time I was searching for `GsTonelOrderedDictionary`.

Here's the after picture:
![image](https://user-images.githubusercontent.com/623951/62654912-bc881f00-b915-11e9-86d8-0049fab2f9f1.png)
Closed and re-opened browser after first incident ... looks like project browser is okay this time, but will close and re-open to be safe ...

**Comment by dalehenrich** [comment]
Got it again ... did 'load' in project browser, then clicked on package in package pane:
![image](https://user-images.githubusercontent.com/623951/62656615-7208a180-b919-11e9-9950-c00d5b95728e.png)

**Comment by ericwinger** [comment]
@dalehenrich Are you sure you've got the latest tagged Oscar loaded? RowanBrowserService>>classHierarchy does exist. 

![image](https://user-images.githubusercontent.com/36212516/62659113-543e3b00-b91f-11e9-8605-55d82ebf02f2.png)

**Comment by dalehenrich** [comment]
ah, good catch ... I'm on branch gs_360 (and I haven't merged 3.0.74 into it yet) ... meanwhile issue_308 where I was working before Allen started his work about a week ago):
![image](https://user-images.githubusercontent.com/623951/62661459-fbbe6c00-b925-11e9-845a-df9bbd1b77dd.png)
it's amazing that I've survived this long without additional issues.
