### ISSUE TITLE
Senders list select doesn't always scroll exactly right (3.0.74)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#505]
I have a method definition such that when you look at senders of another selector, and this is on the list, the highlighted/selected sender is not visible.  It's one line down such that you have to scroll to see it.  Sometimes you can see a few pixels of highlight, but not always.

The original method had a lot of complicated text, the text isn't important, but if I don't leave the white space it doesn't reproduce.  

This reproduces for me (on native Windows 7)

the method:

```
sendersHightlightOff
	| str dictionary |

	
	self dates do: [:aDate | 

	






		dictionary keysAndValuesDo: [:key :value | 
			str := dictionary at: key ifAbsent: [nil].
	



			dictionary at: key put: str, '    ', (aDate asStringUsingFormat: { 2 . 1 . 3 . $/ . 1 . 2 }), ': ', (dictionary at: key) asString, ' - ', value.
			].
		].


   	self dates do: [:aVariety | | details  |
		dictionary at: aVariety ifAbsent: [dictionary at: aVariety put: (String shouldhighlight: '     nothing').  ].
		].
	^str
```

and do senders of shouldhighlight:

![image](https://user-images.githubusercontent.com/13142166/62662114-c74baf80-b927-11e9-8a03-3868bd672ba7.png)

**Comment by ericwinger** [comment]
Added a sender of ``ensureCaretVisible`` after the search in 3.0.75. Seems to do the trick in the example case.

**Comment by LisaAlmarode** [comment]
Works nicely!
