### ISSUE TITLE
Useful to be able to copy a class ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#506]
Similar to rename except the original class is not removed ...

**Comment by ericwinger** [comment]
Got a feature implemented to try out in 3.0.77.

**Comment by LisaAlmarode** [comment]
Copy seems to work fine.

Quibble:  If you have a target name that alrady exists, it puts up a debugger.  
This ought to have an error dialog.

a UserDefinedError occurred (error 2318), reason:halt, There is already a class named 'Pink' in the system.

**Comment by LisaAlmarode** [comment]
closing this; followon in new issue
