### ISSUE TITLE
senders lists get highlighting confused after opening a second senders list

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#508]
If you do "Browse Senders Of...", on foo, you get a list of methods, and then as you click down it highlights an occurrence of the selector foo.

Then do a Browse Senders Of...", on bar, this list will highlight the bars. 

BUT... if you go back to the original method list, it now highlights selector bar if present in the method, and only highlights foo if there's no bar.

![image](https://user-images.githubusercontent.com/13142166/63308915-8f3e5800-c2a9-11e9-83a6-d5f68c4fec00.png)

**Comment by ericwinger** [comment]
Should be fixed in 3.0.76. 

 _Note to self - might be better to retain the first reference state in the browser instead of the method server._
