### ISSUE TITLE
Need better caption for github Jadeite project

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#511]
Going to [the Jadeite GitHub](https://github.com/GemTalk/Jadeite) project for the first time, a user encounters this description: 

``Jade is an Alternative Development Environment (IDE) for GemStone/S that runs on Microsoft Windows``

Seems like we can come up with something better. Or at least say Jadeite. 

![image](https://user-images.githubusercontent.com/36212516/63875078-8fa8b400-c977-11e9-835c-aee12e2ab74b.png)

**Comment by LisaAlmarode** [comment]
I kind of don't think I have permission to change this - at least I haven't been able to track down any way to edit it.  I updated the readme part ages go, but never spotted this line...

**Comment by LisaAlmarode** [comment]
Dale, you're the github expert - if you get me access to that string I'll edit it.

**Comment by dalehenrich** [comment]
@LisaAlmarode, I've given you and @ericwinger admin rights on this repository, so let me know if you can change the caption or not ..

**Comment by LisaAlmarode** [comment]
Easy peasey now - thanks Dale!
However, @dalehenrich  and @ericwinger please take a look at how I describe it, it's a big change.

**Comment by ericwinger** [comment]
I think this is fine, Lisa. Closing.
