### ISSUE TITLE
"run selected" can get disabled after save in debugger (3.0.76)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#512]
If you are running sunit tests from the project browser, and save a method in the debugger, when you come back to the project browser, for the method that you saved... the run selected test menu item is disabled in the method list.

- get to method RowanSample1Test >> test2
- put a breakpoint in
- use method menu run selected test.  See debugger.  add a space or something and save method.  use the go arrow to finish running test.  See Sunit tab.
- the browser still has the test2 method selected.  Try to run selected again.  change to different tabs and methods and it stubbornly stays disabled... you have to go to a different class to use it.

**Comment by ericwinger** [comment]
The instVar ``isTestMethod`` was not getting initialized correctly in RowanMethodService. Fixed in 3.0.77.
