### ISSUE TITLE
(3.0.77) should breakpoint browser come up with the first breakpoint in method highlighted?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#514]
In the picture below,the selected method in the project browser, shows that there is a breakpoint in the method. On the left is a freshly opened breakpoint browser ... would be nice to highlight and make visible the first breakpoint in the method:

![image](https://user-images.githubusercontent.com/623951/64491511-3154be80-d21e-11e9-93d6-41c3329f3464.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0.  If possible, highlight the method selected in the project browser when opening the breakpoint list.

**Comment by LisaAlmarode** [comment]
The (left side of the breakpoint browser) method is now selected, when you open the BB from the project browser.  However, this feature request didn't ask for that; it wants the first breakpoint within the selected method highlighted (in the right side breakpoint browser), and that is not in 3.1prerelease2.

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release4.
