### ISSUE TITLE
Deleting classes and project reload (3.0.77)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#516]
There are a number of odd behaviors, most of which I can't get to repeat.  The following are, I think, incorrect behavior.  These are probably the result of underlying rowan issues, Eric, I'll let you manage that.

(1) Creating a class in a different package or a different project with the same name has the effect of moving the class to that package.  If the new definition has a different superclass, it also changes the  existing class so it has the new superclass.  

While this might possibly maybe be intentional behavior, it seems very risky for those of us who might accidentally pick a name already in use. 

(2) Say you have an existing class.  Change the superclass (from Object to Set, say, and add an instance variable).   Either commit transaction/logout login, or not. Then reload the package.  

The result is your image still has the same version (subclassed from Set) loaded, but there exists a later version, so the class name as (2/3).  This is not correct behavior. 
If you remove the class and reload it's fixed up.

**Comment by ericwinger** [comment]
Note - Found this Rowan curiosity when compiling classes and reloading. Class history seems to increment unexpectedly. 
https://github.com/GemTalk/Rowan/issues/506

**Comment by ericwinger** [comment]
Aside from [the curious issue](https://github.com/GemTalk/Jadeite/issues/516#issuecomment-531033276), I believe this to be fixed in 3.0.78.

**Comment by LisaAlmarode** [comment]
Problems don't reproduce in 3.0.79
