### ISSUE TITLE
Add method history

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#518]
In Dolphin, I can see the method changes in the current image using a nice little method change history browser. It would be nice if we have something like this in Jadeite - even if it's not quite as graphically appealing. 

![image](https://user-images.githubusercontent.com/36212516/64718542-47ab8600-d47b-11e9-9b54-3b7210f3d71a.png)

**Comment by ericwinger** [comment]
Would have been nice for November's release but not going to make it.

**Comment by ericwinger** [comment]
I'm going to call this fixed in 3.0.92 so it can be reviewed.  It's a new feature so we can reopen it and enhance as need be.

**Comment by LisaAlmarode** [comment]
I get an error dialog when I attempt to use the method history menu item (drop down or pop up) on the project browser in 3.0.92-2

![image](https://user-images.githubusercontent.com/13142166/71041566-40c98a80-20de-11ea-8463-bb1d145bd887.png)

**Comment by ericwinger** [comment]
@LisaAlmarode Can you capture the stack from this error in this issue? It should be the last stack in jadeite.errors.

**Comment by ericwinger** [comment]
The dolphin browser I usurped came with a lot of hidden dependencies which weren't present in the runtime image. Think I've got the immediate problem fixed.

**Comment by LisaAlmarode** [comment]
I don't think it's quite correct when there's only one version.  I've filed a separate bug, issue #677,  for this as it's not earthshaking.  I find the interface a bit... not in a smalltalk/gemstone style, but it appears to work (in cursory testing).
