### ISSUE TITLE
(3.0.77) `browse senders`has inconsistent behavior

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#520]
Picking the `Browse Senders` menu item (n a workspace or inspector) produces a populated Senders browsers:
![image](https://user-images.githubusercontent.com/623951/64827283-6d6a8500-d578-11e9-8e53-f5b8d5c3ba7a.png)
However, selecting a multi-arg selector like `cloneSpecUrl:gitRootPath:useSsh:` results in an empty senders browser:
![image](https://user-images.githubusercontent.com/623951/64827329-a30f6e00-d578-11e9-9fd2-d0490d9c9f56.png)

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.78. Can get senders/implementors in a variety of ways in workspace and inspector panes which are hopefully useful. Examples below. 

![image](https://user-images.githubusercontent.com/36212516/64880221-80c73000-d60c-11e9-831f-a19dd38573fe.png)

![image](https://user-images.githubusercontent.com/36212516/64880238-90df0f80-d60c-11e9-9943-e642328dae17.png)

![image](https://user-images.githubusercontent.com/36212516/64880264-a2281c00-d60c-11e9-8443-c0b10be66bc1.png)

![image](https://user-images.githubusercontent.com/36212516/64880322-c683f880-d60c-11e9-83a0-128801cb11b9.png)

**Comment by LisaAlmarode** [comment]
This needs more work.  First of all, I suspect that issue #586 is the result of this fix and boy is that annoying for someone that does a lot of copy and paste.

In a workspace,  highlight the following gets good results (the --> line is what the popup menu item includes)
RBParser parseExpression: 'env:categoriesDo:'
  -> browse senders of parseExpression:
RBParser parseExpression: 'env:categoriesDo:' using: variable
  -> browse senders of parseExpression:using:

But this does not, which was that I started to verify with:
'abcde' perform: #copyFrom:to: with: 2 with: 3 
  -> browse senders of abcde' perform: #copyFrom:to: with: 2 with: 3 

Note that these highlight do not do anything at all in the method pane popup, but I assume that's outside the scope of this bug.

**Comment by ericwinger** [comment]
> This needs more work. First of all, I suspect that issue #586 is the result of this fix and boy is that annoying for someone that does a lot of copy and paste.

@LisaAlmarode - can you explain this comment? I suspect that there was a typo on the issue number as #586 was submitted on October 21st after your comment on October 15th.

**Comment by ericwinger** [comment]
The problem with this example was that it started with a quote but the selection did not end with a quote. 
`'abcde' perform: #copyFrom:to: with: 2 with: 3`
If Jadeite thinks you have a quoted string selected, it tries to help you by assuming that the entire contents of the string is a selector. That's handy in expressions like this: 
`RBParser parseExpression: 'env:categoriesDo:'`
However, Jadeite didn't properly look for the ending quote. That has been fixed. so selecting the entire first expression in a workspace now properly shows you `Browse Senders of ... #perform:with:with:` in the menu. 

Fix on local disk, ready for post-customer release.

**Comment by ericwinger** [comment]
Fixed in 3.0.92

**Comment by LisaAlmarode** [comment]
The example works correctly in 3.0.92-2
