### ISSUE TITLE
autocompletion

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#524]
customer request, not a problem if out of scope for November release

**Comment by ericwinger** [comment]
Should have a decent first-cut at this in 3.0.78. There is a menu option to disable it in the transcript if a user doesn't want it.

**Comment by LisaAlmarode** [comment]
autocommit is not enabled in workspaces, which seems somewhat incorrect.  Otherwise while I am not a personal fan it seems to be working and logically consistent.
