### ISSUE TITLE
Multiple sessions can't keep console project list straight

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#527]
We don't fully support multiple sessions in one jadeite, but since we allow it, it can't be this broken. 

I logged in as gemstone user Lisa, and tried to load a project; it contained a method referencing an class that wasn't loaded.  So I logged in a second time, as SystemUser, to remove that method.  But then my Lisa console displays the projects for SystemUser.  

Go back to my SystemUser condole, and do browse projects; both consoles now show projects for SystemUser.

**Comment by LisaAlmarode** [comment]
It goes downhill; the project browser gets confused too.  I was able to remove a method in one browser that said it was for SystemUser and showed Lisa's package, and I don't think the method was actually remove, but it's there and says Array does not understand #start.

**Comment by ericwinger** [comment]
@LisaAlmarode  I wouldn't expect this to work at all and break badly. 

Because it is a rather gross failure we can try to work around it and open a feature enhancement to allow multiple logins. One possible workaround is to disable the ``Login`` button after successful login and reenable it after logout. 

If we do want to add the feature, we'll need a session browser. The feature request should identify the desired functions in the new browser. 

Thoughts?

**Comment by LisaAlmarode** [comment]
I think for November 19 that multiple logins should be disabled, if they can't be patched up enough.  Disable and re-enable of buttons seems reasonable.

**Comment by ericwinger** [comment]
Login button disabled after login in Oscar 3.0.79.  For full support of multiple sessions, please open a new feature request issue with specifications.

**Comment by LisaAlmarode** [comment]
There are cases when you logout that the login does not become re-enabled.  This happens:
  - open the sunit browser
  - run tests
  - debug a test that has a assertion fail
  - open debugger
  - close console.  All windows go away except the login dialog, but the login dialog login button is still disabled.

**Comment by ericwinger** [comment]
``GciSession current`` wasn't getting set to nil when the transcript was closed. Should see the ``Login`` button enabled properly now in 3.0.80 in [the scenario described] (https://github.com/GemTalk/Jadeite/issues/527#issuecomment-541926154).

**Comment by LisaAlmarode** [comment]
I thought I saw a hole (where it wasn't reenabled) after an exit... but I can't reproduce.  I'm calling this done, it's going to be easy to see if does occur.
