### ISSUE TITLE
debug-it on ad hoc expression not working

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#531]
I wanted to try out the debugger on some ad-hoc code that contained a block.  When I did debug-it, nothing happened.  

It turns out that you cannot have leading whitespace before the first |.  This is perhaps a subset of issue #364, in which leading comments break debug-it; but disallowing white space seems unreasonable.  Surely we could add a trimSeparators.

the code that fails debug-it:

```
	| var i |
	var := WriteStream on: String new.
	i := 2.
	[i > 0] whileTrue: [
			i := i - 1. 
			var nextPut: (Character withValue: 70 - i).
			].
    var contents
```

**Comment by ericwinger** [comment]
Fixed in 3.0.78. Should work for leading cr's & lf's too.
