### ISSUE TITLE
Can't compile class as DataCurator (3.0.77)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#532]
Logged in as DataCurator, loaded RowanSample1. 

Try to add or remove an instance variable from a class and it gives an error in the status bar:

ERROR: a SecurityError occurred (error 2116), An attempt was made to modify the object #'jadeiteCompileClassMethod'->nil in obje

I can copy a class... I just can't edit one, even one I just copied.

**Comment by ericwinger** [comment]
Fixed in 3.0.78. Temp method ``#jadeiteCompileClassMethod``, uses for two-step compile was
not being put in ``SessionTemps current``. It was going to UserGlobals which
was incorrect.
