### ISSUE TITLE
Breakpoint browser seems muddled: method browser with duplicate methods

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#533]
There's browsing breakpoints, and then there's browsing a list of methods with breakpoints.  I think we lean toward the latter and otherwise muddle them together.

If I have three breakpoints in a method, it shows up in the list of methods with breakpoints (the alleged breakpoint browser) three times.  This isn't really useful, since it doesn't particularly highlight one or the other and if you remove one of the breakpoints in removed in all methods, you still have to keep track yourself. 

And the menu item should say "browse methods with breakpoints", since in fact there is not a specific breakpoint browser (at least in 3.0.77).

**Comment by ericwinger** [comment]
After talking with @LisaAlmarode, some of the work in unreleased 3.0.78 fixed the complaint with the exception of the duplicate methods. That is now also fixed.

**Comment by LisaAlmarode** [comment]
And OK with referring to it as a breakpoint browser since (at least we hope, as this went missing in 3.0.79 per recent comment in issue #515) it has the additional clear all breakpoints menu item.
