### ISSUE TITLE
Scope of Clear All Breakpoints is very confusing

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#534]
The only place I find the "Clear All Breakpoints" menu option in on the method menu in the Projects Browser.  This would intuitively apply to a selected method.  

However, it does in fact clear all breakpoints anywhere in the system.  

I think a "Clear all breakpoints everywhere" ought to be somewhere you might associate with the whole system, and not on the method menu.  Perhaps that should be on the console browse menu with the browse methods with breakpoints?  

It does not make sense NOT to have clear all breakpoints available in the browser you get after executing Browse Breakpoints. I can see all the breakpoints, but to clear them all I have to go back to the Project Browser?

If Clear Breakpoints was on a method menu and remove breakpoints in the selected method, then you could select all methods in the breakpoint browser and remove the methods that way.

**Comment by ericwinger** [comment]
I preemptively added a ``Clear All Breakpoints`` to the breakpoint browser in 3.0.78.

**Comment by LisaAlmarode** [comment]
The menu item was added... but went missing per issue #515; should be re-added in that issue.
