### ISSUE TITLE
(Oscar 3.0.77) dialog does not have focus

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#537]
![image](https://user-images.githubusercontent.com/623951/65924817-4814ae00-e3a3-11e9-82ac-f0671cd4c60c.png)
I just had a case where the focus was not taken by the dialog when I tried to do a load ... I logged out and tried again and got the same behavior (hitting CR did not select the 'Yes' button) ... I logged out again and now the issue won't reproduce ... for a very long time I have been in the habit of selecting load on a menu and then hitting cr as almost a reflex when the dialog appears so it is a bit disconcerting to have this apparently start to be unpredictable ... I know that you will say this is Dolphin problem, but that doesn't change the fact that it is disconcerting ... if you can't figure out what might be going on let's leave this open to see if it is something that recurs ... I haven't had this problem until today ...

**Comment by dalehenrich** [comment]
I just came back to the Jadeite window and the "lost focus" happened again ... I did another load and focus was handled

**Comment by LisaAlmarode** [comment]
Given the long time and dolphin port closing this; reopen if it is still happening in 3.2.12 or later.
