### ISSUE TITLE
(3.0.77) select class and method pane comes up empty ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#538]
I didn't take a picture, because I was trying to get work done so I clicked around and the methods reappeard... I've seen this happen several times in the last week or so ... naturally it does not reproduce ... but it has been quite a while since I've seen this behavior, which leads me to believe there's been a bit of a regression ...

**Comment by LisaAlmarode** [comment]
Closing as ancient and vague.
