### ISSUE TITLE
(3.077) package not shown as dirty until it is reselected

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#539]
Here a picture of a freshly written package and classes:
![image](https://user-images.githubusercontent.com/623951/65988096-0c79f280-e43c-11e9-9947-56eecc1f892d.png)

After editing and saving the visible method (notice that I've added a comment and saved):
![image](https://user-images.githubusercontent.com/623951/65988166-30d5cf00-e43c-11e9-9e8e-7cc7bb57955a.png)
... the selected package is not italicized ... The first package is italicized, because the bug did not reproduce on my first try ... so it seems to take two tries to expose the bug ...

When I click off and back on the package, it is properly italicized:
![image](https://user-images.githubusercontent.com/623951/65988370-89a56780-e43c-11e9-97ef-2e9cd5a9652a.png)

**Comment by ericwinger** [comment]
Believe I have a clean fix for this in 3.0.92.

**Comment by LisaAlmarode** [comment]
Verified that it's working correctly in 93-1 (testing as DataCurator but that shouldn't matter)
