### ISSUE TITLE
implementors of selectors within a method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#54]
When I have a method selected, I really would like to be able to find implementors of the selectors that are in that method.  VW and GBS provide a drop down list under browse implementors.  In Jadeite I have to copy them from the method body which is tricky for multiple-keywords.  They are blue in the method so someone knows they are selectors. 

This is the feature I most miss in Jadeite.

**Comment by ericwinger** [comment]
I *think* this is the same as #53. That should be fixed in 3.0.12. If it's not, let me know.

**Comment by LisaAlmarode** [comment]
OK with the #53 API rather than the GBS API.
