### ISSUE TITLE
(3.0.77) empty debugger panes ... no amount of clicking cures problem

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#540]
![image](https://user-images.githubusercontent.com/623951/66000158-b3b65400-e453-11e9-9685-8398ebb12885.png)

If I resize the debugger, the method pane **is** populated, however, a subsequent click returns to total emptiness:
![image](https://user-images.githubusercontent.com/623951/66000279-ef511e00-e453-11e9-92b3-6ba6ad682dd5.png)

**Comment by ericwinger** [comment]
So far not much to report. Dolphin appears to get stuck inside one of it's own ``ifCurtailed:`` blocks during some sort of termination in the variable list view. Jadeite code, so far, does not appear to be implicated.

**Comment by ericwinger** [comment]
Without a reproduction case or much of anything to go on, not going to get put into the November release. Still a priority though.

**Comment by LisaAlmarode** [comment]
Old bug involving debugger and dolphin; closing, new bugs should be filed if similar problems occur.
