### ISSUE TITLE
(3.0.77) popup menu in debugger inspect/printString pane does not set focus; cannot do select all

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#541]
![image](https://user-images.githubusercontent.com/623951/66001159-cf225e80-e455-11e9-8fe1-5869b7e2357e.png)

**Comment by LisaAlmarode** [comment]
Verified that in the right side middle pane, if you have something selected in the upper right pane such that the middle right pane is not empty, the popup menu contains select all, but the select all is not enabled. In this case, if you left-click into the pane so focus is on that pane, though, this menu item (and the others) do become enabled.   

Somewhat worse: if there is not anything selected in the upper right pane, so the middle right pane is empty, and the previously selected pane is the text pane - then, the items on the popup menu is enabled, but they perform the operation on the text pane.

The problem appears to be that the focus isn't getting set to the middle right pane when the popup menu is popped up.

**Comment by ericwinger** [comment]
The focus grab should behave the same as the debugger source pane now, effictive 3.0.80.
