### ISSUE TITLE
(3.0.77) shortcut key for reformat source different than project browser, and it doesn't work

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#542]
`CTL-R` does not reformat source in debugger method pane ... in project browser `CTL-SHIFT-O' is the shortcut .... selecting the menu item does reformat source:
![image](https://user-images.githubusercontent.com/623951/66001513-7bfcdb80-e456-11e9-8ff9-8f95e4d2dd64.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.79

**Comment by LisaAlmarode** [comment]
This is the same as #536.
