### ISSUE TITLE
(3.0.77) selected method not updating in project browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#543]
From the image below, you can see that the method source visible in the method pane does not match the selected method.
![image](https://user-images.githubusercontent.com/623951/66004035-8621d880-e45c-11e9-8791-76237223061e.png)
Note that there _is_ a debugger open and I do have auto commit enabled

**Comment by dalehenrich** [comment]
Just now, I had a similar problem ... in this particular case, when I clicked on a method the source would update but the method name in the method list would not be highlighed ... in both cases I have autocommit turned on ... also in both cases there was a debugger open ...

Today, when I closed the debugger, the project browser updated and the method name was correctly highlighted ...

Clearly there is a nasty glitch in the browser update code that *can* happen when the debugger is open (and autocommit turned on?) ...

**Comment by ericwinger** [comment]
It's not reproducing for me (with autocommit on and debugger open + other open windows based on image in report) so I can only speculate. Perhaps @LisaAlmarode  will have better luck. 

1. If the source changes but not the method list.

>  in this particular case, when I clicked on a method the source would update but the method name in the method list would not be highlighed.

Based on this comment it is possible, although not probable, that the dolphin gui window didn't redraw correctly. If it happens again, one can easily test this by waving the mouse pointer around the method list pane, without clicking,  to see if it redraws with the correct method selected. 

2. If the method list changes, but not the source.

A dolphin error could have left the semaphore in a bad state. That might prevent a round trip.  If that happened, then the failed round trip would have reset the semaphore so everything from then on would continue to work. To learn more, one can look for the time/date of the last entry in the `Jadeite.errors` file for a possible correlation.

**Comment by LisaAlmarode** [comment]
This is an old bug related to dolphin and debugger, which have both many changes as of 3.2.12; closing.  New issues should be filed if similar problems occur.
