### ISSUE TITLE
first class breakpoint browser is desirable

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#545]
This is a follow-on to issue #544 ... apparently there are new features in 3.0.78 that allow the clearing, disabling and enabling of all breakpoints ... while these are good things to have, I think that it is important to be able enable, disable, clear each breakpoint individually as well as wholesale operations on all breakpoints ... I often have multiple breakpoints in a single method, so being able to see each breakpoint that exists in a first class list of breakpoints (select the breakpoint and the method source is shown in a method pane) where the status of the breakpoint is visible (enabled or disabled) would be ideal ... I would also want multi-select in the list, so I could do operations (enable/disable/clear) on several breakpoints at once ...

**Comment by ericwinger** [comment]
Have a first cut at a fully-featured breakpoint browser ready to start testing in 3.1.0

**Comment by LisaAlmarode** [comment]
breakpoint browser present and accounted for.  Some display issues, issue #758, and menu complaints, issue #759.
