### ISSUE TITLE
Status bar should not shrink porportionally (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#547]
In taking a browser screen shot, I see the camera icon was cropped to quarter-size and not recognizably a camera.  

This is exaggerated, but this illustrates the problem.  

![image](https://user-images.githubusercontent.com/13142166/66507106-6fded280-ea83-11e9-82d7-9d3a8529750f.png)

**Comment by ericwinger** [comment]
@LisaAlmarode Is this really a requirement for November release?

**Comment by LisaAlmarode** [comment]
No, not if it's too much work.  The cropping is quite noticeable even with just somewhat smaller windows, but it doesn't become unusable until the window is smaller than anyone would really use.

**Comment by ericwinger** [comment]
Not perfect, but better. The autocommit camera button stays mostly visible with horizontal size changes. It still gets squished vertically, but can still be seen and used unless the window is scrunched beyond reasonable expectations.

**Comment by LisaAlmarode** [comment]
The camera can handle narrow now, but now wide has a problem with the status bar.  Reopen since that's kind of unattractive. 
 
And, as Eric notes, it's still a problem with short and with tall.

This illustrates the problem in 3.0.84 with wide (and tall)
![image](https://user-images.githubusercontent.com/13142166/67608021-5dc78a00-f73b-11e9-9e55-baf292bd6731.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.85
