### ISSUE TITLE
Title for debugger window

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#548]
The title bar for the debugger is "Jadeite Debugger for...".  I'd prefer this to be just "Debugger for...", since I'd then be able to identify it the task bar at the bottom of my screen.

The project browser, implementors and senders, process browser have all had the leading jadeite removed (good)

The leading jadeite is still there on the SUnit Browser - nice to remove it here, too.

I like the leading Jadeite on the console.

For the "Jadeite Logger Browser", I like the 'Jadeite' but "Logger" is ungrammatical, should be "Jadeite Log Browser"

**Comment by ericwinger** [comment]
Debugger title was a holdover for a brief period when the Jadeite debugger was in development. Removed Jadeite from label.
![image](https://user-images.githubusercontent.com/36212516/67528281-f0015c80-f66d-11e9-8963-b48c69347e8b.png)
SUnit browser fixed. 
![image](https://user-images.githubusercontent.com/36212516/67528412-41a9e700-f66e-11e9-9b11-a1018abac196.png)
Log browser changed: 
![image](https://user-images.githubusercontent.com/36212516/67528545-93eb0800-f66e-11e9-8401-903e93253d26.png)


But not sure what you mean by this comment as the console doesn't have Jadeite in it's title.
> I like the leading Jadeite on the console.
![image](https://user-images.githubusercontent.com/36212516/67528593-b0874000-f66e-11e9-8cc8-8c38f4745252.png)

**Comment by LisaAlmarode** [comment]
I think I mean the leading Jadeite on the login window...

**Comment by ericwinger** [comment]
This is fixed in 3.0.84
