### ISSUE TITLE
User Browser hard-to-find, and while otherwise read-only, allows you to add user (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#549]
We have a User Browser that is available as an icon on the console icon bar, but does not have a menu item.  This needs to be added as a menu item - otherwise we will forget it's there and it will decay.

Mostly this appears to be read-only, so is fine in spite of some layout issues.  However, it does appear to allow you to add a user via a popup menu.  This should be disabled.

**Comment by LisaAlmarode** [comment]
Clicking on the UserBrowser icon gives you a walkback.  Likely a removed Jade method; as predicted, it decayed. 
I would not object to removing the icon bar item.

**Comment by ericwinger** [comment]
Decay had happened. Restored server methods necessary for old user browser to run. Toolbar button removed in favor of a Browse menu option.  

This is an old Jade tool. It probably needs a total rework. If that's desirable, a new feature request should be filed.

**Comment by LisaAlmarode** [comment]
I don't think we *need* a user browser, and if we have it, it doesn't *need* to be pretty; but if it is there, it should be readable, information should be correct, and any functions offered should not get DNU.  

(1) Password lower tab layout has overlaps
(2) Password lower tab change password gets MNU "UndefinedObject does not understand forwardTo:"
(3) Groups tab just lists system groups, never indicates the groups of the user
(4) The Clear Old Passwords button, while disabled, should be removed.
(4) with a larger font, the upper Password limits page Disallow User Passwords wraps and is obscured

![image](https://user-images.githubusercontent.com/13142166/214654627-631daa32-3fd6-4f10-a272-741f224433ae.png)

We can tolerate the entry fields and check boxes that look they they should allow changes, since they do display user information.

**Comment by ericwinger** [comment]
Got rid of Browse Users menu option.  If the need to show and modify user information comes up we can build a tool that actually works.
