### ISSUE TITLE
"Reformat source" without save is not working right in method browsers (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#550]
In a Method Browser with a method selected, I select "reformat source".  The source is reformatted and the method pane turns green.

The undo menu item does not work (problem 1).

If I click in the white space to clear the text pane, I click no for "stay on unsaved method"... which gives a purple rectangle artifact.  Then when I click on the method again I get an error dialog "Array does not understand #start".  It also shows the formatted, not the original text.

If I click on the same method in the project browser, the original method is restored and the method browser becomes usable again.

**Comment by LisaAlmarode** [comment]
Side observation of another deficiency in the method browser, the text pane popup menu:  in the PB, the save, undo and redo menu items are disabled if there were no changes.  In the MB, these menu items are always enabled.

**Comment by ericwinger** [comment]
I've got a fix in 3.0.80 to make ``reformat source`` un-doable. However, the second complaint is not related to reformatting. I'm going to close this bug and open a new one for that without the urgent label. It's a weird Dolphin artifact.

**Comment by ericwinger** [comment]
See #567

**Comment by LisaAlmarode** [comment]
Reformat undo/redo working very nicely.  Stickiness gone.

**Comment by LisaAlmarode** [comment]
Another oops reopen.
