### ISSUE TITLE
(3.0.77) Changes menu item returns changes for Rowan project only

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#552]
When I ask for changes on projects other than Rowan, I seem to only get Rowan changes ... a look at RowanProjectServices>>changes is a possible clue. Note that Rowan is wired in as a constant:
```smalltalk
changes

	| jadeServer |
	jadeServer := Rowan platform jadeServerClassNamed: #JadeServer. 
	changes := Array new. 
	(Rowan projectTools diff
		patchesForProjectNamed: 'Rowan') do: [:assoc | 
			"key is packageName, value is a CypressPatch"
			| patch |
			patch := assoc value.
			changes add:(jadeServer new
				_mcDescriptionOfPatch: patch
				baseName: 'closest ancestor'
				alternateName: nil) ].
	self refresh.
	RowanCommandResult addResult: self.
```

**Comment by LisaAlmarode** [comment]
In 3.0.78, I verified that after I changed a method in RowanSample1, Tonel, Rowan, and Izmir, each of these projects, the changes menu item only returns the set of changes in that correct project.

The contents of RowanProjectService >> changes in my image is

	| jadeServer |
	jadeServer := Rowan platform jadeServerClassNamed: #JadeServer. 
	changes := Array new. 
	self packageNames do:[:packageName |
			| patch |
			patch := Rowan packageTools diff patchForPackageName: packageName.
			changes add:(jadeServer new
				_mcDescriptionOfPatch: patch
				baseName: 'closest ancestor'
				alternateName: nil)].
	self refresh.
	RowanCommandResult addResult: self.

**Comment by dalehenrich** [comment]
... just understood that the source for the method in my image is different than the source that you are seeing and that is likely to be a result of a merge mistake on my part when I made changes to how changes were handled for V2.0 ... I'll need to create a patch for V2.0
