### ISSUE TITLE
Jadeite settings in preferences file (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#553]
transcript writes enabled makes my system very slow.  Long ago we added a very basic preferences disk file (you can view it using Console Browse menu item Browse Preferences File), which for me has transcriptEnabled false.  In 3.0.77 and earlier, after I login transcript writes enabled is always off and never slows me down ever. 

Starting with 3.0.78, my setting is ignored, and transcript writes enabled is always on after login.

**Comment by LisaAlmarode** [comment]
The format used in v77 and earlier has changed in v78; a colon is now required.  The legal values should be documented somewhere, possibly in a newly created file.  

- [x] assuming this is how you figure out the settings, there should be an option to create a new file even if one exists rather than having to go look in your directory for some file.

 - [x] all legal tokens for settings should be in this newly created file.  

The following are known to work:
transcriptEnabled: true
openBrowserOnClass: RowanAnsweringService
openBrowserOnPackage: Rowan-Services-Core
openSUnitBrowserOnPackage: Rowan-Services-Tests

and we should have preferences for the following:

- [x] autocommitEnabled: true
- [x] autocompleteEnabled: false
- [x] breakpointsEnabled: true
- [x] loggingEnabled: false

- [x] the Console Jadeite menu needs tweaking.

I recommend moving a couple of items higher, rename "logging" to "logging enabled", and removing the separator for logging.  I also recommend moving the edit operations to the edit menu.  The resulting menu:

```
Jadeite > 
Sleep and Commit  (do we need this?)
Abort Transaction
Commit Transaction
Disable Native Code
--------------------
Inspect Oop...
Description for Error Number ...
--------------------
Transcript Writes Enabled
AutoCommit enabled
Breakpoints enabled
Autocomplete enabled
Logging enabled
```
and then the Console Edit menu:
```
Undo
Redo
--------------------
Cut
Copy
Paste
Delete
--------------------
Select All
--------------------
Find
Find next
Replace
--------------------
Inspect
Display
Execute
Debug
File in 
--------------------
Add Quotes  
Remove Quotes 
```

**Comment by LisaAlmarode** [comment]
- [x] Also; on login, you get an index out of bound error dialog if there's an empty line in the preferences file.  It continues and appears to work, but the error isn't enjoyable to see.

**Comment by ericwinger** [comment]
@LisaAlmarode - Can you provide better default text for the preferences file? Here is a draft: 

```
#Remove # to uncomment option. 
#legal values are either a boolean or a name

#autocommitEnabled: true
#autocompleteEnabled: false
#breakpointsEnabled: true
#loggingEnabled: false
#openBrowserOnClass: <class name>
#openBrowserOnPackage: <package name>
#openBrowserOnProject: <project name> 
#openSUnitBrowserOnPackage: <package name>
#transcriptEnabled: true
```

**Comment by ericwinger** [comment]
Not closed but changes ready for review in 3.0.79

**Comment by LisaAlmarode** [comment]
It's not bad. 
 - the order should match the menu in Jadeite, and not mix options and starting windows.
 - Some defaults should be changed.

```
# Remove the leading # to uncomment an option. 
# legal arguments are either a boolean or a name

#transcriptEnabled: false
#autocommitEnabled: false
#breakpointsEnabled: true
#autocompleteEnabled: false
#loggingEnabled: false
#openBrowserOnProject: <project name> 
#openBrowserOnPackage: <package name>
#openBrowserOnClass: <class name>
#openSUnitBrowserOnPackage: <package name>
```

**Comment by ericwinger** [comment]
You didn't want them alphabetical?  Seems like that would be more predictable than trying to remember to change the order whenever we change the menu.

**Comment by dalehenrich** [comment]
If you were to use STON format for all disk-based objects, we'd have a consistent  syntax that users and computers could share ... just a thought ...

**Comment by dalehenrich** [comment]
accidental close

**Comment by LisaAlmarode** [comment]
I think having to update both if you add or remove menu items is a feature.  Reordering the menu items without making any substantial changes that affect the preferences ought to be rare...

The list isn't currently long enough for alphabetization to matter... but I do want the menu item order to match, and if that gets long enough to require alphabetization in the prefs, then the menu items might need alphabetization too.

My ideal order is most-commonly used first. 

Ideally, the menu items would be ordered by most-commonly-used.  But you could alphabetize them, too.

I think open-window one should be grouped, but the specific order within these four I don't really care about, if you want to alphabetize those.

**Comment by LisaAlmarode** [comment]
Verified in 7.0.79, all five configs are picked up.  Open even works on (NONE), and invalid name causes open without anything selected (correct).

If you forget the semicolon in a setting it can be hard to spot the error, and I think the code ought to be able to work around that... but this is minor, not worth worrying about.

**Comment by LisaAlmarode** [comment]
The system defaults on login with no preferences files are not correct.

autocommitEnabled is false  -good
autocompleteEnabled is true --WRONG
breakpointsEnabled is true  -good
loggingEnabled is true --WRONG (for customers)
transcript writes is true --WRONG (for customers)

The text of the preferences file should match the defaults on startup.

**Comment by LisaAlmarode** [comment]
I'm finding the preferences workspace/s slightly confusing as to the titles and names.

The Browse Preferences file opens with the title
   C:\GS\Oscar\Jadeite.prefs for SystemUser on stone...
and has added menu items 
   Preferences Options Workspace
   Reset Preferences to default.

- [ ] I think this ought to have something in the title, indicating it's the Prefs File Browser - maybe instead, the title could be:
   Preferences File C:\GS\Oscar\Jadeite.prefs
(The user name should not be here since the file itself is common to all users, so it's confusing... and I'm not thinking that there ought to be any stone information either...)

 - [ ] This menu item is also confusing... it sounds like it opens the preferences browser:
  Preferences Options Workspace
instead, perhaps this menu item could be renamed "Default Preferences Workspace".  It's a bit long but would hopefully fit.

The Preferences Options Workspace menu opens a windows with the title
   Jadeite Preferences Options for SystemUser on stone...

 - [ ] This is more preferencey-browsery than the real Preferences Browser... The title should perhaps more clearly be (and match the menu item):
   Default Preferences Workspace for SystemUser on stone...
 
 - [ ] The "Reset Preferences to Default" was unclear; it sounds like it would reset the actual settings, and possibly write the file, not just paste the default into the workspace.  This may be best solved by a larger API change... but I think if this was to say "Reset to default text" that would be much clearer.

 - [ ] the menu needs a separator between Browse Package and the Preferences Options settings.

**Comment by ericwinger** [comment]
@LisaAlmarode  I'm confused by your comment. https://github.com/GemTalk/Jadeite/issues/553#issuecomment-541847476. ``Transcript Enabled`` and ``Auto Complete Enabled`` default to ``true``. 

Here's the defaults that currently exist: 
![image](https://user-images.githubusercontent.com/36212516/66944466-1423c480-f002-11e9-977f-563bfed0e17d.png)

Here's what I changed the default preferences file to effective in 3.0.80 so they match: 
![image](https://user-images.githubusercontent.com/36212516/66944821-cbb8d680-f002-11e9-9969-29df91571d53.png)

**Comment by LisaAlmarode** [comment]
I think autocomplete should be off by default, as it's a startling change (speaking from experience).  The simpler behavior should be the default. And the previously existing behavior - so I'll go along with leaving transcript writes enabled. 

I don't see the funky initial settings now when I delete the prefs and restart... must not have deleted the prefs file enough...

**Comment by ericwinger** [comment]
It's my preference to set the autocomplete default to `true`. If one hasn't used the product before, it won't be a startling change. And if you don't like it, it's easy to disable permanently through preferences. 

The alternative is to stumble across the feature by reading the manual or reading the preferences 
 file or setting menu options then turn it on. Since I find it quite handy, I'd rather know it's there. 

Also, since the symbols are cached now performance should not be an issue. 

Closing. If it's that desirable to default to `false`, let's open a new feature request.

**Comment by LisaAlmarode** [comment]
Of the full set of people who have used this recent jadeite (that didn't themselves implement the feature), with a set size <= 2, at least 50% of them were in fact startled.  I was in fact very startled.

There are a number of open issues earlier in this issue, regarding menu names and window titles... but I'll open another issue so they don't get re-lost
