### ISSUE TITLE
Make class/instance tab status more visible (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#555]
This is a follow-on to issue #530.  It is very hard to notice if you are on the instance or class side; it was easier in GBS, where the class/instance was on the top of the pane.  A boder line being a few pixels lower in the middle of the windows is much harder to see.

I would suggest making the selected tab's title bold.  A color change would work too.  Or some other idea.

**Comment by ericwinger** [comment]
After looking at the available options for making the tab stand out, I think I'd rather invest some time into making a pair of radio buttons work. Then it could be right under the method list. Here's a crude mock-up. 
![image](https://user-images.githubusercontent.com/36212516/70192147-b6c9fc80-16af-11ea-89bb-8bbe4caf478e.png)

**Comment by ericwinger** [comment]
Looking at this again after porting to Dolphin 7.1.9, part of the problem appears to be the unnecessary icons in the Instance/Class & Classes/Hierarchy tabs. They add visual clutter. 

@LisaAlmarode What would you think if I just removed the tab icons like in the picture below? 

Without tab icons ...
![image](https://user-images.githubusercontent.com/36212516/75913241-6de92780-5e07-11ea-98d8-bfbb9ed9dae9.png)

vs with tab icons ...
![image](https://user-images.githubusercontent.com/36212516/75913634-2616d000-5e08-11ea-8a6f-bb543d89d0a6.png)

**Comment by LisaAlmarode** [comment]
The removed icons make the Instance and Class blend in even more with the Package and list of classes and everything else. I need something to draw the eye.
Maybe create a simple glaring icon like a big red and a big green I ?

**Comment by ericwinger** [comment]
I haven't found an icon that makes any sense yet. Would bold text help? 

![image](https://user-images.githubusercontent.com/36212516/79026896-15f8bb80-7b3f-11ea-93b6-820797585344.png)

**Comment by LisaAlmarode** [comment]
Yes!  That was my original request, so I assumed there was a technical reason that it wasn't possible.

**Comment by ericwinger** [comment]
Bold wasn't my first choice aesthetically but it is done in 3.1.0pre-release4.

**Comment by LisaAlmarode** [comment]
the bold doesn't look quite as nice on my windows box as in Eric's picture but it's better than before.
