### ISSUE TITLE
Added menu item "Browse Commit In Github" needs some work (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#558]
This menu item got added at some point, but it is not very useful for end users, (that is, anyone other than Dale and Eric)

When I have selected RowanSample1, and use this menu item, I get a GitHub page that is 404,
```  
https://github.com/dalehenrich/RowanSample1/commit/cf0843d
```
When I select my own package, I get a Jadeite error dialog,  
```
UndefinedObject does not understand #,
```
It should probably be disabled in cases that won't work.

**Comment by dalehenrich** [comment]
Didn't know that menu item existed:) I like the idea, but I think it is a bit difficult to know whether or not a particular commit is actually available on github (you have to have pushed for the commit to be on github) ...
There is code available in the pharo community (requiring a port on our part ... and I guess a port to Dolphin for Jadeite?) that uses the github api that *could* be used to answer the question about whether or not the commit has been pushed or not ...

**Comment by ericwinger** [comment]
@LisaAlmarode @dalehenrich Should I just remove it?  It's pretty basic. It just grabs the project url &  sha and opens a browser.

**Comment by dalehenrich** [comment]
You mean a web browser? Removing it is probably a good idea, at least until we get deeper into the business of supporting the git/github/bitbucket/gitlabs workflows ...

**Comment by ericwinger** [comment]
Removed in 3.0.92pre-release2
