### ISSUE TITLE
Method list browser status pane layout problem

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#56]
The Method list browser has a gray status pane bar intended to be along the bottom of the window.  

This pane is in a fixed, not relative, location and is only visible when the windows is set to the perfect size. When first opened, it's visible, but slightly too low so there's a little white space above.  As I resize the browser window vertically, I can see the bar go by.

**Comment by ericwinger** [comment]
Took me awhile to see that, but thanks to years of Where's Waldo practice I finally found it. Fixed in 3.0.12.
