### ISSUE TITLE
Package/Projects/Class drop down menus get "break at step point 1" menu item (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#560]
if you have a method selected with focus, the Projects, Packages, Classes, Categories methods all get a "Break at step point 1" menu item.  

![image](https://user-images.githubusercontent.com/13142166/66691006-7d918500-ec48-11e9-8fe5-2ba24a49f0e8.png)

**Comment by LisaAlmarode** [comment]
Appears fixed in v3.0.82

**Comment by LisaAlmarode** [comment]
I was incorrect; this does reproduce in 3.0.82; it's just completely unrelated to breakpoints and enablement thereof.

To reproduce: in PB, go to a method (find a long one).  Put focus on the method text, say, near the end. 

Now, go to the menu bar drop-down menus.

The Project, Package, and Classes method all have the menu item "Break at step point 1".  This makes no sense.  The menu item "Break at step point 1" could, reasonably, be on the Methods menu.  But it's NOT there.

**Comment by ericwinger** [comment]
Shouldn't see any breakpoint messages except on the context menu as of 3.0.92pre-release2
