### ISSUE TITLE
need to be able to see full class hierarchies (all the way to the leaf classes independent of package/symbol dictionary boundaries)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#561]
I'm running into an issue where I am not able to a find any single view of a particular class hiararchy ... I'll include a couple of pictures and then we can talk about this when we're all in the office (not Nov target)...

What I would like to be able to do is see all of the subclasses of StashAbstractTool -- in one view ... I am trying to udertand the class hieracyhy and I would also want to be able to drag drop methods amongst the various classes in the hierarchy, but I cannot view the full hiearchy at one time as the subclasses of a class are cut off at package boundaries?
![image](https://user-images.githubusercontent.com/623951/66691698-06aabb00-ec4d-11e9-8f93-af69b176192f.png)
![image](https://user-images.githubusercontent.com/623951/66691699-0ca09c00-ec4d-11e9-9c52-8b31d365a65f.png)
I tried switching to the dictionary view, but the hierarchy is cut off at symbol dictionary boundaries? 
![image](https://user-images.githubusercontent.com/623951/66691708-16c29a80-ec4d-11e9-9eb6-744679dd894a.png)
Right now I am not sure whether or not StashClassTool has any subclasses or not, which is not a good place to be ...

**Comment by dalehenrich** [comment]
This is the type of hierarchy view i'd like to see in one view:
![image](https://user-images.githubusercontent.com/623951/66692582-acadf380-ec54-11e9-8d56-7380885ec1b5.png)

**Comment by LisaAlmarode** [comment]
There is a definite deficiency currently in our ability to see a full heirarchy and get a sense of what all classes are there... and my particular complaint also is that you can get the mistaken impression that a class has only one subclass.  Eric and I discussed this issue in person in the context of issue #156, but it wasn't going to be easy in the current browser.

**Comment by dalehenrich** [comment]
... understood, that's whu this is only tagged enhancement ...

**Comment by dalehenrich** [comment]
Oscar-3.0.89-pre1 does seem to fill the bill (using 'Expand Full Hierarchy' menu item):
![image](https://user-images.githubusercontent.com/623951/69358464-beaf8880-0c3b-11ea-9636-3de854f16a69.png)
![image](https://user-images.githubusercontent.com/623951/69358691-1d750200-0c3c-11ea-8449-128c78036278.png)

@LisaAlmarode next time you are in the office let's talk about this some more ... if I am not familiar with the class hierarchy for a particular class, I would have to be paranoid and use the 'Expand Full Hierarchy' after selecting each class or selecting the 'Hierarch' tab or risk missing out on important hiearchical information ... if there were a visual cue that additional subclasses are being hidden, that might be a solution

**Comment by dalehenrich** [comment]
Here's the view before using 'Expand Full Hierarchy' menu ... no visual cue that **StashGsDevKitTool** has subclasses:
![image](https://user-images.githubusercontent.com/623951/69359108-d9cec800-0c3c-11ea-8dc2-af29c97a0699.png)

**Comment by LisaAlmarode** [comment]
This bug mostly fixed, remaining complaints now under issue #971.
