### ISSUE TITLE
Jadeite Login, Advanced tab, Debug GCI button needs to be a tad wider

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#564]
If you go to the advanced tab, there's a button labled "Debug GCI".  I clicked this (somewhat at random to see if I could get the Login button re-enabled).  While it looks fine when you start there, the act of clicking on it messes up the display.

![image](https://user-images.githubusercontent.com/13142166/66783686-4c55c680-ee8d-11e9-856e-af643742d1bc.png)

**Comment by LisaAlmarode** [comment]
Still like this in 3.2.12. This irks me out of proportion, so putting it the to-fix list.  Seems like it shouldn't be that hard

**Comment by ericwinger** [comment]
Made the button 30 px wider. Can increase more if necessary.
