### ISSUE TITLE
Would like "browse selected" in the SUnit tab of the Project Browser (3.0.79)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#565]
I have a test class hierarchy with inherited tests. When I'm running tests in my concrete subclass, I seem to regularly want to look at the source code for a particular test.  But since the source is in some superclass, that method is not listed in the methods pane.

There's nothing to describe what class that particular method is actually implemented in, and no way to get there; I have to guess and sometimes click on multiple classes to find the method source.

**Comment by ericwinger** [comment]
I've added a menu option `Browse Selected Tests` in the sunit tab. It'll open a method browser on the tests selected similar to how `Browse Selected Methods` does.

**Comment by LisaAlmarode** [comment]
The menu item is there but I can't seem to use it to browse methods that are not on that same class.  Which is the use case that is described in the initial report. 

The abstract TestCase subclass LisaTest implements test_zork, LisaSubTest is the concrete class that inherits it but does not override it.  In the Sunit Browser you see LisaSubTest with the method test_zork.  But I cannot browse LisaTest>>test_zork.

![image](https://user-images.githubusercontent.com/13142166/78709586-c1e4a180-78c8-11ea-9945-0dd4d342c7b0.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0 pre-release4.  Use same code to display selected tests in sunit tab & browser. Menu option named same, too.
