### ISSUE TITLE
Change SUnit menu items in Method Pane popup (3.0.79)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#566]
The method pane has some menu items to run Sunit tests, and they are different from the other menu names that perform these operations, and are also very inconsistent between each other.  I'm often confused.

The method browser items are:
   Debug Tests
   Run All Tests
   Run Selected

Equivalents used elsewhere are:
   Run All
   Run Selected
   Debug

- [x] Items should be in the same order
- [x] if you want to have these includes the word "Test" (reasonable), then use it consistently.  
- [x] if you want to use the word "Selected", use for both Run and Debug
- [x] Parenthesize the plural
- [x] Also, there should be a line above the Debug, since "Remove" is not one of the Sunit options.

Either of these options:

    Run All Tests
    Run Selected Test(s)
    Debug Selected Test(s)

    Run All Tests
    Run Test(s)
    Debug Test(s)

**Comment by ericwinger** [comment]
Should look like this as of 3.0.82. 

![image](https://user-images.githubusercontent.com/36212516/67131502-c81b8000-f1b9-11e9-8196-dfd7fec58896.png)
