### ISSUE TITLE
Weird gui artifact in project browser after clicking on dialog

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#567]
From #550 . 

If I click in the white space to clear the text pane, I click no for "stay on unsaved method"... which gives a purple rectangle artifact. Then when I click on the method again I get an error dialog "Array does not understand #start". It also shows the formatted, not the original text.

If I click on the same method in the project browser, the original method is restored and the method browser becomes usable again.

**Comment by LisaAlmarode** [comment]
close this in favor of issue #795 which has more details and is easier to understand.
