### ISSUE TITLE
Workspace popup menu gets ridiculously long menu items for Browse Senders/Implementors,

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#568]
If you are in a workspace, the popup menu (but not the drop downs from the menu bar) include browse class and browse senders or implementors.  But it doesn't distiguish a method, it's just whatevers highlighted.  When I highlight all to copy, the menu item is... ridiculous.  If nothing else at least the text could be truncated so it stays on the same monitor. 

![image](https://user-images.githubusercontent.com/13142166/66789368-1d951b80-eea0-11e9-8760-ef2e9a02f5cf.png)

The Project Browser doesn't show the menu item unless you have method selected without any cruft, and doesn't have this problem.

To bring this up to actual bug status, if you have a LOT of text, the menu items appears to just get indefinitely long.  However, if you actually click on the super-duper-long menu item, you get a walkback with " ImproperOperation occurred (error 2402), Cannot create a Symbol, String exceeds 1024 Characters. "

**Comment by ericwinger** [comment]
Got a fix for this in 3.0.80. There are any number of ways to truncate a menu item without losing the handy functionality this provides. Now Jadeite truncates the name when it encounters a space as it is possible to have ridiculously and legitimately long selectors.

**Comment by LisaAlmarode** [comment]
thank you!  It's much better.

But it could use more work... 

  - I see my random text truncated with a trailing ..., and then search is on the whole thing.  Given that a space is not ever going to work, I think the appended ... is rather a waste of time, and if the user is going to search, make it be just on the first token.  

  - A ridiculously long method name could in fact use the trailing ... I just think the menu size needs to be limited so it doesn't go over into the second monitor.  The person doing this did actually highlight the method, and there's not multiple options to choose from... so it's not like they need the whole text repeated. 

![image](https://user-images.githubusercontent.com/13142166/66969732-9d0d2100-f03f-11e9-9df3-68410f2b56dc.png)

But these are not necessary for November.

**Comment by ericwinger** [comment]
The ellipses were coming from spaces that could, under some conditions, show up in a selector. If Jadeite detected spaces, it would truncate and add an ellipse. 

After reflecting on this, when all other fiddling is done with the workspace's selection to try to get a searchable selector, I think it's probably better to remove spaces. Then, only add the ellipse if the resulting menu item text is > 50 .  (50 or whatever you'd like.)

**Comment by ericwinger** [comment]
Fixed per description above.

**Comment by ericwinger** [comment]
Fixed in 3.0.92

**Comment by LisaAlmarode** [comment]
Overall I've very happy with this; there's the right amount of detail before the ..., it generally handles class vs. method, it finds long methods.

However, there's one place in which the handling of Class name/selector is not correct, if you highlight text that contains a Class name and keyword selector, but not the argument of the keyword, it appears to be confused.

![image](https://user-images.githubusercontent.com/13142166/71033268-e45d6f80-20cb-11ea-9a35-08269a5e924c.png)

**Comment by ericwinger** [comment]
Parsing random smalltalk and trying to dig out a selector is tricky. Especially if it's not valid code. I believe I have the specific case handled.  As always ... let the highlighter beware.

**Comment by LisaAlmarode** [comment]
This looks great now!
