### ISSUE TITLE
Method Compile on class update should not warn about unused temps (3.0.79)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#569]
When you add an instance variable, class instance variable or class variable to a class...
You can get a bajillion dialogs in sequence, one for each method that is getting recompiled and has unused temps.  This is quite painful; I had to press yes on a dialog 14 times, as it turned out.  

I've marked this November, but it may not actually be important in practice so it could be deferred. 

![image](https://user-images.githubusercontent.com/13142166/66859220-b9c22f80-ef3f-11e9-9449-21396749e1b6.png)

**Comment by ericwinger** [comment]
That is pretty ugly although one could make a case that compile warnings should be cleaned up by the programmer.  Nonetheless, I've suppressed CompileWarning's during the method recompilation phase of the class save in Oscar 3.0.80.
