### ISSUE TITLE
variable references showing unexpected methods 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#574]
The method shown does not have a reference to `args`, however there is a method in the hierarchy with the same selector that does:
 ![image](https://user-images.githubusercontent.com/623951/66943283-aaa2b680-efff-11e9-84ce-4f60e584fe09.png)

**Comment by ericwinger** [comment]
So far not reproducable in time for the November release.

**Comment by ericwinger** [comment]
@LisaAlmarode  Can you take a crack at reproducing this in the 3.1.0pre-releases?

**Comment by dalehenrich** [comment]
it's worth noting that this bug is appearing in 3.5.0 and I think I have seen it off and on since reporting way back when and has shown up off and on ... but then I only use iv refs off and on ... it _could_ be a base bug ..

**Comment by LisaAlmarode** [comment]
I can't reproduce it in small test cases in 3.2.12 with 3.7.  However, it was intermittent and we couldn't reproduce it back then, so who knows. I think there's not much value in leaving it open since there's a reasonable chance other changes in the base or jadeite have incidentally fixed this.
