### ISSUE TITLE
variables tab sort order inconsistency ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#575]
With variables tab active note that `_scriptName`sorts first (after selecting class):
![image](https://user-images.githubusercontent.com/623951/66943566-4b917180-f000-11e9-96c9-e2dea5d30688.png)
... when category tab clicked and returning to variables tab `_scriptName` sorts at bottom:
![image](https://user-images.githubusercontent.com/623951/66943534-39173800-f000-11e9-9c9b-68c77e86fecf.png)
Likely to be due to whether or not unicode sorting is being used and unicode is the preferred sort order(`_` bubbles to top)

**Comment by ericwinger** [comment]
Think I've got a fix for this in 3.0.82. Do the sort on the client now.
