### ISSUE TITLE
(3.0.80) On login, "SmallInteger does not understand isSeparator"

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#577]
This has only happened in one of my 3 stones ... all three stones were built using the same version of Rowan ... the previous build using )scar-3.0.78 was logging in fine:
![image](https://user-images.githubusercontent.com/623951/66971181-0ba0ad80-f045-11e9-9a05-4eaf46f9874e.png)
No error file was produced ...

**Comment by dalehenrich** [comment]
@ericwinger, tomorrow you should be able to do test logins ...

**Comment by dalehenrich** [comment]
Here's the error i get when trying to login as DataCurator:
![image](https://user-images.githubusercontent.com/623951/66971399-f710e500-f045-11e9-9d0a-5f5e41befe63.png)
This does happen to be an image into which tODE has been loaded (as DataCurator) ... also this image is using legacy streams ...

**Comment by dalehenrich** [comment]
I was able to use 3.0.78 to log into the pre-Oscar-3.0.78 merge without a problem ... and of course I'm getting an expected error when I try to use 3.0.78 against this stone:
![image](https://user-images.githubusercontent.com/623951/67024277-fe250b00-f0b8-11e9-8646-1e41e4a78a46.png)

**Comment by ericwinger** [comment]
Have possible fix in server only code - 
https://github.com/GemTalk/Rowan/commit/790f98a2b3e57f145871c856357ffc4c23bed1c9

**Comment by ericwinger** [comment]
Dale confirmed fix. Will be in 3.0.81

**Comment by ericwinger** [comment]
@LisaAlmarode  - The confirmation test is that you have double byte / quad byte symbols in ``AllSymbols`` and can still login.

**Comment by LisaAlmarode** [comment]
I created a DoubleByteSymbol... as a value in UserGlobals.  I presume this puts it in AllSymbols.  Was able to login fine in 3.0.81, but it completely breaks my access to UserGlobals.  Will file a separate bug.
