### ISSUE TITLE
(3.0.80) after closing the error dialg, login button goes inactive

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#578]
![image](https://user-images.githubusercontent.com/623951/66971495-53740480-f046-11e9-9a20-0d7ecfc30bd5.png)

**Comment by ericwinger** [comment]
I would expect less-than-desirable behavior from Jadeite after an unexpected error. The solution in this case is to close the login window and reopen Jadeite. 

If that is not acceptable, I can wrap the login code in an error handler which fixes the conditions so the button will re-enable before showing the error dialog. However, that isn't a very good solution either. 

Reassigning to @dalehenrich for comment and removing `November 19` label.

**Comment by dalehenrich** [comment]
I think that the code should always work correctly even in the presence of errors .... agree that it is not a high priority ... but for completeness this should be fixed ...

**Comment by ericwinger** [comment]
I've reset the session on login errors in 3.0.82. Manual testing shows that the login button re-enables after an error.

**Comment by LisaAlmarode** [comment]
It sometimes take a couple of seconds to reenable, but it seems pretty reliable that it eventually does.
