### ISSUE TITLE
Code formatter always reporting illegal source (3.0.80)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#579]
![image](https://user-images.githubusercontent.com/13142166/67033555-e0f93800-f0ca-11e9-8118-5c4287b7069c.png)

**Comment by ericwinger** [comment]
Not sure what's happening as it's working for me with the same method. If you email me your stone's login information, I might be able to see what error ``RowanMethodService>>reformatSource`` is doing.

**Comment by ericwinger** [comment]
``Interval>>stonOn:``  not committed to package but lived in my stone.
Therefore the bug didn't reproduce for me until I changed stones.
Method committed and issue resolved in 3.0.81.
