### ISSUE TITLE
(3.0.81) Implementors Of.../Senders Of... doesn't show selection list

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#581]
In recent work related to symbol retrieval, the symbol suggestions when you use ``Browse Implementors Of...\\ or ``Browse Senders Of ...`` got broken. You get an empty list which is not helpful.

**Comment by ericwinger** [comment]
Fixed in 3.0.82

**Comment by LisaAlmarode** [comment]
I have no idea how to test - there are a lot of different Browse Implementors Of..., but none of them that I know bring up a list of "symbol suggestions".  Unless this means the one specific symbol appended to the menu?

**Comment by ericwinger** [comment]
@LisaAlmarode Oh, sorry.  Just use a wild card and you should see the selection list to choose from. That was broken in a recent release.

**Comment by LisaAlmarode** [comment]
... and feature added to docs.
