### ISSUE TITLE
Debugger layout regression, after step through added (3.0.81)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#586]
When step through was added, it looks like the text for "Message Not Understood" was not moved with it, and is now covering up the circle-arrow restart icon.

Pre-release 82, and my 81:

![image](https://user-images.githubusercontent.com/13142166/67249011-fb107e80-f41a-11e9-9d3f-2d4b30db2135.png)

Some older version:
![image](https://user-images.githubusercontent.com/13142166/67249122-5d697f00-f41b-11e9-9f94-bd3a1fc4b485.png)

**Comment by ericwinger** [comment]
Should be fixed in 3.0.82.
