### ISSUE TITLE
Add package, update config, reload results in bad state

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#59]
In the package browser, I added a package, class (by editing the template), and method, and wrote to disk (did not commit to git nor GS).  

Went to the on-disk project, and used vi to edit the config file (two places) so that the new package would get loaded.

Then back in the package browser, I loaded the project to make sure I'd still have the new package.  The new package is there but the class is missing (it's doesn't refresh to show it's not there, you have to click on another package and back).

The project write is correct on disk, and if I abort and logout, and then load the project, the new package and classes load correctly, so I'm pretty sure the config file is correct.  

As a symptom of the bad state, if you use find class (to look for the missing class, in my case NewClassOne) you get a walkback:

a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'name'

MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> doesNotUnderstand: @9 line 10
UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
NewClassOne class (Behavior) >> rowanProjectName @7 line 10
[] in  ExecBlock1 (RowanBrowserService) >> allClasses @8 line 8
ClassSet (IdentityBag) >> collect: @9 line 12
RowanBrowserService >> allClasses @5 line 4
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
> Went to the on-disk project, and used vi to edit the config file (two places) so that the new package would get loaded.

Can you elaborate on how you edited the config file? - maybe a diff of before & after?

**Comment by LisaAlmarode** [comment]
I'm going to close this - in my clean image with latest rowan there's some weirdnesses, but I can't reliably produce a walkback.  I think some scenario with changing branches was involved and I have also seen a (different) walkback with inconsistent state, the package was in the config but didn't exist on disk. The earlier problems could also be a side effect of some other actions in the old image.
