### ISSUE TITLE
Inconsistency: Method List Browser calls categories "protocol" (3.0.81)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#590]
There is a lot of unclarity between these terms in Smalltalk, but we should try to be consistent with a single GUI.

![image](https://user-images.githubusercontent.com/13142166/67331724-f8716000-f4d2-11e9-9189-a47ad41dd495.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.83
