### ISSUE TITLE
Project Brower run-all menu item leaves all tests selected (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#591]
If you use the little running guy icon in the SUnit tab, or in the Sunit browser;
or the run all menu items in the SUnit browser, 
or the control-shift-A in the Sunit Browser,
   it does not affect your selection in that browser.

However, the project browser method pane run-all does leave all tests selected, and the control-shift-A in that browser does too.  It means you lose the selection you did have previously.  

It also creates an alarming gray background, which appears to be an alternate color for "selected".  If I go to the method source tab and back, the tests are gray... but focus must be on this pane, since the run-selected button works.  I suspect there's a hole somewhere.

**Comment by ericwinger** [comment]
Fixed in 3.0.84.
