### ISSUE TITLE
Need to fix missing blue icon problems (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#592]
![image](https://user-images.githubusercontent.com/13142166/67418935-996a2480-f580-11e9-9648-c49ac84f9e05.png)

![image](https://user-images.githubusercontent.com/13142166/67419010-bdc60100-f580-11e9-8427-6294c90b2501.png)

![image](https://user-images.githubusercontent.com/13142166/67418981-aedf4e80-f580-11e9-970d-08638c5ab2de.png)

**Comment by ericwinger** [comment]
Missing .ico file. Should be fixed in 3.0.83
