### ISSUE TITLE
Browse Class in workspace on non-class has ugly error (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#593]
I wasn't sure how smart the workspace Browse class menu item was.

So I added a letter after the class name ( Systema ) and highlighted it and used the Browse Class on the popup.

![image](https://user-images.githubusercontent.com/13142166/67428275-ae4fb380-f592-11e9-8cab-840b8c6f6404.png)

However, it does find Repository when I look in SystemRepository, which is somewhat smart.

**Comment by ericwinger** [comment]
Got a targeted fix for this in Dolphin-only code for 3.0.83.
