### ISSUE TITLE
Debugger toolbar and Debug menu order should match (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#594]
Step through was added as the third icon from the left in the toolbar, but the fourth item in the Debug menu.  The order should match; these are confusingly similar enough as it is. 

Also, there are quite a confusing lot of icons here; perhaps we can remove the non-implemented Run to Cursor (the arrow to double parens?)

**Comment by ericwinger** [comment]
Fixed in 3.0.83
