### ISSUE TITLE
Preferences file/workspace menus and preferences window titles unclear (3.0.82) 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#595]
I'm finding the preferences workspace/s slightly confusing as to the titles and names, and correspondence with the menus. This was reported in #553, but that issue got sidetracked on actual defaults.

The Browse Preferences file opens with the title
   C:\GS\Oscar\Jadeite.prefs for SystemUser on stone...
and has added menu items 
   Preferences Options Workspace
   Reset Preferences to default.

- [x] I think this ought to have something in the title, indicating it's the Prefs File Browser - maybe instead, the title could be:
   Preferences File C:\GS\Oscar\Jadeite.prefs
(The user name should not be here since the file itself is common to all users, so it's confusing... and I'm not thinking that there ought to be any stone information either...)

 - [x] This menu item is also confusing... it sounds like it opens the preferences browser:
  Preferences Options Workspace
instead, perhaps this menu item could be renamed "Default Preferences Workspace".  It's a bit long but would hopefully fit.

The Preferences Options Workspace menu opens a windows with the title
   Jadeite Preferences Options for SystemUser on stone...

 - [x] This is more preferencey-browsery than the real Preferences Browser... The title should perhaps more clearly be (and match the menu item):
   Default Preferences Workspace for SystemUser on stone...
 
 - [x] The "Reset Preferences to Default" was unclear; it sounds like it would reset the actual settings, and possibly write the file, not just paste the default into the workspace.  This may be best solved by a larger API change... but I think if this was to say "Reset to default text" that would be much clearer.

 - [x] the menu needs a separator between Browse Package and the Preferences Options settings.

And I still find the ordering in the preferences file hard to see and match with the menu items:

- [ ] the order of setting-preferences in the preferences file example should match the order in the Jadeite menu

- [ ] the setting preferences and the open-windows preferences should be grouped, not leaving poor little transcript writes all alone at the end.

**Comment by ericwinger** [comment]
I think it needs some cleanup as well. What would you think if I made the Options/Default window read-only and had a different background color?

**Comment by ericwinger** [comment]
I'm in agreement with most of the recommended changes although I didn't use the exact language in the issue comment. Instead, I aimed for consistency. Also, I felt the word `settings` was more descriptive than `text`. There are pictures below. 

I was not included to change the alphabetical order of the settings themselves. If someone opens the .prefs file in a Jadeite future with many more settings, it would be difficult to find if they were not alphabetized. I remain, as ever, open to being overruled if a 2-1 majority can be reached. 

Calling this fixed. 

![image](https://user-images.githubusercontent.com/36212516/70002805-070d5700-1516-11ea-8b60-816b9ea581f1.png)
![image](https://user-images.githubusercontent.com/36212516/70003039-c4984a00-1516-11ea-8ec8-a746e0bf5139.png)
![image](https://user-images.githubusercontent.com/36212516/70003390-cf071380-1517-11ea-932a-96f8c92c8229.png)

**Comment by LisaAlmarode** [comment]
I like the new menu items and labels - it's been intuitive to use.

To avoid confusion, I filed a separate issue #672 on the ordering.
