### ISSUE TITLE
variables tab sort order inclear/confusing (3.0.82

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#596]
This is sort of related to issue #575.  If you have instance variables in various superclasses, it would be nice to be able to figure out what was what. 

In this example, I've got instvar names suffixed with the same number as the class.

![image](https://user-images.githubusercontent.com/13142166/67439420-fda1de00-f5aa-11e9-904e-d39b67dfa679.png)

I'd probably prefer, myself, the implementation order.  For example, as is shown in the inspector:

![image](https://user-images.githubusercontent.com/13142166/67439581-799c2600-f5ab-11e9-8b1b-1d56476a3ad7.png)

In GBS, I see the instance variables in the current class in bold font.  This would be an improvement.

**Comment by ericwinger** [comment]
I'm loath to make the variables in implementation order. In a long list or a deep hierarchy, variables are difficult to find. But I agree that bolding inst vars in the selected class would be helpful. 

As far as how to make local variables stand out, italics and colors were harder to see or confusing (to me). Here are three that I think are better - just bold, just underline, and bold & underlined. Preference? 

My preference is bold underlined. 

![image](https://user-images.githubusercontent.com/36212516/67816035-ef016e00-fa65-11e9-92eb-de3d4d33d141.png)

![image](https://user-images.githubusercontent.com/36212516/67816243-95e60a00-fa66-11e9-9095-b3307fefb49e.png)

![image](https://user-images.githubusercontent.com/36212516/67816317-d6de1e80-fa66-11e9-8e90-3a9a460c3fcf.png)

**Comment by LisaAlmarode** [comment]
It's very hard to tell out of context, and my fonts are not identical... but I don't think I like underlining - it just seems like it will make them harder to see.  And in all those cases where you don't have any inherited instance variables, it's pointless to have the clutter of underline.

So... I'd go with just bold (since you ask).  It's not really critical to distinguish at a quick glance, since you have equal access, so a subtle hint would be okay.  All IMO, of course, YMMV.

Have you considered making the inherited ones italic?

**Comment by ericwinger** [comment]
I personally don't think the italics works ... but just bold for locals works for me. 

![image](https://user-images.githubusercontent.com/36212516/67817777-fa579800-fa6b-11e9-8e82-a5f79c67dad0.png)

**Comment by ericwinger** [comment]
Should be fixed (bolded only solution) in 3.0.86.
