### ISSUE TITLE
Disabled Breakpoints only disables existing, doesn't impact one set later; why in preferences? (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#597]
If you have an existing breakpoint in a test method, running it brings up the debugger.
If you click on the Jadeite menu option breakpoints enabled, so that breakpoints are disabled,
   then you can run the test method and it does not bring up the debugger.

If you then put a second breakpoint in the test method, (with breakpoints still disabled), 
  running the test method brings up the debugger on that new breakpoint.

Is this perhaps not the intended behavior?

If it is... it makes me wonder what would be the point of setting it in preferences?  If it only applies to breakpoints that were set previously, why set/unset on login when you can't possibly have any breakpoints set?

**Comment by ericwinger** [comment]
Should have a fix in 3.0.83. Need better highlighting for disabled breakpoints. Creating new issue #598 for that.

**Comment by LisaAlmarode** [comment]
disabling breakpoints makes more sense in v3.0.83.  The lack of highlighting is a problem, though.
