### ISSUE TITLE
Remove or implement "not yet implemented" debugger run-to-cursor (3.0.83)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#601]
The 6th debugger step icon (counting from the left) is "run to cursor" with an arrow pointing to parens.

If you click on it, it does this:

![image](https://user-images.githubusercontent.com/13142166/67523190-fdfdb000-f662-11e9-828b-541b23b9f58e.png)

While implementing it would be nice, meanwhile I think it should be removed, and added in when it is working.

This issue mentioned in #594

**Comment by ericwinger** [comment]
Removed in 3.0.84 in both toolbar & `Debug` menu
