### ISSUE TITLE
When opening multiple browsers on startup, keep console first (3.0.83)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#603]
With the feature that allows you to open multiple browsers and workspace on startup, you may now always have at least 4 windows open, which I see on the toolbar pane at the bottom of my window.  It's nice that these windows open per the order in the preferences file.

However, it's really annoying that the console is the last one in the list to get opened.  I often need to find the console... and having it be next to the login dialog made it much easier to find.
Especially after opening a few other browsers the console is very hard to find.

**Comment by ericwinger** [comment]
@LisaAlmarode  When you say "first" do you mean "on top"?

**Comment by LisaAlmarode** [comment]
I'm talking about the order of opening... which controls the location on my windows task bar.

It might be as good to have a hot key to raise the console too.

**Comment by ericwinger** [comment]
I've implemented a hot key ``Ctrl-F7`` which raises the console from other windows in 3.0.84

**Comment by LisaAlmarode** [comment]
Personally, having the console window not located next to the Jadeite window on the windows bottom task bar makes the opening-browsers feature a bit less usable for me, and the workaround is only marginally helpful.  But... this is given the way I work (on this machine/currently), and may not be a general problem.
