### ISSUE TITLE
Copy class when class exists changes browser focus to wrong class (3.0.83)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#604]
this is follow on to issue #506 
If you copy a class and the name you pick already exists, you get a walkback.  This ought to be an error.

![image](https://user-images.githubusercontent.com/13142166/67527930-fe9b4400-f66c-11e9-8050-01ce45a6d850.png)

**Comment by ericwinger** [comment]
Will get a nicer information dialog in 3.0.84.

**Comment by LisaAlmarode** [comment]
It's a nice error.  However, clicking "okay" seems to bring me to the new class, which is in a different project and package... not what I wanted since I am going to forget what class, I was in and wanting to copy.

**Comment by ericwinger** [comment]
It's not taking you to the new class since the copy failed and there is no new class. However, it may take you to the package where the class is defined if you were in an extension package. I'm not sure that's really all that bad.

**Comment by LisaAlmarode** [comment]
Well, it's bad if your goal was to copy a class (which is hard to argue).  I want focus to return to the class that I was copying from, so I can try the copy again using a different target name.  

Currently, it's taking you now to whatever the package is that contained the existing class whose name you tried to use, which may be completely unrelated to what you're currently working in.  

For example, if you try copying a class to the name "String"... focus goes to String class in the Dictionary view of the (NONE) package. Causing one's head to spin.

**Comment by ericwinger** [comment]
I've added a check as you enter the new class name.  If it is an existing symbol, you are given the opportunity to retry entering a name. Cancel leaves you on the same class.

**Comment by LisaAlmarode** [comment]
Much better behavior!
