### ISSUE TITLE
Configurable method text underline of step points (3.0.84)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#605]
In this version the color of the step point underline was made slightly darker (at my request).  I think I like this - certainly much easier to add breakpoints - but it's slightly more distracting and might impact code readability.  

It might be nice to make this user-configurable.

**Comment by LisaAlmarode** [comment]
Customer did not care for the darker underlines.  That makes this feature much more important.

**Comment by ericwinger** [comment]
Note - color restored to `gray` from `darkGray` for stepPoint underline in 3.0.88

**Comment by LisaAlmarode** [comment]
I think we can allow this to not be further changed.
