### ISSUE TITLE
On breakpoint enable/disable, breakpoint/method list browsers not updated (3.0.84)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#606]
When you have open project browser, breakpoint browser, and method list, all with breakpoints showing in red say, 

and you disable breakpoints, using the menu item... 

the highlight is not updated in the breakpoint or method list browsers, they are still red. PB is updated and correct.

If you click on and off a method in any of the browser, all the browsers do get updated.

**Comment by ericwinger** [comment]
Debugger breakpoints are the only breakpoints I see that are not updating properly. Breakpoint browser, method list browser, and project browser all seem to update in 3.0.89. Could you confirm? 
![image](https://user-images.githubusercontent.com/36212516/69744452-0da26580-10f5-11ea-8f29-3ca5b8aa4713.png)

![image](https://user-images.githubusercontent.com/36212516/69744495-2448bc80-10f5-11ea-9777-c1e9883682a5.png)

**Comment by ericwinger** [comment]
Have a debugger fix in the `waiting` branch in the Jadeite project. Will move to oscar after customer release finished. Tagging as `Move to Oscar` as a reminder.

**Comment by LisaAlmarode** [comment]
looks okay in 3.0.92-2
