### ISSUE TITLE
Mysteriously vanishing underlines (3.0.84)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#608]
method text is underlines to indicate breakpoints.  Sometimes when I compile methods I end up with the method not having underlines.  

One way this happens is to have the same method in two panes, e.g. both a method list and the PB.  Make a trivial change and save in one browser.  The method displayed in the other browser loses its underlines.  You can still add breakpoints, though.

**Comment by ericwinger** [comment]
Fix seems to be working in 3.1.0.

**Comment by LisaAlmarode** [comment]
The underlines now vanish in the same browser pane after saving a method, regardless of any other browsers.  For example:

before:
![image](https://user-images.githubusercontent.com/13142166/78192945-1c47b300-742e-11ea-88e4-1496883901e5.png)

trivial change
![image](https://user-images.githubusercontent.com/13142166/78192967-2ec1ec80-742e-11ea-8d27-2347e677d0f8.png)

after saving method:
![image](https://user-images.githubusercontent.com/13142166/78193005-4305e980-742e-11ea-91ef-41de276dda77.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release3.  Indicators needed to be reset after method save.
