### ISSUE TITLE
Need Performance Improvement in auto complete symbol caching

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#612]
Customer notes that logins are quite slow when logging in. They confirmed that when symbols are not cached, there was a 3-5 second (about 30%)  improvement in performance. 

Based on discussions, need to:
- [x] Make one round trip when caching symbols
- [x] Don't cache every symbol, just class names and selectors
- [x] Don't rebuild the cache after method or class creation.

Possibly: 
- [x] Change auto-complete default to ``false``
- [x] Upon enablement, allow user to do a one-time confirmation before caching symbols. 
- [x] Use "smart update" after project load. Keep cached symbols on server and compare to symbol list. Only add new symbols and ship to client.

**Comment by ericwinger** [comment]
Single round trip and selective caching done. https://github.com/GemTalk/Jadeite/commit/adb9dae98cd8b1a0c040900b4f8a66cc71ebdc7f

**Comment by ericwinger** [comment]
Enhancements made. Faster now and the symbol caching is done when autocomplete is manually turned on from the transcript.

**Comment by LisaAlmarode** [comment]
I have not been able to detect this performance issue, but customer hasn't complained.
