### ISSUE TITLE
(3.0.85) debugger step over broken (3.5.0, Unicode comparison, Legacy streams)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#613]
Presumably passing in 0 for `inFrame: anInteger`:
![image](https://user-images.githubusercontent.com/623951/67991326-0cfdd880-fbf6-11e9-9ddb-4f3729e86db9.png)
Running this test ... uncommitted work ....:
![image](https://user-images.githubusercontent.com/623951/67991392-4fbfb080-fbf6-11e9-8afa-2af703dc3c39.png)

**Comment by LisaAlmarode** [comment]
closing this since it's so back version in server and jadeite debugger; if it occurs with 3.7, rowan3, 3.2.12, file a new issue
