### ISSUE TITLE
Leading * in find implementors... worked in 3.0.65 but not in 3.0.85

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#615]
Say you do browse implementors and enter *ddition.  In 3.0.65 this returns:

![image](https://user-images.githubusercontent.com/13142166/68233251-aab92500-ffb3-11e9-85c6-32d029597c9b.png)

However, in 3.0.85 it returns an empty list.  

I thought that was how it worked.... I believe that's what I put in the 3.0.85 UG...

**Comment by ericwinger** [comment]
Fixed in 3.0.86.
