### ISSUE TITLE
(Oscar-3.0.85) method source for methodFailingRecompile looks like printString

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#616]
Note the doubled `'` in the method source below ... that looks to be a printString of the methodSource:
![image](https://user-images.githubusercontent.com/623951/68247199-24aad780-ffcf-11e9-9d0a-465ce786d7db.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.86

**Comment by LisaAlmarode** [comment]
I've been complaining about this since AUGUST ! ! ! and elapsed time to fix apparently only an hour.  I shall have to be firmer in the future about fixing things.

**Comment by ericwinger** [comment]
Your nags already have varying levels of firmness - like a high quality mattress. If they get much firmer it may impact programmer sleep cycles and thus productivity. :)
