### ISSUE TITLE
error if press sunit debug when focus in method pane (3.0.86 candidate)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#618]
If you have a selected method in the sunit tab and set focus to the method pane:

![image](https://user-images.githubusercontent.com/13142166/68328762-c0e2e600-0084-11ea-88b4-527bc3672b20.png)

and then press the debug button on the side bar of the sunit tab, this happens:

![image](https://user-images.githubusercontent.com/13142166/68328827-e1ab3b80-0084-11ea-89c4-63fd6311249d.png)

**Comment by ericwinger** [comment]
Should be a safe fix in 3.0.87.
