### ISSUE TITLE
Recompiling class does not update subclasses (3.0.86 candidate)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#619]
If you have a hierarchy of three classes, and you add an instance variable to the highest one, all the subclasses are recompiled.  
However, the display shows the older version.  

Here's right after adding the instance variable to the superclass:

![image](https://user-images.githubusercontent.com/13142166/68329407-0358f280-0086-11ea-96b8-fa0f04e99607.png)

Note that it doesn't show any versioning on subclasses.

Then when you click on the subclass:

![image](https://user-images.githubusercontent.com/13142166/68329437-0d7af100-0086-11ea-9db4-5c0bf6ff5507.png)

--> this is the really buggy part; if you add a method to the subclass, compile does not fail but the method does not appear!  changes to existing methods are visible.

Clicking on different classes doesn't help, but if you click on a different project you will see your added methods.

**Comment by martinmcclure** [comment]
I just hit this one. For me, selecting a different package, then back to the affected package cleans up the display. I didn't try selecting a different project, which seems to have worked for Lisa.

**Comment by LisaAlmarode** [comment]
Reproduced in 3.2.12. 

Create a class ClassOne and a subclass of ClassOne named ClassTwo.  In my test ClassOne has ivar one and accessors and ClassTwo has ivar two with accessors.

Add an instance variable to ClassOne.  This recompiles both ClassOne and ClassTwo.
But now, Class Two
  shows (1/2), 
  the class is purple, 
  the definition shows it's not packaged, (subclass, not rwSubclass)
  adding a method appears to work but the method is not displayed.

![image](https://user-images.githubusercontent.com/13142166/202330208-b4af3a9f-372c-4478-ad09-b42957bf4e65.png)

clicking on and off does fix the problem

**Comment by ericwinger** [comment]
Jadeite was not updating subclasses after a super class compile. 
Fixed in 3.2.14.
