### ISSUE TITLE
(3.0.85) sort auto complete list by shortest match?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#622]
Here's a screen shot, where I've typed `condition` and I'm aiming at `conditionalPackages` ... if the list were sorted by shortest match first, I'd be able to hit `tab` and be done:
![image](https://user-images.githubusercontent.com/623951/68404916-19bd8780-0134-11ea-8994-ebbb1459fa1f.png)
as it is I have to type `conditionalPackage` before I am a `tab` away ...
Just a thought ...

**Comment by ericwinger** [comment]
Believe fixed in #636
