### ISSUE TITLE
(3.0.85) when multiple packages selected the browser tab not updated with class name

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#623]
I expect the selected class name to show up in the tab:
![image](https://user-images.githubusercontent.com/623951/68421862-ef7bc200-0153-11ea-9693-7cbefb85c87c.png)

**Comment by LisaAlmarode** [comment]
Reproduces in 3.2.12
If a project is selected but no package, the projectname shows in the project browser tab label.
If you select one package, the tab shows package name 
If you have one package selected and select a class, the class name shows in the tab.
If you select multiple packages, the tab shows the project name, which is reasonable.

However, if you select one class when you have multiple projects selected, the tab still shows only the Project, this case should show the class.

**Comment by ericwinger** [comment]
Tab shows the class name when multiple packages are selected.

**Comment by ericwinger** [comment]
Fixed in 3.2.14.
