### ISSUE TITLE
(3.0.85) A revert menu item in the changes browser would be useful

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#624]
I'm pretty sure that the current data structures don't have the necessary data, but we could arrange to provide the disk source for each modification/removal and the `Revert` menu item would simply replay the source:
![image](https://user-images.githubusercontent.com/623951/68424417-c873bf00-0158-11ea-8d57-9b2cfa6531db.png)
... this would be pretty useful when you want to revert only selected methods ...

**Comment by dalehenrich** [comment]
... actually it looks like the complete source is in the disk pane, so the data **is** there, so it should be relatively easy to implement ...

**Comment by ericwinger** [comment]
I've got a version of revert that works for methods (add, remove, change) in 3.0.92. Closing as fixed for review.

**Comment by LisaAlmarode** [comment]
Revert of added, removed, and changed methods appears to be working nicely.  

Revert of add added method shows (removed), revert of an removed method shows (restored), but revert of a modified method does not show anything.  It would be kind of nice if selector said included something like (reverted); makes one feel more confident that something happened.  This isn't very important.

If you remove a class, it shows the list of methods for that class.  If you try to restore any of those, you get a walkback.  This ought to be fixed, I think.

**Comment by ericwinger** [comment]
Reverted modifications now have a `(reverted)` label and reverts that fail have a nicer warning, in particular the [use case mentioned](https://github.com/GemTalk/Jadeite/issues/624#issuecomment-574821488).

**Comment by LisaAlmarode** [comment]
This is looking good. 
It would be nice to be able revert class add/remove too; this is a separate feature request.
Also, if you revert changes, they remain in the changes.  It doesn't appear to be a problem, but if you're pruning the changes list it would make it less useful. This I'll file as a separate issue; probably involves rowan.

**Comment by LisaAlmarode** [comment]
Another note: finding senders/implementors doesn't work for reverted methods, reported separately as issue #686 since I don't think it's worth holding up 92.
