### ISSUE TITLE
Edits to non-rowanized class methods become instance methods (3.0.87)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#625]
If you have a non-Rowan class (in UserGlobals), and you go to it in the projects browser and edit the source code for a new or existing class method, the method is saved as an instance method.  Class methods are just not editable!

**Comment by ericwinger** [comment]
@LisaAlmarode Could you try this experiment for me. Either in a workspace or topaz try running these methods and press resume at the warning. 
```
AbstractCharacter  rwCompileMethod: 'ghi' category: 'other'
AbstractCharacter class rwCompileMethod: 'jkl' category: 'other'
```
I see that both methods end up on the instance side of the class. This would implicate Rowan instead of Jadeite.

**Comment by LisaAlmarode** [comment]
Yes, the problem reproduces.  Reported on rowan as https://github.com/GemTalk/Rowan/issues/547.  Will close but leave in my review list hoping for a fix.

**Comment by LisaAlmarode** [comment]
Still broken in 92.3. Dale has fixed in master but this may still need Eric to pack port. Reopen optimistically.

**Comment by ericwinger** [comment]
Backported in https://github.com/GemTalk/Rowan/commit/7ac21f584475379f3582fc2c8606bf1a8a036897

Awaiting feedback.

**Comment by LisaAlmarode** [comment]
Class methods stay on the class side now, thank goodness.
