### ISSUE TITLE
(3.0.85) inspect of an object with printing error in debugger ends up inspecting the Error

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#627]
Doing an inspect on the receiver in this case ends with an isnpector that is missing the fields in the receiver:
![image](https://user-images.githubusercontent.com/623951/68700920-9ee0dc00-053a-11ea-92eb-a6a59842575c.png)
Errors **printing** an object should not effect the list of fields visible in the inspector ... I open the inspector to help me understand the state of the object that is leading to the error on printing ..

**Comment by ericwinger** [comment]
Many aspects of the inspection code still use the old Jade model which doesn't have a quick and dirty server side fix.  Probably worth a small port of  `JadeServer>>inspect:` to services and bringing back the instance variables even if the `printString` of the object fails.

**Comment by ericwinger** [comment]
The client entry point is `JadeInspector>>displayObject`

**Comment by ericwinger** [comment]
I believe that this is fixed in 3.0.92. In my test case, the object inspected from the debugger is the object not the error. Instance variables are visible.

**Comment by LisaAlmarode** [comment]
Works nicely.  Can even edit the problem fields and make the error go away.
