### ISSUE TITLE
(3.0.87) Implementors selection with wildcard displays blank window

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#631]
Recent fix for #615 not sufficient. Occasionally still see empty selection list. Could be that we're still depending on autocomplete symbols in some path. 

Hint - if seen, turning on autocomplete makes the problem go away.

**Comment by ericwinger** [comment]
`JadeiteSearch` class variables `AllClassNames` and (the inappropriately named) `AllSymbols` were not getting initialized properly because we were doing an `ifNil:` test instead of an `isEmpty` test.  Refactored the code a bit to remove redundancy as well. 

Added sanity test to ensure that if the class vars are nil, they get initialized.

**Comment by LisaAlmarode** [comment]
wasn't able to reproduce, so can't confirm fix
