### ISSUE TITLE
(3.0.87) Spaces in openWorkspace: preferences config option not handled

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#633]
Need to allow blanks in the ``openWorkspace:`` preference.

**Comment by ericwinger** [comment]
Allow blanks in prefs - `openWorkspace:` - fixed in 3.0.88.

**Comment by LisaAlmarode** [comment]
About one time in 10 or so, the login button doesn't re-enable by itself.  However, I haven't yet been able to make it happen on purpose.  When I try to setup complicated sets of windows to trigger the not-reenablement... it very reliably works correctly.  So reopening, but leaving assigned to myself.

**Comment by LisaAlmarode** [comment]
reclosing, reopened the wrong issue.  The spaces in paths for opening workspaces work very nicely although it's a bit unsettling to not use some kind of quotes or demarcation.
