### ISSUE TITLE
(3.0.85) GemStone Error on doit - possibly releasing oops too early

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#637]
![image](https://user-images.githubusercontent.com/623951/68967118-676d6c00-0794-11ea-84c1-bf366cf3cc6b.png)

While doIt's use services code, there still is a hook that gets the returned object's printString from the server in a second round trip by old Jade code. It is possible that the returned oop 129598209 was gc'd before the printString. 

Not reliably reproducable.

**Comment by jgfoster** [comment]
See https://kermit.gemtalksystems.com/bug?bug=48217 for a description of this server bug (fixed in 3.5.1) and a workaround: "use GciSaveObjs to put the result of GciNewUtf8String in the export set."

**Comment by ericwinger** [comment]
This should have been fixed in https://github.com/GemTalk/Jadeite/commit/c901396fe3461bd22a7d72d6be9b2285757487de. Please reopen if ad-hoc executions don't seem to hold onto their results long enough.
