### ISSUE TITLE
Set Compiler Environment causes error dialog (3.0.88pre-release3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#638]
I saw a strange menu item in the PB, Class >> set compiler environment.   I have no idea why this is here - it is new?  It appears to be only enabled in the menu bar menu, only when the SUnit pane is selected, but then it errors: 

JadeiteSUnitInClassPresenter does not understand #setEnvironment

![image](https://user-images.githubusercontent.com/13142166/69098772-1a94ca00-0a0e-11ea-92bd-ac00a30b131b.png)

I suspect it should not be on this menu in the released product.  Possibly a build artifact in this pre-release version?

**Comment by ericwinger** [comment]
@LisaAlmarode I'm not seeing this in either the .exe or development. Did you have to have a certain combination of class/method/packages selected?

**Comment by ericwinger** [comment]
Cancel ... I see what you're saying. I think that's always been there but should be removed because we don't support multiple environments in Jadeite.

**Comment by ericwinger** [comment]
Fixed in 3.0.88. Removed menu option
