### ISSUE TITLE
leading * in implementorsOf: acts like it also has a trailing *  (3.0.88.3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#639]
I've got a test case with 6 methods: water_one, water_One, Water_one, one_water, one_Water, One_water.  There are also 4 base/rowan methods that include "Water" and 1 "water".

In both 3.0.88.3 and 3.0.87,
  ```water*```  returns 5 matches
  ```*water*``` returns 11 matches

But: 
   in 3.0.87,   ``` *water``` returns 5 matches (correct)
   in 3.0.88.3,  ```*water``` returns 11 matches (that is, same result as ```*water*```)

This is probably the result of recent changes for #631; at least I think it was correct in 3.0.88.1.

**Comment by ericwinger** [comment]
This is a good catch.  Have a fix in 3.0.88 to review.
