### ISSUE TITLE
Rowan Method List Browser popup menu error

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#64]
I'm not sure how to get here; I did senders of and implementors of for a while, so I get to a browser that is titled "Jadeite Method List Browser...", on CharacterCollection >> withoutGemstoneLineEndings

If I put the cursor on the indexOfAnyOf:startingAt:ifAbsent, and do senders, I get a browser labeled
"Method List Browser..."

If I do implementors of that selector, I get a browser labeled "Rowan Method List Browser..."

The Method List and Rowan Method List Browsers both get an error attempting the popup menu on the code pane,  "MethodListPresenter does not understand #selection" and  "PackagemethodListPresenter does not understand #selection", respectively.  

The Jadeite Method List works correctly (except for save as noted elsewhere)

Side note: I think these dialogs should start off with a smaller list porttion and a larger text portion; say 2/5 and 3/5 to the bottom.  I seem to have big whitespaces to the top and crunched methods.

**Comment by LisaAlmarode** [comment]
Possible-related walkback on popup in debugger's code pane.  This one says JadeDebugger does not undersatnd #methodListPresenter.

**Comment by ericwinger** [comment]
Both senders/implementors use the Jadeite method list browser now. Also, made that browser a little less "top heavy" so there's more room for source code display. Fix will be in 3.0.13

**Comment by LisaAlmarode** [comment]
If I am in the Dictionaries Browser, senders of, I get to the old Rowan Method List Browser with the misaligned status and broken popup.

**Comment by ericwinger** [comment]
Fixed in 3.0.14. Dictionary browser shows new Jadite senders/implementors

**Comment by ericwinger** [comment]
Fixed in 3.0.15.
