### ISSUE TITLE
Error dialogs from PB menu items when on Sunit tab

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#640]
When you are on the Sunit tab, all the class drop down menu items give you error dialogs like this: 

![image](https://user-images.githubusercontent.com/13142166/69208870-0635f780-0b0a-11ea-96a5-4cda9b4da200.png)

Same thing with Projects menu and preferences menu.

**Comment by ericwinger** [comment]
I don't see this.  Please be more specific on how you're trying to rename a class. 

![image](https://user-images.githubusercontent.com/36212516/69258913-43ce6b00-0b72-11ea-840c-1ec995e265ef.png)

**Comment by LisaAlmarode** [comment]
Not just rename - all the class, preference, and project menu items do the same thing.
I'm happy that it works for you, though.

**Comment by ericwinger** [comment]
Can you explain in more detail which menu item your pressing, in what menu, with what tabs selected, etc?

**Comment by LisaAlmarode** [comment]
There aren't any details not already provided - it's not a subtle or complicated problem (for me!). All it takes: SUnit tab selected, drop down any of the listed menus and click on any of the menu items. 

In pictures:

![image](https://user-images.githubusercontent.com/13142166/69265647-754d3380-0b7e-11ea-9eec-4f633c29eb88.png)

then press the mouse and this happens:

![image](https://user-images.githubusercontent.com/13142166/69266014-310e6300-0b7f-11ea-89f8-365a479e6492.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.89
