### ISSUE TITLE
SUnit Browser should change icon to a `neutral icon` when running test manually ....

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#642]
... if you abandon the test for some reason (close debugger for example), the test will not shows as passing or failing ... and has an unknown state ... it would help me keep trak of which test I was manually working with as well as mark the test indeterminate state on last run ...

**Comment by LisaAlmarode** [comment]
I'm not entirely sure what is intended here and this bug is very old and very idle, so closing this.
