### ISSUE TITLE
(3.0.88) Need to remove rename class

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#644]
My rationale for summarily removing the rename class menu item is that there is a [previously reported Rowan bug](https://github.com/GemTalk/Rowan/issues/490) associated with moving classes with extension methods between packages that can be triggered by the rename class code and I don't want our customer to run into this corruption inadvertently. The root cause of the bug is creating a new class version of a class with extension methods and this is what rename class does when it moves old subclasses from the old class to the new class.

The bug with rename class was discovered yesterday and initially [reported against Jadeite](https://github.com/GemTalk/Jadeite/issues/643 ). After investigating a little bit with @ericwinger , we determined that there was some corruption in the Rowan method data structures and as I dug more deeply into the bug last night, I found that there was additional corruption in the class extension data structures. While the method data structure corruption is relatively benign, the class extension data structure corruption is not benign and more concerning, this corruption is not detected by the project audit.

I don't believe that the customer is in the habit of intentionally creating new class versions, so I don't think that developers will intentionally move a class with extension methods from one superclass to another, so I haven't been worried that they would trip across this bug during normal development tasks. However, rename class does move a class from one superclass to another without warning and one of my concerns is  that a developer using rename class, could introduce undetectable corruption and not be aware that new class versions were created "underneath the covers".

Additionally, independent of the bugs involved, I am concerned that a simple rename class for a class with no subclasses is not safe. The rename function basically creates a new class with the same name and copies the code from the old class to the new class, then the old class is deleted. The fundamental problem is that there is no provision for migrating the old class instances to the new class instances. No class versions are created so there is no way for automatic migration to be triggered --- we could arrange to do this in the original development image, but there is no way (currently) for Rowan to know that a class has been renamed when loading the code into a production image, so to provide a `rename class` function that does not really deliver on the promise is not a good idea. 

The `copy class` menu item is a better way to expose this functionality to a customer ... creating a new class and copying the code from an old class is still useful functionality and gives no illusion to a developer than anything else is being done ... if the developer wants to arrange to migrate instances of the old class to the new class, they will be aware of the fact that they would have to do this work themselves, thus during deployment to production they will be well aware of the fact that they will need to manually migrate the instances.

**Comment by ericwinger** [comment]
Removed in 3.0.89.

**Comment by LisaAlmarode** [comment]
Verified menu item is not there.
