### ISSUE TITLE
Hover breakpoint display flickers annoyingly (3.0.89)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#646]
When you're over a breakpoint, you get a hover help that says "step point #2" (for example).  

If you move the mouse slightly, the first help goes away and another identical one pops up a few pixels away.  

If you are moving slowly.... considering where you want to put the breakpoint... it comes across as a flicker.  

This was in the debugger and it looked at first like Jadeite was busy doing something or another.   But the flicker occurs in the browser, too.

This may not be visible over a superfast connection.

**Comment by ericwinger** [comment]
There's a ``hoverTime`` setting that can be changed for the method source pane. Right now it's set at 200ms. From experiments, making it shorter increases the "flicker" so making it longer is probably the right answer. However, it's hard to know what the proper duration should be. 

Perhaps we can look at this together next time you're in the office, @LisaAlmarode .

**Comment by LisaAlmarode** [comment]
I'm going to close this, at least for now. I suspect something else was going on that first time that made it sooo visible.  It's still there in 92.3... but I can't describe it as annoying.
