### ISSUE TITLE
Adding class doesn't update autocomplete symbols

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#647]
When you add a new class in Jadeite, the class name should be cached for autocomplete. It wasn't. Fix in Rowan ``RowanBrowserService>>updateSymbols:`` to properly return the name of the cached class names and update it in the client.

**Comment by ericwinger** [comment]
Fixed in 3.0.90.

**Comment by LisaAlmarode** [comment]
Verified in 89 and  not 90. Applies to class names only, method names are updated in both versions.
