### ISSUE TITLE
(3.0.89) should be able to enable/disable breakpoints from menu in breakpoint browser and debugger 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#648]
It's a natural place to have that menu item .. when you have the breakpoint browser open you shouldn't have to hunt for the console to toggle breakpoints .. the debugger is another spot where it would be useful to toggle breakpoints on and off ... if I had to choose only one, I would want to be able to do that in the debugger ... 

While I'm thinking about it the test browser is the other natural spot where you would want to want toggle breakpoints before running a test ...

**Comment by ericwinger** [comment]
Should be ready to test with the work from #545 .
