### ISSUE TITLE
Status bar and icon resizing still not ideal in Project Browser (3.0.90) 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#652]
This was originally reported as #547.  It's better after the changes in that issue, but still annoying. 

Interesting, the Method List Browser behaves perfectly.  That can be a model to fix the Project Browser.  The Sunit browser also has a well-behaved status bar although it doesn't have the same compile issue.  The debugger cuts off similarly to the project browser.

![image](https://user-images.githubusercontent.com/13142166/70101142-e5c96b00-15e8-11ea-9ac5-471794418e3e.png)

![image](https://user-images.githubusercontent.com/13142166/70101223-232df880-15e9-11ea-8f65-959862e2a10a.png)

![image](https://user-images.githubusercontent.com/13142166/70101432-aea78980-15e9-11ea-954e-920c1166e681.png)

**Comment by ericwinger** [comment]
Debugger & project browser fixed in 3.1.0pre-release3.
