### ISSUE TITLE
Confusingly named "Jadeite Preferences" icon opens very ugly window (3.0.90)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#653]
I was surprised to notice an icon on the Console with the label "Jadeite Preferences".  Oh, I said to myself, a shortcut to open the Jadeite Preferences File. Could be handy. But then I open it and see this... which, well, is one of the less attractive GUI windows I've faced.  

Besides aesthetics, 
- It is nice that you can apparently change system fonts here but it NEEDS ! an undo. 
- The codefont button doesn't work (at least as far as I can deduce purpose and observe results), since method source formatting is controlled by the source styler.

Looking back, this icon has been around since at least as far back as v3.0.65.  What's changed lately is that "Jadeite Preferences" now means something specific and does not mean this dialog.

![image](https://user-images.githubusercontent.com/13142166/70101514-ffb77d80-15e9-11ea-8842-6b173fc4e351.png)

**Comment by ericwinger** [comment]
This is the toolbar button in question. 
![image](https://user-images.githubusercontent.com/36212516/70166022-c9750f00-1678-11ea-8286-5386ad3c00ed.png)

- [ ] These are the old Jade preferences. It would be nice to incorporate this functionality into the new Jadeite preferences. 

- [ ] While we're at it, it would also be nice to integrate the browser Preferences as well. 
![image](https://user-images.githubusercontent.com/36212516/70166111-fa554400-1678-11ea-980e-8f789d243525.png)

**Comment by LisaAlmarode** [comment]
I see where the code font is used - it's for workspaces.  Apparently the Source Styler only applies to code in the method browsers, while the stealth dialog lets you change just the base font for workspaces.  

If you did want say your comments to be in pink rather than green, you can change this is the method browsers; but you're stuck with the predefined colors in workspaces.

**Comment by ericwinger** [comment]
I've replaced the not so useful old preferences file browser with the jadeite preferences browser so that the toolbar button and menu item are at least consistent. 

If the old preferences file with only a couple options is still desired, let's open a new issue.

**Comment by LisaAlmarode** [comment]
While it's possible we want to give folks more control over fonts, we'll wait for the complaints to come pouring in.

**Comment by dalehenrich** [comment]
Is there a new prefs file browser? I copied my old 3.0.93 prefs file into the 3.1.0 directory and when I click on the icon or menu I get the workspace variant of "prefs file editor", Am I missing the ability to control font size?

**Comment by LisaAlmarode** [comment]
There's the source styler still available on the project menu bar, but yes, the ability to control the system font and styling in the workspace was removed by this change.  Are you a complaint pouring in?

**Comment by dalehenrich** [comment]
Well, I guess so ... I've been waiting to ask for the ability to change fonts until the new Dolphin was integrated ... now that it has been integrated, I didn't actually look for that capability until I saw this bug, that seemed to imply that changing fonts and font sizes might actually be a thing now:)

Does the source styler save the settings to a file? if not then I won't waste time figuring out if I want to change settings:)

For me there's the usual screen real estate versus readable fonts battle, but if I had the option to choose font sizes and those choices were saved in a prefs file, then I would see if I can find a nice balance between font and screen real estate ... I won't know whether I will be happier with a different font or font size until I give it a go...

**Comment by LisaAlmarode** [comment]
The source styler doesn't write to any file, and changes don't persist over jadeite restart.  I wouldn't expect the currently inaccessible preferences to change workspace code styling and system fonts to be persistent either. 

The source styler has about a bajillion options (well, 240) so maybe a bit much for a file and overkill for what you want, which would be a single override for font size - and what might be most useful is a separate configuration for +1 or -1 configuration, so you don't need to set the font size individually for all 30 of the styles (since you do want the temporary variable open bar, and the temporary variable close bar, and the temporary varible declarations, to all match...).

**Comment by dalehenrich** [comment]
I wouldn't necessarily expect that the preferences for styling to be "human usable", but there should be a way to persist the settings across jadite invocations ... I assume that the styler is the same one used for Dolphin development where I assume there is the ability to save an image ... the same goes for system fonts and font sizes ... I wouldn't expect to be changing them by hand ... for Jadeite, there should be a way to persist the choices across invocations since we don't have the benefit of a saved Dolphin image ...

**Comment by LisaAlmarode** [comment]
You might want to actually look at the source styler (PB menu bar item for Preferences > Source Styler...).  Personally I'd hate to have to adjust font and font size for readability using the source styler, 30 separate changes to adjust font size...

**Comment by dalehenrich** [comment]
Yikes ..yeah that is not what I think of when I say "change font and font size":) Since all of the fontfields (that  I looked at) are empty, I don't even know which font or font size i'm actually using ... I would think there's be a simpler way to set font size ... and more persistent:)

**Comment by LisaAlmarode** [comment]
I've formulated the request as issue #805, so any further discussion should be on that issue.
