### ISSUE TITLE
Cannot inspect all of an array with more than 200 items (3.0.91)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#657]
If you inspect the following:

```
| coll |
coll := Array new.
1 to: 2000 do: [:i |
	coll add: 'entry', i asString].
coll
```
The inspection is acting like it contains exactly and only 200 elements. When I was looking at a collection of all metaclass3 instances, this flummoxed me since I'm pretty sure there are more than 200 classes.

I also saw the elements not being protected from GC.  The inspector was open, and I could go up and down the elements, then some were nil and then they were instance of other classes. It was kind of fun to watch.  I can't reproduce this trivially... but then I have a massive toc.  Earlier when I was doing lots of listIinstances and renames it was more likely to do gc.

**Comment by ericwinger** [comment]
There were some old limits still hanging around the inspector code on the server. Not sure why they were there but are removed. See server method `JadeServer64bit3x>>inspect:`

**Comment by LisaAlmarode** [comment]
I tried this with:
| coll |
coll := Array new.
1 to: 2000000 do: [:i |
	coll add: 'entry', i asString].
coll

Perhaps surprisingly, it seems to have "worked" but the resulting inspector appears to be confused; as I move or drag the slider bar down, it shows non-sequential ranges, and I haven't been able to reach any given desired element by dragging the slider.  I can get at least to element 76k using the page-down, but that's not a reasonable way to find an element.

**Comment by dalehenrich** [comment]
In tODE I gave the user the  option of ineractively increasing/decreasing the number of elements displayed (via dialog) and that worked well ...

**Comment by ericwinger** [comment]
This [request ](https://github.com/GemTalk/Jadeite/issues/657#issuecomment-565665949) is really more of an enhancement to inspector functionality. Opening a new issue.

**Comment by LisaAlmarode** [comment]
With this example, I have a non-squirrelly inspector with 65553 elements, but with 65554 elements, scrolled down the the bottom shows indexes 21, 22, etc.  So, this bug is fixed for collections up to a bit over 65k.  

It would be more correct to cut off the element display, rather than display it in such a broken way.  But hopefully the new feature can be implemented before the next public release, otherwise this ought to be reopened.

**Comment by LisaAlmarode** [comment]
Hopefully issue #668 means this can be closed.
