### ISSUE TITLE
Class autocomplete is not case insensitive (fix #636 not complete in 3.0.91)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#660]
While method autocomplete is case insensitive, autocomplete for Classes (starting with capital letter) is still case sensitive.

I have a lot of classnames that start with MAV.
When I type in MA I see them. But not with Ma.

![image](https://user-images.githubusercontent.com/13142166/69208545-ca4e6280-0b08-11ea-9f19-972b31b5b765.png)

![image](https://user-images.githubusercontent.com/13142166/69208529-c0c4fa80-0b08-11ea-9449-655419e36c44.png)

**Comment by ericwinger** [comment]
Should be fixed in 3.0.92pre-release2.
