### ISSUE TITLE
Auto-open file path resolution not the same on first vs. subsequent logins (3.0.91)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#661]
This is part of issue #632.

Say you have the following files:
  C:/GS/Oscar/Jadeite.prefs 
  C:/GS/Oscar/jadeite91.exe
  C:/GS/Oscar/testws1.gs
  C:/GS/Oscar/testws3.gs
  C:/GS/Oscar/operations/testws1.gs
  C:/GS/Oscar/operations/testws4.gs

and the preferences file has:
openWorkspace: testws1.gs
openWorkspace: testws3.gs
openWorkspace: testws4.gs

And you start jadeite using a shortcut that specifies 
   Start in: as C:\GS\Oscar\operations

After you start the jadeite91 executable, the first login opens
  C:/GS/Oscar/testws3.gs
  C:/GS/Oscar/operations/testws1.gs
  C:/GS/Oscar/operations/testws4.gs

but the second login (not restarting jadeite) opens:
  C:/GS/Oscar/testws1.gs
  C:/GS/Oscar/testws3.gs
  an error dialog saying it can't find testws4.gs

The following files show the older version number, but the behavior is the same in 3.0.91.

![image](https://user-images.githubusercontent.com/13142166/69209555-7a719a80-0b0c-11ea-9cd0-031debe67c81.png)

first login:

![image](https://user-images.githubusercontent.com/13142166/69209599-af7ded00-0b0c-11ea-894e-3a4964c60714.png)

second login:
![image](https://user-images.githubusercontent.com/13142166/69209684-02f03b00-0b0d-11ea-9039-3b1b448842b2.png)

**Comment by ericwinger** [comment]
The working directory was getting set to the image directory only after the first login. This would give inconsistent results between the first and subsequent logins. See `JadeLoginShell>>onViewOpened` for sender that sets the working directory.

**Comment by LisaAlmarode** [comment]
In 3.0.92-2, the second behavior works for both logins, which makes me happy.
