### ISSUE TITLE
(3.0.91) OOM when attempting to remove method with #new selector ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#663]
There are some 2000+ senders of #new and similar to the slow performance after doing a large set of changes ... I clicked on something after the method was removed (took a long time) then blew out of memory ... fortunately I had autoCommit on, so the method was removed, however the large number of new senders being passed around cause the OOM event ...

Putting into `December 2019` project because this could pop as a customer issue ...

**Comment by dalehenrich** [comment]
While removing a method that does not have a bunch of senders (in the same image as the original report), the performance is completely acceptable  ... so it occurs to me that Jadeite must be shipping the collection of methods that send the selector across the wire, however, the confirmation dialog is clearly only using the number of methods that send the selector, so the whole operation would run faster, if the only the number of senders was returned to the client ...

**Comment by ericwinger** [comment]
Should check to see if senders are getting returned to the client. Only need to return the count.

**Comment by ericwinger** [comment]
That was indeed the case. The code was foolishly returning method services when only the sender counts were needed. Fixed in 3.0.92pre-release2.

**Comment by LisaAlmarode** [comment]
very snappy remove in 3.0.92
