### ISSUE TITLE
More efficient handling of large collections. 

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#668]
While the inspector will open on the expression below, it's not terribly useful. Should be faster and easier to see the entire range of elements. Need to enhance the inspector to do one of the following. 

1. Add a "More" and "All" option to a collection inspector per [this suggestion](https://github.com/GemTalk/Jadeite/issues/657#issuecomment-565722658). Initial number of elements could be 200. More could bring in 200 additional elements. All would bring in all elements. 

2. Like VisualWorks inspectors, create ranges based on the species of collection being inspected. The left pane would have a range of say 1 ... 200. If clicked it would show the first two hundred elements in a middle pane. The right pane would still show the inspected element. 

It's somewhat expected that even though it's not efficient to inspect a 2 million element collection, it should still be possible. 

``` 
| coll |
coll := Array new.
1 to: 2000000 do: [:i |
coll add: 'entry', i asString].
coll
```

**Comment by LisaAlmarode** [comment]
The inspector is broken (in 3.0.92-2) with more than (in this test) 65553 elements.  For the next customer release, we should make sure that the inspector either handles larger numbers of elements, or just doesn't even try.  

I kind of like the single large inspector; the GBS ones with having to scroll through ranges to find the ones I want can be very annoying, especially if it's alphabetic (e.g. inspect Globals keys).  But we do need to consider performance...

**Comment by ericwinger** [comment]
@LisaAlmarode I'm open to how we display inspectors on collections. Here is one proposal: 

![image](https://user-images.githubusercontent.com/36212516/71112777-1b418d00-2181-11ea-897c-cb4e212f4c2b.png)

The default number of indexed items is open. I selected 1000 randomly. 
Thoughts?

**Comment by LisaAlmarode** [comment]
I like this better than the sets-of-ranges solution, and 1000 is probably a good size... though I worry about customer performance.
However, if you have a very large collection, and display all just bring it all into the inspector... it will just run into the unusable-inspector-scroll-with-over-65k-elements (which is probably a dolphin thing).

**Comment by ericwinger** [comment]
Should be improved in 3.0.92.

**Comment by LisaAlmarode** [comment]
It works fairly nicely for an initial open, and if you are just wanting to look at a smallish number of elements.

However, if you do theuse the "display all" option, and are very very patient while it hangs for five minutes, you get what is probably a correct inspector for 2M objects, but still not actually usable since the scroll bar is broken. 

I do think I could use the mouse down scroll, to examine all the way to the last element... perhaps if I used an electric drill with some rubber around the end, it would make it scroll far and fast enough to get to the larger elements need the end? 

If I try to use the scroll bar in the pane, however, it's the unusable-inspector-scroll-with-over-65k-element problem.  Still broken, in other words.

**Comment by LisaAlmarode** [comment]
I tried to make a change with the inspector open on the 2M object collection.  This hung too; I tried to wait it out but VPN disconnected.

**Comment by ericwinger** [comment]
>  Still broken, in other words.

I'm not sure I would characterize the new problems the same way as the old problems. Previously, simply trying to open a 2M collection would hang and break. Now, you can display and manipulate at least some of the collection if you don't try to display everything.

Since displaying "segmented" inspector ranges was vetoed, we may be at the mercy of Dolphin's graphic limitations when displaying large collections. As an aside, Dolphin doesn't even let you do a "Display All" if you inspect a large collection. They give you 200 elements and you can only ask for 200 more at a time. 

One alternative, similar to Dolphin's chosen solution, is to not give the user the 'Select All' option if the collection is sufficiently large. I question the usefulness of seeing 2 million elements in practice anyway. I would be open to making this change. Perhaps disable 'Select All' at 50K?

fyi - The over-65K elements is a separate, probably Dolphin, bug.

**Comment by LisaAlmarode** [comment]
I think limiting the display-all to 50k (why not 65k?) would be better; the current behavior is kind of disturbing.  Can we do that in December?  I agree 2M not really reasonable.

**Comment by dalehenrich** [comment]
I'll just chime in that I agree that there is no need to see all 2M entries in a collection, but being able to inspect a 2M entry collection and looking at an arbitrary chunk of 200 entries is something that would still allow you to use the inspector when you do have a 2M entry collection ... otherwise we're in the same boat that we were when the limit was 200 entries.

**Comment by LisaAlmarode** [comment]
What we probably will end up needing is a simple inspector to some size limit (say 10k), and a segmented one for anything larger.  Using "more" will get old pretty quick.

Maybe "inspect all" can open the segmented inspector.

**Comment by ericwinger** [comment]
So, the decision is to reverse the previous decision?  i.e. We now want to use segmented inspectors thus reversing [this comment?](https://github.com/GemTalk/Jadeite/issues/668#issuecomment-566795924) This will involve another lengthy inspector rewrite, fyi. 

> I kind of like the single large inspector; the GBS ones with having to scroll through ranges to find the ones I want can be very annoying, especially if it's alphabetic (e.g. inspect Globals keys). But we do need to consider performance...

**Comment by dalehenrich** [comment]
If there is significant work to be done to implement the segmented, my vote would be to defer the work until after the Dolphin port is done and that the segmented inspector be included as part of the work for supporting V2.0 ...

**Comment by LisaAlmarode** [comment]
I agree that being able to inspect collections with more than 65k objects is not needed for December/before Dolphin port.

I'm not comfortable with the current behavior with collections over 65k; besides it's-hung level slowness, the scrollbar is dysfunctional over 65k elements. My recommendation is to limit the max number to display in an inspector (with inspect-all) to 65k or less for now.  This means that in this release, we won't be able to inspect the elements past the first 65k.  Which you can't reliably do now, either.  

Ultimately solving this may require a second kind of inspector or a rewrite or something.  I don't think the final solution will be quick and easy.  And, maybe the Dolphin upgrade will fix the scrollbar issue.

**Comment by ericwinger** [comment]
I've limited the number of maximum displayable variables or keys to 65,000. We'll want to bug note this somehow. @LisaAlmarode Can you open a new issue on the full solution (segmented) and how you think the inspector should behave? 

![image](https://user-images.githubusercontent.com/36212516/72573986-59af9200-387c-11ea-8f8d-6aee40ee82ac.png)

**Comment by LisaAlmarode** [comment]
The behavior in 92-4 is good; filed issue 683 for further work.
