### ISSUE TITLE
Could use better senders/implementors pattern matching ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#669]
As I point out [here](https://github.com/GemTalk/Jadeite/issues/208#issuecomment-566175357), I tend to  use the selector pattern (both senders and implementors) to find likely methods where I actually read the method or look at the class to know if it is the one(s) I am looking for.

It would be much more efficient (for the user) to get a list of all of the methods that match the pattern than a list of symbols that match the pattern. Offhand I don't remember the patterns that I have recently used that give back large numbers of false positives and since I've stopped using the pattern match feature, I'm not likely to generate more ... but just trust me ... it is a thing.

Getting a list back that is just a list of symbols makes it very tedious to use this tool when there are a large number of false positive symbol matches ... I have started using `browse methods containing`, instead of the pattern matches, because I at least get back a list of methods that I can sort through, rather than having to wade through all of the false positive results provided by matching symbols ...

I've put this in December 2019, becaus I don't want it ignored ...

**Comment by ericwinger** [comment]
Should have a fix for this in 3.1.0. Should improve the autocomplete seletions as well.

**Comment by LisaAlmarode** [comment]
I think this is working as designed... it's a great change if so as that was very annoying in GBS.
