### ISSUE TITLE
Add temporary switch to turn on RowanDebugger

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#67]
To make it easy for @dalehenrich to test the new debugger work from @jgfoster, we need to add a temporary switch in the gui to allow him to turn it on or off. 

Turn on:  ``RowanDebugger debuggerClass: RowanDebugger``
Turn off: ``RowanDebugger debuggerClass: JadeDebugger``

**Comment by ericwinger** [comment]
@dalehenrich @LisaAlmarode @jgfoster 

Adding a temporary switch to enable/disable the new Jadeite debugger James is working on. There is a radio button menu item in the Jadite menu on the transcript. Also, the debugger caption reflects either "New Jadeite Debugger" or "Jade Debugger". 

Added in Oscar 3.0.13
Hope this helps.

**Comment by LisaAlmarode** [comment]
Verified it's there and there are different results enabled or disabled.
