### ISSUE TITLE
Ordering of Elements in Preferences File and the Jadeite settings menu items (3.0.92)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#672]
The preferences file contains two kinds of settings: booleans that correspond to items in the Jadeite drop-down menu (one setting per), and instructions to open certain windows (multiples of any of these).  

These are currently sorted together alphabetically, and they should be sorted separately, since the alphabetic sort puts one of the boolean flags alone at the end.  Eric speculates that alphabetic would make it easier if someday we add lots more settins; but I suggest that dividing the settings into two categories, each of which is sorted alphabetically, provides a two-level lookup that would be faster and easier than looking through a single longer list.

Also, the order in the Jadeite drop-down menu and the order in the preferences file should be the same, to reduce the confusion of people who are updating their settings and double checking.  I can't see any particular logic in the current order in the jadeite menu, so I think that should be updated to be alphabetic - in case we add more preferences, they will be easier to find.

Dale, Eric would like your opinion on this...

**Comment by dalehenrich** [comment]
In general I prefer any list to be sorted alphabetically ... in my case I haven't memorized the names so I don't always know what it's name is so alphabetical sorting is as good as random sorts ... chunked groups of similar settings might make scanning a bit easier ... I have a default set of settings that I like and I copy the prefs file without looking when I install a new Jadeite, so at this point I probably don't have a valid opinion ...

**Comment by ericwinger** [comment]
My preference is alphabetic, too. I alphabetized the Jadeite menu options for @LisaAlmarode 's review in 3.0.92.

**Comment by LisaAlmarode** [comment]
The menu is fixed, but the preferences file is still wrong.  Filed this as a separate bug with specific proposal.
