### ISSUE TITLE
(3.0.91) clicking on hierarchy tab shows direct subclasses as if they have extension methods when they do not

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#674]
![image](https://user-images.githubusercontent.com/623951/71201473-f3b8f600-224e-11ea-942a-ef07db968f01.png)
There are no extension methods in `AbstractBagEnumerator`.

**Comment by LisaAlmarode** [comment]
It doesn't look at all like this in 3.2.12 and probably fixed.
