### ISSUE TITLE
Ordering of Elements in Preferences File (3.0.92)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#676]
This is the unfixed part of issue #672

This really irks me.  Besides not being able to find the lost transcript enabled, the legal values statement with is always wrong.

```
#Remove # to uncomment option. 
#legal values are either a boolean or a name

#autocommitEnabled: false
#autocompleteEnabled: false
#breakpointsEnabled: true
#loggingEnabled: false
#openBrowserOnClass: <class name>
#openBrowserOnPackage: <package name>
#openBrowserOnProject: <project name> 
#openSUnitBrowserOnPackage: <package name>
#openWorkspace: <file path without quotes or nil> 
#transcriptEnabled: false
```

I believe it ought to be:
```
#Remove # to uncomment option. 

#legal values are a boolean
#autocommitEnabled: false
#autocompleteEnabled: false
#breakpointsEnabled: true
#loggingEnabled: false
#transcriptEnabled: false

#legal values are a name (without quotes) or nil
#openBrowserOnClass: <class name>
#openBrowserOnPackage: <package name>
#openBrowserOnProject: <project name> 
#openSUnitBrowserOnPackage: <package name>
#openWorkspace: <file path without quotes or nil> 
```

**Comment by ericwinger** [comment]
Fixed per recommendation.

**Comment by LisaAlmarode** [comment]
Oh Happy Day!  Easy to find my most problem stat, transcript writes, which if on makes my system so very slow.

Minor tweak; the example I listed has my preferred default, which is 
    #transcriptEnabled: false

But the current actual default is true, so the preferences file example does not match the behavior in the image.   It would be more consistent to have:

    #transcriptEnabled: true

**Comment by ericwinger** [comment]
Got a fix for the next release ready.
