### ISSUE TITLE
Print-it for out of range characters is... peculiar (3.0.92.3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#678]
This is the unfixed part of issue #435.

If you enter ``` 'aa', (String with: (Character withValue: 353)) ``` or ```Character withValue: 353 ``` in a workspace, highlight and print-it, you get no display result, and the selected area is set to something obviously wrong. 

![image](https://user-images.githubusercontent.com/13142166/72467752-79698c00-3790-11ea-85f8-78022d38ec76.png)

**Comment by ericwinger** [comment]
Should have a fix for this in 3.0.92 prerelease 4
