### ISSUE TITLE
binding of "self" in new inspectors (3.0.92-3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#679]
If you are inspecting a dictionary, executing code in the right pane that uses "self" seems to have very disparate results.

inspecting this: ```Dictionary new at: #abc put: 'hello'; yourself```

print it (and execute it) works as expected.
inspect it gets a walkback, as if self was nil. (see right side)
debug it gets an error dialog.

![image](https://user-images.githubusercontent.com/13142166/72471841-40351a00-3798-11ea-8899-be51fa24ef4c.png)

**Comment by ericwinger** [comment]
Fixes in 3.0.92 prerelease4
