### ISSUE TITLE
The position of the walkback window (3.0.92)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#680]
As I was testing the position of the debugger, I got to wondering what caused the position of the initial walkback window.

Turns out this opens in a sequence of 14. The first one is just a bit away from the upper left of the main monitor (regardless of where and on which monitor the workspace executing the code is).  Subsequent (unrelated) walksbacks open a little down and right, for each new walkback, until it gets to #15, which is opened in the original location.

It would be nice if the walkback at least opened on the same monitor, if not having some kind of respect for the location of the workspace.

**Comment by ericwinger** [comment]
@LisaAlmarode - When you say " walkback window" are you referring to the notifier window?

**Comment by ericwinger** [comment]
Did some work on window positioning in #735. Might be worth checking this again.

**Comment by LisaAlmarode** [comment]
This issue seems to be made irrelevant by the fix for issue #741.  Now, the debugger always opens on the location of the last closed debugger, and on whatever monitor that was on.  I'm good with this.
