### ISSUE TITLE
Write out login values if "Debug GCI" is enabled

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#681]
When debugging a connection, it is valuable to see the actual parameters sent to the gci. On login, write out those values to a file, but only if the Debug GCI is enabled from the `Advanced` tab on the login window.

**Comment by ericwinger** [comment]
Fix per the issue report in 3.0.92 prerelease 4.

**Comment by LisaAlmarode** [comment]
Verified.  Note that the password is written out in plain text, which is kinda what you need for debugging but does need to be documented or noted somewhere.

I could (but won't) complain about the Debug GCI button... it has layout issues per issue #564, and also it's a bit weird to turn it off, you press it, and cancel when it asks for a log file name.
