### ISSUE TITLE
Revert of method changes leaves the change in the next changes browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#685]
If you open the Changes Browser, and revert all the method changes, and close and reopen the Changes Browser... all the changed methods are still present in the list. 

If I were using this feature to prune out changes I didn't want to commit and I had a boatload of methods (this is exactly my use case when I do work on the bug system), I would really be annoyed at not being able to get the reverted methods off of the list of changes.

See below.  I made two changes, then reverted them.  This is the reopened changes browser.

![image](https://user-images.githubusercontent.com/13142166/72646584-59220480-392b-11ea-8fbb-5e772567df65.png)

**Comment by ericwinger** [comment]
I believe this was related to #742 and should be fixed in 3.1.0.
