### ISSUE TITLE
Changes Browser Browse senders/implementors doesn't work after reverting changes (3.0.92)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#686]
In the Changes Browser, if you revert changes to add/remove/modify a method, it displays in the Changes Browser as the selector 'methodName (reverted)'

Unfortunately, the senders/implementors menu item then attempts to find selectors with the selector 'methodName (reverted)', and of course can't find anything.

Trivial side comment: it's disallowed to browser senders/implementors for a removed method.  But in theory, with a reverted removed method, finding senders/implementors doesn't need to be disallowed...

**Comment by ericwinger** [comment]
Fixed in 3.1.0 per changes in commit.
