### ISSUE TITLE
Dictionaries browser pop up menu broken

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#69]
Dialog that says: 

Error while processing error: RowanSystemBrowserPresenter does not understand #methodMenuBreak:

**Comment by ericwinger** [comment]
Refactoring in 3.0.13 broke the dictionary menus. *Should* be fixed in 3.0.14

**Comment by LisaAlmarode** [comment]
Pop in dictionaries menu now says 

Array does not understand #appendToSourceMenu:presenter:

**Comment by ericwinger** [comment]
The dictionary browser has list models which are vastly different the project browser. Sharing code between them requires a bit of extra shoe-horning to coerce those models into services. Fixed in 3.0.15
