### ISSUE TITLE
Would like to be able to open method browser on all methods in selected categories

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#693]
Just as it is useful to browse a set of selected methods, I'm finding it useful to be able to open a method browser on selected categories ...

**Comment by dalehenrich** [comment]
Bonus points if the method browser stays up-to-date with the selected protocols when a methos is added or removed from the protocol

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.93. @dalehenrich I'd like a full copy of the contest rules along with my bonus points, please. :)

**Comment by LisaAlmarode** [comment]
Either it's broken, or there's a mysterious rule that I don't know that causes the menu item I suspect implements this, "browse category methods", to become enabled and usable.  
I'm seeing it always disabled.

**Comment by ericwinger** [comment]
Enablement should be fixed in prerelease3

**Comment by LisaAlmarode** [comment]
Working in 93-3.  But it appears that the bonus points will not be awarded in this round.  At least, I see that the method browser updates the name of the category for contained methods, but I suspect the bonus feature was that methods get added and removed from the method browser. Please refer to the award terms:
![image](https://user-images.githubusercontent.com/13142166/73894547-a3fbb180-4831-11ea-973c-d15dcb83081e.png)

**Comment by ericwinger** [comment]
Now that is some fiiiiinnne print. :)
