### ISSUE TITLE
Inspector icon bar missing icon, broken option, and bubble help confusing

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#694]
- [x] The inspector icon bar fourth icon is a question mark, which is probably not the intended graphic for add object:

![image](https://user-images.githubusercontent.com/13142166/73387789-eba89900-4285-11ea-9e62-252cc1da96f5.png)

- [x] The fifth icon, the one with the little magnifying glass, gives me a walkback:

![image](https://user-images.githubusercontent.com/13142166/73387932-2ca0ad80-4286-11ea-82b3-5eed0735a205.png)

- [x] The bubble help for the forward and backward arrows say 'previous object' and 'next object', which for a collection seems very much like it would mean the previous or next object in the collection, not the parent (up) or child (down) object.  
VW uses "dive" and "back" which would be less confusing. 
This last item could be discussed and is not critical for December.

**Comment by ericwinger** [comment]
Fixed in 3.0.93. Icon problem was a bad path.
