### ISSUE TITLE
(3.0.91) finf methods containing `allusers` selects second occurrence in method

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#695]
Note that the second occurrence is selected (and that there  are three visible occurrences of the string in the method:
![image](https://user-images.githubusercontent.com/623951/73409269-a13e1100-42b3-11ea-9d98-920498b0d910.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.93. An old Jade hook on the "left key pressed" was looking for the wrong string.
