### ISSUE TITLE
Override of Association>>stonOn: should be avoided

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#698]
To support gemstone ston, it was necessary to temporarily override this method. Need a better solution if possible to avoid harsh-looking warning on Jadeite code load into Dolphin. 

```
stonOn: stonWriter
	"overriden by Jadeite. Need key value format for gemstone" 
	^super stonOn: stonWriter

```

**Comment by ericwinger** [comment]
Also, Time>>stonOn: is problematic too. 
```
stonOn: stonWriter
	"Use an ISO style HH:MM:SS representation"

	stonWriter writeObject: self listSingleton: (self asStringUsingFormat: #($: true false))
```

**Comment by dalehenrich** [comment]
@ericwinger what are the specific problems you are having ... are there existing STON messages in the newer version of Dolphin or ???

**Comment by ericwinger** [comment]
The new Dolphin version, 7.1.9, added ston support. However, the format it has chosen for a couple objects clashes with the gemstone version. The solution is easy enough. Use the older format. 

The challenge is how to override those methods in Dolphin and still get my code to load cleanly. Dolphin does not have a good way to allow an override. 

It is a client issue. I need to invent some kind of way to override Dolphin code on package load.

**Comment by ericwinger** [comment]
Not ideal, but I've added the two overrides into BootJade.st. In a development environment, that script is what loads the Jadeite code into the Dolphin image on startup.  Not an issue when stripping the runtime image as the overrides are already present in the image.

**Comment by LisaAlmarode** [comment]
Nothing to verify...
