### ISSUE TITLE
would be nice to be able get a copy the selected frame printstring

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#704]
I'd love to get the frame inform from the selected frame into the copy buffer:
![image](https://user-images.githubusercontent.com/623951/73983412-462ba000-48eb-11ea-9d2e-b43d4940196d.png)
When I am debugging a problem I take notes and often the information I want is in the selected frame ...

In generat it would be useful to be able to copy the selected item in list or the entire list into the paste buffer ...

**Comment by ericwinger** [comment]
@dalehenrich Will `Edit menu>Copy Stack` suffice?

**Comment by dalehenrich** [comment]
That's not what I'm looking for ... 

I would like to copy the selected frame in a form that I can paste into a note or a message ... to use copy stack, I would have to copy the stack, then open a an editor, then search for the frame ---- and that would entail having to hand type the very information that I am trying to avoid typing (and mistyping) 

This could be viewed as a general feature that one should be able to copy any selected item in a list- yyou and I both know that the string to be copied is lying right there underneath the surface of the window and my request is to provide simple access to the string ... that goes for package names, class names, method selectors, test selectors, etc. I am either writing a note or bug report, or I'm working with topaz ... reading code in Jadeite and then turning that into a breakpoint in topaz or ....

**Comment by ericwinger** [comment]
Fixed in 3.1.0 pre-release2
