### ISSUE TITLE
testing slack

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#709]

**Comment by dalehenrich** [comment]
> this is a comment submitted from slack
<sub>[View in Slack](https://gemtalksystems.slack.com/archives/DTBDE7DEE/p1581099363001900)</sub>

**Comment by dalehenrich** [comment]
> this is another comment
<sub>[View in Slack](https://gemtalksystems.slack.com/archives/DTBDE7DEE/p1581099363001900)</sub>

**Comment by dalehenrich** [comment]
this is yet another comment

**Comment by ericwinger** [comment]
testing

**Comment by ericwinger** [comment]
whoops

**Comment by dalehenrich** [comment]
hello slack? are you there?
