### ISSUE TITLE
Dictionaries Browser Method menu 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#71]
The Dictionary Browser and Projects Browser's methods menu has differences that are somewhat jarring; it would be nice if these were the same. 

- [x] Particularly, they should both use either Remove Method(s) ... or Delete Method(s).  

- [x] the are-you-sure-you-want-to-delete dialog is much nicer in the Projects Browser.

- [x] Also the Browser History in the Dictionaries Browser is broken.

(edited to create task list. Needed dashes)

**Comment by ericwinger** [comment]
Think these three should all be fixed in 3.0.14. The second item took quite awhile as the dictionary & projects browser didn't share code well. At least for this feature they do now.

**Comment by LisaAlmarode** [comment]
There's more that ought to be done, like a line under Browse Senders of..., and the BrowseMethod Pragmas rubs me the wrong way, but that all can wait.
