### ISSUE TITLE
Test issue for GitHub integration analysis

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#710]

**Comment by dalehenrich** [comment]
and this is a comment

**Comment by dalehenrich** [comment]
and yet another comment

**Comment by ericwinger** [comment]
> commenting on issue from GitHub/Slack
<sub>[View in Slack](https://gemtalksystems.slack.com/archives/DTBG47D98/p1581100088001100)</sub>

**Comment by dalehenrich** [comment]
> this is a comment submitted from slack
<sub>[View in Slack](https://gemtalksystems.slack.com/archives/DTBDE7DEE/p1581100356002600)</sub>

**Comment by dalehenrich** [comment]
comment from slack ... with the `view link` template commented out
