### ISSUE TITLE
Inspectors don't handle tab characters; it replaces them with '?'

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#711]
If you inspect this:
```
'a	b'
```
you get:
![image](https://user-images.githubusercontent.com/13142166/74072848-0fbe5580-49bd-11ea-9cd7-516e7ba5538a.png)

My application creates strings that are tab-delimited excel spreadsheet contents, so this could be said to break my application (or I have to specify ? as the separator character...)

**Comment by ericwinger** [comment]
Have a fix that can go into 3.0.93.
