### ISSUE TITLE
Inspect UserGlobals from Method list, get ByteArray DNE asHexString

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#712]
Say you have a method that contains a reference to UserGlobals.  You can select UserGlobal in the project browser method, and use the popup menu inspect to open an inspector on that dictionary.

![image](https://user-images.githubusercontent.com/13142166/74079260-9ab54500-49e9-11ea-9342-b537a7980f99.png)

However, if you do browse implementors on that method to bring up a method list browser and select the same UserGlobals in the same method and the same menu item...  you get this:

![image](https://user-images.githubusercontent.com/13142166/74079218-2084c080-49e9-11ea-9eac-fa18bf41ad18.png)

**Comment by ericwinger** [comment]
Got a fix for 3.0.93 ready. Wasn't passing context oop correctly. Will go into pre-release 4. 

Noticed that there were different paths to inspect an object which explains different behavior in different browser. Hopefully got that cleaned up, too.
