### ISSUE TITLE
Copy instance method to class, get walkback (3.0.93-3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#713]
Take an existing instance method, copy the contents, select the class side and a class category, and paste it as a class method.  Save.  

This gives you a walkback:
![image](https://user-images.githubusercontent.com/13142166/74099096-db3dbd00-4ad4-11ea-9504-b5600e7dee90.png)

Unfortunately when I go to copy the stack, I get this:

![image](https://user-images.githubusercontent.com/13142166/74099104-ed1f6000-4ad4-11ea-9503-481949c971c7.png)

**Comment by ericwinger** [comment]
Have a fix ready for 3.0.93pre-release4. Jadeite didn't get it's class set correctly when trying to initialize method history. Believe this was recently introduced. 

Good catch @LisaAlmarode!
