### ISSUE TITLE
A second open debugger walkback notifications wrecks the first one (3.0.94-4)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#719]
If I do ```String foo``` in one workspace, and see a notification, and don't close it.

Then I do ```String bar``` in a different workspace, and see a notification, and don't close it.

And go back to the first notification and try to debug it...  the stack is gone and I get a walkback.

![image](https://user-images.githubusercontent.com/13142166/74365985-fc780500-4d83-11ea-823e-6563de25a236.png)

I can still debug the second walkback.

**Comment by ericwinger** [comment]
The notifier dialog needed to be registered on the server along with the gs process oop.
