### ISSUE TITLE
Ctrl-B in inspector code pane broken

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#721]
Inspector code pane claims to handle `Ctrl-B` but hot key doesn't work.

**Comment by ericwinger** [comment]
Ctrl-B added to `additionalAccelerators` in inspector

**Comment by LisaAlmarode** [comment]
the debug-it should be on the menu too.

**Comment by ericwinger** [comment]
debug-it is in the `Jadeite` menu now as well. Fixed in 3.1.0pre-release3
