### ISSUE TITLE
Handle removed class references better

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#725]
If one removes a class, no help is given if the class is referenced elsewhere. At least bring up a method list browser of methods which will no longer compile, i.e. that reference the removed class.

**Comment by ericwinger** [comment]
Raises a class references message list browser as well as a dialog suggesting that the user handle references to the deleted class now.

**Comment by LisaAlmarode** [comment]
Quibble: the method list returns methods that have a symbol matching the class name, as well as methods with actual class references.  I think this is probably the most helpful result, but technically the one with the symbol will compile just fine.
