### ISSUE TITLE
On opening debugger, get walkback MNU #stackDepth (3.0.93-5)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#729]
Almost every time I go to open a debugger from a walkback notificatin, I get an error.  It's never repeatable and I think it's when I go to hit the debug too fast; I think if I take my time it's more likely to not happen.  It's making debugging very cumbersome.  
I had not seen this in previous prereleases.

![image](https://user-images.githubusercontent.com/13142166/75104945-eb20cb00-55c3-11ea-8294-adaafc443ee7.png)

![image](https://user-images.githubusercontent.com/13142166/75104948-f4119c80-55c3-11ea-8738-605c5986f4af.png)

**Comment by ericwinger** [comment]
Candidate fix in 3.0.93pre-release6. Most of work is on server. 

Problem was that the process could get gc'd before the debugger or notifier had registered it. 

Not reliably reproducable so will need thorough testing.

**Comment by LisaAlmarode** [comment]
I wasn't able to reproduce in pr6, so I'm going to call it good.  Had to fake things up a bit in my usual reproduction case, due to issue #731 so will retest again when that's fixed.
