### ISSUE TITLE
Copy stack produces un-stopable error (3.0.93-7)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#734]
Copy stack appears to be not only broken, but require at least 23 dialog closes, or hard-kill of the image, to continue working. 

![image](https://user-images.githubusercontent.com/13142166/75407469-ed3aa080-58c7-11ea-8265-97840955e1b8.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.93-8.

**Comment by LisaAlmarode** [comment]
stacks copy fine in pr8
