### ISSUE TITLE
In multi-monitor setupt, inconsistent locations for opening windows (3.0.93-7)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#735]
With three monitors, there's some choice about where to open windows.  It appears sensitive to the location of the file explorer from which jadeite was launched, but inconsistent  

If file explorer is on left-hand or the right-hand monitor, the following open on the center (main) monitor:
 - login window
 - the console
 - the Project Browser 
regardless of where the cursor or the window from which they are launched is located.

All the other windows open on same monitor as the file explorer where I launched Jadeite. 

It was disconcerting to suddenly have the debugger notifications way over the the left monitor when otherwise everything looks perfectly ordinary.  

This isn't critical, I expect it's been true for a while and I hadn't noticed.

**Comment by ericwinger** [comment]
There were three places in old Jade code that were forcibly putting the login shell, console, and project browsers to a hard-coded position. It's pretty poor style to have constants buried in the code anyway so they were removed.

Fixed in 3.1.0pre-release2. We may still need to implement a "lastPosition" type of solution for all Jadeite windows depending on the needs of the issue writer.

**Comment by LisaAlmarode** [comment]
It's now consistent, but annoying.  I don't like having to move the file explorer before I open Jadeite.  Now I have to close it down, move the file explorer, and restart jadeite so I don't have to move every single new window.

I think the windows should all be opened in a location relative to the current location of either the jadeite login dialog or the console.

**Comment by ericwinger** [comment]
You might create a shortcut on the desktop / monitor you'd like to open Jadeite in. That seems to be reasonably consistent for me. Given the various combinations & possibilities of windows & monitors available, I'm not sure I can auto code window placement and satisfy everyone. 

I would suggest we open a new enhancement issue to create a human-editable file that records the last known location & size when a window is closed. Jadeite can use that file to open new windows. It could even be the preferences file. I wasn't satisfied with the .stb file based solution that Jade used because the file was clunky to edit manually.

**Comment by LisaAlmarode** [comment]
The first window that opens should correctly open whereever file explorer is, since that's where the cursor is and what has focus.  I don't think we need to worry about exact location on the monitor.

I can't imagine opening further windows based on which monitor the cursor is on, or the monitor of whatever window currently has focus, could surprise anyone; that's how the everything else works.  

I don't care about the exact location; just the selection of which monitor to display on.  I continue to be annoyed by this.

While I don't object to a vsd-style recording, I don't feel particular interested in having that feature, so I am not inclined to open a new feature.  

If I didn't need to keep running new versions of jadeite, I wouldn't mind creating shortcuts.

**Comment by ericwinger** [comment]
> I think the windows should all be opened in a location relative to the current location of either the jadeite login dialog or the console.

I've lost track in the issue comment chain. Is this the request? If not, can you clarify the request? 
If it is the request, I think that Jadeite already does this when I can control the windows. (I'm not sure I can control all dialog boxes)  Perhaps sending me pictures or a list of which Jadeite windows are problematic would help?

**Comment by LisaAlmarode** [comment]
Here's the story line.  I have a file explorer on monitor #3, and I double click on the executable.  The login dialog opens on monitor 3.  This is expected and correct.

![image](https://user-images.githubusercontent.com/13142166/79026060-7a664b80-7b3c-11ea-95e4-25a80d414b16.png)

----

I drag the login window over to the main monitor.  Then I press the login button.  Now, I think the console should appear on the main window.  Instead, it's way off on monitor #3 

![image](https://user-images.githubusercontent.com/13142166/79026134-a97cbd00-7b3c-11ea-97f1-74c3024c477c.png)

-----

I drag the console over to the main monitor.  Then I want to open a project browser.  I use the menu item on the console.  Again, I would expect this to open on the main monitor, where the parent windows is and where focus is... but no, again out in right field.

![image](https://user-images.githubusercontent.com/13142166/79026188-db8e1f00-7b3c-11ea-9e9e-cf54639317ba.png)

**Comment by ericwinger** [comment]
Hopefully this will do what is requested. All windows will open relative to the upper left corner of the console (25@25). The transcript will open relative to the login window. Debugger continues to do it's own thing per other issues. Fixed in 3.1.0pre-release4.

**Comment by LisaAlmarode** [comment]
Yes!  Happy Dance.
