### ISSUE TITLE
nice to have `Browse selected method` menu item in debugger, too

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#740]
Often I just want a method browser for the method in the debugger and opening a big old project browser to view a single method is overkill and a waste of screen real estate...

**Comment by ericwinger** [comment]
Fixed in oscar 3.1.0pre-release3

**Comment by LisaAlmarode** [comment]
Please rename "Browse Frame Method" to just "Browse" on the debugger menu.  I believe the unadorned Browse means the project browser with or without specific method selected.

Browse Frame Method and Browse Selected Method aren't semantically distinguishable.

**Comment by ericwinger** [comment]
renamed to `Browse` in 3.1.0pre-release4
