### ISSUE TITLE
(3.0.93) Incomple revert in changes browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#742]
Over the last week or so, I've started noticing that when you revert a method (everytime?) you end up with an extra lf at the end of the method (sometimes?), so the reverted method stays modified when you look at changes again. Here's an example method:
![image](https://user-images.githubusercontent.com/623951/76169181-f252e780-6132-11ea-8408-4e984d5f1362.png)
Note that the comparison doesn't show any visible changes (nothing is highlighted) and apparently both methods have two blank likes at the end and when I write to disk the extra lf does show up at the end of the method ... the fact that this is the only change means that the revert was "imperfect":
![image](https://user-images.githubusercontent.com/623951/76169251-7dcc7880-6133-11ea-97f1-38cae83cbf5a.png)

**Comment by ericwinger** [comment]
Changes browser is on the "to rewrite some day" list. In the meantime, work around clumsy old Jade code that delimits strings with an lf during server replication. In this case, it was leaving an lf at the end old and new method sources, preventing a proper revert.  Fixed in 3.1.0.
