### ISSUE TITLE
(3.0.93) would be nice to be able to inspect the keys of a dictionary 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#745]
I've got identity key value dictionaries, so the keys are of interest and there doesn't seem to be a way to inspect the keys:
![image](https://user-images.githubusercontent.com/623951/76476968-14fa3000-63c1-11ea-9a26-e4988f387086.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0.
