### ISSUE TITLE
(3.0.93) would be nice if the "unsaved changes" dialog would include the window title in the message

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#747]
Related to #746, when I get an "unsaved changes" dialog I often have several windows that could be dirty open and my choice of whether or not I want the changes saved depends upon which window is dirty ...

The case when this happens is when I am exiting a session and all of the windows are being closed ... when I am closing a single window, I do know which window is being referred to ...

**Comment by ericwinger** [comment]
Should be ready for review in 3.1.0.

**Comment by LisaAlmarode** [comment]
The changes dialog contains the windows titles. The sum total behavior has shortcomings, see issue #773.
