### ISSUE TITLE
(3.0.93) compile errors not visilble when in full window method source view

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#751]
I got an error compiling a method in full window and while the offending symbol is highlighted, I have to guess what the error is:
![image](https://user-images.githubusercontent.com/623951/77193664-dab52080-6a9b-11ea-88b0-3a06505936b7.png)
... I **can** switch to normal method view to see the error, but I think that the error message pane should be visible ... especially if there are warnings, since the only indication that we have a warning is something showing up in the warning pane at the bottom:
![image](https://user-images.githubusercontent.com/623951/77194020-63cc5780-6a9c-11ea-8959-aba39b380e4b.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0 pre-release2.
