### ISSUE TITLE
(3.0.93) empty (invisible) debugger window?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#754]
Before:
![image](https://user-images.githubusercontent.com/623951/77488196-c0f44000-6df1-11ea-9214-a7f87e078400.png)
After clicking on `Debug`:
![image](https://user-images.githubusercontent.com/623951/77488240-dec1a500-6df1-11ea-8139-35e984ec9695.png)
So there is no debugger window that is visible, and the window picker(?) shows a blank view of the debugger (lower right). I can close the debugger with the window picker(?)...

I'm hoping that when I restart Jadeite, I'll be back in business:)

I assume that something has gone wrong with the `remembered debugger position`, but unfortunately I don't know what I did ... I've been using the debugger all day ... okay ever since I upgraded to 3.0.93, but a little while ago when I pressed the `Debug` button there was a flash (I think) and the system went into the state i'm in right now ... every debugger I open is `invisible` ... I may have clicked again when the debugger was opening, but your guess is as good as mine ...

This **is** not easy to reproduce, but it did happen, which is the point of this bug.

**Comment by dalehenrich** [comment]
I quit the Jadeite session and restarted and the debugger is still `invisible` ... a `self halt` in a workspace goes immediately to the invisible debugger ... I enclosed a picture of the STB file before I delete it and see if that helps:
![image](https://user-images.githubusercontent.com/623951/77488728-43313400-6df3-11ea-8581-29feb8e2b56b.png)
If clearing the STB file, does not repair things, I would assume that the debugger window location is being persisted? ... I'm in the middle of development and would rather not have to rebuild my stone at this moment ...

**Comment by dalehenrich** [comment]
**WHEW**, restarting the Jadeite process has cleared things up ... at least the `self halt` brings up a debugger

**Comment by dalehenrich** [comment]
... and I can debug the original issue ... so it is clearly something funky happening with the saved debugger location ... maybe we need a 'clear debugger default` menu item?

**Comment by ericwinger** [comment]
If this happens again, and you are using multiple monitors, you might try
using <Shift-Windows Key-Left Arrow>. Right Arrow works, too. 

This moves the current window one monitor to the left. Repeatedly pressing
this combination will cycle the window through each of your monitors. (You may 
also use <Windows Key-Left Arrow> which pushes the window to the edge
of the current monitor first before transitioning to another monitor.) 

Once the debugger is visible, closing it should save the last position cleanly.
Currently, that position is saved internally, but could be exposed in the
preferences file if this becomes a persistent problem.

**Comment by dalehenrich** [comment]
The invisible window occurred on my laptop inside a vm that was sized to fullscreen of the laptop ... so this event did not involve multiple monitors.

It is curious that the window showed up blank in the window picker(?) ... it implies (to me) that the window was not being displayed properly... I don't know if this would happen if the windows was being drawn outside the visible bounds of the display or if the window was being drawn inside of a zero width/hieight region ....

It might be worth mentioning that in 3.0.93, I've noticed that the project browser has a habit of stealing focus from the debugger, when I simply move the mouse over the project browser panes while the debugger is on top and has focus ... it has happened often enough for me to notice that I am not clicking the mouse ... it is the simple fact of moving the mouse over the project browser ... IIRC, it would happen when I moved the mouse over the class pane --- very distinctive boundary ...

This weird behavior was definitely occurring before the invisible debugger incident -- VERY annoying. Trying this morning I don't see this greedy behavior reproducing (of course), but I would be curious if the invisible window happened because the project browser stole focus from the debugger at a critical point in window creation and that combined with the fact that Jadeite was stashing away the debugger window origin(?)...

I distinctly remember clicking on the `Debug` button and immediately moving my mouse (over to the location where the debugger would be opened, perhaps?) and then "feeling" a flash (perhaps the project browser grabbing focus?) and voila no debugger window.

When the project browser would grab focus, it would immediately pop to the top and would have to click on the title bar of debbuger window to bring it back to the top ... which is not normal ...

Oh wait, I _can_ reproduce the focus stealing behavior. The project browser needs to be in hierarchy view ; create a debugger, then move the mouse (at medium speed)over the class pane, out of the class pane and then back in again ... the project browse will grab focus and pop to the top and then it will be necessary to select the title bar to bring the debugger back to the top again ... it seems to me that you need to trigger the little mouse over action for an obscured class name to show the full name ... when that happens the project browser will grab focus ... I also found that the project browser will grab focus from a console with workspace open ... so it seems that the flaw is in how the pop up is triggered ... I tried to get trigger the pop up in the transition from debug dialog to debugger window, but the popup seems to be sensitive to mouse speed and other things, because the popup doesn't consistently `pop up` even when the project browser is on top ...


Anyway, my guess is that the invisible debugger is more likely related to bad interaction between the project browse class name popup focus stealing than to anything else ...

**Comment by ericwinger** [comment]
> It is curious that the window showed up blank in the window picker(?) ... it implies (to me) that the window was not being displayed properly... 

I can reproduce this. If you open a notifier, it will not show up in the Windows 10 "windows picker". This happens with Dolphin notifier windows, too. Not sure much is I can do about it. 

> When the project browser would grab focus, it would immediately pop to the top and would have to click on the title bar of debbuger window to bring it back to the top ... which is not normal ...

Don't believe Jadeite does anything to have one window "steal" another without a click. Before I investigate further, can you check your Windows settings to see if you have `Activate a window by hovering over it with the mouse` clicked?  This is in the Control Panel and the path to the setting is in the title bar of the image below. 
![image](https://user-images.githubusercontent.com/36212516/78389764-2f769200-7598-11ea-966b-26af8faad327.png)

**Comment by LisaAlmarode** [comment]
This is an old bug related to dolphin and debugger, which have both many changes as of 3.2.12; closing.  New issues should be filed if similar problems occur.
