### ISSUE TITLE
SUnit browser runs test in abstract test class if more than one test class selected

### ISSUE THREAD

**Issue by martinmcclure** [ericwinger/Jade#755]
Found in 3.0.93.

Select more than one test class within the same test package. Select a test to run that is defined in an abstract test class. Run the test. The test is run in the abstract class, so if, for instance, your #setUp relies on a method that is #subclassResponsibility in the abstract class, the test will fail.

**Comment by ericwinger** [comment]
Currently, if a single class is selected, the SUnit browser runs tests in the scope of the selected class. If more than one class is selected, it runs the test within the scope of the class where the test method is defined. 

This example illustrates the challenges faced by the SUnit browser when running hierarchical tests: 
- Define classes (A1 & A2 are subclasses of A): 
A  (all test methods defined here) 
--A1
--A2
- Now, select all three classes in the SUnit browser. 

Which class should be the scope of the test run? 

My suggestion is to only select the subclass and run tests. All tests visible in the subclass's hierarchy will be displayed. 

I'm open to ideas on how this can be done better without complicating the display.

**Comment by martinmcclure** [comment]
If more than one class is selected, and a test method is legitimate in more than one class, the method should be both displayed and run multiple times, once in each selected class. Otherwise it's very time-consuming to run all tests when one has a lot of test classes.

In the case I ran into (and I think this will generally be more common) the common superclass where the test methods are defined is defined as abstract, so does not appear in the SUnit browser at all. It is never useful to run a test method in the context of an abstract test class.

But if more than one subclass of an abstract test class is selected, each method should be run in each test class.

**Comment by ericwinger** [comment]
Have a fix for this in 3.1.0 - the tests pane was converted to show the test selector as well as the test it will executed in.

**Comment by LisaAlmarode** [comment]
I think this is working - there are probably some old bugs of mine that are also fixed as I do seem to be able to get the test results I expect from various inherited breakages.
