### ISSUE TITLE
SUnit Browser does not handle duplicated test method selectors well

### ISSUE THREAD

**Issue by martinmcclure** [ericwinger/Jade#756]
Found this while testing issue 755.
If you select two test classes in the same package, and the classes each contain a test method with the same selector, the selector is listed in the methods pane twice. This seems desirable and correct. "Run all" runs both tests, which also seems desirable and correct.

However, if one of the tests passes and the other fails, both tests get marked with the same marker -- either both get the green checkmark or both get the red X. 
If you select one of the tests and "Run Selected" the result of that test will change the marker of both tests.

**Comment by ericwinger** [comment]
Fixed along with #755 should show test results properly for each inherited test in the test run. Oscar 3.1.0pre-release3.
