### ISSUE TITLE
Remove instance variables with accessors requires saving definition for each individual accessor method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#757]
This is the second part of issue #692.

If you have a class with two instance variables, each with accessor methods, 
and you want to remove the two instance variables; 
when you save the updated class definition:
  you get a dialog with a single method, 
  remove the method, 
  close the method list browser, 
save the class definition again, 
 get a dialog with a single method, 
  remove the method, 
  close the method list browser
save the class definition again, 
  get a dialog with a single method, 
  remove the method, 
  close the method list browser, 
save the class definition again, 
   get a dialog with a single method, 
   remove the method, 
   close the method list browser, 
save the class definition again, and finally the new method definition save succeeds. 

I think this ought to be be simplified.  One can work around by finding all accessor and deleting those methods upfront... but that not what I'd do normally.

What really bothers is is the window title is "Methods failing recompilation" and that s is wrong... more accurate now would be "one of an unknown number of methods that are or are going to fail recompilation"

**Comment by ericwinger** [comment]
@LisaAlmarode It seems that this is already an issue waiting on Rowan support. See #733 . 

If I am correct, please close and/or merge #733 & #757.

**Comment by LisaAlmarode** [comment]
Yes, appears to be the same as issue #733, but described as user rather than from developer point of view.  I'll close this.
