### ISSUE TITLE
Empty breakpoint browser appears to want me to save a method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#758]
I went to open the breakpoint browser.

![image](https://user-images.githubusercontent.com/13142166/78184318-21046b00-741e-11ea-8a74-8b377280b218.png)

My, is it large.  And apparently wants me to save a method.

![image](https://user-images.githubusercontent.com/13142166/78184490-704a9b80-741e-11ea-947e-c7869b79d123.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0 pre-release3
