### ISSUE TITLE
Duplicate classes pop up if a class is selected (3.1prerelease2)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#760]
Things look normal with package selected:
![image](https://user-images.githubusercontent.com/13142166/78193264-fa9afb80-742e-11ea-976c-6dfc2a34b00d.png)

And I select a class: oops, there are two:
![image](https://user-images.githubusercontent.com/13142166/78193287-04bcfa00-742f-11ea-8e61-2eaa669951e0.png)

and another class; two duplicate classes
![image](https://user-images.githubusercontent.com/13142166/78193323-1bfbe780-742f-11ea-818e-61ed876c9de4.png)

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release3. Make sure we don't add class twice when updating the class list.
