### ISSUE TITLE
Debug-it in debugger / missing menu item, failure on up arrow, and error dialog (3.1pr3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#762]
Say I have a breakpoint in a method called by a test method, run the test, and get a debugger. 

Then, I select some code in the method and want to do a debug-it.  

(1) the popup menu does not include the Debug item, although it's in the Edit menu.  The shortcut does work.

![image](https://user-images.githubusercontent.com/13142166/78413430-34edcf80-75cc-11ea-9232-bee21aa1cdd0.png)

(2) if I try to get to the edit menu and hit the immediately below debugger up arrow by accident, I get an error

![image](https://user-images.githubusercontent.com/13142166/78413633-25bb5180-75cd-11ea-9053-54c0ab5a92bb.png)

When I finally can do a debug it, I get a second RowanProcessService.  
So far so good.  In this second service, I do a run (horizontal arrow), since I want to get out of where-ever I am. 

(3)  This gives me an error dialog:
![image](https://user-images.githubusercontent.com/13142166/78413312-ae38f280-75cb-11ea-89c3-594209c0b80d.png)

**Comment by ericwinger** [comment]
I've got (1) working in pre-release4. However, (2) & (3) seem to be code specific. Can you post the code you were debugging as well as the frame you are on when getting this error?  And also where you had the breakpoint which was hit in (3)?

**Comment by LisaAlmarode** [comment]
(2) and (3) are not code specific for me, running as DataCurator in PR3.  

Try putting a breakpoint on the assert: in RowanSample1Test >> test1.  
Run the test (from Sunit tab); let the debugger open, then press the up arrow.  See error.  

You'll have to close the debugger and run test again. This time highlight "RowanSample1 new foo" and debug-it (from the edit drop down menu).  Then press the run button and see error.

**Comment by ericwinger** [comment]
> Try putting a breakpoint on the assert: in RowanSample1Test >> test1.
> Run the test (from Sunit tab); let the debugger open, then press the up arrow. See error.

Still not seeing error.  By default the Process list pull-down combobox is the focus subview. So the up arrow key will operate on that list. Can you manually pull down that down so I can see what's in it? 

Note - when I do up/down arrow, it rotates through the different processes correctly. Here's what my list looks like. 

![image](https://user-images.githubusercontent.com/36212516/79010167-437d3f00-7b16-11ea-8317-329424cf43d5.png)

**Comment by LisaAlmarode** [comment]
Did you try as DataCurator?

When I run as SystemUser I don't have a problem either.

**Comment by ericwinger** [comment]
DataCurator works ok for me. I suspect it's related to a variable in a process you're switching to. 

What does your process list look like when it fails?  
Also, can you send me an entire screen shot of your debugger + error dialog when it happens?

**Comment by LisaAlmarode** [comment]
Update: the problem does only seem to happen if I have more than one process in the drop down list.  So it might not happen in a fresh image.  After I've run tests in the debugger and closed tests I get a second process and that's when the up arrow button becomes entirely broken.

Isn't the up arrow supposed to bring me up in the process stack?  the help says top of stack.  the current process is the top of the list.... I wouldn't think it would move me to a process lower on the list? 

With a process list of size > 1, execute `String foo` and open the debugger on the notification. Press the up arrow:
![image](https://user-images.githubusercontent.com/13142166/79402526-00b9cd80-7f41-11ea-9a72-371f4fcf711d.png)

press OK:

![image](https://user-images.githubusercontent.com/13142166/79402538-0b746280-7f41-11ea-8a5e-996dcc579e5d.png)

and the process list:

![image](https://user-images.githubusercontent.com/13142166/79402549-129b7080-7f41-11ea-826d-d2049ff2af51.png)

**Comment by ericwinger** [comment]
The underlying problem was that an old-school GsProcess was being used instead of a RowanProcessService. That created problems when sorting the variable list pane. Fixed in 3.1.0pre-relesae5.

**Comment by LisaAlmarode** [comment]
Not fixed in pr5.  

The act of clicking on the up-arrow appears to be turning innocent RowanProcessServices into GsProcesses.  

Get my debugger, see dropdown of RowanProcessServices:

![image](https://user-images.githubusercontent.com/13142166/79810483-0ab84380-8328-11ea-8385-117a41917f6f.png)

click on the up arrow, have problems:

![image](https://user-images.githubusercontent.com/13142166/79810507-160b6f00-8328-11ea-859e-086ced9a6958.png)


(I'll skip the second error dialog)

Then:

![image](https://user-images.githubusercontent.com/13142166/79810459-f5431980-8327-11ea-8a2f-817df5041d18.png)

**Comment by ericwinger** [comment]
I'm not seeing GsProcesses appear. 

Notes: 
- When I first open the debugger, clicking up arrow now moves to the next frame, not process. 
- When I open the process list and arrow up/down, I see no change. 
- I'm creating processes using this code
```
25 timesRepeat: [[(Delay forSeconds: 30) wait] fork].
(Delay forSeconds: 5) wait. "get em started"
```

Question: 
- @LisaAlmarode Would it be better to change the print back to a GsProcess for clarity when this bug is fixed? I'm inclined to think so.

**Comment by ericwinger** [comment]
I believe I have the fix for GsProcess's fix. It was a bit invasive so some extra emphasis in testing process list switching and termination would be appreciated. Ready for testing in 3.1.0pre-release6

**Comment by LisaAlmarode** [comment]
I don't get problems on arrow-up, which is good!  Still the maddening list of RowanProcessServices.
