### ISSUE TITLE
Breakpoint browser text pane not refreshed on method disappear (3.1pr3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#763]
If you remove all breakpoints from a method, the method is removed from the left side pane of the breakpoint browser. 

However, the method itself remains in the text pane.  This may or may not be a feature.

The right side text pane popup menu does allow you to re-add the breakpoint you just cleared (it allows you to enable it, not set it).  However, the popup menu here is not updated with the step point that the mouse is over, it always is asking me about step point 2.

If leaving the method here is a feature, you should have a normally functioning popup menu so you can set a breakpoint anywhere in the method.

**Comment by ericwinger** [comment]
This was, in fact, a feature.  I couldn't decide if removing a breakpoint should make your method disappear completely as it is jarring even though it is technically correct. It would be cleaner to make the method source disappear completely.  What would you prefer?

**Comment by LisaAlmarode** [comment]
I can see value in keeping the last method text there; but in that case the popup menu needs to be fixed, so it works as if there was no breakpoint in the method... then you could add a breakpoint whereever you wanted.

I'm okay with the method text disappearing completely, which is easier and perhaps less fraught.

**Comment by ericwinger** [comment]
Method source disappears after last breakpoint removed. This is a cleaner solution. Fixed in 3.1.0pre-release4.
