### ISSUE TITLE
Debugger dropdown RowanProcessService (3.1 pr3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#767]
Above the stack, there's a drop down with RowanProcessService that I usually ignore.  But the scrolling issue has brought it to my attention.

- [x] If you set focus on the debugger, but don't select a method in the stack, the focus is on the RowanProcessservice drop down, and a down-scroll will bring you to an inscrutable stack.  Default focus should be anywhere else!

- [x] As I do testing, my drop down has grown and grown and the debugger is getting slower and slower to open and finish painting.  It's up to say 7 seconds now which is at the annoyance level. I usually use the windows upper-left box to close the debugger when I'm done; I expect this isn't terminating something.  

![image](https://user-images.githubusercontent.com/13142166/78711962-b4c9b180-78cc-11ea-8819-bc2a047a8fae.png)

**Comment by ericwinger** [comment]
Initial focus is set on the stack list now. Much more useful. 

Regarding checkbox #2 ... I created lots of processes that didn't do much to test if building the debugger was slow because of the number of processes. I didn't see any delay opening the debugger with this code running in the background: 
`1 to: 50 do: [:idx | [30 timesRepeat: [(Delay forSeconds: 1) wait]] fork]`.  

It's possible one or more of the processes you've started is doing something unexpected. If I recall, server processes only run when a gci call is active. Hence the need for the old gbs load balancer code. (Or whatever it is called). Is it possible one of your processes is getting activated when the debugger is getting built, thus making the debugger take longer to open?

**Comment by LisaAlmarode** [comment]
The performance impact is serious.

I'm not doing anything with processes myself, my code is pretty simple and contains neither forks, knives nor spoons.  The various processes in my stack (currently there are 7 besides the MNU that the debugger is for) all have stacks like this:

![image](https://user-images.githubusercontent.com/13142166/79404293-17aeee80-7f46-11ea-9458-959330a9b44d.png)

**Comment by ericwinger** [comment]
Server only fix should speed up debugger opening when many background processes are running. Available in 3.1.0pre-release5. 

Here's some example code to run before / after fix: 

Run this first to get 25 processes going. Then open a debugger on `1 zork`.  Should see a big performance win. 
```
25 timesRepeat: [
	[| time | 
	time := (Random new next * 100) ceiling. 
	(Delay forSeconds: time) wait] fork].
(Delay forSeconds: 5) wait.
```

**Comment by LisaAlmarode** [comment]
The performance is MUCH better.  However, that's not really a fix, although it makes the consequences much less dire.

What causes the leftover RowanProcessService instances to get stuck in the environment and never go away, is when I have a breakpoint in code in or called by an sunit test; run the test and instead of doing anything in the debugger, I close it using the upper right title bar x icon.

This doesn't need to be fixed for 3.1 but it's an open issue

**Comment by ericwinger** [comment]
Original issue report:
> As I do testing, my drop down has grown and grown and the debugger is getting slower and slower to open and finish painting. It's up to say 7 seconds now

Comment after performance is improved:
> The performance is MUCH better. However, that's not really a fix,

Uhhhh, the problem was performance. How can improved performance not be a fix?

**Comment by LisaAlmarode** [comment]
Well, I believe that the problem is that there are excess RowanProcessServices.  They ought to not be there, I assert.  It's great that these guys are now not making things very slow is great, and it means it's not urgent, but it doesn't fix the problem that they exist.  You can close the closet door and not see the mess, but that doesn't mean the closet is cleaned up...

**Comment by ericwinger** [comment]
Sounds like this is an omnibus bug. As I've suggested before, it's best to focus the issue as narrowly as is reasonable to avoid confusion & complications. This sounds like it should have been two issues. 

Do you want the extra processes to go away when the process finish?  If so, that's a behavior change in the debugger. The debugger doesn't update on the fly as that can be disturbing when you are debugging a stack. Therefore, it doesn't update the process list except when the debugger is opened.

**Comment by LisaAlmarode** [comment]
My guess is that when the debugger is closed after a breakpoint is encountered, it's not cleaning up after itself, which may be the same sort of cause as issue #768.  
Users define bugs by symptoms, engineers define bugs by causes; a cause may have multiple symptoms and there may be multiple ways to fix a single symptom.  I try... but it's hard enough to figure out what people did, never mind what they are going to do...

**Comment by LisaAlmarode** [comment]
Haven't been seeing this lately, so optimistically closing.
