### ISSUE TITLE
(3.0.93) highlighted compile error message is not selected

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#769]
When I see the following in a workspace, I am inclined to hit `backspace` to delete the error message, like I would with any other selected text:
![image](https://user-images.githubusercontent.com/623951/78932419-4b78a880-7a5c-11ea-89f2-2fa040922e5c.png)
However, the `backspace` does not work and it seems I have to explicitly select the error message get rid of it ...

**Comment by LisaAlmarode** [comment]
Compile errors now show up in the status bar, so no backspace required.
