### ISSUE TITLE
Remove "delete" menu item from pop up method edit menu (PR4)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#771]
This menu item works differently in the project browser method pane and the method list method pane.  It's also kind of pointless - I am a menu user and often copy and paste with menus but delete has a key on my keyboard. I suggest this open be removed rather than bothering to make the behavior consistent.

This is a leftover from issue #583.  Not very important.

**Comment by LisaAlmarode** [comment]
As of 3.2.12, delete doesn't work on the popup in the method text in the project browser, and is disabled in the method text of a method list browser.  I think worth cleaning up for release.

**Comment by ericwinger** [comment]
Removed Delete's from browser's Edit menu and method browser source pop-up menu.  Let me know if there are more extraneous menu items cluttering up the menus.

**Comment by LisaAlmarode** [comment]
The popup menu for the PB Class Definition tab and ReadMe tab have extraneous delete items.

I believe the ReadMe is also missing the save option.  It's confusing, since there's no option allowing you to save, but control-S does seem to work to save this and appears to generate a README.md in the project root.  This probably needs to be in Jadeite help.

**Comment by ericwinger** [comment]
Tweaked per last comment - removed delete menu items and added save.
