### ISSUE TITLE
Disable Browse* debugger frame list menu options if method not visible

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#774]
Per https://github.com/GemTalk/Jadeite/issues/765, disable debugger's frame `Browse` menu options if method isn't visible to the user. 

The use case is to try browsing the upper frames of a server stack using services, say a method on `RowanAnsweringService`.

**Comment by rjsargent** [comment]
I don't understand why preventing browsing is the desirable behavior here. You do have the method object and therefore the class object. They could be browsed.

**Comment by ericwinger** [comment]
@rjsargent Yes, they could be browsed but not for 3.1.0.  It's a fair bit of work to make the browsers handle all the nuances of code that's not visible. See this comment. https://github.com/GemTalk/Jadeite/issues/765#issuecomment-614317314

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release5. Re-enablement will be when #765 is fixed & browsers can handle non-visible code better.

**Comment by LisaAlmarode** [comment]
I agree with deferring making this work correctly, I think that is outside the scope of this bug, I just don't like error dialogs.   I think we need a separate bug for the future work.

As for this bug:  If I double click on one of these lower methods in the list of frames, I do still get an error.  It would be nice to close this hole. 

![image](https://user-images.githubusercontent.com/13142166/79809554-9f6d7200-8325-11ea-8ec0-52d4b4310808.png)

**Comment by ericwinger** [comment]
The failure I found was with a class method. Similar to one of the problems in #765 https://github.com/GemTalk/Jadeite/issues/765#issuecomment-613693480.  If there is a further problem, please provide the stack & stack frame to aid debugging.

**Comment by LisaAlmarode** [comment]
Did you miss that this was only for attempting to browse using double-click?  

You did fix this issue for the browse menu item, that is now disabled.  But the double-click performs a Browse and runs into the same problem.

Since this bug was only for the browse menu item, perhaps I should file a separate bug?

![image](https://user-images.githubusercontent.com/13142166/80014812-b2975380-8485-11ea-902e-8bc73445c585.png)

**Comment by ericwinger** [comment]
Yes, I did notice it was only for double-click. And, after trying every frame in the stack I found that the class side methods failed. So I fixed that. The example that you provided doesn't fail for me. https://github.com/GemTalk/Jadeite/issues/774#issuecomment-617929130

**Comment by LisaAlmarode** [comment]
I don't see any class methods in my typical example, which very reliably always triggers an error and leaves an PB around.  

![image](https://user-images.githubusercontent.com/13142166/80126832-5d704600-8548-11ea-8233-2eea0f5b7ee1.png)

**Comment by ericwinger** [comment]
I was able to reproduce and have a fix in 3.1.0.
