### ISSUE TITLE
SUnit browser updated with lists of classes without updating the package selection (3.1pr4)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#776]
I opened an SUnit browser and didn't select any packages. So column 2 and 3 are empty.

Left that to one side, I opened the project browser and selected a test class and saved a method. 

Suddenly, the Sunit browser has a list of the test classes in my current package in the PB... and since there is no package selected, they are purple.  

In the project browser, if I now go a different project and package and select a test class and remove an method - the middle pane of the SUnit browser now has all the test classes in the first package PLUS all the test classes in the second package.  All purple.

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release5
