### ISSUE TITLE
Method list browser pane does not turn green on edit (3.1 PR4)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#777]
In the method list browser, you can start editing a method and it doesn't turn green until you mouse click. 

It's working correctly in the project browser.

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release5

**Comment by ericwinger** [comment]
Fix seems to cause an issue with method source reverting. Re-opening for investigation.

**Comment by ericwinger** [comment]
Wasn't accounting for changed source pane views and updates were coming more frequently for method list browsers. Should be fixed in pre-release5 again.

**Comment by LisaAlmarode** [comment]
I am still seeming some problems, both in the project and method browsers.

If you delete an empty line partway through a method, it does not turn the pane green.

**Comment by ericwinger** [comment]
I dont' see this. 
Project Browser Before: 
![image](https://user-images.githubusercontent.com/36212516/79895707-253bfc80-83bc-11ea-8495-24c738e96ab5.png)
After:
![image](https://user-images.githubusercontent.com/36212516/79895732-338a1880-83bc-11ea-952e-072ddb59b3af.png)

Method list browser before: 
![image](https://user-images.githubusercontent.com/36212516/79895830-5e746c80-83bc-11ea-8d38-0f5f2bdc77a7.png)
After:
![image](https://user-images.githubusercontent.com/36212516/79895873-6fbd7900-83bc-11ea-93bb-906fbf2f31ea.png)

**Comment by ericwinger** [comment]
wrong button

**Comment by ericwinger** [comment]
Dolphin doesn't seem to handle some keys correctly. For example, if press Ctrl-X, it cuts but does not seem to run the `editCut` method defined in the gui. If you use the menu option (with accelerator key defined) it will run that method. In the case of #777, I  think the user was pressing the `Del` key which seems to not run smalltalk code but only windows vm code and also doesn't update the text view's model. Regardless, I added some hooks to handle changes to the view's text even with updatePerCharacter turned on. Yuck.

**Comment by LisaAlmarode** [comment]
Not fixed for pressing delete key in project browser (nor in debugger, for that matter).  

Delete key does make pane green in method browser so you must be on the right track.

**Comment by ericwinger** [comment]
Same fix as for method list browser. Should be fixed in pre-release7.
