### ISSUE TITLE
Unsaved changes dialog is missing option to cancel

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#781]
I closed an inspector that I didn't want to close, by blindly clicking on the righmost button.  Turns out I expect that to be a cancel.

I did a quick survey of applications that I use and universally if you have unsaved work, you get three buttons: save, discard changes and close, and cancel.

akelpad
Save changes to document <filename> before closing?
[Save] [Close without saving] [Cancel]

libreoffice
Document was modified. Do you want to save it?  
[Yes]  [No]  [Cancel]

ms office
Want to save your changes to <filename>?
[save]  [don't save]  [Cancel]

adobe frame
Unsaved Changes in File: <filename>.  Save before closing?
[Yes]  [No]  [Cancel]

thunderbird
Save this message to drafts?
[Save]   [Discard changes]   [Cancel]

**Comment by LisaAlmarode** [comment]
Adding to to-do for first release, since there's a risk of losing work.

**Comment by LisaAlmarode** [comment]
**All windows with text panes**
- [x] the meaning of the button on the right be that you do not close the window and lose your work.  The right should also be the default. This is true for inspectors and non-inspector windows such as workspaces and project browsers.

- [x] Depending on the options to change button labels, the dialog's question may need to be rewritten, such that the label of the right button means continue to edit and not close. 

**Windows with textpanes that are not workspaces (inspectors and browsers)**
- [x] Windows with textpanes that are not workspaces (inspectors and browsers) don't need a save button; while the pane has a save option so save is a possible action, it could be confusing and you should probably have to go back and make a specific save decision.  So these should continue to have only two buttons, but the right button must have the effect of continue to edit and do not close.

- [x] Ideally, the buttons read [Discard changes] **[Cancel]** (or other options TBD) but for first release, we could live with yes/no or no/yes if the dialog question is worded clearly.

**Workspaces/File editors**
- [x] Workspaces ought to have three buttons, with the location and behavior as is common in windows applications (save and close, discard changes and close, continue editing).  This is not necessary for first release.

- [x] Ideally, the buttons read [Save] [Discard changes] **[Cancel]**  (or other options TBD)

**Comment by LisaAlmarode** [comment]
As I've been testing the fonts in the preferences dialog, I KEEP expecting to be able to just close the window and answer yes to the question do you want to save your changes.  Over and over and over. Every time I have to cancel and then open a menu item to save. Thus, increasing the complaint level.

**Comment by ericwinger** [comment]
Have a fix for this. Button names are Yes/No/Cancel or Yes/No as the native windows dialogs are used. Question adjusted accordingly. Needs time and development work to flush out bugs.

**Comment by LisaAlmarode** [comment]
I like the workspace three-buttons.  This made sense to me. Thank you!

However, the "Really exit?" does not work.  Especially when I'm in a browser and click on another method, it sounds like it's going to close the browser, and I have to think about what exit means. "Discard changes and continue?" would be both clear on what I'm saying yes to, and not make me wonder if it's going to do something other than I'm trying to do.

**Comment by ericwinger** [comment]
Changed per suggestion. 
![image](https://user-images.githubusercontent.com/36212516/214949420-6c5baccd-54c8-4c4a-a438-1055ea2e59f4.png)
