### ISSUE TITLE
(Oscar-3.1.0) 3.6.0 libraries not included?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#784]
The GemStone version drop down is missing 3.6.0:
![image](https://user-images.githubusercontent.com/623951/80543371-92730300-8963-11ea-8399-6327b9aa2246.png)

**Comment by LisaAlmarode** [comment]
your title bar implies you're running 3.0.71?

**Comment by dalehenrich** [comment]
I.m clicking on my 3.1.0 shortcut ... I'll see if I created the shortcut in the wrong directory..

**Comment by dalehenrich** [comment]
The shortcut is from my 3.1.0 directory ... I'll redownload the runtime.zip

**Comment by dalehenrich** [comment]
![image](https://user-images.githubusercontent.com/623951/80543995-f518ce80-8964-11ea-8e4f-a5f9da54c6d1.png)
![image](https://user-images.githubusercontent.com/623951/80544065-15e12400-8965-11ea-8fd6-434539bcd2e9.png)

I think the runtime.zip file that was uploaded to github is wrong ...

**Comment by ericwinger** [comment]
Hmm, not sure what happened.  Just recut the runtime.zip.  It shows the proper 3.6 library & `jadeite.exe`.  If this fixes the problem, please close the bug, @dalehenrich.

**Comment by ericwinger** [comment]
Speculating on what might have happened for future ... For whatever reason, `.gitignore` refuses to acknowledge that I want to ignore `runtime.zip` in my Jadeite git directory. Been this way forever.  Every time I cut a new runtime, I have to remove that change from my dirty git directory or commit another version. I may have cleared that change before I dragged the file into the Assets of the release.

**Comment by dalehenrich** [comment]
runtime.zip is working now ... picked up the 3.1.0 executable and 3.6.0 present. Thanks!
