### ISSUE TITLE
(Oscar-3.1.0) some extra files in runtime.exe

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#785]
I believe that the STB file and `call trace log` file are extraneous files:
![image](https://user-images.githubusercontent.com/623951/80543478-cd753680-8963-11ea-8224-ef04c360d895.png)

**Comment by dalehenrich** [comment]
..these extra files are still present in the updated runtime.zip file ... just a cleanliness issue, no bad side effects.

**Comment by LisaAlmarode** [comment]
I've looked at the runtime.zip for the release (https://github.com/GemTalk/Jadeite/releases, click on runtime.zip) and today there no extra files within the zip.

**Comment by dalehenrich** [comment]
Yeah, those extra files seem to randomly appear in a release ... this time they were present because the wrong zip file had been uploaded:)
