### ISSUE TITLE
(Oscar-3.1.0) Duplicate variables in nested blocks in debugger

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#788]
This is a view of the debugger with the outermost method context selected (no duplicate variables):
 ![image](https://user-images.githubusercontent.com/623951/80623205-b5062a00-89fe-11ea-9e42-9c8307ce23a8.png)
and here is a shot with an inner block selected and it seems that all of the duplicated names are from the block temps:
![image](https://user-images.githubusercontent.com/623951/80623780-8f2d5500-89ff-11ea-86d5-6d8a4674d463.png)

**Comment by LisaAlmarode** [comment]
I have confirmed that this reproduces with candidatev2.0 and 3.6, but not in 3.1.0 with 3.2.1.5.  

The given example reproduces easily in candidatev2.0 and 3.6.

**Comment by LisaAlmarode** [comment]
Trivial cases look fine in 3.2.9
