### ISSUE TITLE
(oscar 3.1.0) Frozen project browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#789]
At some point during my debugging session, the project browser has become disfunctional. Not that the GemStone64 project is selected, but the packages are from the Rowan project which was perviously selected:
![image](https://user-images.githubusercontent.com/623951/80625428-09f76f80-8a02-11ea-81f6-f937b7dc5106.png)
I first noticed the freeze because the slider bar in the package pane would move, but the list of packages would not scroll ... The debugger itself still appears to be functional ... If I close the debugger, the project browser begins working again.

Bringing the debugger up again does not immediately cause the project browser to freeze, so I guess it will be "good luck reproducing the issue" and "cross our fingers that it either happens frequently (so it can be fixed) or never happens again".

It is worth noting that I am doing this work in 3.6.0 image from a private build. It is also worth noting that I have been using 3.0.93 in a similar environment for several weeks.

There is no error file present.

**Comment by dalehenrich** [comment]
I am doing a lot of debugging/development today and I am continually hitting this issue ... I cannot use the project browser if the debugger is open, which is quite a serious issue and it is definitely hindering my ability to use Jadeite.

**Comment by dalehenrich** [comment]
As a data point, I've found that if I drag the debugger window around on the screen the project browser becomes momentarily active and updates ... the sequence is:
1. discover project browser is unresponsive with debugger open
2. select a method (with no effect)
3. drag debugger around
4. method becomes visible, but project browser is still unresponsive
Hopefully this will help you isolate the problem ... and yes this is happening pretty regularly

**Comment by dalehenrich** [comment]
Another case of image frozen Jadeite with open debugger (3.2pre-release7). You can see the debugger underneath the project browse and I have to use taskmanager to kill, since whole process frozen.
![Screenshot from 2022-07-14 16-16-45](https://user-images.githubusercontent.com/623951/179116788-7abefe12-f748-4e9f-a80c-b108b2928d74.png)

**Comment by ericwinger** [comment]
If you can come up with a reproduction case, I would be most appreciative. It's been an elusive bug to fix.

**Comment by dalehenrich** [comment]
At the moment it seems to me that if I open a debugger and leave it open then go about doing development, I eventually hit the problem ... in fact at the moment there are a couple of tests that I've been running and debugging patterns that pretty much cause a problem almost immediately (at least that was the case yesterday before I "left the office") ... perhaps we can screen share today sometime and you can watch me while I attempt to reproduce the bug and if successful, you should be able to reproduce it by logging into my stone ... and then we can go from there (with fingers crossed)

**Comment by dalehenrich** [comment]
... it took a couple of minutes, but I think I've got the formula for creating a hang ... so we should be able to create the problem in your dev environment ...

**Comment by ericwinger** [comment]
Note - Jadeite 3.2.8 will have a possible fix

**Comment by LisaAlmarode** [comment]
Eric should verify if this was in fact fixed in 3.2.8 and close.

**Comment by ericwinger** [comment]
This, likely, is part of the debugger freeze problem that was fixed in https://github.com/GemTalk/Jadeite/issues/927. Closing.
