### ISSUE TITLE
(3.1.0/3.0.93) bottom of Changes browser extends beyond bottom of visible screen

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#790]
Changes browse has to be resized in order to be able to see the full extent of the window in my vm:
![image](https://user-images.githubusercontent.com/623951/80628376-1d0c3e80-8a06-11ea-96b8-d7ec9880a160.png).
I observed this behavior in 3.0.93, but waited for 3.1.0 to see if it had improved.

**Comment by ericwinger** [comment]
Fixed in 3.2. Changes browser is about the same height as the project browser now.
