### ISSUE TITLE
MNU #asUppercase in method browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#794]
Here's the error:
![image](https://user-images.githubusercontent.com/623951/80636451-5ba7f600-8a12-11ea-8382-e7530ac93dae.png)
here's the stack:
[stack.txt](https://github.com/GemTalk/Jadeite/files/4554020/stack.txt)
and when I went to the project browser and multi-selected the two methods, the obscured method browser refreshed (automagically) and in the background you can see that the source panes are no longer empty ...
![image](https://user-images.githubusercontent.com/623951/80636969-1a641600-8a13-11ea-8367-b523a4243472.png)
and indeed the error was magically repaired

**Comment by dalehenrich** [comment]
Another occurrence:
![image](https://user-images.githubusercontent.com/623951/80639527-002c3700-8a17-11ea-99bb-cb68cf651633.png)
Not sure what is triggering this problem, but it didn't take long to hit it again ... reselecting the method in the project browser, seems to have unlocked the method browser ...

**Comment by LisaAlmarode** [comment]
Based on the stack it looks like a premature GC issue; hopefully things have improved during the changes over the last couple of years; closing, file new issue with fresh stack if problem still occurs.
