### ISSUE TITLE
(3.0.93/3.1.0) in method browser clicking off of selected method to revert changes ends up with a region select

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#795]
I had forgotten that in 3.1.0 there is a revert menu item, but if you do click off of a method and then elect to not keep changes, you get this annying region select, which requires an extra click before getting back in business:
![image](https://user-images.githubusercontent.com/623951/80640331-1a1a4980-8a18-11ea-8dba-7d8d3f30fdbc.png)
this probably shouldn't happen, but **is** less critical now that there is an offical way to revert a method ...

**Comment by LisaAlmarode** [comment]
This is reliabley reproducible in 3.2.1.5... I've seen intermittent purple area selection and been annoyed which may or may not be the same.

**Comment by ericwinger** [comment]
This turned out to be a bug in Dolphin 7.1.9. Upgrading to the latest release, 7.1.14, fixed the problem.
