### ISSUE TITLE
(3.1.0) MNU #asString after `browse test method`

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#796]
Here's the shot:
![image](https://user-images.githubusercontent.com/623951/80647968-2f957080-8a24-11ea-89f5-e52683fbe6de.png)
here's the stack
[stack.txt](https://github.com/GemTalk/Jadeite/files/4554644/stack.txt)

**Comment by dalehenrich** [comment]
reselecting the class and test method allowed me to finally open the method browser

**Comment by LisaAlmarode** [comment]
Eric should take a look at the stack and see if there's anything to be gleaned; otherwise, absent a reproduction case or further reports from Dale, this could be closed.

**Comment by ericwinger** [comment]
This appears to be a case where the method service class name wasn't set properly. In the time since this bug was reported, improvements were made to ensure the method service in the test browser has the correct class name set before the method list browser is opened.
