### ISSUE TITLE
(3.1.0) hung Jadeite process

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#797]
I believe that I clicked the close button on the inspector and now the whole process is hung:
![image](https://user-images.githubusercontent.com/623951/80662780-f8848680-8a46-11ea-9f39-40b85a579f11.png)
I'm going to have to kill the process to move forward ... thank god for auto commit

**Comment by dalehenrich** [comment]
This is a case similar to #746, in that I was probably prompted (or should have been prompted) to keep changes and I would have answered no ... only this didn't happen during image shutdown  ... It's also worth noting then I was in a phase where I did the same operation (close a dirty inspector) several times in a row, before the the image hung

**Comment by dalehenrich** [comment]
hung again ... got `invalid session`, clicked okay the project browser closed and perhaps another and then froze. The window on top appears to be the workspace tab of the console and it would not have been saved, so Jadiete froze before/while bringing up the `save` dialog:
![image](https://user-images.githubusercontent.com/623951/81728121-ce679700-943e-11ea-8a96-091775439958.png)

**Comment by LisaAlmarode** [comment]
This bug is old enough and there are enough changes to 3.2.12, dolphin, and 3.7 that I'm closing it.  File new bugs if there are still similar hanging cases.
