### ISSUE TITLE
(3.1.0) disabled step over and step into icons in debugger

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#798]
If you notice, the cursor is over the step over button, but the button is not highlighted and that means that the icon button doesn't work ...
![image](https://user-images.githubusercontent.com/623951/80663630-616cfe00-8a49-11ea-9e8f-2416a575d264.png)
I've had this happen to me a couple of times today..... and using the Debug menu items doesn't appear to reenable the icons when they stop being enabled

**Comment by dalehenrich** [comment]
bumping this one to critical ... happens pretty much randomly, but today it seems like every third debugger comes up with the icons disabled and using the menu to step is VERY annoying...

Assigning this to @LisaAlmarode so that perhaps work on this particular bug can be prioritzed

**Comment by LisaAlmarode** [comment]
Hopefully this has not been sitting around for 2 years still critical!  Reassign to @dalehenrich for updated status, and more information on reproducing it.

**Comment by LisaAlmarode** [comment]
Close as old.
