### ISSUE TITLE
(3.1.0) frozen debugger

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#802]
debugger is frozen ... not updated and clicking on different frames doesn't change state:
![image](https://user-images.githubusercontent.com/623951/80893573-6bc90b00-8c88-11ea-8dc1-b553e8efb457.png)
resize debugger causes the method pane to refresh, but the frame list is still not updating:
![image](https://user-images.githubusercontent.com/623951/80893589-94e99b80-8c88-11ea-98c8-49ce028564a6.png)

**Comment by dalehenrich** [comment]
Hit frozen debugger for the second or third time today ... creates a real break in development flow when you have to restart image to continue with your next thought ... I was closing debugger so I could edit code in the project browser without freezing the project browser (#789)... when debugger freezes I have to kill and restart Dolphin

**Comment by dalehenrich** [comment]
hit frozen debugger again ... killed image start over ... unsaved method in progress lost

**Comment by dalehenrich** [comment]
hit frozen debugger again ... this time I had modified a method and then clicked on another frame ... a dialog should have come up, so I'm suspicious that something in the debugger is blocking the creation of the dialog and or processing windows events in some way ...

**Comment by dalehenrich** [comment]
image froze again with open debugger and a `dirty` inspector, so again a dialog was expected with debugger open and the image is frozen:
![image](https://user-images.githubusercontent.com/623951/84545408-12ef8800-acb4-11ea-9fde-8dffb70d90b0.png)

**Comment by LisaAlmarode** [comment]
Much work on debugger hangs has been done leading up to 3.2.12; please file new bugs if there are still hangs.
