### ISSUE TITLE
Preference to adjust font size (3.1.0)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#805]
It is likely that someone would want to adjust their font size for:
  (1) all fonts everywhere (system and code), 
  (2) have that be persistent across restarts of Jadeite.  
  (3) have it be fairly easy to change, so e.g. you could adjust the font size if you sometimes ran with an external monitor and sometimes not. 

Currently, we have the sourceStyler which only updates the style for method code in the PB; this has 30 different things that must be individually modified to change the font size; there are 8 different features that can be changed (italic, background color, etc) for each of these 30 styles. Which meets none of the above (1) (2) (3).

There used to be a way to set the System fonts and workspace fonts, but the unattractive and confusing preferences dialog was made inaccessible in issue #653.  But this wasn't persistent as far as I know.

We probably need to make the sourceStyler persistent... While I personally rather like not having colors and fonts flipping around, it does seem generally popular.  But it would be too much to change each setting to update font size.  

My first idea was to add a +1/-1 that would apply to the source styler, but if the source styler is persisted this is too messy. 

Perhaps a default setting for font size, and allow individual styles to override... in fact if there were internal defaults for everything, then you'd only need to adjust one setting if you like your comments to be lilac or something.  

I just DO NOT want to see 240 entries in the preferences, however this is implemented.

**Comment by ericwinger** [comment]
Added a setting in the `Jadeite.prefs` file which will set the point size of the text pane globally.

**Comment by ericwinger** [comment]
Also, added handy set & reset font size menu options to the `Preferences` browser menu.  Font size can be set  from 1 to 50. Reset sets it to the system default which appears to be about 10.  

Remember, with great power comes great responsibility. 

![image](https://user-images.githubusercontent.com/36212516/92274230-b6120100-eea1-11ea-8f7d-2019ded03e34.png)

**Comment by LisaAlmarode** [comment]
Unfortunately, being able to read class and methods names and menu items is also necessary (see requirement 1 in my list), so I can't call this fixed, although it appears to work fine for requirements 2 and 3.
  
Also... I believe that the only way to update the text pane font size, is to edit the preferences file, and logout and login again?  We don't have a reload or refresh?  It's okay, just was looking and not finding.

**Comment by ericwinger** [comment]
> Also... I believe that the only way to update the text pane font size, is to edit the preferences file, and logout and login again? We don't have a reload or refresh? It's okay, just was looking and not finding.

Maybe I'm missing something but Preferences>Set Font Size... will instantly change the text pane in the browser.  Or am I misunderstanding the question?  
![image](https://user-images.githubusercontent.com/36212516/187307690-42265aff-1fdc-499f-9380-4609ddc5047d.png)
![image](https://user-images.githubusercontent.com/36212516/187307747-abfcb627-d0e6-40f4-b1c2-0a620fbae0fe.png)

**Comment by LisaAlmarode** [comment]
![image](https://user-images.githubusercontent.com/13142166/187317747-eadfaf24-681a-4091-ac6f-caaa23efab94.png)

**Comment by ericwinger** [comment]
I've reworked the Font Size menu options for Jadeite 3.2.11
![image](https://user-images.githubusercontent.com/36212516/187532715-f48d1361-94fb-4a81-879b-fa19cce55d6c.png)

`Set Font Size ...` will set the non-text panes (lists, etc) to the font size specified. 
`Set Text Font Size ...` will set the text panes font size. 
`Reset Font Size` will reset to the system default. 

The preferences file can also be set: 
```
#legal values are an integer or nil
#fontSize: <anInteger or nil>
#textFontSize: <anInteger or nil>
```

**Comment by LisaAlmarode** [comment]
It's nice to have a way to handle this but it needs more work.

- [x] the Set Font Size and Text Pane Font Size menu items always opens showing a value of 1.  If you set it to something else, say 10, the next time it opens it's showing 1 again. 1 is not a good default.

- [x] If you press cancel on the dialog for Set Font Size, you get an error dialog, "UndefinedObject does not understand #*".  OK for Text Pane Font Size

- [x] Set Font Size is ambigious, calling this Set System Font would be easier to report bugs on :-) 

- [ ] While the Text fonts look normal, the System Fonts you get with Set System look terrible, they are bitmapy rather than smooth.  Using the preferences file setting, you do get nice looking fonts.  

- [ ] Reset font size resets to a smaller font size than the original.  After setting a system font size... the only way to get back to the original, non-bitmapy font is to restart Jadeite.

- [ ] Some buttons and text areas don't handle a larger font well at all.  Specifically, the Add Package section of a Project Browser, the My  Session tab of the console (buttons following Abort near bottom), Stone tab (top pane), Login dialog.  

- [x] it doesn't entirely make sense to set the font size for the entire system on the project browser.

- [ ] Given the niceness of using the ini file and the ugliness of the fonts set using Preferences menu setting (4), and the oddness of this being on the project Browser (7), I suggest removing the menu item Set Font size and Reset Font size, and requiring users to use the ini file if they want to adjust the font size.  

Issue 6, panes/buttons resizing to fit fonts, could be deferred as just an annoyance.  If we want to retain the Set Text Font Size menu item, that would be fine, and we could tolerate the default 1 (issue 1).

**Comment by ericwinger** [comment]
There are so many font setting changes in the fixes I think it's best to just open a new issue and start over. Need to reference that issue here when it's opened.
