### ISSUE TITLE
Changes Browser menu items

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#81]
Modify a method.  Look at project changes.
- [x] The inspect gets an error:
MCModification does not understand #inspect

- [x] the browse menu item brings up a dictionary browser.  It should bring up a package browser.

**Comment by LisaAlmarode** [comment]
weeelll it opens the projects browser, but only gets as far as selecting the class; it doesn't actually select the category or  method.  But nothing is broken so we could maybe let this pass.

However:
- [ ] if the change you are trying to browse is a class comment modification, or an added class, you get a walkback. 

a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'comment'

**Comment by ericwinger** [comment]
Fixed in 3.0.16.  the changes browser is a hack and will be replaced. If we get an error trying to find a change in our image, just put up a nice dialog box saying the change cannot be browsed instead.

**Comment by LisaAlmarode** [comment]
I think it should not first take the time to open a project browser and then close it and say it can't be browsed... especially since it could technically be browsed at least as precisely as a method. 
However given that this browser is "a hack"... we can defer further attention.
