### ISSUE TITLE
(3.1.0) MNU `stackDepth` in middle of debugging session

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#810]
Here's the error stack:
![image](https://user-images.githubusercontent.com/623951/81975987-b75eab80-95dc-11ea-8035-5f48f2a2e5b4.png)
The blank window on the left was the original debugger, the blank widow center was a debugger that I think was coming up after a step in the original debugger (offset error) and the visible debugger is the `stack depth` mnu:
![image](https://user-images.githubusercontent.com/623951/81976284-26d49b00-95dd-11ea-8610-7b33c89128c4.png)

... with all of the windows blanked out, I can't tell exactly what I was doing, since I was in fhe middle of debugging a complicated problem with several breakpoints involved... I'm not done with the resolving the problem, so I might get unlucky and see this problem again ...

**Comment by dalehenrich** [comment]
hit it again ... sorta ... this time the `offset error` window has frozen the image and I'm going have to kill jadeite:
![image](https://user-images.githubusercontent.com/623951/81980153-f3950a80-95e2-11ea-9d78-6abdc3e024d5.png)

**Comment by dalehenrich** [comment]
I think that this the method that is causing the problem:
```smalltalk
commitId
	^ [ 
	| gitHome gitTools |
	gitTools := Rowan gitTools.
	gitHome := (gitTools self
		gitrevparseShowTopLevelIn: self repositoryRoot pathString) trimBoth.
	gitTools gitcommitShaIn: gitHome ]
		on: Error
		do: [ :ignored | 
			"most likely no commits yet"
			'' ]
```
Note that there is a `send to self` in this method ... earlier the `gitcommitShaIn` was throwing errors, but notice that there **IS** and ERROR handler block in place, so not clear to me why the debugger would get confused ... I **am** using stepping around in here and it is 3.6.0.

**Comment by ericwinger** [comment]
I hit the same symptom but don't yet have a reproduction case. Here are the notes I took. 

Possible timing bug.  Initial process oop of debugger got recycled. Not obviously reproducible. Very intermittent.
Scenario where issue was encountered: 

- Debug tests in sunit browser on failing tests.
- Open debugger. 
- In separate browser, run same test that fails. 
- Get notifier, open debugger - Walkback - `aGsProcess dnu stackDepth`  process oop appears to have been recycled

**Comment by LisaAlmarode** [comment]
I think this bug is old enough and the debugger and dolphin changes such that it's not worth leaving it open.
