### ISSUE TITLE
(Oscar3.1.0) long delays for opening `Ernie-Tests` in SUnit browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#814]
This is a multi-minute delay when I'm logged in as Ernie in 3.6.0 with base and Ernie packaged ... I understand that it doesn't make sense to do performance improvements until we have started using RSR, so treat this issue as a test case (packaged base and Ernie test suites) for performance moving forward.

Once the SUnit browser is opened, click on `Ernie-Tests` and settle down to wait... there are quite a few test cases in ernie:
![image](https://user-images.githubusercontent.com/623951/83290349-5ff33a80-a19b-11ea-8427-e6a22df7ab3f.png)
Here's the status of the prefs:
![image](https://user-images.githubusercontent.com/623951/83290675-db54ec00-a19b-11ea-879b-f75d94dea569.png)

**Comment by dalehenrich** [comment]
Turns out that the long delay for find class dialog was actually an instance of #801, as I had a debugger open at the time ... SUnit browser was opened **before** I brought the debugger up, so it's long opening time is still a valid complaint

**Comment by LisaAlmarode** [comment]
This is a rather old bug; while performance issues still are likely I think we should file new bugs.
