### ISSUE TITLE
(3.1.0) find string dialog disabled when debugger is present

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#818]
I'm actually trying to search in the workspace (upper right), but the debugger is apparently blocking the proper operation of the dialog:
![image](https://user-images.githubusercontent.com/623951/84527392-e0816300-ac92-11ea-9c50-31e36de90629.png)
Related issues: #789,  #801, #802

**Comment by ericwinger** [comment]
Might be related to #801

**Comment by LisaAlmarode** [comment]
This appears to be working okay in 3.2.12
