### ISSUE TITLE
Breakpoints don't stay disable

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#821]
I disabled breakpoints for a method using breakpoint browser:
![image](https://user-images.githubusercontent.com/623951/84815637-2b1f1a00-afc8-11ea-839e-48463dfead35.png)
then proceeded to run a test via doit in workspace and ended up hitting the disabled breakpoint:
![image](https://user-images.githubusercontent.com/623951/84815777-628dc680-afc8-11ea-983c-1b165de27d90.png)

**Comment by ericwinger** [comment]
The first picture of the breakpoint browser shows that there is a disabled breakpoint. But the second picture (copied below) shows that the same breakpoint is not disabled. If the second one is to be believed, then the correct behavior was for the test to stop at the second breakpoint. 

![image](https://user-images.githubusercontent.com/36212516/89690108-998ea300-d8ba-11ea-9d98-c01f111c7126.png)

Presumably though, there's nothing in your test that enables breakpoints. Also, I assume you didn't manually enable breakpoints from another browser, the transcript, etc between the time you disabled the breakpoint and started the test. That implies Jadeite re-enabled the breakpoint (or all breakpoints) magically. 

It's not reproducable, so if it's not too inconvenient, can you add `self halt` in `GsNMethod class>>_enableAllBreaks` and `GsNMethod>>setBreakAtStepPoint:`? These are the two methods that services uses to enable breaks. If it is getting enabled magically through Jadeite, we would get a stack showing the path through services code back to the client command. That would help debugging.

**Comment by dalehenrich** [comment]
I haven't been using the breakpoint browser recently ... I think I have several issues submitted and I'm waiting for those issues to be addressed (I think this gets them: https://github.com/GemTalk/Jadeite/issues?q=is%3Aopen+is%3Aissue+author%3Adalehenrich+breakpoint+browser).... don't get me wrong ... i **want** to use the breakpoint browser:)

**Comment by LisaAlmarode** [comment]
Not easily reproduced in 3.2.9, presume fixed.
