### ISSUE TITLE
would be nice to be able to choose to browse a method, when full project browser is overkill

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#822]
There are a number of places in Jadeite, where one is given the option to `browse`, but you end up with an entire project browser when all you want is to browse the method:
![image](https://user-images.githubusercontent.com/623951/84835194-e60ae000-afe7-11ea-880e-67491b185679.png)

I've shown the breakpoint browser here, but there are a number of places where the `browse` menu item shows up and in each of those cases (where there isn't already a `browse method`) it should be possible to browse just the method

**Comment by ericwinger** [comment]
Might be worth including some of the method menu functionality here as well. That would bring in the "Browse Selected Method" feature. See https://github.com/GemTalk/Jadeite/issues/831#issuecomment-670616423

**Comment by LisaAlmarode** [comment]
The breakpoint browser ought to have a browse selected methods menu option.  I'm not aware of other places that don't have this option nowadays.

**Comment by ericwinger** [comment]
Should be able to browse just the selected method now. 
![image](https://user-images.githubusercontent.com/36212516/213829338-5b79cecd-bf4c-43ac-a069-793411f91b41.png)
