### ISSUE TITLE
[V2.0] Restore RowanProjectService>>addPackageNamed: so client tests work

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#823]
Adding a V2.0 Package is different but the client tests that exercise the now-removed `RowanProjectService>>addPackageNamed:` should still work. Need to setup a default using 'Core' component. 

For reference: https://github.com/GemTalk/Rowan/issues/623

**Comment by dalehenrich** [comment]
If this method is included in Jadeite, then we run the risk of leading any users of Jadeite that `add package` can be used ... if the menu items that call addPackage: are disabled, then I'm not concerned about having `RowanProjectService>>addPackageNamed:` implemented.

**Comment by ericwinger** [comment]
The only concern of this bug is to make sure we can continue to run Jadeite tests which add packages as part of testing other gui functions. It's not related to product features. Currently, some Jadeite tests won't run because `addPackageName:` is missing. 

When Jadeite is updated to add V2.0 packages, all the menu items will be updated and tests written (& rewritten). Then I'll "re-remove" `addPackageName:`

Hope that clarifies.

**Comment by dalehenrich** [comment]
So the `Add package` menu item in 3.1.0 has been removed? ... I removed the method, because I don't want developers to think that add package works ... same rationale for remove the newGit... method ... better to get a MNU than to do something random that the user doesn't expect ... The add package should not work until it has been converted to v2.0 ... I understand that you want tests to pass, but I am concerned that users of Jadeite, will try to use the add package menu item.

Hope that clarifies.

**Comment by ericwinger** [comment]
`Add package` is present in the current Jadeite git branch based on Jadeite 3.1.0.   

However, I see your concern now of adding the method `addPackageNamed:` back into server services and will disable the client menu option `Add package` in my next Jadeite commit. 

If you want me to remove other gui features. I can do that, but I'd need a list of menu items and features to disable listed in a separate issue.  After that is done, I think it would be wise to tag a new internal release for developers. 

If anyone is using Jadeite 3.1.0 for work on Rowan v2.0 against servers other than 3.2.15 then it must be considered, "use at your own risk" until the necessary work to make Jadeite work against Rowan v2.0 is complete.

**Comment by ericwinger** [comment]
`addPackageNamed:` was restored to `RowanProjectService` in Rowan project and `Add package` menu option was disabled in the Jadeite gui temporarily.
