### ISSUE TITLE
Does it make sense to maintain menu item order across windows?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#826]
I've got several screen shots here and the `Browse Selected Method` menu item bounces around a bit and is missing from the message browser ... consequently every time I want to browse a method that I have selected I end up searching the menu for `Browse selected method` because I can't count on it being in the same place (or even being present) when I have a method selected. ... and I do this fairly frequently. Would be nice it were always tucked up after `Browse senders` near the top of the list ...
![image](https://user-images.githubusercontent.com/623951/85606930-7bb9f700-b608-11ea-8983-cfa6bc13fc54.png)
![image](https://user-images.githubusercontent.com/623951/85607144-aad06880-b608-11ea-8dfc-fe4c1ff7b765.png)
![image](https://user-images.githubusercontent.com/623951/85607423-f420b800-b608-11ea-979f-d9f9d0c91576.png)
![image](https://user-images.githubusercontent.com/623951/85607727-3d710780-b609-11ea-8e49-3e9f177308ae.png)

**Comment by ericwinger** [comment]
This is a @LisaAlmarode question.  If menu order is desirable, then I'd ask that you (kindly) coordinate on what the order should be for each menu.

**Comment by dalehenrich** [comment]
Here are a couple of examples for the "Jadeite" menu. Two menus with the same name, but entirely different content ... I actually would like the "Jadeite" menu from the console to be present on all of the windows, so I don't want to have to hunt for the console window to toggle one of the properties (auto commit or breakpoints):
![image](https://user-images.githubusercontent.com/623951/85625126-cbf08380-b61f-11ea-8de6-52f99e025ab6.png)
![image](https://user-images.githubusercontent.com/623951/85625186-e3c80780-b61f-11ea-9a80-c9315f00f8cd.png)

**Comment by ericwinger** [comment]
A related comment about the method menu is here https://github.com/GemTalk/Jadeite/issues/831#issuecomment-670616423.

**Comment by LisaAlmarode** [comment]
the initial point and bulk of this bug was fixed by the fix for #831.  Examined the options for browsing on the four menus, and really don't find anything reasonably missing. Will file a new bug for the Jadeite menu since that is both yes, we should fix and a much more difficult problem.
