### ISSUE TITLE
Would be nice to be able to request that all `browse` menu items be routed to an existing project browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#827]
I often find myself in a position where there is the opportunity to use the `browse` menu item:
![image](https://user-images.githubusercontent.com/623951/85783972-ab3a3380-b6dc-11ea-99da-546f7c7029f3.png)
and I really want to browse the class and the method, but I already have enough window clutter that opening another project browser when I already have a perfectly serviceable project browser ready and waiting with multiple tabs .... so instead, I manually bring up the existing project browser and type in find class (and hope to avoid typos) and then select the right method (again avoiding typos) ...

So I would really appreciate this feature:)

**Comment by ericwinger** [comment]
This certainly wouldn't be too hard to do. It would add YAMO (Yet Another Menu Option). If my suggestion in #831 is implemented https://github.com/GemTalk/Jadeite/issues/831#issuecomment-670616423, that would add to an already busy menu. 

Jadeite would also have to guess which browser to add a tab to if multiple project browsers were already open. Maybe that doesn't matter?

Another possibility would be to enhance the drag/drop features of Jadeite so you could drag a method from one browser to another - or drag a stack frame to a browser. 

Just thoughts ... I'd be curious what opinions @LisaAlmarode has.

**Comment by dalehenrich** [comment]
I can understand menu clutter ... this happens to be a case where a preference could be used ... I only EVER have one project browser open at a time ... if there are multiple project browsers open, I would think that randomly choosing one to add the new tab to would be preferable to creating a new project browser ... 

> Another possibility would be to enhance the drag/drop features of Jadeite so you could drag a method from one browser to another - or drag a stack frame to a browser.
I would definitely like this feature ... I often want to consolidate methods from several method browsers and being able to drag a method to a new tab in a project browser would be useful as well ...

I have a pet peeve about drag drop between windows ... I am concerned that I would have to resize windows and move them around in order to get the drag source and drag target easily accessible ... resizing and monkeying with window positions is a non-starter for me ... in tODE I've used a copy/paste metaphor, that avoids that particular problem...

**Comment by ericwinger** [comment]
Fixed per commit comments.  See "Browse in Existing Browser" menu item in pictures. If no browser exists, a new one is opened.  In order to reduce the number of menu items, a case could be made for eliminating the "Browse" functionality and just always browse debugger frame methods and method list methods in an existing browser. 

![image](https://user-images.githubusercontent.com/36212516/173155923-91ebd518-573c-459a-a5ec-af9fce00b9b5.png)

![image](https://user-images.githubusercontent.com/36212516/173155967-56a000b6-9ad5-490c-85a7-8147313c5ce1.png)
