### ISSUE TITLE
browse selected method menu item would be useful in method browser, too

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#831]
Everywhere that you have a method selected, it would be useful to have `browse selected method` option to open a method browser on that method in a separate method browser ...

**Comment by dalehenrich** [comment]
in case a use case is needed for justification. Window on left is list of failing tests methods that need work. I just finished getting the first test to pass, and now want to move on to the other tests ... the window opened on right is in separate window for reference, but I had to navigate to the project browser and the method in order to open the window:
![image](https://user-images.githubusercontent.com/623951/87230991-42072100-c368-11ea-8b79-c57255a58df0.png)

**Comment by ericwinger** [comment]
I think that the best course of action is to use a common method menu anywhere method lists & sources are displayed. Currently the respective menus for the browser, debugger, and the method list are different and maintained separately. Unifying them (and allowing for window-specific menu enablement - e.g. not running tests from the debugger possibly) would be easier to maintain. 

![image](https://user-images.githubusercontent.com/36212516/89669490-646f5a00-d894-11ea-8181-906313cf1df5.png)
![image](https://user-images.githubusercontent.com/36212516/89669535-72bd7600-d894-11ea-9788-a684fd235248.png)
![image](https://user-images.githubusercontent.com/36212516/89669831-fa0ae980-d894-11ea-8521-9e0ebee36019.png)

**Comment by ericwinger** [comment]
For now, just fix the immediate request. `Browse Selected Methods` was added to the method menu list. 

Also fixed that annoying pause when opening the method list context menu - was making an unnecessary round trip.
