### ISSUE TITLE
Doing a Find Class with unsaved method changes should confirm then save changes

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#835]
If you have unsaved changes in a project brower, then do a `Ctrl-Shift-F` and go to a new class, the tab stays starred and the method source pane stays on the changed method but the class is different.  

Should send `isOkayToChange` or a cousin before allowing the browser to move to the new class.

**Comment by ericwinger** [comment]
Fixed in Jadeite 3.2.0.

**Comment by LisaAlmarode** [comment]
"Keep unsaved changes" implies, well, that something will be kept.  The message should be more like "You have unsaved changes: continue editing?"  Seems to work fine, though.

**Comment by ericwinger** [comment]
Fix in Jadeite 3.2.11 per recommendation
