### ISSUE TITLE
Managing packages for Rowan V2.0

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#839]
When we add support to Jadeite for the Rowan package convention (no correlation between packages and method categories) we will need to change how the Monticello and RowanHybrid conventions are handled and the main take away is that it seems that we will no longer manage packages in Jadeite by dragging a method to a category (see GemTalk/Rowan#639). If we explicitly move methods between packages, then "all we need to do" is ensure that the category involved matches the package convention of the target package ... and if it doesn't "do the right thing" ... this happens to be the way that Rowan deals with the different conventions when reading and writing packages from/to disk --- Rowan ensures that the category for each method conforms to the convention used by the package ...

**Comment by LisaAlmarode** [comment]
This is probably related to issue #956 and other related confusion regarding *categories and now to move methods between packages.  Thus, needs to be resolved for end-2022.

**Comment by LisaAlmarode** [comment]
This has been implemented as of 3.2.x.  There are still a number of questions and issues in this area, which are being handled under individual issues, so not worth keeping this open.
