### ISSUE TITLE
Review Project Refresh

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#841]
I'm not sure that refreshing a project after updating the disk sha is working correctly. Need to make sure that the correct sha & color (red for skew) is done in both the project list and project browser.

**Comment by ericwinger** [comment]
It's ok. Refresh doesn't reload your code but does change the color of the text to red if the disk has become skew from the loaded project.

**Comment by dalehenrich** [comment]
I just noticed in release5 that when you do a refresh of the console, not all of the projects that should turn read actually turn red until you mouse aross them .. (this was using the Rowan project which has required projects) ... there's a sample project that I can dig up if you want a RowanSample9 project to work against ...

**Comment by ericwinger** [comment]
The console's project list needed to invalidate it's views after doing an update. 
Will be fixed in Oscar3.2_prerelease6

**Comment by LisaAlmarode** [comment]
Refresh does cause a skew project to turn red.
