### ISSUE TITLE
Pop up messages while evaluating a Do It expression

### ISSUE THREAD

**Issue by rjsargent** [ericwinger/Jade#845]
I was evaluating a Do It expression to load a project in tonel format. I got a Jadeite message box with "Index 238 is out of bounds". I have seen other numeric values in the message, once as high as 447. No idea what it was working with. Dale thinks it might have been malformed STON in the reply from the server.

Sometimes I get a pop up compiler warning about an unused temporary variable, but not always. If I "Proceed" from the compiler warning, I get the Index out of bounds pop up.

If I Debug the load expression, I can get to a compile error for an Undefined Symbol (known to be in the filed in code) or I can get a different compile error from a malformed tonel method definition (also now known to be in the filed in code).

Inspect, Display, and Execute for evaluating the expression seem to produce different results.

Jadeite does correctly handle an error in the Do It expression itself, but not compile errors and warnings from what the expression causes to happen.

For the record, the load expression follows. I will have the problematic code cleaned up before anyone can address this issue, so the expression is just for guidance.
(Rowan 
	projectFromUrl: 'file:$ROWAN_PROJECTS_HOME/announcements/t2f2t/specs/tonel.ston' 
	gitUrl: 'file:$ROWAN_PROJECTS_HOME/announcements') load

**Comment by ericwinger** [comment]
There should be a `Jadeite.errors` file in your Jadeite directory.  Can you peel off the last stack containing the Index 238 error and attach it to this issue?

**Comment by rjsargent** [comment]
This is the first one I encountered, with offset 447.
Line 115 has CodeSourcePresenter>>showCompileError: trying to insert 'undefined symbol' into the Do It string rather than the method source.

[Stack_InsertingCompileErrorInTheDoItString.txt](https://github.com/GemTalk/Jadeite/files/5639181/Stack_InsertingCompileErrorInTheDoItString.txt)

**Comment by rjsargent** [comment]
Per request, here's a slightly different variation when the source offset (25) isn't out of range.

Evaluating:
GsFileIn fromServerPath: '~/BadFileIn.tpz'
results in the workspace displaying:
GsFileIn fromServerPath: undefined symbol'~/BadFileIn.tpz'


BadFileIn.tpz looks like this:
DoIt
 Object subclass: 'BadClass'
  instVarNames: #()
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: UserGlobals
  options: #()
%
method: BadClass
iContainACompileError

	^SomethingThatDoesNotExist at: #key ifAbsent: [42]
%

**Comment by rjsargent** [comment]
Jadeite needs to trap compilation errors while compiling the expression, but not while executing the resulting compiled code.

**Comment by ericwinger** [comment]
Before doing ad-hoc execution, compile the string. If it fails, report the compilation error inline. If it succeeds, run the execution. Any compile errors during execution will be shown with a debugger. 

Fix will be in Jadeite 3.2.9.
