### ISSUE TITLE
Errors during menu display make it difficult to do anything to deal with the error

### ISSUE THREAD

**Issue by rjsargent** [ericwinger/Jade#847]
When I removed GemToGemAnnouncement, the #installStaticHandler method was presented in the list of methods referencing the class. When I right clicked on the method in the list, I got an error pop up. But, because the error occurred while creating the menu, I could not see my cursor anywhere over the Jadeite windows.

I was able to close the debugger prompt, after which the menu finished displaying and everything else was working again.

**Comment by LisaAlmarode** [comment]
In 3.2.12, right clicking causes the method list to update and remove a method reference the class that is on the removed class.  I think that means this bug has been fixed.

**Comment by rjsargent** [comment]
Is this fixed by eliminating the specific error that I encountered or is it fixed for future errors occurring while opening the menu?

**Comment by LisaAlmarode** [comment]
The particular case no longer reproduces a problem. Whether whatever else has changed over the last couple of years also includes fixes for other unknown issues that may arise in the future is unknown.  However, an error opening a menu shouldn't ever occur and is a high priority, so one likes to think that graceful handling of broken menus will not be a useful area of focus.
