### ISSUE TITLE
Should be able to select all in the debugger's message description field

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#849]
The highlighted text pane in the example is kind of long.  Should be able to copy it quickly. Select All would be convenient. 

![image](https://user-images.githubusercontent.com/36212516/102660168-73fa8b80-412f-11eb-8a96-7c34768616fd.png)

**Comment by LisaAlmarode** [comment]
Assuming that Eric means the static single-line at the top of the debugger, this contains a select all menu item that selects all, so this has got itself fixed.
