### ISSUE TITLE
Upgrade to 3.6.1 

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#850]
- [ ] Move Jadeite development to 3.6.1
- [ ] Change name of 3.6.0 client library to "64-bit 3.6.0" from "64-bit 3.6.0 unreleased" 
- [ ] Connect to masterV2.1 branch (See Dale's email of 12/22/20) 
- [ ] Ensure works with Sparkle

**Comment by LisaAlmarode** [comment]
Not a current concern (and clearly not ever pressing)
