### ISSUE TITLE
would be convenient if `Expand Full Hierarchy` was enabled when `Classes` tab selected in project browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#852]
Whenever I want to `expand full hierarchy` I am often sitting in the `Classes` tab, so I have to click the `Hierarchy` tab, then select the  `expand full hierarchy` menu item ... would save some mouse movement to simply have the  `expand full hierarchy` menu item `select` the `Hierarchy` tab for me ...

**Comment by LisaAlmarode** [comment]
I suspect that the class-hierarchy display tabs need some thought, to ensure they are intuitive (as I recall things are not shown that I'd expect to see, and we should at least have the specific rules described somewhere). However, assuming this is what you want to do, I don't see a downside to having the expand full hierarchy shortcut on the class pane.

**Comment by ericwinger** [comment]
3.2.12 - Expand Full Hierarchy will open a full hierarchy on a class from the class list. 
![image](https://user-images.githubusercontent.com/36212516/197297962-05f43096-76b1-44d8-99d6-94e989708b93.png)
