### ISSUE TITLE
Fatal error does not cleanup well

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#855]
If Jadeite encounters a fatal error, the session is invalidated and GsSession's instance variable `library` is set to nil.  However, Jadeite doesn't tell you that. Instead, it silently lets you believe that everything is ok.  But then, Jadeite will give you a random error on pretty much any action taken thereafter.  That's not user friendly. 

After encountering a fatal error, Jadeite should give you a nice error message and then shut down the console and any open windows except the Login dialog.  (I'd be open to ideas on how to better respond - @dalehenrich @LisaAlmarode, Any ideas?)   

To reproduce with a stone running with a default `gem_tempobj_cache_size` run this code: 
```
UserGlobals at: #foo put: Array new. 

1 to: 10000000 do:[:index | 
	(UserGlobals at: #foo) add: 'abcdefghijklmno', index printString]
```
It'll get a fatal error: 
![image](https://user-images.githubusercontent.com/36212516/107725681-975b3600-6c9b-11eb-9b8e-8bc94af058aa.png)

Then, press the commit button which gives this strange message: 
![image](https://user-images.githubusercontent.com/36212516/107725796-e4d7a300-6c9b-11eb-9af0-03f509f6a8b3.png)

**Comment by ericwinger** [comment]
Note - Running with servers that use the default `gem_tempobj_cache_size` is good to do to catch other bad behavior that might result if a fatal error is encountered.

**Comment by dalehenrich** [comment]
.... and a good memory stressor is to do changes against the gemstoneBaseImage project ...

**Comment by ericwinger** [comment]
@dalehenrich - Thoughts on how you'd like to see Jadeite cleanup from a fatal error?

**Comment by ericwinger** [comment]
Attaching Jadeite errors showing the second error in the issue report. Fatal error does not appear because it was displayed and handled by Jadeite. 

[Jadeite.errors.txt](https://github.com/GemTalk/Jadeite/files/5973122/Jadeite.errors.txt)

**Comment by LisaAlmarode** [comment]
I get lost session errors a lot (as vpn disconnects overnight), and clicking on anything in the project browser (but not in the debugger, as I recall) causes all open windows to close.  This behavior seems okay to me.  

The out of memory doesn't work like that and you get those errors all over the place.  While not critical for end-2022, it's fairly unpleasant.

**Comment by ericwinger** [comment]
Now, if a fatal error like out of memory is encountered, the user will get a message not only saying what the error is but that the session is being shut down. Jadeite goes through the usual shutdown of windows after that.
