### ISSUE TITLE
better gci error reporting is needed ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#858]
I had an incorrect IP address for my host and got "An unknown GciLoginFailed has occurred" error which didn't give me enough info about where to look for my problem ...
![image](https://user-images.githubusercontent.com/623951/115283260-f99f3f80-a0ff-11eb-8a17-b582b17805cc.png)

**Comment by jgfoster** [comment]
If you try the same thing with Topaz, what error do you get? My guess is that Jadeite is reporting the full error message from the GCI library. If so, then it would be nice to get a more descriptive error message from the GCI library.

**Comment by dalehenrich** [comment]
```
topaz> login
-----------------------------------------------------
GemStone: Error         Fatal

Error Category: [GemStone] Number: 4042 NetLDI service 'rowan_dev_l_ldi' not found on node '192/168.122.2', host not found, service not found Arg Count: 0
```

**Comment by jgfoster** [comment]
Thanks, I stand corrected! That was much more useful message. It does seem that it ought to be able to be provided in Jadite as well. Sorry for the misdirection.

**Comment by ericwinger** [comment]
Pulling the gci login error information from the `reason` inst var of the error instead of the `message`.  Forcing a login error shows me this before and after: 
![image](https://user-images.githubusercontent.com/36212516/176512399-b8803123-4623-42e6-9624-df6d6efe9cae.png)
![image](https://user-images.githubusercontent.com/36212516/176512426-c61a38a4-ae4a-4a59-a7f3-8eacbf5eb043.png)

**Comment by LisaAlmarode** [comment]
Not all login errors are caught.  E.g.
![image](https://user-images.githubusercontent.com/13142166/187519432-eb5d7960-cfc1-43bf-b2e4-cf9510252363.png)

The bad host or netldi name error message is not quite as good as of 3.2.10 although passable ![image](https://user-images.githubusercontent.com/13142166/187518846-9c837da0-4c63-4cce-905d-bf11235bece4.png)

just for yucks I looked on the advanced tab and was a little surprised to see I'm allow to select a linked gem?  It errored (as expected), with this message (just for the record), but we shouldn't be given the option to select 32-bit IMO.

![image](https://user-images.githubusercontent.com/13142166/187519863-44baa36f-0e8c-409c-a84d-9a1612fe1f55.png)

**Comment by ericwinger** [comment]
Removed Linked login option from Advanced tab. @LisaAlmarode - Could you clarify what else should be done on this bug (or close it if complete) 

![image](https://user-images.githubusercontent.com/36212516/193147913-64b9c9b1-5363-4e39-8834-15f2a774a6b5.png)

**Comment by LisaAlmarode** [comment]
If I edit the stone host to be localhostx, I get the unknown GciLoginFailed as occurred. I think this is the equivalent to
```
topaz> set gemnetid !@localhostx#netldi:40037!gemnetobject
topaz> login

GemStone: Error         Fatal

Error Category: 231169 [GemStone] Number: 4042 NetLDI service '40037' on node 'localhostx' port 40037, not found, connect failed, host not found, getaddrinfo failed, EAI error -2, Name or service not known,  Arg Count: 0 Context : 20 exception : 20
```

**Comment by LisaAlmarode** [comment]
I also get the unknown GciLoginFailed error:
 -- if there is no stone with the given name
 -- if the user does not exist (SystemUserx) 
 -- if the password is wrong

**Comment by ericwinger** [comment]
There were two fields in the login error object that show gci failure information. Display both on login failure.
