### ISSUE TITLE
Need a "Stop Active Tests" button in SUnitBrowser & maybe other places

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#861]
It's annoying to not be able to easily stop a test run. Would like a button in the SUnit browser gui that stops the active test thread.  Might be handy in the browser, too, if you accidentally start a long test.

**Comment by ericwinger** [comment]
Running tests is now forked and a stop test run button has been added. Stop button does not interrupt the server process because that's not necessary or desirable, but will let the active test finish before stopping the test run.

**Comment by LisaAlmarode** [comment]
Looks like it does what it says on the tin.
