### ISSUE TITLE
Don't truncate the printString of the selected variable in the debugger

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#862]
It's rather misleading to truncate the printString of the selected variable in the debugger's variable pane. Instead, we should probably show the entire string. Or, at least as much as the inspector shows. 

![image](https://user-images.githubusercontent.com/36212516/116740111-68568580-a9a9-11eb-9a6c-30488b02c790.png)

Work around - Double-click or right-mouse inspect the variable to open an inspector.

**Comment by ericwinger** [comment]
Looks like the truncation was actually in this method. Still, worth double-checking the debugger at some point to make sure it isn't truncating. Once verified, close this issue. 
```
TestCase>>assert: anObject equals: otherObj
  anObject = otherObj ifFalse:[ | a b |
    a := anObject printString .
    b := otherObj printString .
    a size > 100 ifTrue:[ a size: 100; addAll:'... ' ].
    b size > 100 ifTrue:[ b size: 100; addAll:'... ' ].
	  self
		 assert: false
		 description: a, ' is not equal to ' , b .
  ].
```

**Comment by LisaAlmarode** [comment]
I don't see truncation (although I haven't looked everywhere possible).
