### ISSUE TITLE
method browser menu item `Run Tests` should be `Run Selected Tests`?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#866]
When there are multiple test methods in a method browser, it isn't clear whether `Run Tests` will run **ALL** of the test methods in the method browser or just the selected tests ... the project browser uses `Run Selected Test(s)` and `Run All Tests` which is sorta where the confusion (for me) comes into play ... If you and Lisa think developers won't be confused then I'm fine with that ... a while back I ended up running all of the tests in the project browser because I was used to see `Run Tests` in the method browser ... and I had to kill my image to correct my mistake ... now I'm gun shy about using `Run Tests` because it looks like it might run all of the tests in the class :)

**Comment by LisaAlmarode** [comment]
This is indeed confusing.  The menu item says "run tests", the result says "tests passed", both which had me somewhat convinced that all tests were being run. 

The method list browser Methods menu item should say "Run Selected test(s)", to match the project browser method pane.  I don't think it's necessary to add "Run All Tests" to this menu, but I wouldn't object. 

The SUnit brower and tab just says "Run All" and "Run Selected" but then the SUnit browser says "Browse Selected Tests".  It's inconsistent but not bothersomely so.

**Comment by ericwinger** [comment]
Because the functionality matches "Debug Selected Test(s)" in the project browser, renamed it the same. Hopefully, this is even more clear than the previous naming suggestions.
