### ISSUE TITLE
(Oscar-3.1.1-release1) revert of a class method restores as an instance method (apparently)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#867]
after reverting a class method in changes browser and saving to git, noticed the following:
![image](https://user-images.githubusercontent.com/623951/117739763-d8d48200-b1b3-11eb-8167-11d214d790c4.png)

**Comment by LisaAlmarode** [comment]
In 3.2.12, if you have an existing class method, and revert it in the changes browser, it becomes an instance method.

**Comment by ericwinger** [comment]
Not taking into account class meta state when reverting a method.  Also, browsing a reverted class method works better now.
