### ISSUE TITLE
(Oscar-3.1.1-release1) debugger selects incorrect frame

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#868]
The selected frame looks like the correct frame to select (at first glance), however note that the frame `[] in RwRowanSample9Test >> testSpec_0052_3` is a better choice:
![image](https://user-images.githubusercontent.com/623951/117852826-97d48000-b23c-11eb-8bd7-7564f789325d.png)
The problem is that it took me several tries debugging the test failure to realize that the assertion failure that **I was expecting** was up the stack :( ... 

If you are going to give me a short cut to the frame that "I want to see" you'd better make the right choice, otherwise I won't be able to trust the debugger and have to scan the stack (anyway) whenever the debugger comes up to make sure I'm not missing something important ... 

I appreciate the feature, but it needs to be fine tuned a bit more ...

**Comment by LisaAlmarode** [comment]
With the following methods:
```
test868
 [{ 1 . 2 . 3 } select: [:ea | 
	(self deleteProject = ea) ]] 
	on: Error 
	do: [:ea | self assert: false].
-----------------
deleteProject
self error: 'Cannot do this'
```
I can produce the kind of stack that Dale feels is wrong, that the frame 5 upwards should have been selected. I can see it might be misleading, although it doesn't seem very urgent to me.  

![image](https://user-images.githubusercontent.com/13142166/200993833-351a75be-28d3-4c48-9b6f-9acb8633479b.png)

**Comment by ericwinger** [comment]
Fixed the specific issue for the example given in the issue but opened a new issue to make the code in this area less brittle. 
https://github.com/GemTalk/Jadeite/issues/996

**Comment by LisaAlmarode** [comment]
My example reproduces exactly the same in 3.2.15. However, I'm not sure now that it's actually an error... unless there's a handler around the error, the error would stop in the test execution before it gets to the assertion.  Reopen for discussion, possibly with Dale as to more specifics.

**Comment by ericwinger** [comment]
Right or wrong behavior, it would be nice to understand why I see different results than @LisaAlmarode. In the runtime executable, I added the two test methods in a new class ThreeTest and executed `ThreeTest new test868` from a workspace. A notifier appears and I press Debug. The debugger has the block context selected. 

![image](https://user-images.githubusercontent.com/36212516/217391730-8229a7f5-9333-4dd2-9073-12d52e7ecdb8.png)

**Comment by ericwinger** [comment]
@LisaAlmarode 's class is a subclass of GsTestCase. That explains the difference.

**Comment by ericwinger** [comment]
Conceptually, I think you'd want the selected frame to be the first place in the stack where "your" code appears. In @LisaAlmarode 's example, that would be the frame above the "assert".  If that is true, the Jadeite code is wrong. `JadeDebugger>>stackInitialSelection` should compare a frame against all possible "error" frames and NOT compare an "error" frame against all stack frames.  With this change you'd get the frame above the first "error" frame in the stack.
