### ISSUE TITLE
#methodListSelection is the responsibility of the subclass

### ISSUE THREAD

**Issue by jgfoster** [ericwinger/Jade#87]
Trying to debug #74. I opened a RowanSystemBrowser, added a method to JadeServer in UserGlobals, right-clicked to set a breakpoint, and got the following error:

5:56:24 PM, Monday, August 20, 2018: '#methodListSelection is the responsibility of the subclass'
RowanSystemBrowserPresenter(Object)>>subclassResponsibility
RowanSystemBrowserPresenter(JadePresenterA)>>methodListSelection
RowanSystemBrowserPresenter(JadePresenterA)>>setBreakPointAt:in:
MessageSend>>forwardTo:withArguments:
MessageSend(MessageSendAbstract)>>forwardTo:
CommandDescription>>performAgainst:
[] in Command>>value
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Command>>value
ShellView>>performCommand:
RowanSystemBrowser(Shell)>>performCommand:
CommandQuery>>perform
DelegatingCommandPolicy(CommandPolicy)>>route:
[] in ScintillaView(View)>>onCommand:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Cursor>>showWhile:
ScintillaView(View)>>onCommand:
ScintillaView(View)>>wmCommand:wParam:lParam:
ScintillaView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam:cookie:
InputState>>pumpMessage:
InputState>>loopWhile:
InputState>>mainLoop
[] in InputState>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess

**Comment by ericwinger** [comment]
@jgfoster  Have a partial fix for this. Need to merge https://github.com/ericwinger/Jade/pull/86 and see if the fix still works.

**Comment by ericwinger** [comment]
Believe this is fixed in sha 28e4d6e7174092a4c039f6168156af69822ec58e
