### ISSUE TITLE
GciErrSType64_3[01] >> reason gets subclassResponsibility error

### ISSUE THREAD

**Issue by martinmcclure** [ericwinger/Jade#876]
Attempting to log in when the netldi is not running should produce an error, but probably subclassResponsibility is not the best error.

The cause seems to be that #reason sends #fromAddress: to the class String, which defines it as subclassResponsibility. Using a subclass such as AnsiString instead of String would probably fix this.

This bug appears to be present in at least 3.1.1-pre-release2 and oscar30911.

**Comment by LisaAlmarode** [comment]
In 3.2.12, login says NetLDI service nnn on node nnn port nnn failed.  Work has been done on login errors under other issues, so optimistically calling this fixed.
