### ISSUE TITLE
Error when committing from Jadeite when GemStone runs on Mac Big Spur

### ISSUE THREAD

**Issue by chisandrei** [ericwinger/Jade#877]
When trying to commit from Jadeite I get an error. The GemStone server is running on MacOs. Seems that `mktemp --template` fails on MacOs; `mktemp -t` works in MacOs and Linux and could be used instead. I'm using jadeite-3.1.1-pre-release3

<img width="1350" alt="Screenshot 2021-08-19 at 16 24 01" src="https://user-images.githubusercontent.com/3534711/130106689-9e3a04d1-1035-48d2-ae08-b347ea049634.png">

I also had to change the executable location to point to /usr/bin/mktemp ; Strangely enough even with sudo I could not create a symbolic link

```
sudo ln -s /usr/bin/mktemp /bin/mktemp                                             
ln: /bin/mktemp: Operation not permitted
```

**Comment by dalehenrich** [comment]
Closing this issue in favor of GemTalk/Rowan#739
