### ISSUE TITLE
Removing class does not remove class from sunit browser

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#879]
In `JadeiteSUnitSupportTestCase>>test_extensionTestShowsUpInSUnitBrowser` removes the test class at the end of the method. While the test class is removed from the browser, it is not removed from the sunit browser. 
```
self projectsPresenter basicRemoveClass: self projectsPresenter selectedClass
```
It would be nice if it was.

**Comment by LisaAlmarode** [comment]
verified in 3.2.12, and probably should be fixed if possible.

**Comment by ericwinger** [comment]
Needed to ensure sunit browser got registered for the proper service updates.

**Comment by LisaAlmarode** [comment]
Class does get removed from the list of classes in the SUnit tester.

However, the SUnit tester is now displaying non SUnit classes and abstract SUnit classes that are in this package. 
before removing PlantisWindowsTester:
![image](https://user-images.githubusercontent.com/13142166/207713034-96072d66-5442-41c4-9254-5f14cdd32db5.png)

after removing it, the non-SUnit TestMovingClass and the abstract SUnit class PlantisTester are incorrectly included:
![image](https://user-images.githubusercontent.com/13142166/207713073-39ffc0e1-ae80-4d00-ab1d-211000f21b79.png)

**Comment by ericwinger** [comment]
Non test classes should no longer get added into the sunit browser after class add in another browser.
