### ISSUE TITLE
(Oscar3.2pre-release3) Console refresh after changing SHA for project ... changes don't show up until moused over

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#882]
You can see in this screenshot that Rowan and STON have updated (after I moused over them), but Cypress and FileSystemGs have yet to refresh:
![Screenshot from 2021-09-10 09-29-53](https://user-images.githubusercontent.com/623951/132886782-2c569047-c735-498d-997b-faf0f8864cb7.png)

**Comment by LisaAlmarode** [comment]
It doesn't update until I click on the project (or a class in the project). However, I'm not sure what realistically can be done; should discuss with @dalehenrich for preferred tradeoff with constantly checking disk.  I'm fine with close/deferring per Dale's needs.

**Comment by ericwinger** [comment]
I think the request is that when the Refresh button is pressed, the gui is refreshed instantly rather than lazily. Should be fixed as of 3.2.13.
