### ISSUE TITLE
Differentiate components better in component hierarchy

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#883]
From @dalehenrich via Slack:

> To disambiguate the components in the Component pane, I think that the condition should be appended to the name of the Component. The top level components don't have a condition but the subcomponents all have conditions (a string) ... platform componts have an array of conditions ... so we probably want to have a method (title? or label?) that creates a suitable label ...

An alternative would be to show the hierarchical structure of the components ... as seen on disk (vim screen shot):
![Screenshot from 2021-09-14 11-12-30](https://user-images.githubusercontent.com/623951/133311281-bfe74850-cd2a-4fbb-9b87-da615b977dd2.png)

**Comment by dalehenrich** [comment]
fixed as part of #760

**Comment by ericwinger** [comment]
Does `RowanComponentService` need to new accessor to get the improved display, @dalehenrich ?  Right now, Jadeite & Services are looking at the component's name & basename.

**Comment by dalehenrich** [comment]
I've fixed the bugs in both Rowan and RowanClientServices, but I have not published the fixes to candidateV3.0  ... the branch that I did the work on also relies on changes to the GemStone base, so I will have to do a new private build to make the fixes generally available ... If you look at the screen shot in #886, you can see the new labels ... finally, I am in the final throes of a major method renaming campaign and plan to wait until I finish those changes before doing a new build --- the changes I am making could break some of the scripts that you are using, so I want to finish making all of the API breaking changes before doing a new private build ...

**Comment by ericwinger** [comment]
Ahh, got it. Looks like no Jadeite work needed. :+1:
