### ISSUE TITLE
Add Jadeite option to handle SigAborts

### ISSUE THREAD

**Issue by nrgiii** [ericwinger/Jade#885]
Email from Gunnar and UBS:

Hi,

We would like to request a change in Jadeite. There should be a feature in Jadeite to act on SIGABORTs.

Reasons
    Reduce risk of large commit-records (and all related problems)
    Reduce manual actions of hitting abort-button periodically
    Eliminate risk losing the session

 Suggested solution

    Add preferences in Jadeite for the session transaction mode (#auto #manual #transactionless)
    For #auto nothing else is needed (will be mostly used by developers)
    For #manual or #transactionless you need to fork a process (which is yet not possible in jadeite) that reacts on SIGABORT.

The main issue here is the possibility of forking a process (minimum requirement).

Would it be possible to add this to Jadeite?

Thanks
Gunnar

**Comment by LisaAlmarode** [comment]
same as issue #889
