### ISSUE TITLE
(Oscar 3.2) by default the components in the Components pane should be opened 1 level

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#886]
By opening the first level, the component organization is revealed and provides easy navigation to a desired collection of packages:
![Screenshot from 2021-09-24 10-24-05](https://user-images.githubusercontent.com/623951/134716016-14c5a285-3630-4d56-8d01-8186efa62ed4.png)
If we implement this feature, then it would also be nice to have appropriate component selected when one does a `find class` (or equivalent) in the project browser

**Comment by ericwinger** [comment]
Fixed as part of work to support Rowan V3.0

**Comment by LisaAlmarode** [comment]
In the absence of a components pane in 3.2.9, not going to worry too much about this (since then I'd have to figure out the relationship between components and packageGroups)
