### ISSUE TITLE
(Oscar V3.2) consider having the `Preferences>>Package list visible` menu apply to all tabs in a browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#887]
also consider putting an entry into the Preferences file for this as well ...

**Comment by LisaAlmarode** [comment]
All other items on the Package list menu apply to all tabs and indeed all browsers of any kind everywhere  (see issue #951).  Intuitively it makes sense to me that these visibility options apply to all tabs on a single project browser, at least, and not to other project browsers. Adding to preferences file is even more useful but probably more work, this was separated out to issue #952)

I think having Project Groups Visible being in preferences file would be very useful indeed.  Until such time as I might need to use them, they are just clutter.

**Comment by ericwinger** [comment]
Menu options should toggle package lists and package groups globally now. Preferences added in preference file.
