### ISSUE TITLE
Cannot copy stack and error message with new debugger ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#89]
Running test from Dictionary Browser in 3.0.15, the debugger comes straight up without dialog box ... and it isn't objvious how I can copy the stack and error message:

![image](https://user-images.githubusercontent.com/623951/44378491-675dbe00-a4b6-11e8-93ce-c33ca34e142a.png)

**Comment by ericwinger** [comment]
- [ ] Add error message to Copy button on "pre-debugger notifier" 
- [ ] Add copy menu item to debugger itself which copies stack to clipboard.

**Comment by ericwinger** [comment]
Added Copy Stack to Edit menu of the debugger. Both it and Copy on notifier write error message to clipboard as well. Fixed in 3.0.16
