### ISSUE TITLE
should be able to do senders of a removed method in Changes browser 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#892]
In this particular case I am comparing to later version of the project on disk, so despite the fact that is says `Removal` in the browser this would be an addition (if loaded) and I'm looking to see what other implementers of #time are in the image... If it was a removal, I could be scanning  the image to verify that I've removed all relevant senders of the message one last time before writing to disk... In general it seems to me that if I've got a selector under your mouse, you should be allowed to do senders/implementers if you want to
![Screenshot from 2021-12-17 12-38-14](https://user-images.githubusercontent.com/623951/146605157-6f32cfdf-d3ac-4cd0-85b6-4b8d78d9866c.png)

**Comment by ericwinger** [comment]
Does the option "Browse Senders" exist in your version of Jadeite?   If not, it will exist when "Jadeite for Rowan 3.0" is debuted. 
Would that do the trick? 

![image](https://user-images.githubusercontent.com/36212516/150038704-e71440df-1e01-42cb-926c-f37a77ea7add.png)

**Comment by dalehenrich** [comment]
the `browse senders` menu item was there, but when you selected it you got the notifier visible in the bug report ... looks great!

**Comment by ericwinger** [comment]
Browse senders of a removed method should work in the next version of Jadeite. If not, please reopen the issue.
