### ISSUE TITLE
As of 3.7.0 GCI, need to use GciNbExecuteStrDbg or GciNbPerformNoDebug ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#893]
... to avoid GciTransportError when invoking client useractions ...  see internal bugs 49809 and 49623 ... not a blocking issue, but something that should be fixed before going live with 3.7.0

**Comment by ericwinger** [comment]
Should be fixed in Jadeite for Rowan 3.0. https://github.com/GemTalk/Jadeite/commit/ae7af5fee9bad8d6499c9b295e6aa035a2ceeb48

**Comment by ericwinger** [comment]
Found a few more paths that needed the gci lib arguments or function changed. Latest fixes in https://github.com/GemTalk/Jadeite/commit/85a4a3b7f639297dec5deaed89544aa7305e4350

**Comment by LisaAlmarode** [comment]
Assuming this is my burning, GsFile on Windows client issue, that appear to be working just fine in 3.2.10.
