### ISSUE TITLE
When writing projects, it would be useful to display the project's repositoryRoot ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#896]
... as confirmation of the disk location where the package changes will be written:
![Screenshot from 2022-04-05 10-39-00](https://user-images.githubusercontent.com/623951/161817289-f54524f7-a718-4f42-87dd-746e936b571c.png)

**Comment by ericwinger** [comment]
Seemed easy enough to add in Jadeite for Rowan v3.0. 
![image](https://user-images.githubusercontent.com/36212516/161823661-5e2a4439-eef0-4479-b69d-4ebcd2f06134.png)
