### ISSUE TITLE
Let's consider using the loaded project for displaying packageGroups in the project browser ... 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#898]
I [cleaned up the Security Error](https://github.com/GemTalk/Rowan/issues/782), but when I tried to open a project browser I got [another error](https://github.com/GemTalk/Rowan/issues/782#issuecomment-1140054130) ... 

Currently the `packageGroupNames` for Rowan is empty, but because of the Security error we never get to see that the packageGroupNames is empty ... 

For simply displaying the packageGroups, I would prefer that we use the loaded project instead of the defintion of the loaded project ... I already play similar games in terms only showing the visible packages in the package browser, so some similar games can be played with respect to the packageGroups ... 

_For editing components, it is probably not appropriate for anyone to change the components if they don't have write access on the underlying objects ... so we may want to provide a read only variant of the editors in these cases ..._ Separated this out into #899  it's own issue as it's not related to package groups. ew

**Comment by dalehenrich** [comment]
see [RowanClientServices:issue_898](https://github.com/GemTalk/RowanClientServices/tree/issue_898) for patches/workarounds to get use of packageGroupNames to work for both SystemUser and DataCurator... 

Here's a workspace that can be used as SystemUser or DataCurator to load RowanSample9:spec_0061:
```smalltalk
| fileUrl spec loadSpec resolvedProject |
	fileUrl := 'file:$GS_HOME/shared/repos/Rowan/test/specs/RowanSample9_0000.ston'.
	spec := (((System users userWithId: 'SystemUser') objectNamed: #RwSpecification) fromUrl: fileUrl)
		projectsHome:  '/home/dhenrich/rogue/_homes/rogue/_home/server/stones/rowan_dev_l/git/testRepositories';
		yourself.
	spec revision: 'spec_0061'.
	resolvedProject := spec resolveStrict.
"load project"
	resolvedProject load.
```

**Comment by dalehenrich** [comment]
The patch does not address issues involved with using the package group editor ... presumably an alternate path for creating (and persisting) the definition that is being edited is still needed ...

**Comment by ericwinger** [comment]
The browser now uses package groups from the loaded project instead of the project definition.
