### ISSUE TITLE
(Oscar3.2pre-release5) CTL-E in workspace tab of project console brind up loaded component editor

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#900]
CTL-E in console:
![Screenshot from 2022-05-31 15-55-35](https://user-images.githubusercontent.com/623951/171297188-6714c938-9bb1-439a-8114-62c910ba8141.png)
CTL-E in workspace:
![Screenshot from 2022-05-31 15-57-00](https://user-images.githubusercontent.com/623951/171297310-b686de5f-214c-42ec-9e30-62a8760a254c.png)

**Comment by ericwinger** [comment]
Ctrl-E hotkey has been removed.
