### ISSUE TITLE
Need to be able to enter server path in server file selector for navigation

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#904]
Navigation is a bit limited at the moment. It starts in $ROWAN_PROJECTS_HOME for navigation. Should expand this. 

![image](https://user-images.githubusercontent.com/36212516/178845760-ce20f887-bf29-4062-b0a3-26e3dbff11c7.png)

**Comment by ericwinger** [comment]
Should be fixed in pre-release8 when released.

**Comment by LisaAlmarode** [comment]
I'm not sure what what's wasn't working before, so not sure what is fixed. I can enter a path in the entry field, and I can go up by pressing .. or the hard-to-spot folder-arrow icon.  It's a little er quirky in how it jumps from ROWAN_PROJECTS_HOME to the path, and I don't like the way it handles clicking on .. in the main pane, and the file icon could use improvement (especially the hover help of pop cannot be described as helpful)... but overall I think it does the job.
