### ISSUE TITLE
Jadeite-3.2pre-release7 walkback when ?ing too far

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#905]
When you press the ? icon and you are at the root of the filesystem you get a walkback (stack attached)
![Screenshot from 2022-07-13 15-15-09](https://user-images.githubusercontent.com/623951/178846216-bae5e1fd-2a0d-4a12-96f2-df3baa5d278a.png)

[stack.txt](https://github.com/GemTalk/Jadeite/files/9106450/stack.txt)

**Comment by ericwinger** [comment]
I believe this is a server bug #50035 root path gets error when sent #asString
https://kermit.gemtalksystems.com/bug?bug=50035

Leaving issue open so we can test when that bug is fixed.

**Comment by ericwinger** [comment]
Believe this is fixed with the fixed to 50035. The ? icon should also now be an up arrow.
