### ISSUE TITLE
Jadeite3.2prerelease7 inspector window opened from debugger takes two clicks on X to close?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#908]
I have to click twice on the X to close the window?
![Screenshot from 2022-07-14 14-44-11](https://user-images.githubusercontent.com/623951/179091392-f4e7f913-04b0-4ebd-b159-db85110b2098.png)
so far only the inspectors opened from debugger are stubborn closers ... doesn't seem to matter which frame is open or which object is inspected ... two clicks to close ...

we can huddle and share screens if it doesn't reproduce for you ... here's snapshot of console:
![Screenshot from 2022-07-14 14-47-56](https://user-images.githubusercontent.com/623951/179091949-72f03dfc-2f17-477e-be2f-71ea29409118.png)

**Comment by dalehenrich** [comment]
It's possible that the two click problem is related to a "hidden open debugger" (see https://github.com/GemTalk/Jadeite/issues/789#issuecomment-1185007586), since I don't know how long that debugger was there ... finally ended up killing the program because the image froze ...

**Comment by dalehenrich** [comment]
Confirmed that without an open debugger, the inspectors take only one click to close (as expected) ..

**Comment by dalehenrich** [comment]
It seems that with a hidden debugger, the inspectors still take only one click to close ... it took quite awhile for the image to [freeze](https://github.com/GemTalk/Jadeite/issues/789#issuecomment-1185007586) but I'm guessing it has to do with a hidden debugger

**Comment by dalehenrich** [comment]
now I've got a case where the image is not frozen, but none of the close buttons on any of the windows are working ... when I touch a window it comes to the front ... method selection works ... I just can't close any windows ... and there is a debugger open ... the console does not close either ... 
![Screenshot from 2022-07-14 18-16-31](https://user-images.githubusercontent.com/623951/179127308-c24ec7f6-fed6-40df-8e97-8540b6479034.png)

**Comment by dalehenrich** [comment]
attempting to write out the dirty packages from the console caused the image to hang ... no changes were written to disk before the hang ...

**Comment by dalehenrich** [comment]
after killing image and logging in I was able to save my changes ... It is worth noting that I am running on a later version of GemStone than you are using (my version of 3.7.0 dates from May 31) this may or may not have an impact ... although we never did get to the bottom of the hanging image with debugger issue from before and this smells an awful lot like that one...

**Comment by dalehenrich** [comment]
... another observation ... I have continued doing development as before, i.e. running tests and heavily using debugger, but I am running without an open project browser and have not had any hangs or unresponsive close buttons ... not proof by any means, but ... interesting

**Comment by dalehenrich** [comment]
Accidentally left project browser open and did a method save in the debugger and now the close buttons don't work ... I can select windows and the menus appear to be functional ... I just cannot close any windows ... have to terminate process ... reproducible test case? Not going to spend time trying , since even the reproducible tests cases aren't ... and I'm able to make progress if I remember to close the project browser ...

**Comment by dalehenrich** [comment]
windows is in a hot loop...100 % cpu ...

**Comment by dalehenrich** [comment]
Just had a hang using 3.2.9

**Comment by ericwinger** [comment]
Probably worth rechecking in Jadeite 3.2.10. I made some drastic changes in the area of the code that I think was causing the hangs.

**Comment by LisaAlmarode** [comment]
Much debugger was work done as of v 3.2.12. Closing optimistically, @dalehenrich reopen, or open a new issue, if this shows up again.
