### ISSUE TITLE
(3.2.7) While single stepping debugger got 'The Specified Error Dictionary contains no information for error number 6015 in the current language.' ERROR

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#912]
unfortunately the debugger on that error came up empty so I have no additional details ...

**Comment by LisaAlmarode** [comment]
6015 is ERR_TIMEOUT_INTERRUPT.  It appears to be related to bug 42998, for the ProcessScheduler to correctly handle multiple Delay expirations. However, we need some information to do any work at all; closing, please reopen if it occurs again (even the original stack being stepped through would be something).
