### ISSUE TITLE
v3.2.7 package browser feature requests

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#914]
1. persistent project browser preferences
   1. would be nice to be able to save the browser prefs in the browser preferences file
   2. would be nice if the project browser opening size was adjusted based on the chosen preferences. I don't know about you, but in 3.2.7, the project browser itself takes up about 3/4 of the screen width on my terminal which means that my windows vm takes up 5/6ths of the screen and still leaves me very little spare room to put other windows around the project browser (the Oscar3.1.1... project browser was too big (maybe 2/3 of screen width) but I had a touch more spare room) ... 
   3. since I tend to use either the package pane or group pane, I could free up some screen space by turning one of them off
![Screenshot from 2022-07-29 16-14-56](https://user-images.githubusercontent.com/623951/181859440-dfc6db4f-f777-41f2-8ea0-9ba79b4157fc.png)

**Comment by ericwinger** [comment]
> would be nice to be able to save the browser prefs in the browser preferences file

Are you talking about all 9 of these preferences? 

![image](https://user-images.githubusercontent.com/36212516/182231026-d2b394ae-7efd-4276-94cd-60b813ea001f.png)

> would be nice if the project browser opening size was adjusted based on the chosen preferences. I don't know about you, but in 3.2.7, the project browser itself takes up about 3/4 of the screen width on my terminal which means that my windows vm takes up 5/6ths of the screen and still leaves me very little spare room to put other windows around the project browser (the Oscar3.1.1... project browser was too big (maybe 2/3 of screen width) but I had a touch more spare room) ...

That might be possible with some work. Although I think it would be easier to make the sizing specific. What if we changed these preference options to include a window size parameter? There could even be a menu option to record the class and size to open the browser so the user doesn't have to guess the window dimensions. Example:

#openBrowserOnClass: <class name>  ==>  #openBrowserOnClass: <class name> dimensions: <point> 

>since I tend to use either the package pane or group pane, I could free up some screen space by turning one of them off

I'd be ok displaying one or the other rather than both.

**Comment by dalehenrich** [comment]
.. I was thinking of the `package list visible` and `package groups visible` properties ... it's a ~pane~ pain to have to toggle preferences every time you open a browser when your default preferences are different than the default preferences  "mandated" by the system ... I assumed that is what the preferences file is for? Setting a project browser dimension is an okay solution, if you can't make the size of the window a function of the number of ~pains~ panes that are visible ... 

Perhaps you and Lisa and I ought to do a bit of brainstorming before committing to a solution?

**Comment by ericwinger** [comment]
> Perhaps you and Lisa and I ought to do a bit of brainstorming before committing to a solution?

That sounds wise. Lisa has aesthetically-pleasing ideas.

**Comment by ericwinger** [comment]
Closed in favor of https://github.com/GemTalk/Jadeite/issues/915
