### ISSUE TITLE
Use default symbol dictionary when adding package

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#917]
In the Add Package pane in the browser, one shouldn't have to enter a symbol dictionary to specify that the default dictionary should be used. 

- [x] Populate the Symbol Dictionary combo box with the default on open
- [x] If no dictionary is specified, enter the default when Add Package is pressed. 

Also, make sure to understand (and fix) where this message is coming from: 
![image](https://user-images.githubusercontent.com/36212516/183132669-75f2cde0-b5cf-4464-b314-124e732e9a69.png)

**Comment by ericwinger** [comment]
Some Slack comments: 
Eric: Does it work if you specify a symbol dictionary?
Dale: Yes ... and it actually does the right thing (i.e., it does not fill in the field in the component object because it recognizes that I selected the default?) ...
So perhaps listing the default at the top of the selection field and "marked as DEFAULT would be sufficient ...

**Comment by ericwinger** [comment]
Should be fixed in the referenced commit.  Now, default is selected by default in the list and shown below the list presenter for reference. 
![image](https://user-images.githubusercontent.com/36212516/183149847-18fbe2f0-251d-4254-9842-8ae58484483c.png)

**Comment by LisaAlmarode** [comment]
The default appears to be always UserGlobals, I don't see anyplace this can be anything else. But that's fine.
It would be nice to be able to edit the package to change the SymbolDictionary it's in.  Waiting to see if that shows up before I add a feature request.
