### ISSUE TITLE
RowanDebuggerTestCase>>testSaveMethod fails

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#92]
Second assert is expecting a 'halt' but the debugger hasn't stepped into ``testMethod`` yet. 

1:14:58 PM, Tuesday, August 21, 2018: 'Expected: ''halt'' Actual: ''testMethod''.'
RowanDebuggerTestCase(TestCase)>>fail:
RowanDebuggerTestCase(TestCase)>>assert:equals:
RowanDebuggerTestCase>>testSaveMethod
RowanDebuggerTestCase(TestCase)>>performTest
[] in RowanDebuggerTestCase(TestCase)>>runCase
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
RowanDebuggerTestCase(TestCase)>>runCase
[] in RowanDebuggerTestCase(TestCase)>>debug
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
RowanDebuggerTestCase(TestCase)>>debug
UnitTestPlugin>>debugTest:
UnitTestPlugin>>debugTest
Symbol>>forwardTo:
CommandDescription>>performAgainst:
[] in Command>>value
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Command>>value
ShellView>>performCommand:
IdeaSpaceShell(Shell)>>performCommand:
CommandQuery>>perform
DelegatingCommandPolicy(CommandPolicy)>>route:
[] in PushButton(View)>>onCommand:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Cursor>>showWhile:
PushButton(View)>>onCommand:
PushButton(CommandButton)>>onActionPerformed
PushButton(View)>>performAction
PushButton>>command:id:
ContainerView(View)>>wmCommand:wParam:lParam:
ContainerView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam:cookie:
PushButton(ControlView)>>defaultWindowProcessing:wParam:lParam:
MouseEvent(WindowsEvent)>>defaultWindowProcessing
PushButton(View)>>onLeftButtonReleased:
PushButton(View)>>wmLButtonUp:wParam:lParam:
PushButton(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam:cookie:
ShellView(View)>>isDialogMessage:
ShellView>>preTranslateMouseInput:
ShellView(View)>>preTranslateMessage:
InputState>>preTranslateMessage:
InputState>>pumpMessage:

**Comment by jgfoster** [comment]
This should be covered in #62.
