### ISSUE TITLE
(3.2.8) No way to see the dictionary of a package

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#920]
I've been getting a number of errors when I try to create a category with a leading *, saying that *whatevername is not a loaded package or is not in the same symbol dictionary.  While I suspect some of these errors are incorrect, some are valid.

I cannot find any way in Jadeite to see what the SymbolDictionary of a particular package is, to check if the error is valid or not...

**Comment by ericwinger** [comment]
Similar to how we show the containing dictionary for a class, now a user can see the containing dictionary for a package. They can select the menu item and be taken to the dictionary, too.

See package menu pop-up menu item
Go to Containing Dictionary (<dictionary name>)

**Comment by dalehenrich** [comment]
... technically there is no "containing"  symbol dictionary for a PACKAGE ... there is a symbol dictionary associated with a package in which all classes defined in the package will be created ... but extension methods may be included in a package for classes that are not in the package symbol dictionary ... and those classes not in the package symbol dictionary will certainly show up in the class list for the package ... 

I'll suggest that the menu should be "class creation dictionary" which is closer to the "truth" but not necessarily ... but I won't fight for this :smile: , I mainly want to nitpick a technicality for information purposes

**Comment by dalehenrich** [comment]
reopening for consideration of a rename of the menu item

**Comment by ericwinger** [comment]
@LisaAlmarode - different naming suggestion? Ok with Dale's idea?

**Comment by ericwinger** [comment]
Closed per suggestion

**Comment by LisaAlmarode** [comment]
In 3.2.9, the menu item is Go to Containing Dictionary (Globals), which is good.  A package is certainly associated with a SymbolDictionary, we display methods that are in different packages as a convenience for browsing...
