### ISSUE TITLE
(3.2.8) Menu item issues

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#924]
- [x] (1) the system browser packages pane popup, and Packages menu item, "Add Package..." gives a dialog "Packages cannot be added in RowanV2.0 yet".  This give the impression you can't add a package, and yet with the right things selected you can locate a package creation dialog in the lower right. 

- [x] (2) When you have a package selected, the create new package form hidden.  If you unselect the package, the lower pane still shows the class creation expression and still hides the new package form.  If you click on your project in the project pane, it still leaves the class creation expression showing and no new package form.  You have to actually select a different project and then back to get the new package form to display.

- [x] (3) In the console, if you do not have a project selected and choose the Load Git Project... menu item, you get a Jadeite dialog, JadeiteTranscript does not understand #loadProjects.

**Comment by ericwinger** [comment]
(1) Add Package menu item will no longer be in menus as of 3.2.9. Was already fixed in https://github.com/GemTalk/Jadeite/commit/0f4ae2d31de9ef6017e17c785d037bd7a0d16503

**Comment by ericwinger** [comment]
(2) & (3) should be fixed now.

**Comment by LisaAlmarode** [comment]
I would prefer that add package bring you to the project pane and make the dialog visible, and why do we need to keep the non-working unload package and write package on the menu if can remove add, that now actually works?  

However, the package creation dialog location is rather inelegant, and this may be under work and/or not in scope, so I'll file a new issue/feature request for general improvement.

**Comment by ericwinger** [comment]
Unload has been renamed to Remove for Jadeite 3.2.10 here - https://github.com/GemTalk/Jadeite/issues/930#issuecomment-1223322341
