### ISSUE TITLE
(3.2.8) SystemBrowser Project pane copy gets error dialog

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#925]
I wanted the path to my repository to verify something, so I tried a copy from the text of the project pane.  
When I select something and copy, I get an error dialog:

![image](https://user-images.githubusercontent.com/13142166/184243048-974596f0-e220-47b3-bce1-33a631f12550.png)

**Comment by ericwinger** [comment]
Two accessors were only referenced by test methods. The runtime image stripper therefore thought they were removable.
Moved #projectUrl and #rowanProjectsHome to 'must not strip' category so they won't get stripped.
