### ISSUE TITLE
(328) walkback when pressing `?` button in Server File Selector (RowanFileService>>pop incorrect)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#926]
Stack attached at bottom ... 
RowanFileService>>pop is using #asString to presumably get the path of the parent:
```smalltalk
pop
	path := (Path from: path) parent asString. 
	self directoryContents
```
however, #asString is equivalent to #printString when sent to a FileReference ... the correct way to convert a FileReference into a path is to send #pathString ... confirmed that #pathString works ...

I'm guessing that this issue was masked by the GemTalk/FileSystemGs#54

[stack.txt](https://github.com/GemTalk/Jadeite/files/9312272/stack.txt)

**Comment by ericwinger** [comment]
Fixed per issue report - https://github.com/GemTalk/RowanClientServices/commit/7ff78e38d92fa99af109d8fbcc9d8e78b4740c57

Use pathString in 3.2.9.
