### ISSUE TITLE
Pass in the projects home and other attributes when loading a project from file

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#929]
When the user specifies a .ston file as the load spec for a rowan project, we need to let the user specify a different projectsHome if $ROWAN_PROJECTS_HOME is not correct. 

In the fullness of time, the user should be able to specify these additional attributes. 
Here's the full list from Dale: 

projectAlias - uncommon
revision - uncommon
projectSpecFile - uncommon
componentNames
customConditionalAttributes
projectsHome

**Comment by ericwinger** [comment]
New Load Project gui support for componentNames, customConditionalAttributes, and projectsHome in Jadeite 3.2.10. Closing for Lisa's review. Can reopen for feature improvements, bugs or if "uncommon" aspects need to be added to gui. 

![image](https://user-images.githubusercontent.com/36212516/186538276-bfdf03dd-8ed4-40c6-b066-2d46a48a3f61.png)

**Comment by LisaAlmarode** [comment]
layout and navigation opinions after discussion are on issue #981.  Issue #989 also came up as a result of discussing this dialog.
