### ISSUE TITLE
[3.2.10] New project browser window opens with Comparison tab selected

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#937]
If you open a new project browser, it has the comparison tab selected.  While any tab would be empty, this particular selected really makes no sense, and since it has a distinctive center bar, it's quite noticeable.  

When you then select a project, it adds the Project tab, then the ReadMe tab, then you can see it decides to select the Project tab. This is a little jarring (it is not fast enough not to be visible).  I hate things popping up and moving around unnecessarily..

If we always have the Class Defintion, Class Documentation, Method Source, SUnit, Comparison tabs (with nothing selected), I don't see why we need to carefully hide the Projects and Readme tabs?  If we must hide the Project and ReadMe, then shouldn't we also hide the Class Definition tab, whenever you are not allowed to create a class and there's no class to view?  

So: my request is to have these two tabs (Project and ReadMe) always shown, and a newly opened Project Browser default to select the project tab, which will be empty (since no project is selected).

**Comment by ericwinger** [comment]
> If you open a new project browser, it has the comparison tab selected. While any tab would be empty, this particular selected really makes no sense, and since it has a distinctive center bar, it's quite noticeable.

Just to clarify a little, if you do not have a project selected in the console the comparison tab is shown when a browser is opened. If you have a project opened, the Project tab would be selected.

**Comment by ericwinger** [comment]
Fixed per the request - project & readme shown when a new browser is opened without a project specified. Project tab selected.
