### ISSUE TITLE
[3.2.10] restore Package menu item "Go to containing package" vs. new, terrible "Go to Class Creation Dictionary"

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#938]
This was a change as a side issue on some other issue, but I object to the new name as confusing and uninformative.  I would accept "Go to associated package".  But the Class Creation thing make no sense to me.

The reason I requested something, which turned out to be this menu option, was so I could check if I would be allowed to move a method from another package into this package.  This is controlled by the package's associated SymbolDictionary, since everything in a package has one and only one SymbolDictionary.  

Dale's argument was that a dictionary doesn't define a package, and selecting a package not all the contents to the left will be in that dictionary.  But this is not going to confuse anyone, the font changes make it pretty clear,

**Comment by ericwinger** [comment]
Changed per request

**Comment by dalehenrich** [comment]
hold on a second ... let me clarify, AGAIN? 

 The symbol dictionary that you end up in after using the "go to containing package" has nothing to do with a package ... and you will see ALL of the classes defined in that symbol dictionary independent of package  ... so 'package' is totally unrelated to the operation you are performing ... BTW the original menu item was 'Go to containing dictionary', which is a better name than 'Go to package" .... perhaps 'Go to dictionary' is not a bad name either ... but package?

**Comment by ericwinger** [comment]
I think Lisa had a typo- I called it `Go to associated dictionary` in my fix. That work?

**Comment by dalehenrich** [comment]
Yeah ... that's fine ...since the typo wasn't called out in the actual issue and the fix message was 'fixed per request' I didn't realize the request was made in some other place :smile:

**Comment by LisaAlmarode** [comment]
I'm not sure I follow this thread but I don't object to the current menu items.
