### ISSUE TITLE
[3.0.91.2] Review inconsistencies with Jadeite keyboard shortcuts

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#940]
Need to review keyboard shortcuts for ad-hoc execution in text menus of debugger, inspector, browser, etc.  Ideally, any pane where text or code can be written would have the following working shortcuts. 

- Ctrl-E Execute
- Ctrl-D Display
- Ctrl-Q Inspect
- Ctrl-B Debug

Customer comment from Richard: _"The keyboard shortcut Ctrl+B (Debug) works correctly in a Jadeite workspace but not in an inspector window.
Please fix it in a future releases and perhaps check other shortcuts."_

**Comment by ericwinger** [comment]
Since the customer reported it against Jadeite 3.0.91.2, we would need to decide if a special release of the older Jadeite is warranted.  Or, could that be included along with other customer-requested changes.

**Comment by dalehenrich** [comment]
I don't believe the customer is anticipating any other changes ... so it is probably a matter of when they would want the new version. @rjsargent, could you ask for a time frame for the fix?

**Comment by rjsargent** [comment]
Gunnar replied:
"No fix in the current version is needed.
But please fix it in the next release."

**Comment by ericwinger** [comment]
Discovered (so far) that the method list browser & breakpoint browser's accelerator keys were not working right. Fixed those. Also, got the accelerator keys in the variable data presenter (little text box middle right) to work.

**Comment by ericwinger** [comment]
Did a review of every tool in Jadeite that I could think of that had a text pane. Think I got most, if not all, accelerators consistent. Would be great if @LisaAlmarode used her eagle eye to find more problems.
