### ISSUE TITLE
(3.2.10) 'AnsiString does not understand #value' when trying to "Edit Load Spec from file..."

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#945]
Attached stack occurs, when I double click on `Rowan'
![image](https://user-images.githubusercontent.com/623951/188489907-dd2e763c-0d1b-456e-92dc-f8f9aff8f817.png)

[stack.txt](https://github.com/GemTalk/Jadeite/files/9491258/stack.txt)

**Comment by LisaAlmarode** [comment]
This does not reproduce for me in 3.2.11.  Closing; @dalehenrich, reopen if it's still occurring.
