### ISSUE TITLE
(3.2.10) Project Browser / Class "Move To Package..." menu is grayed out?

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#947]
I suppose, that grayed out means "not implemented"? If so, then this is the Rowan code to be used implement this functionality:
```
Rowan projectTools browser
			moveClassNamed:  className
			toPackage: packageName
```

**Comment by LisaAlmarode** [comment]
Dragging a class between packages does work, just the menu item is not enabled.

**Comment by ericwinger** [comment]
I'm not seeing the menu item grayed out. What class are you looking at? Maybe it's something specific to that class/package/project. Or maybe I'm just misunderstanding. 

![image](https://user-images.githubusercontent.com/36212516/197634340-bf1c7fc7-7b7f-4fe4-ac7c-f78d7ae7cd10.png)
![image](https://user-images.githubusercontent.com/36212516/197634470-c637d520-b70c-4b0d-99c9-6139ed53f6a8.png)

**Comment by LisaAlmarode** [comment]
I think you keep forgetting that your dev system is not the reality that the users see, we've had this issue before. 

![image](https://user-images.githubusercontent.com/13142166/199589092-0b210327-dccb-4e82-8796-0d6ad65ad020.png)
![image](https://user-images.githubusercontent.com/13142166/199589119-0e01738b-943f-41eb-a35c-35f192c11d7e.png)

**Comment by ericwinger** [comment]
Yes, you were correct @LisaAlmarode. It was a runtime image only problem. The image stripper removed the menu item's target method. Dolphin disables the menu item in that case.
