### ISSUE TITLE
[3.2.11] Project Browser preferences menu should be on console

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#951]
All the options on this menu, except the Package List Visible and Package Group Visible, apply to every browser everywhere and all future opened browsers.  This menu belongs on the console, it makes very little sense where it is.

Package List Visible and Package Group Visible only apply to a specific tab, which is two degrees narrower (see issue #887) 

I'm not saying this is critical for 2022,...

**Comment by ericwinger** [comment]
Since the `Package list visible` and `Package groups visible` menu items now apply to all browsers, I believe those menu options should stay put. @LisaAlmarode thoughts?

**Comment by LisaAlmarode** [comment]
If you have two separate project browser windows open (not tabs in one windows, but actually separate windows), changing Package List Visible on of them, one modifies all of them.  

The preference menu item source styler, makes changes that apply only to the current browser windows (all tabs in that window), but it doesn't have the side-effect of modifying other project browser windows.  This is the expected behavior for a browser-specific preference.  The implication of having the menu item on the project browser, is that you could have some project browsers showing the pane, and another one not showing it, but that's not possible. 

Also anything in the preferences file should be on the Jadeite menu, that's a clear clue that something is system-wide and belongs on the console.

**Comment by ericwinger** [comment]
Moved browser preferences to transcript Jadeite menu since they are universal browser settings.
