### ISSUE TITLE
[3.2.11] Add projectGroupsVisible to preferences file

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#952]
Since Project groups are not heavily used, it's annoying to have to select the menu item to hide it, for every new browser.  Having a default in the preference file would be very useful, assuming this is not a temporary hack. 

This was a bonus issue added to issue 887 but getting it's own issue.

**Comment by dalehenrich** [comment]
Agree with the preferences file entry .... 

Also agree with #887 even when we actually have some projects with package groups, we will probably be fiddling with the settings ...

At the end of the day, some projects will have package groups and some will not ... so if a project doesn't have package groups project browser should just show packages (even if the package group preference is set) ... if the package preference is set no package groups should be shown (even if present in a project) ...

**Comment by ericwinger** [comment]
Think this was covered when #887 was fixed.
