### ISSUE TITLE
File Browser for server files

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#953]
A browser that lets you open and edit server files on Windows (e.g. load specs) would be very useful.  

The Jadeite load project dialog allows you to navigate though server files.  This is the start of a server file browser.

**Comment by ericwinger** [comment]
A first cut server file editor is on the Console File>Open Server File ... . Will need additional work most likely. Closing bug for Lisa's review and suggestions for improvements.

**Comment by LisaAlmarode** [comment]
After opening a server file, save is fine, but save as was a little confusing. 

- [x] There's an upper area for the path, which happens to also include the filename of the file you are editing. Then there's a lower pane next to the save button, but this has bad layout; it's partially obscured by default (depending on the exact size of the window, it's apparently defined at a fixed offset). Easy to see if you resize this dialog.

- [x] the expected behavior would be to have the upper pane show the path of the current file, excluding the filename, show the files in that directory, and put the filename itself in the lower pane.  

- [x] Since I didn't exact the filename to be in the path, I entered my new filename into the lower dialog.  This resulted in a walkback, a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'nextPutAll:',.  I imagine this was path/oldfilenamename/newfilename which is reasonable to not work, but shouldn't walkback.

- [x] When you have a server file open, the File menu does not have a way to open another server file.  The menu options are a little confusing: what's the difference between a file and a workspace?  And both client and server files File menu items are the same, but operate differently
    - new workspace  (always client file)
    - open workspace  (always client file)
    - save  (either client or sever, depending on current file)
    - save as  (either client or sever, depending on current file)

**Comment by ericwinger** [comment]
Per checkbox 4 - Renamed open workspace to Open Client File ...   Hopefully that's more clear.  Also, added a way to open a server file. 

![image](https://user-images.githubusercontent.com/36212516/200974384-53d38ad9-5bb5-42fd-bbb1-bcdf047c68ea.png)

**Comment by ericwinger** [comment]
@LisaAlmarode  Can you put a picture of the first checkbox layout issue? https://github.com/GemTalk/Jadeite/issues/953#issuecomment-1301350248  

![image](https://user-images.githubusercontent.com/36212516/201176512-391f517a-c62f-45bd-bf5b-d6d7fd33c2e6.png)

Here is what I see:

**Comment by ericwinger** [comment]
Think I've got the bulk of the requests fixed with a few test improvements.  Closing for review.

**Comment by LisaAlmarode** [comment]
The Console File menu needs to be more consistent with respect to the Workspace File menu.  

- [x] Console File menu has 'Open Workspace',  but the Workspace File menu has 'Open Client File'.  I think they should both be Open Client File.
- [x] 'File In Server File...' is on the File menu for the Console, but the Jadeite menu for a Workspace.   I think this should move to the File menu since it invokes selecting a new file, and is not relevant to the current workspace. 
- [x] a Workspace has an item 'File In Selected Text'.  The Console has the Edit menu item 'File In'.  The Workspace menu item can change to File In and stay there.  It won't be with the File In Server File, but that's okay.

There are other operations on the Workspace Jadeite menu that ar eon the Edit menu of the console, but that's post-first release, so just the above changes relate to this issue.


As a side note, I'm unclear why there is a disabled revert on the Console menu. I can't figure out what circumstances would enable it. This is however just a nit.

**Comment by ericwinger** [comment]
> As a side note, I'm unclear why there is a disabled revert on the Console menu. I can't figure out what circumstances would enable it. This is however just a nit.

I removed the Revert option.  That's a way to revert an open client file to it's disk state which is only a workspace operation. Since we now open client files in a new window, it's no longer really applicable. 

The Save and Save As ... are workspace-centric, too, but make some sense to leave alone. I will disable them unless the workspace tab is selected.
