### ISSUE TITLE
Need online help; our formatting is somewhat opaque

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#954]
After I did a write to git, I noticed that my project was no longer bold.  But it had an asterisk.  I had no idea what that meant (on reflection, perhaps it's the "active project" if that has any meaning?). And I see that my RowanClientServices is red, and (UnPackaged) is bold and italic.  And I see lots of purple classes, and purple methods, some purple methods are underlined and some are not and the meaning of the underline has faded from my memory.  

There really needs to be a way to look up the meanings of all this highlighting online.  

A simple html file seems fine, and I could put this together.  There is already a help button (only on the console, which is not actually where I looked) that brings you to the projects, so we could just add another item.

**Comment by ericwinger** [comment]
Could it be a web page somewhere with a link from the Console's help menu?  Then it could be maintained separately from Jadeite but still accessible easily within Jadeite.

**Comment by LisaAlmarode** [comment]
Keeping help in sync with the product version is helpful, though.

**Comment by ericwinger** [comment]
Lisa made an .html/.css file and Jadeite now has Help>Jadeite Help menu option on the Console as of version 3.2.12.

**Comment by LisaAlmarode** [comment]
The html and css files should be in a subdirectory e.g. help/.  This will make life much easier as help expands to include graphics, screen shots, multiple files; better not to overwhelm the root directory.

**Comment by ericwinger** [comment]
Help files are now in the help directory. Added Lisa's new help files, too, in the last commit.
