### ISSUE TITLE
[3.2.12] Use of *category to specify package depends on a repository quality that needs to be visible

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#956]
I don't see how to determine if a project has "rowan" (*category is not meaningful) or old-style (*lowercase-category moves the method to a different package).  

Currently in RowanSample10 I'm able to create *exactcase-category and have those function as making things move to another package, but earlier today I thought they were restricted on creating that category, but if you did manage to create the category they didn't move methods to that package.  I think the quality is an attribute of the project, but it may be related to the package. 

This issue to make the quality that defines appropriate behavior visible somewhere, so I can complain when it doesn't work according to whatever the rules for that quality are.

**Comment by dalehenrich** [comment]
Good points ... the '*' can be used with every package convention, but it definitely has different meanings ... maybe we should schedule a brainstorming session to explore possibilities?

**Comment by LisaAlmarode** [comment]
- [x] add the project's package convention to project tab in browser
- [x] remove restrictions on * category or as discussed with Dale. 
- [ ] add packaging convention details to jadeite help (this is for lisa)

**Comment by ericwinger** [comment]
Checkbox #1 and #2 are complete. Checkbox #3 is for Lisa. Reassigning to her.

**Comment by LisaAlmarode** [comment]
conventions were added to help, although more work always needed. Close; needs review once next build is ready.
