### ISSUE TITLE
[3.2.12] make package groups invisible by default

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#958]
This is controlled by a preference, the preference should be off for now.

Also the pane widths of the project browser when it starts up with packageGroupsVisible: false should be balanced; the default should have the most likely arrangement. We do not need that much space for the package names (not even rowan package names are that long).

![image](https://user-images.githubusercontent.com/13142166/199609552-3f1dc4ad-b18a-49c0-8f97-677e78a76d33.png)

**Comment by ericwinger** [comment]
Should default  to non-visible now in the preferences file and the panes are more balanced. Open to further sizing adjustments if needed.
