### ISSUE TITLE
[3.2.12] Hang on logout after some unsaved changes dialogs

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#962]
This may be related to other open old bugs, but I've seen it twice in 3.2.12 and don't recall seeing it before.  Not easily reproducible, but it occurs with not a whole lot of stuff open.  I believe it's related to when I have unsaved changes in text windows (once the console, once a workspace), and I logout, which brings up the do you want to continue editing.  Possibly I accidentally hit the yes button (cf issue #781), at least, I believe both times I saw the dialog more than once.  After one of the unsaved-changes-dialog's button is pushed, the image hangs.

There were change in the "We should never get here" which were not filed as an issue but possibly addressed around October 19.

**Comment by ericwinger** [comment]
Given the ubiquitous recent changes to the unsaved changes dialog, we should determine if this is still a bug and if possible find a reproduction case.

**Comment by LisaAlmarode** [comment]
Closing this optimistically hoping it's healed.
