### ISSUE TITLE
[3.2.12] Get rid of asterisk: fonts (and icons) in the project list

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#966]
The asterisk is not a good indicator for on-disk dirty state.  A new font style needs to be used instead.

- changes in the repository are indicated by Bold and Italic.  Are there any cases that are Bold/normal-angle or normal-weight/Italic?  Do we really need two font changes to indicate dirtiness?  Could we use italic for dirty on disk (replace asterisk) and have bold indicate changes in image? Italic isn't very noticeable, though. 

- Add underline for dirty?  I don't like this since I think this state will be common and it's harder to read.

- another color?  We could use Blue and then dirty+skew could be purple but this is a little too cute for me. 

Alternately, we could replace the invariable three-golden-apples icon with different icons indicating dirtiness or skew.

**Comment by ericwinger** [comment]
Added tool tip for project list in browser & transcript. 
Removed icon. 
Test added. 
Here's Lisa's slack message with details: 
```
Disk/image consistent
       regular font
Dirty on disk
       italic
Dirty in image
        bold, not italic
Dirty on disk; Dirty in image
        bold and italic
Skew in sha
        red
Skew in sha; Dirty on disk
         red and italic
Skew in sha; Dirty in image
         red and bold (not italic)
Skew in sha; Dirty on disk; Dirty in image
         red, bold, and italic
Does not exist on disk
         parens
Does not exist on disk; Dirty in image
         parens and bold (not italic)
[12:16](https://gemtalksystems.slack.com/archives/C03SKU8HL5V/p1668543360305189)
In case that wasn't clear, the first line is the actual hover help, and I've got the decorations following.
```

**Comment by LisaAlmarode** [comment]
The help text needs to be updated.  Reopen, leave on my list until I have text to send to Eric.

**Comment by LisaAlmarode** [comment]
Reclose this in favor of #993;  don't want to keep it hostage for help when the help update cycles is so different.
