### ISSUE TITLE
(Oscar-3.1.1-pre-release4) looks like CRLF used when `Add Accessor` generates methods

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#968]
Have not looked at 3x version, but assume that the same thing is done in 3x ... if not then no need to update 3.1...

`git diff` shows the CR:
```
+
+category: 'accessing'
+method: ObjectTally
+initialNilSlotOffset^M
+       ^initialNilSlotOffset
+%
+
```

**Comment by LisaAlmarode** [comment]
I think it's okay, at least vi doesn't show the ^M that I know and er don't love.
