### ISSUE TITLE
[3.2.13pr1] Project tab text uses isDirty and it's unclear if disk or image or both is meant

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#979]
The project browser project list uses bold and italic for dirty in image and dirty on disk.

However, the project tab shows only isDirty: pane, and confirming the current font styling against status in hover help against the project tab is not making sense. 

I'd like to have the project tab include both status for dirty on disk and dirty in the image. Failing that, the label isDirty should identify exactly what it is that is dirty.

![image](https://user-images.githubusercontent.com/13142166/205413903-adfe6b79-5c53-4d03-934f-ebfe9a2cae91.png)

**Comment by ericwinger** [comment]
The hover help text in the project list is now used in the project info tab.

**Comment by LisaAlmarode** [comment]
The hover help doesn't update immediately.  
Test case: make method change.  Font of project updates correctly (to bold). Click on project tab. This is correct (image dirty). 
Hover over project.  This has the previous status. 
![photoOfScreen](https://user-images.githubusercontent.com/13142166/207129614-6aacb8d8-3c1c-4a6d-a218-dbde79208f13.jpg)

**Comment by LisaAlmarode** [comment]
project tab status could use a separator:  DirtyOnDiskDirtyInImage

**Comment by ericwinger** [comment]
space separator added and hover help status updated every time to capture disk status changes that happened outside Jadeite.
