### ISSUE TITLE
[3.2.13] Cleanup load project dialog

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#981]
This dialog has layout issues; it is tabbed without having actual tabs, and looks like a second dialog opened in front of another. 
It also has scope issues, since we would like to not worry about components in the first release, and I don't know what either of those fields means in context.  I suppose resolve strict could be useful.

I think we should remove second tab and all the fields on the right side.  It's fine to keep the tab structure with only one tab, against future use.
If removing isn't the right option (that is, Dale needs some of these fields) then we can discuss what they mean and how to logically organize and how the layout can be fixed. Stuffing them onto a back tab would be OK. 

![image](https://user-images.githubusercontent.com/13142166/207200612-fb558b10-635d-4f35-872b-cec3fd62e153.png)

**Comment by ericwinger** [comment]
Notes - 

- [x] Need to expand $ROWAN_PROJECTS_HOME in Path before opening
- [x] 3rd tab to hide components and custom attributes
- [x] Make Select to be tab-specific (one select for each select) and single Load button
- [x] Add text for each tab (Lisa will add suggestions) 
- [x] Change Rowan Projects Home tab name to Project Home

**Comment by LisaAlmarode** [comment]
Project Spec tab
Select the project specification that you wish to load.  You should also ensure that the Project Home is correct.
Project Home tab
Select the home directory for this project.  This is equivalent to the old $ROWAN_PROJECTS_HOME.
Advanced tab
Components and attributes are features in Rowan v3 that are not yet fully supported in Jadeite.

**Comment by ericwinger** [comment]
Dialog should be cleaned up and ready for inspection.

**Comment by LisaAlmarode** [comment]
Much better.  Needs tweaking.  Warning: besides actual complaints, some very minor nits are included. 
 
- [x]  the Project Home tab is peculiarly yellow.  

- [x] the Project Spec and Project Home tabs appear to be identical (except for the one being peculiarly yellow).  The text describing the pane should be much more visible... at the top of the tab would be best.  

If you don't want to use the vertical space, you could replace "Path:" with "Project home path:" / "Load spec path:", but I think we have more vertical space than horizontal space available.

- [x] I think you should say "verify" that the Project Home is correct rather than "ensure".  It's slightly more passive and thus less threatening. 

- [x] The instructions on the URL page are a bit telegraphic, but I'm okay with it.  However, the displayed pattern should include two // , rather than https:/

- [ ] If I chose a random invalid Project Home directory I get a DNU walkback but I'm not strongly inclined to worry about idiot proofing.

**Comment by ericwinger** [comment]
`the Project Home tab is peculiarly yellow.`

I changed the background color to help the Project Home tab stand out from the Project Spec tab. They are nearly identical in look. If you have suggestions, @LisaAlmarode to make it stand out in a less-yellow way please let me know.

**Comment by ericwinger** [comment]
All the check boxes are complete except the last one.  There are a lot of different ways that a bad selection can fail badly. Perhaps that can be a new issue if we really want to pursue, as you say @LisaAlmarode, "idiot proofing."

**Comment by LisaAlmarode** [comment]
per comment 6, I don't think it needs to stand out more than it does now, with the added leading text being the first thing you see. The dialog opens on the important field (the spec), and if they click on a different tab with different leading text and are still confused... well, there's only so much we can do.
