### ISSUE TITLE
[3.2.13] Create project dialog has fixed-location buttons, which are hidden when window resized

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#982]
I believe this has been mentioned to Eric somewhere, but making a separate issues since I can't find whereever that was and it hasn't been fixed.

![image](https://user-images.githubusercontent.com/13142166/207438445-293d6d57-a562-4078-85a8-df532ce3c543.png)

**Comment by ericwinger** [comment]
It is a flexible display now which shouldn't cut off the buttons in normal usage.
