### ISSUE TITLE
[3.2.13] Class fileout gets error on filein to nonrowan image

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#984]
I filed out one of the classes in my rowan project and it looks fine. 
Then tried to file it into GemStone base 3.7 nonrowan image, and the ^M characters are apparently causing problems.

```
input  /benton1/users/gsadmin/ROWAN37/myrowan/CSVReader.gs
topaz 1 +> fileformat utf8^M!^M! From ! GEMSTONE: 3.7.0, Wed Dec  7 17:41:07 2022 (branch 370_rowanv3); IMAGE: GemStone/S64 v3.7.0 kernel classes filein completed at 07/12/2022 18:01:08^M! ^M^M! On 14/12/2022, 12:39:46^M!^Mset compile_env: 0
The rest of the command ('^M!^M! From ! GEMSTONE: 3.7.0, Wed Dec  7 17:41:07 2022 (branch 370_rowanv3)') was ignored.
unknown command: IMAGE:
topaz 1 +> ! ------------------- Class definition for CSVReader
topaz 1 +> expectvalue /Class
topaz 1 +> doit
Object subclass: 'CSVReader'
  instVarNames: #()
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: UserGlobals
  options: #()
```

**Comment by dalehenrich** [comment]
That sounds like some CRLF Windows monkey business ... I would have thought that fileout would have been a server-side operation and not get involved with Windows?

**Comment by ericwinger** [comment]
There was some fileout header code copied from the windows client. Converted to use lf's. Also found that the auto-generator code that created inst var accessing methods had cr's in it.
