### ISSUE TITLE
[3.2.13]  Saving a server text file with extended characters is not good

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#988]
This may not yet be supported, but filing an issues to be sure it is tested. 
Yes, my image is in UnicodeComparisonMode.

In vi, I created a UTF-8 server file that included a extended character 353. This opens and looks great in Jadeite.

Edit to add some text, and save the file.  On reopen, it's an unreadable mess.

After opening the file, before editing:
![image](https://user-images.githubusercontent.com/13142166/207725463-6546d92e-38bd-490a-868e-0ee29251cb71.png)

after edit, save, and re-open:
![image](https://user-images.githubusercontent.com/13142166/207725549-21bec2fe-011d-4e4f-b1fd-01f509d2e63d.png)

**Comment by ericwinger** [comment]
A few things wrong - 

- GsFile was still being used to write the file on save. 
- Getting the file contents was actually wrong. Should have used FileReference. 
- Once getting file was corrected, discovered a problem setting the view's unicode string.
