### ISSUE TITLE
Jadeite Login window resizes poorly

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#994]
Resizing the Jadeite Login window results in an unreadable window. Should make the widgets' size resize relative to the parent. 

![image](https://user-images.githubusercontent.com/36212516/208503590-182cba8f-2fb6-4293-ad31-9b31398c7133.png)

**Comment by ericwinger** [comment]
Believe I had done some work on this before. Will mark as close unless there are specific suggestions for improvement.

**Comment by LisaAlmarode** [comment]
Belief not confirmed:
![image](https://user-images.githubusercontent.com/13142166/217094458-52993f66-04c8-4b9b-8678-8b13539f9a6d.png)

**Comment by ericwinger** [comment]
Should be better for 12pt fonts now.
