### ISSUE TITLE
[3.2.16] regression: set font gets MNU if font not set in prefs

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#999]
If you don't have a font set in the prefs file, when you go to Jadeite/set font..., you get "UndefinedObject does not understand #currentFont".

**Comment by ericwinger** [comment]
[Jadeite3.2.16.ERRORS.txt](https://github.com/GemTalk/Jadeite/files/10796424/Jadeite3.2.16.ERRORS.txt)
Attaching error file Lisa put in Slack

**Comment by ericwinger** [comment]
Lisa confirmed the bug only occurs when no prefs file is present. If the Jadeite.prefs file wasn't found, Jadeite was bailing out on reading it but it still should have initialized the JadeitePreferences Current class variable.
